// Generated by boring build --target wgpu.

struct Dimension {
    width: i32,
    height: i32,
}

// ─── kernel Saxpy ───

@group(0) @binding(0) var<storage, read> saxpy_x: array<f32>;
@group(0) @binding(1) var<storage, read_write> saxpy_y: array<f32>;
struct SaxpyParams {
    alpha: f32,
}
@group(0) @binding(2) var<uniform> saxpy_params: SaxpyParams;



@compute @workgroup_size(1, 1, 1)
fn Saxpy_main(
    @builtin(local_invocation_id) bp_tid:  vec3<u32>,
    @builtin(workgroup_id)         bp_bid:  vec3<u32>,
    @builtin(num_workgroups)       bp_gdim: vec3<u32>,
) {
    let bp_bdim = vec3<u32>(1u, 1u, 1u);
    let alpha: f32 = saxpy_params.alpha;
    let i = (i32(bp_tid.x) + (i32(bp_bid.x) * i32(bp_bdim.x)));
    saxpy_y[u32(i)] = ((alpha * saxpy_x[u32(i)]) + saxpy_y[u32(i)]);
}

