// Generated by boring build --target wgpu.

struct Dimension {
    width: u32,
    height: u32,
}

// ─── kernel VectorAdd ───

@group(0) @binding(0) var<storage, read> a: array<i32>;
@group(0) @binding(1) var<storage, read> b: array<i32>;
@group(0) @binding(2) var<storage, read_write> result: array<i32>;

override block_x: u32 = 1;
override block_y: u32 = 1;
override block_z: u32 = 1;

@compute @workgroup_size(block_x, block_y, block_z)
fn VectorAdd_main(
    @builtin(local_invocation_id)   __tid:  vec3<u32>,
    @builtin(workgroup_id)           __bid:  vec3<u32>,
    @builtin(local_invocation_size) __bdim: vec3<u32>,
    @builtin(num_workgroups)         __gdim: vec3<u32>,
) {
    let i = ((i32(__bid.x) * i32(__bdim.x)) + i32(__tid.x));
    if ((i < 1000)) {
        result[u32(i)] = (a[u32(i)] + b[u32(i)]);
    }
}

