// Generated by boring build --target wgpu.

struct Dimension {
    width: i32,
    height: i32,
}

// ─── kernel VectorAdd ───

@group(0) @binding(0) var<storage, read> vectoradd_a: array<i32>;
@group(0) @binding(1) var<storage, read> vectoradd_b: array<i32>;
@group(0) @binding(2) var<storage, read_write> vectoradd_result: array<i32>;


@compute @workgroup_size(256, 1, 1)
fn VectorAdd_main(
    @builtin(local_invocation_id) bp_tid:  vec3<u32>,
    @builtin(workgroup_id)         bp_bid:  vec3<u32>,
    @builtin(num_workgroups)       bp_gdim: vec3<u32>,
) {
    let bp_bdim = vec3<u32>(256u, 1u, 1u);
    let i = ((i32(bp_bid.x) * i32(bp_bdim.x)) + i32(bp_tid.x));
    if ((i < 1000)) {
        vectoradd_result[u32(i)] = (vectoradd_a[u32(i)] + vectoradd_b[u32(i)]);
    }
}

