// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// MSL (Metal Shading Language) device code emitter.

use crate::ast::*;
use crate::transpiler::helpers::{
    reachable_free_fns,
    labeled_array_at_index, labeled_array_dim_literal,
};

pub(super) fn emit_device_msl(program: &Program) -> String {
    let mut e = DeviceEmitter::new();
    e.emit_program(program);
    e.out
}

struct DeviceEmitter {
    out: String,
    indent: usize,
    current_fields: Vec<KernelFieldDecl>,
    current_kernel: String,
    /// Auto-barrier mode: true when the kernel `def` has no explicit `sync` statements.
    /// When false (manual mode), the developer owns all barriers.
    auto_sync: bool,
    // Top-level scalar lets inlined into MSL (not in scope in kernel functions).
    top_level_scalars: std::collections::HashMap<String, String>,
}

impl DeviceEmitter {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            current_fields: vec![],
            current_kernel: String::new(),
            auto_sync: false,
            top_level_scalars: std::collections::HashMap::new(),
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program) {
        // Pre-pass: collect top-level scalar lets for inlining in MSL kernel bodies.
        for item in &program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    let is_scalar = crate::transpiler::helpers::is_scalar_let_value(val, s.ty.as_ref());
                    if is_scalar {
                        let rhs = self.expr(val);
                        self.top_level_scalars.insert(s.name.clone(), rhs);
                    }
                }
            }
        }

        self.line("// Generated by boring build --target metal.");
        self.blank();
        self.line("#include <metal_stdlib>");
        self.line("using namespace metal;");
        self.blank();
        // 64-bit integer aliases for MSL
        self.line("typedef long     int64_t;");
        self.line("typedef ulong    uint64_t;");
        self.blank();
        // Boring built-in Dimension type (mirrors host-side struct)
        self.line("struct Dimension { uint width; uint height; };");
        self.blank();

        // Emit free functions as device helpers callable from any kernel --
        // but only those actually reachable from kernel code. Free functions
        // are ordinary Boring functions shared with the host (CPU) build, and
        // routinely use dynamic-array / heap constructs (`[float]` growable
        // arrays, `.push`, etc.) that have no MSL equivalent (MSL forbids
        // pointer params without an explicit address space and has no heap
        // allocator in device code). Emitting every free function
        // unconditionally — regardless of whether any kernel calls it — used
        // to make the generated kernels/main.metal fail to compile as soon as
        // the program had ANY host-only helper with this shape, even if no
        // kernel ever touched it. Restrict emission to the transitive closure
        // of functions called from kernel entry points/methods instead.
        let reachable = reachable_free_fns(program);
        for item in &program.items {
            if let Item::Fn(decl) = item {
                if decl.qualifier.is_none() && !decl.task && reachable.contains(&decl.name) {
                    self.emit_free_device_fn(decl);
                    self.blank();
                }
            }
        }

        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.emit_kernel_decl(decl);
            }
        }
    }

    fn emit_free_device_fn(&mut self, decl: &crate::ast::FnDecl) {
        let ret = decl.return_ty.as_ref().map(msl_type).unwrap_or_else(|| "void".into());
        let params: Vec<String> = decl.params.iter().map(|p| {
            let ty = p.ty.as_ref().map(msl_type).unwrap_or_else(|| "int64_t".into());
            format!("{} {}", ty, p.name)
        }).collect();
        self.line(&format!("inline {} {}({}) {{", ret, decl.name, params.join(", ")));
        self.indent += 1;
        for stmt in &decl.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_decl(&mut self, decl: &KernelDecl) {
        self.current_fields = decl.fields.clone();
        self.current_kernel = decl.name.clone();
        self.line(&format!("// ─── kernel {} ───", decl.name));
        self.blank();

        // Device helper methods.
        for method in &decl.methods {
            if !method.name.is_empty() {
                self.emit_device_fn(&decl.name, method, &decl.fields);
                self.blank();
            }
        }

        // Entry point: `def ()`.
        if let Some(entry) = decl.methods.iter().find(|m| m.name.is_empty()) {
            self.emit_entry_point(decl, entry);
            self.blank();
        }
    }

    fn emit_device_fn(&mut self, kernel: &str, method: &FnDecl, fields: &[KernelFieldDecl]) {
        let ret = method.return_ty.as_ref().map(msl_type).unwrap_or_else(|| "void".into());
        let fn_name = format!("{}_{}", kernel, method.name);
        let mut params = buffer_field_params(fields);
        for p in &method.params {
            let ty = p.ty.as_ref().map(msl_type).unwrap_or_else(|| "int64_t".into());
            params.push(format!("{} {}", ty, p.name));
        }
        self.line(&format!("static {} {}({}) {{", ret, fn_name, params.join(", ")));
        self.indent += 1;
        for stmt in &method.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_entry_point(&mut self, decl: &KernelDecl, entry: &FnDecl) {
        let fn_name = format!("{}_kernel", decl.name);

        // Build parameter list with [[buffer(N)]] and [[threadgroup(N)]] indices.
        let mut buf_idx: u32 = 0;
        let mut tg_idx: u32 = 0;
        let mut params: Vec<String> = Vec::new();

        // 1. 'unified / 'global / 'actor'global / 'actor'unified array (and LabeledArray) fields → device T* [[buffer(N)]]
        for f in &decl.fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::ActorUnified => {
                    let elem_ty: Option<&Type> = match &f.ty {
                        Type::Array(inner) | Type::ArrayN(inner, _) => Some(inner.as_ref()),
                        ty if ty.as_labeled_array().is_some() => Some(ty.as_labeled_array().unwrap().0),
                        _ => None,
                    };
                    if let Some(inner) = elem_ty {
                        let elem = elem_msl_type(inner);
                        let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                        params.push(format!("device {}{}* {} [[buffer({})]]",
                            constness, elem, f.name, buf_idx));
                        buf_idx += 1;
                    }
                }
                // 'surface pixel buffers use 32-bit uint (BGRA8Unorm = 4 bytes/pixel)
                GpuQual::Surface => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => {
                            params.push(format!("device uint* {} [[buffer({})]]", f.name, buf_idx));
                            buf_idx += 1;
                        }
                        _ => {}
                    }
                }
                _ => {}
            }
        }

        // 2. 'const fields → constant T* [[buffer(N)]]
        //    - Scalars: param named __name (pointer), deref'd in body as `const T name = *__name;`
        //    - Fixed arrays: param named name (pointer), accessed directly as name[i]
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Const) {
                let elem = elem_msl_type(&f.ty);
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: use the field name directly — accessed as name[i] in the kernel body.
                        params.push(format!("constant {}* {} [[buffer({})]]", elem, f.name, buf_idx));
                    }
                    ty if ty.as_labeled_array().is_some() => {
                        // Fixed-shape LabeledArray: same direct-pointer treatment.
                        params.push(format!("constant {}* {} [[buffer({})]]", elem, f.name, buf_idx));
                    }
                    _ => {
                        // Scalar: param named __name, dereferenced into a local below.
                        params.push(format!("constant {}* __{} [[buffer({})]]", elem, f.name, buf_idx));
                    }
                }
                buf_idx += 1;
            }
        }

        // 3. Scalar 'local fields → constant T* [[buffer(N)]] (passed from host as scalar)
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Local)
                && !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))
                && f.ty.as_labeled_array().is_none() {
                    let ty = msl_type(&f.ty);
                    params.push(format!("constant {}* __{}_init [[buffer({})]]", ty, f.name, buf_idx));
                    buf_idx += 1;
                }
        }

        // 4. Dynamic 'shared array fields → threadgroup T* [[threadgroup(N)]]
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Actor)
                && matches!(f.ty, Type::Array(_)) {
                    let elem = elem_msl_type(&f.ty);
                    params.push(format!("threadgroup {}* {} [[threadgroup({})]]", elem, f.name, tg_idx));
                    tg_idx += 1;
                }
        }

        // 5. Built-in position parameters.
        params.push("uint3 __thread_pos [[thread_position_in_threadgroup]]".into());
        params.push("uint3 __block_pos [[threadgroup_position_in_grid]]".into());
        params.push("uint3 __block_dim [[threads_per_threadgroup]]".into());
        params.push("uint3 __grid_dim [[threadgroups_per_grid]]".into());
        // SIMD-group (warp) built-ins — scalars, unlike the vec3 params above.
        // Unconditional, same as the other built-in position params: MSL
        // SIMD-group builtins need no capability/enable step, so there's no
        // cost to always accepting them even on kernels that don't use
        // `gpu.warp.*`.
        params.push("uint __simd_lane_id [[thread_index_in_simdgroup]]".into());
        params.push("uint __simd_size [[threads_per_simdgroup]]".into());

        self.line(&format!("kernel void {}(", fn_name));
        self.indent += 1;
        for (i, p) in params.iter().enumerate() {
            let comma = if i + 1 < params.len() { "," } else { "" };
            self.line(&format!("{}{}", p, comma));
        }
        self.indent -= 1;
        self.line(") {");
        self.indent += 1;

        // Declare static 'shared arrays inside the kernel body.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Actor) {
                if let Type::ArrayN(inner, n) = &f.ty {
                    let elem = elem_msl_type(inner);
                    self.line(&format!("threadgroup {} {}[{}];", elem, f.name, n));
                } else if let Some((elem, _)) = f.ty.as_labeled_array() {
                    // See cuda::device's identical `labeled_array_len()` note:
                    // `None` (a const-generic axis) isn't handled here yet.
                    if let Some(len) = f.ty.labeled_array_len() {
                        self.line(&format!("threadgroup {} {}[{}];", elem_msl_type(elem), f.name, len));
                    }
                }
            }
        }

        // Declare 'const scalars: deref the constant buffer pointer into a local.
        // Arrays (and LabeledArray) are passed directly as `constant T* name` and need no deref.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Const) {
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: accessed directly via name[i] — no deref needed.
                    }
                    ty if ty.as_labeled_array().is_some() => {}
                    _ => {
                        let ty = msl_type(&f.ty);
                        self.line(&format!("const {} {} = *__{};", ty, f.name, f.name));
                    }
                }
            }
        }

        // Declare 'local arrays inside the kernel body.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Local) {
                match &f.ty {
                    Type::ArrayN(inner, n) => {
                        let elem = elem_msl_type(inner);
                        self.line(&format!("{} {}[{}];", elem, f.name, n));
                    }
                    Type::Array(_) => {}
                    ty if ty.as_labeled_array().is_some() && ty.labeled_array_len().is_some() => {
                        let (elem, _) = ty.as_labeled_array().unwrap();
                        let len = ty.labeled_array_len().unwrap();
                        self.line(&format!("{} {}[{}];", elem_msl_type(elem), f.name, len));
                    }
                    // A LabeledArray whose length isn't computable (const-generic
                    // axis) falls here rather than into the scalar branch below —
                    // same "not representable, skip" treatment as `Type::Array(_)`.
                    ty if ty.as_labeled_array().is_some() => {}
                    _ => {
                        // Scalar 'local: initialize from the constant buffer parameter.
                        let ty = msl_type(&f.ty);
                        self.line(&format!("{} {} = *__{}_init;", ty, f.name, f.name));
                    }
                }
            }
        }

        let has_sync_fields = self.current_fields.iter().any(|f| matches!(f.qual, GpuQual::Actor));
        self.auto_sync = has_sync_fields && !body_has_explicit_sync(&entry.body);
        if self.auto_sync {
            // Emit initial write-phase barrier after the first block of statements that
            // write to 'sync fields, before any loop that reads them cross-thread.
            let split = first_loop_index(&entry.body);
            for stmt in &entry.body[..split] { self.emit_stmt(stmt); }
            if split < entry.body.len() {
                self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
            }
            for stmt in &entry.body[split..] { self.emit_stmt(stmt); }
        } else {
            for stmt in &entry.body { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let mutable = matches!(s.binding, BindingKind::Mut | BindingKind::Var | BindingKind::Lazy);
                let ty = s.ty.as_ref().map(msl_type).unwrap_or_else(|| "auto".into());
                let kw = if mutable { "" } else { "const " };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{}{} {} = {};", kw, ty, s.name, rhs));
                } else {
                    self.line(&format!("{}{};", kw, ty));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    // `print` → silent no-op in Metal kernels (no device-side printf in MSL).
                    ExprKind::Call(callee, _)
                        if matches!(&callee.kind, ExprKind::Var(n) if n == "print") => {}
                    ExprKind::Assign(lhs, rhs) => {
                        // Atomic compound assign on an 'actor'global field.
                        if let Some(line) = self.try_atomic_assign(lhs, rhs) {
                            self.line(&line);
                        } else {
                            let l = self.expr(lhs);
                            let r = self.expr(rhs);
                            self.line(&format!("{} = {};", l, r));
                        }
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if ({}) {{", c)); }
                    else        { self.line(&format!("}} else if ({}) {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while ({}) {{", cond));
                self.indent += 1;
                // In auto-sync mode, insert a barrier at the top of each loop iteration
                // so that 'sync writes from the previous iteration are visible to all threads.
                if self.auto_sync && body_accesses_sync_field(&w.body, &self.current_fields) {
                    self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
                }
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let var = f.vars.first().cloned().unwrap_or_else(|| "_i".into());
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let op = if *inclusive { "<=" } else { "<" };
                        self.line(&format!("for (int64_t {var} = {lo}; {var} {op} {hi}; {var}++) {{"));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        self.line(&format!("/* for {var} in {iter} -- unsupported */"));
                        self.line("{");
                    }
                }
                self.indent += 1;
                if self.auto_sync && body_accesses_sync_field(&f.body, &self.current_fields) {
                    self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
                }
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            // sync → threadgroup memory barrier.
            Stmt::Comment(c) if c == "sync" => {
                self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
            }
            Stmt::Comment(_) => {}
            _ => { self.line("/* unsupported stmt in kernel */"); }
        }
    }

    /// `'actor'global` or `'actor'unified` — MSL's atomic cast at the call site doesn't
    /// care which `MTLResourceOptions` backs the buffer, only that it's `device` address
    /// space, so both qualifiers take the identical atomic codegen path.
    fn is_atomic_field(&self, name: &str) -> bool {
        self.current_fields.iter().any(|f|
            f.name == name && matches!(f.qual, GpuQual::ActorGlobal | GpuQual::ActorUnified))
    }

    /// Detect `arr[i] OP= v` on an `'actor'global`/`'actor'unified` field and emit Metal
    /// atomic intrinsic.
    fn try_atomic_assign(&mut self, lhs: &Expr, rhs: &Expr) -> Option<String> {
        let ExprKind::Index(arr, _idx) = &lhs.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !self.is_atomic_field(&arr_name) { return None; }
        let ExprKind::BinOp(op, _lhs_copy, value) = &rhs.kind else { return None; };

        let target = self.expr(lhs);
        let v = self.expr(value);

        // MSL atomic intrinsics — no atomicSub: use add with negation.
        let intrinsic = match op {
            BinOp::Add    => format!("atomic_fetch_add_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::Sub    => format!("atomic_fetch_add_explicit((device atomic_long*)&{}, -(long)({}), memory_order_relaxed)", target, v),
            BinOp::BitOr  => format!("atomic_fetch_or_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::BitAnd => format!("atomic_fetch_and_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::BitXor => format!("atomic_fetch_xor_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            _ => return None,
        };
        Some(format!("{};", intrinsic))
    }

    /// Detect `arr[i].min/max/swap/cas(...)` where `arr` is an
    /// `'actor'global`/`'actor'unified` field and emit the corresponding MSL
    /// atomic intrinsic. Handled in expression position — unlike
    /// `try_atomic_assign`'s statement-only compound-assign desugar, these
    /// return the previous value.
    ///
    /// `min`/`max`/`swap` map directly onto MSL's
    /// `atomic_fetch_min_explicit`/`atomic_fetch_max_explicit`/
    /// `atomic_exchange_explicit`, which already return the previous value
    /// like their CUDA/HIP equivalents — same `(device atomic_long*)` cast
    /// pattern already used for `+=`/`-=`/etc. above (`atomic_fetch_min/max_explicit`
    /// on 64-bit `atomic_long` specifically is not independently verified
    /// against a real Metal compiler in this environment — same caveat this
    /// backend's docs already carry elsewhere for untestable-locally MSL
    /// codegen).
    ///
    /// `cas` is a real shape mismatch: MSL's
    /// `atomic_compare_exchange_weak_explicit(object, &expected, desired, ...)`
    /// takes a *pointer* to the expected value (overwritten with the real
    /// current value on failure) and returns a `bool`, not the previous
    /// value directly — unlike CUDA/HIP's `atomicCAS`, which just returns
    /// it. Bridged via a GNU/Clang statement-expression (`({ ... })`,
    /// supported by Metal's Clang-based compiler) so the whole thing is
    /// still usable as a single expression: bind `expected` into a local,
    /// call compare-exchange (ignoring the bool — the local now holds
    /// whichever value actually ends up correct: unchanged if it succeeded,
    /// the real current value if it didn't), and yield that local.
    fn try_atomic_method_call(&mut self, obj: &Expr, method: &str, args_s: &[String]) -> Option<String> {
        let ExprKind::Index(arr, _idx) = &obj.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !matches!(method, "min" | "max" | "swap" | "cas") { return None; }
        let target = self.expr(obj);
        if self.is_atomic_field(&arr_name) {
            match (method, args_s) {
                ("min", [v]) => Some(format!(
                    "atomic_fetch_min_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v)),
                ("max", [v]) => Some(format!(
                    "atomic_fetch_max_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v)),
                ("swap", [v]) => Some(format!(
                    "atomic_exchange_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v)),
                ("cas", [expected, new]) => Some(format!(
                    "({{ long __boring_cas_exp = (long)({}); atomic_compare_exchange_weak_explicit((device atomic_long*)&{}, &__boring_cas_exp, (long)({}), memory_order_relaxed, memory_order_relaxed); __boring_cas_exp; }})",
                    expected, target, new
                )),
                _ => None,
            }
        } else {
            // Not atomic-qualified -- plain read-modify-write, no atomic cast
            // or memory-order needed. Bridged via the same GNU/Clang
            // statement-expression as the atomic `.cas` case above (Metal's
            // compiler is Clang-based) since there's no intrinsic call to
            // lean on for the "return the previous value" contract here.
            match (method, args_s) {
                ("min", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = min({t}, ({v})); __old; }})", t = target, v = v)),
                ("max", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = max({t}, ({v})); __old; }})", t = target, v = v)),
                ("swap", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = ({v}); __old; }})", t = target, v = v)),
                ("cas", [expected, new]) => Some(format!(
                    "({{ auto __old = {t}; if (__old == ({e})) {t} = ({n}); __old; }})",
                    t = target, e = expected, n = new)),
                _ => None,
            }
        }
    }

    /// `a.axis` — read-only shape-query property on a fixed-shape
    /// `LabeledArray` field (dynamic-shape ones are already desugared to a
    /// shadow field before codegen — see `desugar_labeled_array`). `a[width =
    /// w, height = h]`-style indexing is a distinct `ExprKind::LabeledIndex`
    /// node, handled directly in `expr()`'s main match instead of here.
    fn try_labeled_array_field_access(&mut self, obj: &Expr, field_name: &str) -> Option<String> {
        let ExprKind::Var(name) = &obj.kind else { return None; };
        let field = self.current_fields.iter().find(|f| &f.name == name)?;
        let (_, axes) = field.ty.as_labeled_array()?;
        labeled_array_dim_literal(axes, field_name)
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)   => n.to_string(),
            ExprKind::Float(f) => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)  => if *b { "1".into() } else { "0".into() },
            ExprKind::Str(s)   => format!("\"{}\"", s),
            ExprKind::Nil      => "0".into(),
            ExprKind::Void     => "".into(),
            ExprKind::Var(name) => {
                // A kernel field of the same name shadows the top-level scalar
                // (e.g. `kernel Saxpy: let float alpha` vs. top-level `let alpha = 2.0`
                // in examples/saxpy.br) -- the field is a real local/parameter in the
                // generated device function, so it must win, not the outer literal.
                // Previously unguarded: silently miscompiled `alpha * x[i] + y[i]` to
                // always use the top-level literal instead of the runtime parameter --
                // no compile error, just a wrong-value bug (confirmed via
                // `boring build --target metal examples/saxpy.br`).
                if self.current_fields.iter().any(|f| f.name == *name) {
                    name.clone()
                } else {
                    self.top_level_scalars.get(name).cloned().unwrap_or_else(|| name.clone())
                }
            }

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_msl(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_msl(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                format!("{}[{}]", self.expr(arr), self.expr(idx))
            }
            ExprKind::LabeledIndex(obj, args) => {
                // Stringify every arg's value first (needs `&mut self`) —
                // only then borrow `self.current_fields` immutably, so the
                // two borrows never overlap.
                let pairs: Vec<(String, String)> = args.iter()
                    .filter_map(|a| a.label.clone().map(|l| (l, self.expr(&a.value))))
                    .collect();
                let resolved = if let ExprKind::Var(name) = &obj.kind {
                    self.current_fields.iter().find(|f| &f.name == name)
                        .and_then(|field| field.ty.as_labeled_array())
                        .and_then(|(_, axes)| labeled_array_at_index(axes, &pairs))
                        .map(|offset| format!("{}[{}]", name, offset))
                } else {
                    None
                };
                resolved.unwrap_or_else(|| "/* unsupported labeled index */".to_string())
            }
            ExprKind::Field(obj, field) => {
                if let Some(msl) = self.try_labeled_array_field_access(obj, field) {
                    msl
                } else {
                    let obj_s = self.expr(obj);
                    map_gpu_field(&obj_s, field)
                }
            }
            ExprKind::Call(callee, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                let fn_s = match &callee.kind {
                    ExprKind::Var(n) => map_builtin_fn(n),
                    _ => self.expr(callee),
                };
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                if is_gpu_warp_receiver(obj) {
                    if let Some(msl) = gpu_warp_method_call(method, &args_s) {
                        return msl;
                    }
                }
                if let Some(msl) = self.try_atomic_method_call(obj, method, &args_s) {
                    return msl;
                }
                if matches!(&obj.kind, ExprKind::Var(n) if n == "self") {
                    // `self.method(args)` → the sibling device function this method was
                    // emitted as (see `emit_device_fn`): `KernelName_method(fields..., args)`.
                    let mut all_args = buffer_field_arg_names(&self.current_fields);
                    all_args.extend(args_s);
                    format!("{}_{}({})", self.current_kernel, method, all_args.join(", "))
                } else if let Some(msl) = float_unary_method_msl(method, &self.expr(obj), &args_s) {
                    // Boring's built-in numeric methods (`x.exp()`, `x.sqrt()`, ...) map
                    // directly onto MSL's `metal_stdlib` free functions of the same shape.
                    msl
                } else {
                    // Method calls on a receiver other than `self` have no MSL equivalent
                    // in this minimal device emitter — leave a visible marker rather than
                    // silently discarding the call.
                    let obj_s = self.expr(obj);
                    format!("/* unsupported: {}.{}({}) */", obj_s, method, args_s.join(", "))
                }
            }
            ExprKind::Cast(inner, ty) => {
                format!("(({})({})) ", msl_type(ty), self.expr(inner))
            }
            ExprKind::If(i) => {
                if let Some((cond, then_body)) = i.branches.first() {
                    let c = self.expr(cond);
                    let t = then_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    let e = i.else_body.as_ref().and_then(|b| b.last()).and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    format!("({} ? {} : {})", c, t, e)
                } else {
                    "0".into()
                }
            }
            ExprKind::Range { start, end, .. } => {
                format!("/* range {}..{} */", self.expr(start), self.expr(end))
            }
            _ => "/* expr */".into(),
        }
    }
}


// ── Free helpers ──────────────────────────────────────────────────────────────

/// Parameters for device helper functions (no [[attribute]] annotations).
fn buffer_field_params(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Actor | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::ActorUnified | GpuQual::Surface => {
                let elem = elem_msl_type(&f.ty);
                let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                Some(format!("device {}{}* {}", constness, elem, f.name))
            }
            GpuQual::Const => {
                let elem = elem_msl_type(&f.ty);
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: direct pointer, no deref — same as in the entry point.
                        Some(format!("constant {}* {}", elem, f.name))
                    }
                    ty if ty.as_labeled_array().is_some() => {
                        Some(format!("constant {}* {}", elem, f.name))
                    }
                    _ => {
                        // Scalar: passed as __name pointer so helper can access it.
                        Some(format!("constant {}* __{}", elem, f.name))
                    }
                }
            }
        }
    }).collect()
}

/// Argument names to pass at a call site for `buffer_field_params(fields)` — same
/// filtering as that function, but just the bare field names.
fn buffer_field_arg_names(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Actor | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::ActorUnified | GpuQual::Const | GpuQual::Surface => {
                Some(f.name.clone())
            }
        }
    }).collect()
}

/// MSL has no native 64/128-bit integer type (Apple GPUs historically lack native 64-bit
/// int ALU ops) — flag it in a comment rather than silently emitting a type that doesn't
/// exist in MSL (the previous behavior for `Uint8`, which fell through to `void*`).
fn msl_unsupported_width(name: &str, fallback: &str) -> String {
    format!("{} /* ERROR: `{}` is not supported on --target metal (MSL has no 64/128-bit integers) */", fallback, name)
}

/// MSL has no native `double` (Apple GPUs don't support 64-bit float ALU ops) — same
/// "flag it in a comment" convention as `msl_unsupported_width` above, with its own
/// message rather than that function's integer-specific wording
/// (docs/float-width-types.md §6).
fn msl_unsupported_f64(fallback: &str) -> String {
    format!("{} /* ERROR: `float64` is not supported on --target metal (MSL has no native double — use float32) */", fallback)
}

fn msl_type(ty: &Type) -> String {
    match ty {
        Type::Int              => "int64_t".into(),
        Type::Uint             => "uint64_t".into(),
        // MSL natively supports char/uchar (8-bit), short/ushort (16-bit), int/uint (32-bit).
        Type::Uint8             => "uchar".into(),
        Type::Int8               => "char".into(),
        Type::Int16              => "short".into(),
        Type::Uint16             => "ushort".into(),
        Type::Int32              => "int".into(),
        Type::Uint32             => "uint".into(),
        Type::Int64               => msl_unsupported_width("int64", "int64_t"),
        Type::Uint64               => msl_unsupported_width("uint64", "uint64_t"),
        Type::Int128               => msl_unsupported_width("int128", "int64_t"),
        Type::Uint128               => msl_unsupported_width("uint128", "uint64_t"),
        Type::Float32            => "float".into(),
        // MSL has no native `double` — a `float64` (or plain `float`, its alias) kernel
        // field used to be silently computed at 32-bit precision on-device with nothing
        // telling the author (docs/float-width-types.md §6). Flagged the same way the
        // unsupported integer widths above already are, instead of a silent narrowing lie.
        Type::Float64            => msl_unsupported_f64("float"),
        Type::Bool             => "bool".into(),
        Type::Str              => "const char*".into(),
        Type::Nil | Type::Void => "void".into(),
        Type::Array(inner)     => format!("{}*", msl_type(inner)),
        Type::ArrayN(inner, n) => format!("{}[{}]", msl_type(inner), n),
        Type::LabeledArray(inner, _) => format!("{}*", msl_type(inner)),
        Type::Named(n) => match n.as_str() {
            "float32" | "f32"       => "float".to_string(),
            "float" | "float64" | "f64" => msl_unsupported_f64("float"),
            "int"                   => "int64_t".to_string(),
            "uint"                  => "uint64_t".to_string(),
            "uint8"                 => "uchar".to_string(),
            "int8"                  => "char".to_string(),
            "int16"                 => "short".to_string(),
            "uint16"                => "ushort".to_string(),
            "int32"                 => "int".to_string(),
            "uint32"                => "uint".to_string(),
            "int64" | "i64"         => msl_unsupported_width("int64", "int64_t"),
            "uint64" | "u64"        => msl_unsupported_width("uint64", "uint64_t"),
            "int128" | "i128"       => msl_unsupported_width("int128", "int64_t"),
            "uint128" | "u128"      => msl_unsupported_width("uint128", "uint64_t"),
            "bool"                  => "bool".to_string(),
            other                   => other.to_string(),
        },
        Type::Qualified(inner, _) => msl_type(inner),
        Type::Optional(inner)  => msl_type(inner),
        Type::TypeParam(p)     => p.clone(),
        _                      => "void*".into(),
    }
}

fn elem_msl_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)        => msl_type(inner),
        Type::ArrayN(inner, _)    => msl_type(inner),
        Type::Qualified(inner, _) => elem_msl_type(inner),
        Type::LabeledArray(inner, _) => msl_type(inner),
        _                         => msl_type(ty),
    }
}

fn binop_msl(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",  BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",  BinOp::Rem => "%",
        BinOp::Eq  => "==", BinOp::NotEq => "!=",
        BinOp::Lt  => "<",  BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&", BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<", BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_msl(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "~",
    }
}

fn map_gpu_field(obj: &str, field: &str) -> String {
    // gpu.thread / gpu.block etc. map to the kernel built-in parameters.
    match (obj, field) {
        ("gpu", "thread")    => "__thread_pos".into(),
        ("gpu", "block")     => "__block_pos".into(),
        ("gpu", "block_dim") => "__block_dim".into(),
        ("gpu", "grid_dim")  => "__grid_dim".into(),
        // Dimension accessors — cast to int64_t for arithmetic.
        ("__thread_pos", "x") => "(int64_t)__thread_pos.x".into(),
        ("__thread_pos", "y") => "(int64_t)__thread_pos.y".into(),
        ("__thread_pos", "z") => "(int64_t)__thread_pos.z".into(),
        ("__block_pos",  "x") => "(int64_t)__block_pos.x".into(),
        ("__block_pos",  "y") => "(int64_t)__block_pos.y".into(),
        ("__block_pos",  "z") => "(int64_t)__block_pos.z".into(),
        ("__block_dim",  "x") => "(int64_t)__block_dim.x".into(),
        ("__block_dim",  "y") => "(int64_t)__block_dim.y".into(),
        ("__block_dim",  "z") => "(int64_t)__block_dim.z".into(),
        ("__grid_dim",   "x") => "(int64_t)__grid_dim.x".into(),
        ("__grid_dim",   "y") => "(int64_t)__grid_dim.y".into(),
        ("__grid_dim",   "z") => "(int64_t)__grid_dim.z".into(),
        ("gpu", "warp")       => "__warp".into(),
        ("__warp", "size")    => "(int64_t)__simd_size".into(),
        ("__warp", "lane")    => "(int64_t)__simd_lane_id".into(),
        _                    => format!("{}.{}", obj, field),
    }
}

/// `gpu.warp.sync()` / `gpu.warp.shuffle_down/up/xor/shuffle(...)` — MSL
/// SIMD-group intrinsics need no capability/mask handling (unlike CUDA's
/// `_sync` mask), so these map straight across.
fn gpu_warp_method_call(method: &str, args: &[String]) -> Option<String> {
    match method {
        "sync"         => Some("simdgroup_barrier(mem_flags::mem_none)".into()),
        "shuffle_down" => Some(format!("simd_shuffle_down({}, {})", args[0], args[1])),
        "shuffle_up"   => Some(format!("simd_shuffle_up({}, {})", args[0], args[1])),
        "shuffle_xor"  => Some(format!("simd_shuffle_xor({}, {})", args[0], args[1])),
        "shuffle"      => Some(format!("simd_shuffle({}, {})", args[0], args[1])),
        _ => None,
    }
}

fn is_gpu_warp_receiver(obj: &Expr) -> bool {
    matches!(&obj.kind, ExprKind::Field(inner, name) if name == "warp"
        && matches!(&inner.kind, ExprKind::Var(v) if v == "gpu"))
}

fn map_builtin_fn(name: &str) -> String {
    match name {
        "int"   => "(int64_t)".into(),
        "float" => "(float)".into(),
        "abs"   => "abs".into(),
        "min"   => "min".into(),
        "max"   => "max".into(),
        "sqrt"  => "sqrt".into(),
        "exp"   => "exp".into(),
        "log"   => "log".into(),
        "log2"  => "log2".into(),
        "log10" => "log10".into(),
        "sin"   => "sin".into(),
        "cos"   => "cos".into(),
        "tan"   => "tan".into(),
        "tanh"  => "tanh".into(),
        "pow"   => "pow".into(),
        "floor" => "floor".into(),
        "ceil"  => "ceil".into(),
        "round" => "round".into(),
        other   => other.into(),
    }
}

/// Maps Boring's built-in float methods (`x.exp()`, `x.sqrt()`, ...) to MSL
/// `metal_stdlib` calls. Mirrors the Rust-target mapping in
/// `transpiler::emit_methods`'s `FLOAT_UNARY_METHODS` (same method set, MSL
/// names instead of Rust `f64` method names). Returns `None` for methods this
/// device emitter doesn't recognize, so the caller can fall back to its
/// `/* unsupported */` marker.
fn float_unary_method_msl(method: &str, obj: &str, args: &[String]) -> Option<String> {
    let simple = match method {
        "sqrt" => "sqrt", "cbrt" => "cbrt", "abs" => "fabs",
        "floor" => "floor", "ceil" => "ceil", "round" => "round",
        "exp" => "exp", "exp2" => "exp2", "ln" => "log",
        "log2" => "log2", "log10" => "log10",
        "sin" => "sin", "cos" => "cos", "tan" => "tan",
        "asin" => "asin", "acos" => "acos", "atan" => "atan",
        "sinh" => "sinh", "cosh" => "cosh", "tanh" => "tanh",
        _ => "",
    };
    if !simple.is_empty() {
        return Some(format!("{}({})", simple, obj));
    }
    match method {
        "pow" | "powf" => {
            let exp = args.first().cloned().unwrap_or_else(|| "1.0".into());
            Some(format!("pow({}, {})", obj, exp))
        }
        "log" => {
            let base = args.first().cloned().unwrap_or_else(|| "M_E_F".into());
            Some(format!("(log({}) / log({}))", obj, base))
        }
        "atan2" => {
            let other = args.first().cloned().unwrap_or_else(|| "0.0".into());
            Some(format!("atan2({}, {})", obj, other))
        }
        "signum" => Some(format!("sign({})", obj)),
        "recip"  => Some(format!("(1.0 / {})", obj)),
        "toRadians" => Some(format!("({} * (M_PI_F / 180.0))", obj)),
        "toDegrees" => Some(format!("({} * (180.0 / M_PI_F))", obj)),
        _ => None,
    }
}

// ── Auto-sync helpers ─────────────────────────────────────────────────────────

/// Returns true if the body contains at least one explicit `sync` statement at any depth.
fn body_has_explicit_sync(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Comment(c) if c == "sync" => true,
        Stmt::While(w)   => body_has_explicit_sync(&w.body),
        Stmt::For(f)     => body_has_explicit_sync(&f.body),
        Stmt::If(i)      => i.branches.iter().any(|(_, b)| body_has_explicit_sync(b))
                         || i.else_body.as_ref().is_some_and(|b| body_has_explicit_sync(b)),
        _ => false,
    })
}

/// Returns true if the body references any field declared with `'sync`.
fn body_accesses_sync_field(stmts: &[Stmt], fields: &[KernelFieldDecl]) -> bool {
    let sync_names: Vec<&str> = fields.iter()
        .filter(|f| matches!(f.qual, GpuQual::Actor))
        .map(|f| f.name.as_str())
        .collect();
    if sync_names.is_empty() { return false; }
    stmts_reference_any(stmts, &sync_names)
}

fn stmts_reference_any(stmts: &[Stmt], names: &[&str]) -> bool {
    stmts.iter().any(|s| stmt_references_any(s, names))
}

fn stmt_references_any(stmt: &Stmt, names: &[&str]) -> bool {
    match stmt {
        Stmt::Expr(e) => expr_references_any(e, names),
        Stmt::Return(r) => r.value.as_ref().is_some_and(|v| expr_references_any(v, names)),
        Stmt::Let(s) => s.value.as_ref().is_some_and(|v| expr_references_any(v, names)),
        Stmt::While(w) => stmts_reference_any(&w.body, names),
        Stmt::For(f)   => stmts_reference_any(&f.body, names),
        Stmt::If(i)    => i.branches.iter().any(|(_, b)| stmts_reference_any(b, names))
                       || i.else_body.as_ref().is_some_and(|b| stmts_reference_any(b, names)),
        _ => false,
    }
}

fn expr_references_any(expr: &Expr, names: &[&str]) -> bool {
    match &expr.kind {
        ExprKind::Var(n)           => names.contains(&n.as_str()),
        ExprKind::Index(a, i)      => expr_references_any(a, names) || expr_references_any(i, names),
        ExprKind::Field(e, _)      => expr_references_any(e, names),
        ExprKind::BinOp(_, l, r)   => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::UnaryOp(_, e)    => expr_references_any(e, names),
        ExprKind::Assign(l, r)     => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::Call(f, args)    => expr_references_any(f, names) || args.iter().any(|a| expr_references_any(&a.value, names)),
        _ => false,
    }
}

/// Returns the index of the first While or For loop in the statement list.
/// Used to split the pre-loop write phase from the loop phase.
fn first_loop_index(stmts: &[Stmt]) -> usize {
    stmts.iter().position(|s| matches!(s, Stmt::While(_) | Stmt::For(_)))
        .unwrap_or(stmts.len())
}
