// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// MSL (Metal Shading Language) device code emitter.

use crate::ast::*;

pub(super) fn emit_device_msl(program: &Program) -> String {
    let mut e = DeviceEmitter::new();
    e.emit_program(program);
    e.out
}

struct DeviceEmitter {
    out: String,
    indent: usize,
    current_fields: Vec<KernelFieldDecl>,
    current_kernel: String,
}

impl DeviceEmitter {
    fn new() -> Self {
        Self { out: String::new(), indent: 0, current_fields: vec![], current_kernel: String::new() }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program) {
        self.line("// Generated by boring build --target metal.");
        self.blank();
        self.line("#include <metal_stdlib>");
        self.line("using namespace metal;");
        self.blank();
        // 64-bit integer aliases for MSL
        self.line("typedef long     int64_t;");
        self.line("typedef ulong    uint64_t;");
        self.blank();

        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.emit_kernel_decl(decl);
            }
        }
    }

    fn emit_kernel_decl(&mut self, decl: &KernelDecl) {
        self.current_fields = decl.fields.clone();
        self.current_kernel = decl.name.clone();
        self.line(&format!("// ─── kernel {} ───", decl.name));
        self.blank();

        // Device helper methods.
        for method in &decl.methods {
            if !method.name.is_empty() {
                self.emit_device_fn(&decl.name, method, &decl.fields);
                self.blank();
            }
        }

        // Entry point: `def ()`.
        if let Some(entry) = decl.methods.iter().find(|m| m.name.is_empty()) {
            self.emit_entry_point(decl, entry);
            self.blank();
        }
    }

    fn emit_device_fn(&mut self, kernel: &str, method: &FnDecl, fields: &[KernelFieldDecl]) {
        let ret = method.return_ty.as_ref().map(|t| msl_type(t)).unwrap_or_else(|| "void".into());
        let fn_name = format!("{}_{}", kernel, method.name);
        let mut params = buffer_field_params(fields);
        for p in &method.params {
            let ty = p.ty.as_ref().map(|t| msl_type(t)).unwrap_or_else(|| "int64_t".into());
            params.push(format!("{} {}", ty, p.name));
        }
        self.line(&format!("static {} {}({}) {{", ret, fn_name, params.join(", ")));
        self.indent += 1;
        for stmt in &method.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_entry_point(&mut self, decl: &KernelDecl, entry: &FnDecl) {
        let fn_name = format!("{}_kernel", decl.name);

        // Build parameter list with [[buffer(N)]] and [[threadgroup(N)]] indices.
        let mut buf_idx: u32 = 0;
        let mut tg_idx: u32 = 0;
        let mut params: Vec<String> = Vec::new();

        // 1. 'unified / 'global / 'actor'global array fields → device T* [[buffer(N)]]
        for f in &decl.fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                    match &f.ty {
                        Type::Array(inner) | Type::ArrayN(inner, _) => {
                            let elem = elem_msl_type(inner);
                            let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                            params.push(format!("device {}{}* {} [[buffer({})]]",
                                constness, elem, f.name, buf_idx));
                            buf_idx += 1;
                        }
                        _ => {}
                    }
                }
                _ => {}
            }
        }

        // 2. 'const fields → constant T* [[buffer(N)]]
        //    - Scalars: param named __name (pointer), deref'd in body as `const T name = *__name;`
        //    - Fixed arrays: param named name (pointer), accessed directly as name[i]
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Const) {
                let elem = elem_msl_type(&f.ty);
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: use the field name directly — accessed as name[i] in the kernel body.
                        params.push(format!("constant {}* {} [[buffer({})]]", elem, f.name, buf_idx));
                    }
                    _ => {
                        // Scalar: param named __name, dereferenced into a local below.
                        params.push(format!("constant {}* __{} [[buffer({})]]", elem, f.name, buf_idx));
                    }
                }
                buf_idx += 1;
            }
        }

        // 3. Scalar 'local fields → constant T* [[buffer(N)]] (passed from host as scalar)
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Local) {
                if !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                    let ty = msl_type(&f.ty);
                    params.push(format!("constant {}* __{}_init [[buffer({})]]", ty, f.name, buf_idx));
                    buf_idx += 1;
                }
            }
        }

        // 4. Dynamic 'shared array fields → threadgroup T* [[threadgroup(N)]]
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Shared) {
                if matches!(f.ty, Type::Array(_)) {
                    let elem = elem_msl_type(&f.ty);
                    params.push(format!("threadgroup {}* {} [[threadgroup({})]]", elem, f.name, tg_idx));
                    tg_idx += 1;
                }
            }
        }

        // 5. Built-in position parameters.
        params.push("uint3 __thread_pos [[thread_position_in_threadgroup]]".into());
        params.push("uint3 __block_pos [[threadgroup_position_in_grid]]".into());
        params.push("uint3 __block_dim [[threads_per_threadgroup]]".into());
        params.push("uint3 __grid_dim [[threadgroups_per_grid]]".into());

        self.line(&format!("kernel void {}(", fn_name));
        self.indent += 1;
        for (i, p) in params.iter().enumerate() {
            let comma = if i + 1 < params.len() { "," } else { "" };
            self.line(&format!("{}{}", p, comma));
        }
        self.indent -= 1;
        self.line(") {");
        self.indent += 1;

        // Declare static 'shared arrays inside the kernel body.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Shared) {
                if let Type::ArrayN(inner, n) = &f.ty {
                    let elem = elem_msl_type(inner);
                    self.line(&format!("threadgroup {} {}[{}];", elem, f.name, n));
                }
            }
        }

        // Declare 'const scalars: deref the constant buffer pointer into a local.
        // Arrays are passed directly as `constant T* name` and need no deref.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Const) {
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: accessed directly via name[i] — no deref needed.
                    }
                    _ => {
                        let ty = msl_type(&f.ty);
                        self.line(&format!("const {} {} = *__{};", ty, f.name, f.name));
                    }
                }
            }
        }

        // Declare 'local arrays inside the kernel body.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Local) {
                match &f.ty {
                    Type::ArrayN(inner, n) => {
                        let elem = elem_msl_type(inner);
                        self.line(&format!("{} {}[{}];", elem, f.name, n));
                    }
                    Type::Array(_) => {}
                    _ => {
                        // Scalar 'local: initialize from the constant buffer parameter.
                        let ty = msl_type(&f.ty);
                        self.line(&format!("{} {} = *__{}_init;", ty, f.name, f.name));
                    }
                }
            }
        }

        for stmt in &entry.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let mutable = matches!(s.binding, BindingKind::Mut | BindingKind::Var | BindingKind::Lazy);
                let ty = s.ty.as_ref().map(|t| msl_type(t)).unwrap_or_else(|| "auto".into());
                let kw = if mutable { "" } else { "const " };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{}{} {} = {};", kw, ty, s.name, rhs));
                } else {
                    self.line(&format!("{}{};", kw, ty));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    // `print` → silent no-op in Metal kernels (no device-side printf in MSL).
                    ExprKind::Call(callee, _)
                        if matches!(&callee.kind, ExprKind::Var(n) if n == "print") => {}
                    ExprKind::Assign(lhs, rhs) => {
                        // Atomic compound assign on an 'actor'global field.
                        if let Some(line) = self.try_atomic_assign(lhs, rhs) {
                            self.line(&line);
                        } else {
                            let l = self.expr(lhs);
                            let r = self.expr(rhs);
                            self.line(&format!("{} = {};", l, r));
                        }
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if ({}) {{", c)); }
                    else        { self.line(&format!("}} else if ({}) {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while ({}) {{", cond));
                self.indent += 1;
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let var = f.vars.first().cloned().unwrap_or_else(|| "_i".into());
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let op = if *inclusive { "<=" } else { "<" };
                        self.line(&format!("for (int64_t {var} = {lo}; {var} {op} {hi}; {var}++) {{"));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        self.line(&format!("/* for {var} in {iter} -- unsupported */"));
                        self.line("{");
                    }
                }
                self.indent += 1;
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            // sync → threadgroup memory barrier.
            Stmt::Comment(c) if c == "sync" => {
                self.line("threadgroup_barrier(mem_flags::mem_threadgroup);");
            }
            Stmt::Comment(_) => {}
            _ => { self.line("/* unsupported stmt in kernel */"); }
        }
    }

    fn is_actor_global_field(&self, name: &str) -> bool {
        self.current_fields.iter().any(|f|
            f.name == name && matches!(f.qual, GpuQual::ActorGlobal))
    }

    /// Detect `arr[i] OP= v` on an `'actor'global` field and emit Metal atomic intrinsic.
    fn try_atomic_assign(&mut self, lhs: &Expr, rhs: &Expr) -> Option<String> {
        let ExprKind::Index(arr, _idx) = &lhs.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !self.is_actor_global_field(&arr_name) { return None; }
        let ExprKind::BinOp(op, _lhs_copy, value) = &rhs.kind else { return None; };

        let target = self.expr(lhs);
        let v = self.expr(value);

        // MSL atomic intrinsics — no atomicSub: use add with negation.
        let intrinsic = match op {
            BinOp::Add    => format!("atomic_fetch_add_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::Sub    => format!("atomic_fetch_add_explicit((device atomic_long*)&{}, -(long)({}), memory_order_relaxed)", target, v),
            BinOp::BitOr  => format!("atomic_fetch_or_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::BitAnd => format!("atomic_fetch_and_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            BinOp::BitXor => format!("atomic_fetch_xor_explicit((device atomic_long*)&{}, (long)({}), memory_order_relaxed)", target, v),
            _ => return None,
        };
        Some(format!("{};", intrinsic))
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)   => n.to_string(),
            ExprKind::Float(f) => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)  => if *b { "1".into() } else { "0".into() },
            ExprKind::Str(s)   => format!("\"{}\"", s),
            ExprKind::Nil      => "0".into(),
            ExprKind::Void     => "".into(),
            ExprKind::Var(name) => name.clone(),

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_msl(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_msl(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                format!("{}[{}]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                let obj_s = self.expr(obj);
                map_gpu_field(&obj_s, field)
            }
            ExprKind::Call(callee, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                let fn_s = match &callee.kind {
                    ExprKind::Var(n) => map_builtin_fn(n),
                    _ => self.expr(callee),
                };
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                if matches!(&obj.kind, ExprKind::Var(n) if n == "self") {
                    // `self.method(args)` → the sibling device function this method was
                    // emitted as (see `emit_device_fn`): `KernelName_method(fields..., args)`.
                    let mut all_args = buffer_field_arg_names(&self.current_fields);
                    all_args.extend(args_s);
                    format!("{}_{}({})", self.current_kernel, method, all_args.join(", "))
                } else {
                    // Method calls on a receiver other than `self` have no MSL equivalent
                    // in this minimal device emitter — leave a visible marker rather than
                    // silently discarding the call.
                    let obj_s = self.expr(obj);
                    format!("/* unsupported: {}.{}({}) */", obj_s, method, args_s.join(", "))
                }
            }
            ExprKind::Cast(inner, ty) => {
                format!("(({})({})) ", msl_type(ty), self.expr(inner))
            }
            ExprKind::If(i) => {
                if let Some((cond, then_body)) = i.branches.first() {
                    let c = self.expr(cond);
                    let t = then_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    let e = i.else_body.as_ref().and_then(|b| b.last()).and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    format!("({} ? {} : {})", c, t, e)
                } else {
                    "0".into()
                }
            }
            ExprKind::Range { start, end, .. } => {
                format!("/* range {}..{} */", self.expr(start), self.expr(end))
            }
            _ => "/* expr */".into(),
        }
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

/// Parameters for device helper functions (no [[attribute]] annotations).
fn buffer_field_params(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Shared | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                let elem = elem_msl_type(&f.ty);
                let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                Some(format!("device {}{}* {}", constness, elem, f.name))
            }
            GpuQual::Const => {
                let elem = elem_msl_type(&f.ty);
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        // Array: direct pointer, no deref — same as in the entry point.
                        Some(format!("constant {}* {}", elem, f.name))
                    }
                    _ => {
                        // Scalar: passed as __name pointer so helper can access it.
                        Some(format!("constant {}* __{}", elem, f.name))
                    }
                }
            }
        }
    }).collect()
}

/// Argument names to pass at a call site for `buffer_field_params(fields)` — same
/// filtering as that function, but just the bare field names.
fn buffer_field_arg_names(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Shared | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                Some(f.name.clone())
            }
        }
    }).collect()
}

fn msl_type(ty: &Type) -> String {
    match ty {
        Type::Int              => "int64_t".into(),
        Type::Uint             => "uint64_t".into(),
        Type::Float            => "float".into(),
        Type::Bool             => "bool".into(),
        Type::Str              => "const char*".into(),
        Type::Nil | Type::Void => "void".into(),
        Type::Array(inner)     => format!("{}*", msl_type(inner)),
        Type::ArrayN(inner, n) => format!("{}[{}]", msl_type(inner), n),
        Type::Named(n) => match n.as_str() {
            "float" | "f64" | "f32" => "float",
            "int"   | "i64"         => "int64_t",
            "uint"  | "u64"         => "uint64_t",
            "bool"                  => "bool",
            other                   => return other.to_string(),
        }.into(),
        Type::Qualified(inner, _) => msl_type(inner),
        Type::Optional(inner)  => msl_type(inner),
        Type::TypeParam(p)     => p.clone(),
        _                      => "void*".into(),
    }
}

fn elem_msl_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)        => msl_type(inner),
        Type::ArrayN(inner, _)    => msl_type(inner),
        Type::Qualified(inner, _) => elem_msl_type(inner),
        _                         => msl_type(ty),
    }
}

fn binop_msl(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",  BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",  BinOp::Rem => "%",
        BinOp::Eq  => "==", BinOp::NotEq => "!=",
        BinOp::Lt  => "<",  BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&", BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<", BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_msl(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "~",
    }
}

fn map_gpu_field(obj: &str, field: &str) -> String {
    // gpu.thread / gpu.block etc. map to the kernel built-in parameters.
    match (obj, field) {
        ("gpu", "thread")    => "__thread_pos".into(),
        ("gpu", "block")     => "__block_pos".into(),
        ("gpu", "block_dim") => "__block_dim".into(),
        ("gpu", "grid_dim")  => "__grid_dim".into(),
        // Dimension accessors — cast to int64_t for arithmetic.
        ("__thread_pos", "x") => "(int64_t)__thread_pos.x".into(),
        ("__thread_pos", "y") => "(int64_t)__thread_pos.y".into(),
        ("__thread_pos", "z") => "(int64_t)__thread_pos.z".into(),
        ("__block_pos",  "x") => "(int64_t)__block_pos.x".into(),
        ("__block_pos",  "y") => "(int64_t)__block_pos.y".into(),
        ("__block_pos",  "z") => "(int64_t)__block_pos.z".into(),
        ("__block_dim",  "x") => "(int64_t)__block_dim.x".into(),
        ("__block_dim",  "y") => "(int64_t)__block_dim.y".into(),
        ("__block_dim",  "z") => "(int64_t)__block_dim.z".into(),
        ("__grid_dim",   "x") => "(int64_t)__grid_dim.x".into(),
        ("__grid_dim",   "y") => "(int64_t)__grid_dim.y".into(),
        ("__grid_dim",   "z") => "(int64_t)__grid_dim.z".into(),
        _                    => format!("{}.{}", obj, field),
    }
}

fn map_builtin_fn(name: &str) -> String {
    match name {
        "int"   => "(int64_t)".into(),
        "float" => "(float)".into(),
        "abs"   => "abs".into(),
        "min"   => "min".into(),
        "max"   => "max".into(),
        "sqrt"  => "sqrt".into(),
        other   => other.into(),
    }
}
