// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Rust host-side code emitter for the Metal backend.
// Uses the `metal` crate (objc2-metal migration planned).

use crate::ast::*;

pub(super) fn emit_host_rs(program: &Program, kernel_names: &[String]) -> String {
    let mut e = HostEmitter::new(kernel_names);
    e.emit_program(program, kernel_names);
    e.out
}

struct HostEmitter {
    out: String,
    indent: usize,
    kernel_names: std::collections::HashSet<String>,
    kernel_decls: std::collections::HashMap<String, KernelDecl>,
    var_kernel_type: std::collections::HashMap<String, String>,
    gpu_vars: std::collections::HashSet<String>,
    // Top-level scalar lets (name → Rust expression), used to inline scalars
    // that are in scope in main() but not in kernel new() functions.
    top_level_scalars: std::collections::HashMap<String, String>,
    // Screen / display support
    screen_var: Option<String>,
    screen_width_expr: String,
    screen_height_expr: String,
    screen_title: String,
    // true while emitting render loop body (? → .expect() for kernel launches)
    in_render_loop: bool,
}

impl HostEmitter {
    fn new(kernel_names: &[String]) -> Self {
        Self {
            out: String::new(),
            indent: 0,
            kernel_names: kernel_names.iter().cloned().collect(),
            kernel_decls: std::collections::HashMap::new(),
            var_kernel_type: std::collections::HashMap::new(),
            gpu_vars: std::collections::HashSet::new(),
            top_level_scalars: std::collections::HashMap::new(),
            screen_var: None,
            screen_width_expr: String::new(),
            screen_height_expr: String::new(),
            screen_title: String::new(),
            in_render_loop: false,
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program, kernel_names: &[String]) {
        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.kernel_decls.insert(decl.name.clone(), decl.clone());
            }
        }

        // Pre-pass: collect top-level scalar lets so they can be inlined inside
        // kernel new() functions (emitted before main(), where these vars live).
        for item in &program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    let is_scalar = matches!(val.kind,
                        ExprKind::Int(_) | ExprKind::Float(_) | ExprKind::Bool(_)
                    ) || s.ty.as_ref().map(|t| matches!(t,
                        Type::Int | Type::Uint | Type::Float | Type::Bool
                    )).unwrap_or(false);
                    if is_scalar {
                        let rhs = self.expr(val);
                        self.top_level_scalars.insert(s.name.clone(), rhs);
                    }
                }
            }
        }

        // Pre-pass: detect Screen before prelude so emit_prelude can add screen helpers.
        self.detect_screen(program);

        self.line("// Generated by boring build --target metal.");
        self.line("#![allow(dead_code, unused_variables, unused_parens, unexpected_cfgs)]");
        self.blank();
        self.emit_prelude();

        for item in &program.items {
            match item {
                Item::Kernel(decl) => {
                    self.blank();
                    self.emit_kernel_struct(decl);
                }
                Item::Fn(f) => {
                    self.blank();
                    self.emit_fn(f, None);
                }
                Item::Struct(s) => {
                    self.blank();
                    self.emit_struct(s);
                }
                Item::Enum(e) => {
                    self.blank();
                    self.emit_enum(e);
                }
                Item::Stmt(_) | Item::Let(_) => {}
                _ => {}
            }
        }

        let has_stmts = program.items.iter().any(|i| matches!(i, Item::Stmt(_) | Item::Let(_)));
        if has_stmts || !kernel_names.is_empty() {
            self.blank();
            self.line("fn main() -> Result<(), Box<dyn std::error::Error>> {");
            self.indent += 1;
            let mut screen_setup_emitted = false;
            for item in &program.items {
                match item {
                    Item::Let(s) => {
                        // Skip `let screen = Screen(...)` — replaced by emit_screen_setup().
                        if self.screen_var.as_deref() == Some(s.name.as_str()) {
                            if !screen_setup_emitted {
                                self.emit_screen_setup();
                                screen_setup_emitted = true;
                            }
                            continue;
                        }
                        let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                        let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                        if let Some(val) = &s.value {
                            self.track_kernel_var(&s.name, val);
                            let rhs = self.expr(val);
                            // Track scalar top-level lets so they can be inlined
                            // inside kernel new() functions where they are not in scope.
                            let is_scalar = matches!(val.kind,
                                ExprKind::Int(_) | ExprKind::Float(_) | ExprKind::Bool(_)
                            ) || s.ty.as_ref().map(|t| matches!(t,
                                Type::Int | Type::Uint | Type::Float | Type::Bool
                            )).unwrap_or(false);
                            if is_scalar {
                                self.top_level_scalars.insert(s.name.clone(), rhs.clone());
                            }
                            self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                        }
                    }
                    Item::Stmt(stmt) => self.emit_stmt(stmt),
                    _ => {}
                }
            }
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }
    }

    // ── Metal prelude ──────────────────────────────────────────────────────────

    fn emit_prelude(&mut self) {
        self.line("use metal::*;");
        self.line("use std::mem;");
        self.blank();
        self.line("const BORING_MSL: &str = include_str!(\"../kernels/main.metal\");");
        self.blank();
        // Default device helper.
        self.line("fn boring_metal_device() -> Device {");
        self.indent += 1;
        self.line("Device::system_default().expect(\"no Metal device found — macOS 10.14+ required\")");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // GPU(n) → indexed device.
        self.line("fn boring_metal_device_n(idx: usize) -> Result<Device, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("let devices = Device::all();");
        self.line("devices.into_iter().nth(idx)");
        self.indent += 1;
        self.line(".ok_or_else(|| format!(\"GPU index {} out of range\", idx).into())");
        self.indent -= 1;
        self.indent -= 1;
        self.line("}");
        self.blank();
        // GPU family tier helper (computeCapability equivalent).
        self.line("fn boring_gpu_family(device: &Device) -> Vec<i64> {");
        self.indent += 1;
        self.line("let families: &[(MTLGPUFamily, [i64; 2])] = &[");
        self.indent += 1;
        self.line("(MTLGPUFamily::Apple9, [9, 0]),");
        self.line("(MTLGPUFamily::Apple8, [8, 0]),");
        self.line("(MTLGPUFamily::Apple7, [7, 0]),");
        self.line("(MTLGPUFamily::Apple6, [6, 0]),");
        self.line("(MTLGPUFamily::Apple5, [5, 0]),");
        self.line("(MTLGPUFamily::Apple4, [4, 0]),");
        self.line("(MTLGPUFamily::Apple3, [3, 0]),");
        self.line("(MTLGPUFamily::Apple2, [2, 0]),");
        self.line("(MTLGPUFamily::Apple1, [1, 0]),");
        self.indent -= 1;
        self.line("];");
        self.line("for (family, ver) in families {");
        self.indent += 1;
        self.line("if device.supports_family(*family) { return ver.to_vec(); }");
        self.indent -= 1;
        self.line("}");
        self.line("vec![0, 0]");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // KernelHandle — Metal is synchronous (wait_until_completed in __boring_launch).
        self.line("struct KernelHandle<T> { inner: T }");
        self.line("impl<T> KernelHandle<T> {");
        self.indent += 1;
        self.line("fn wait(self) -> T { self.inner }");
        self.line("fn done(&self) -> bool { true }");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // Boring built-in Dimension type used by 2-D kernels.
        self.line(crate::transpiler::helpers::DIMENSION_STRUCT_RUST);
        if self.screen_var.is_some() {
            self.emit_screen_prelude();
        }
    }

    // ── Screen / display support ───────────────────────────────────────────────

    fn detect_screen(&mut self, program: &Program) {
        for item in &program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    if let ExprKind::Call(callee, args) = &val.kind {
                        if let ExprKind::Var(name) = &callee.kind {
                            if name == "Screen" {
                                let (w, h) = args.first()
                                    .map(|a| {
                                        if let ExprKind::Call(c2, a2) = &a.value.kind {
                                            if let ExprKind::Var(n) = &c2.kind {
                                                if n == "Dimension" {
                                                    let w = a2.first().map(|x| self.expr(&x.value)).unwrap_or_else(|| "800".into());
                                                    let h = a2.get(1).map(|x| self.expr(&x.value)).unwrap_or_else(|| "600".into());
                                                    return (w, h);
                                                }
                                            }
                                        }
                                        ("800".into(), "600".into())
                                    })
                                    .unwrap_or_else(|| ("800".into(), "600".into()));
                                let title_expr = args.iter()
                                    .find(|a| a.label.as_deref() == Some("title"))
                                    .or_else(|| args.get(1))
                                    .map(|a| self.expr(&a.value))
                                    .unwrap_or_else(|| "\"Boring\"".into());
                                let title_str = if title_expr.starts_with('"') && title_expr.ends_with('"') {
                                    title_expr[1..title_expr.len()-1].to_string()
                                } else {
                                    "Boring".to_string()
                                };
                                self.screen_var = Some(s.name.clone());
                                self.screen_width_expr = w;
                                self.screen_height_expr = h;
                                self.screen_title = title_str;
                                return;
                            }
                        }
                    }
                }
            }
        }
    }

    fn emit_screen_prelude(&mut self) {
        self.blank();
        self.line("#[macro_use] extern crate objc;");
        self.blank();
        self.line("fn boring_screen_present(");
        self.indent += 1;
        self.line("layer: &metal::MetalLayer,");
        self.line("queue: &metal::CommandQueue,");
        self.line("src: &metal::Buffer,");
        self.line("width: u64,");
        self.line("height: u64,");
        self.indent -= 1;
        self.line(") {");
        self.indent += 1;
        self.line("let drawable = match layer.next_drawable() { Some(d) => d, None => return };");
        self.line("let cmd_buf = queue.new_command_buffer();");
        self.line("let blit = cmd_buf.new_blit_command_encoder();");
        self.line("blit.copy_from_buffer_to_texture(");
        self.indent += 1;
        self.line("src, 0, width * 4, width * height * 4,");
        self.line("metal::MTLSize { width, height, depth: 1 },");
        self.line("drawable.texture(), 0, 0,");
        self.line("metal::MTLOrigin { x: 0, y: 0, z: 0 },");
        self.line("metal::MTLBlitOption::empty(),");
        self.indent -= 1;
        self.line(");");
        self.line("blit.end_encoding();");
        self.line("cmd_buf.present_drawable(&drawable);");
        self.line("cmd_buf.commit();");
        self.line("cmd_buf.wait_until_completed();");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("fn boring_key_str(key: winit::event::VirtualKeyCode) -> String {");
        self.indent += 1;
        self.line("use winit::event::VirtualKeyCode::*;");
        self.line("match key {");
        self.indent += 1;
        self.line("Escape => \"\\x1B\".into(),");
        self.line("Space => \" \".into(),");
        self.line("Return => \"\\r\".into(),");
        self.line("Up => \"\\x1B[A\".into(),");
        self.line("Down => \"\\x1B[B\".into(),");
        self.line("Left => \"\\x1B[D\".into(),");
        self.line("Right => \"\\x1B[C\".into(),");
        self.line("A => \"a\".into(), B => \"b\".into(), C => \"c\".into(),");
        self.line("D => \"d\".into(), E => \"e\".into(), F => \"f\".into(),");
        self.line("G => \"g\".into(), H => \"h\".into(), I => \"i\".into(),");
        self.line("J => \"j\".into(), K => \"k\".into(), L => \"l\".into(),");
        self.line("M => \"m\".into(), N => \"n\".into(), O => \"o\".into(),");
        self.line("P => \"p\".into(), Q => \"q\".into(), R => \"r\".into(),");
        self.line("S => \"s\".into(), T => \"t\".into(), U => \"u\".into(),");
        self.line("V => \"v\".into(), W => \"w\".into(), X => \"x\".into(),");
        self.line("Y => \"y\".into(), Z => \"z\".into(),");
        self.line("Key1 => \"1\".into(), Key2 => \"2\".into(), Key3 => \"3\".into(),");
        self.line("Key4 => \"4\".into(), Key5 => \"5\".into(), Key6 => \"6\".into(),");
        self.line("Key7 => \"7\".into(), Key8 => \"8\".into(), Key9 => \"9\".into(),");
        self.line("Key0 => \"0\".into(),");
        self.line("_ => format!(\"{:?}\", key).to_lowercase(),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_screen_setup(&mut self) {
        let w = self.screen_width_expr.clone();
        let h = self.screen_height_expr.clone();
        let title = self.screen_title.clone();
        self.line("use winit::platform::run_return::EventLoopExtRunReturn;");
        self.line("let mut boring_event_loop = winit::event_loop::EventLoop::new();");
        self.line("let boring_window = winit::window::WindowBuilder::new()");
        self.indent += 1;
        self.line(&format!(".with_title(\"{}\")", title));
        self.line(&format!(".with_inner_size(winit::dpi::LogicalSize::new({w} as u32, {h} as u32))"));
        self.line(".build(&boring_event_loop)?;");
        self.indent -= 1;
        self.line("let boring_device = boring_metal_device();");
        self.line("let boring_layer = metal::MetalLayer::new();");
        self.line("boring_layer.set_device(&boring_device);");
        self.line("boring_layer.set_pixel_format(metal::MTLPixelFormat::BGRA8Unorm);");
        self.line("boring_layer.set_framebuffer_only(false);");
        self.line(&format!("boring_layer.set_drawable_size(core_graphics::geometry::CGSize::new({w} as f64, {h} as f64));"));
        self.line("unsafe {");
        self.indent += 1;
        self.line("use winit::platform::macos::WindowExtMacOS;");
        self.line("use objc::runtime::*;");
        self.line("let ns_view = boring_window.ns_view() as *mut Object;");
        self.line("let () = objc::msg_send![ns_view, setLayer: boring_layer.as_ref()];");
        self.line("let () = objc::msg_send![ns_view, setWantsLayer: YES];");
        self.indent -= 1;
        self.line("}");
        self.line("let boring_queue = boring_device.new_command_queue();");
        self.line("let mut boring_frame: i64 = 0;");
        self.line("let boring_start = std::time::Instant::now();");
        self.line("let mut boring_keys: std::collections::HashSet<String> = Default::default();");
        self.line(&format!("let mut boring_screen_width: i64 = {w};"));
        self.line(&format!("let mut boring_screen_height: i64 = {h};"));
        self.line("let mut boring_screen_resized = false;");
        self.line("let mut boring_screen_closed = false;");
    }

    fn emit_render_loop(&mut self, loop_body: &[Stmt]) {
        self.line("boring_event_loop.run_return(|__boring_event, _, __boring_cf| {");
        self.indent += 1;
        self.line("*__boring_cf = winit::event_loop::ControlFlow::Poll;");
        self.line("boring_screen_resized = false;");
        self.line("match __boring_event {");
        self.indent += 1;
        self.line("winit::event::Event::WindowEvent { event: winit::event::WindowEvent::CloseRequested, .. } => {");
        self.indent += 1;
        self.line("boring_screen_closed = true;");
        self.line("*__boring_cf = winit::event_loop::ControlFlow::Exit;");
        self.indent -= 1;
        self.line("}");
        self.line("winit::event::Event::WindowEvent { event: winit::event::WindowEvent::Resized(__boring_size), .. } => {");
        self.indent += 1;
        self.line("boring_screen_width = __boring_size.width as i64;");
        self.line("boring_screen_height = __boring_size.height as i64;");
        self.line("boring_screen_resized = true;");
        // Don't resize the drawable — it stays fixed at the surface buffer dimensions.
        self.indent -= 1;
        self.line("}");
        self.line("winit::event::Event::WindowEvent { event: winit::event::WindowEvent::KeyboardInput { input: __boring_ki, .. }, .. } => {");
        self.indent += 1;
        self.line("if let Some(__boring_key) = __boring_ki.virtual_keycode {");
        self.indent += 1;
        self.line("let __boring_ks = boring_key_str(__boring_key);");
        self.line("match __boring_ki.state {");
        self.indent += 1;
        self.line("winit::event::ElementState::Pressed  => { boring_keys.insert(__boring_ks); }");
        self.line("winit::event::ElementState::Released => { boring_keys.remove(&__boring_ks); }");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("winit::event::Event::MainEventsCleared => {");
        self.indent += 1;
        self.in_render_loop = true;
        let stmts: Vec<Stmt> = loop_body.to_vec();
        for stmt in &stmts {
            self.emit_render_loop_stmt(stmt);
        }
        self.in_render_loop = false;
        self.line("boring_frame += 1;");
        self.indent -= 1;
        self.line("}");
        self.line("_ => {}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("});");
    }

    fn emit_render_loop_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Break(_, _) => {
                self.line("*__boring_cf = winit::event_loop::ControlFlow::Exit;");
                self.line("return;");
            }
            Stmt::Expr(e) => {
                // screen.present(pixels) special case
                if let ExprKind::MethodCall(obj, method, args) = &e.kind {
                    let screen_var = self.screen_var.clone();
                    if let ExprKind::Var(v) = &obj.kind {
                        if Some(v.as_str()) == screen_var.as_deref() && method == "present" {
                            if let Some(pixels_arg) = args.first() {
                                let pixels_ref = self.emit_pixels_ref(&pixels_arg.value);
                                // Use surface's own Dimension for blit, not window size.
                                let (w_expr, h_expr) = if let ExprKind::Field(pobj, pfield) = &pixels_arg.value.kind {
                                    if let ExprKind::Var(kvar) = &pobj.kind {
                                        let dim_field = self.kernel_decls.values()
                                            .find(|kd| kd.fields.iter().any(|f| &f.name == pfield && matches!(f.qual, GpuQual::Surface)))
                                            .and_then(|kd| kd.fields.iter().find(|f| matches!(&f.ty, Type::Named(n) if n == "Dimension")))
                                            .map(|f| f.name.clone());
                                        if let Some(df) = dim_field {
                                            (format!("{}.{}.width as u64", kvar, df),
                                             format!("{}.{}.height as u64", kvar, df))
                                        } else {
                                            ("boring_screen_width as u64".into(), "boring_screen_height as u64".into())
                                        }
                                    } else {
                                        ("boring_screen_width as u64".into(), "boring_screen_height as u64".into())
                                    }
                                } else {
                                    ("boring_screen_width as u64".into(), "boring_screen_height as u64".into())
                                };
                                self.line(&format!(
                                    "boring_screen_present(&boring_layer, &boring_queue, {pixels_ref}, {w_expr}, {h_expr});"
                                ));
                                return;
                            }
                        }
                    }
                }
                if let ExprKind::Assign(lhs, rhs) = &e.kind {
                    let l = self.expr(lhs);
                    let r = self.expr(rhs);
                    self.line(&format!("{l} = {r};"));
                } else if let Some(launch) = self.try_emit_kernel_launch_call(e) {
                    self.line(&format!("{launch};"));
                } else {
                    let s = self.expr(e);
                    self.line(&format!("{s};"));
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if {c} {{")); }
                    else { self.line(&format!("}} else if {c} {{")); }
                    self.indent += 1;
                    let body_clone: Vec<Stmt> = body.to_vec();
                    for s in &body_clone { self.emit_render_loop_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    let else_clone: Vec<Stmt> = else_body.to_vec();
                    for s in &else_clone { self.emit_render_loop_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            other => self.emit_stmt(other),
        }
    }

    fn emit_pixels_ref(&mut self, e: &Expr) -> String {
        if let ExprKind::Field(obj, field) = &e.kind {
            if let ExprKind::Var(obj_name) = &obj.kind {
                return format!("&{}.{}", obj_name, field);
            }
        }
        format!("&{}", self.expr(e))
    }

    // ── Kernel struct → Rust host wrapper ─────────────────────────────────────

    fn emit_kernel_struct(&mut self, decl: &KernelDecl) {
        let name = &decl.name;

        self.line(&format!("struct {} {{", name));
        self.indent += 1;
        self.line("__device: Device,");
        self.line("__queue: CommandQueue,");
        self.line("__pipeline: ComputePipelineState,");
        for field in &decl.fields {
            match field.qual {
                GpuQual::Sync | GpuQual::Local => {}
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const | GpuQual::Surface => {
                    match &field.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => {
                            self.line(&format!("{}: Buffer,", field.name));
                        }
                        _ => {
                            let ty = rust_type(&field.ty);
                            self.line(&format!("{}: {},", field.name, ty));
                        }
                    }
                }
            }
        }
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Local) {
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        let ty = rust_type(&field.ty);
                        self.line(&format!("{}: {},", field.name, ty));
                    }
                }
            }
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line(&format!("impl {} {{", name));
        self.indent += 1;

        for init in &decl.inits {
            self.emit_kernel_new(name, &decl.fields, init);
            self.blank();
        }
        if decl.inits.is_empty() {
            self.emit_kernel_new_default(name, &decl.fields);
            self.blank();
        }

        // Read accessors for 'unified/'global array fields (D2H).
        for field in &decl.fields {
            match field.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                    if matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        let elem = elem_rust_type(&field.ty);
                        self.line(&format!(
                            "fn read_{}(&self) -> Vec<{}> {{",
                            field.name, elem
                        ));
                        self.indent += 1;
                        self.line(&format!(
                            "let n = self.{}.length() as usize / mem::size_of::<{}>();",
                            field.name, elem
                        ));
                        self.line(&format!(
                            "let ptr = self.{}.contents() as *const {};",
                            field.name, elem
                        ));
                        self.line("unsafe { std::slice::from_raw_parts(ptr, n).to_vec() }");
                        self.indent -= 1;
                        self.line("}");
                        self.blank();
                    }
                }
                _ => {}
            }
        }

        self.emit_boring_launch(name, &decl.fields);

        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new(&mut self, name: &str, fields: &[KernelFieldDecl], init: &InitDecl) {
        let params: Vec<String> = init.params.iter().map(|p| {
            let ty = p.ty.as_ref()
                .map(host_param_type)
                .unwrap_or_else(|| "()".into());
            format!("{}: {}", p.name, ty)
        }).collect();

        let all_params = if params.is_empty() {
            "__device: Device".into()
        } else {
            format!("__device: Device, {}", params.join(", "))
        };

        self.line(&format!(
            "fn new({}) -> Result<Self, Box<dyn std::error::Error>> {{",
            all_params
        ));
        self.indent += 1;

        self.emit_pipeline_init(name);

        let assigned: std::collections::HashSet<String> = init.body.iter()
            .filter_map(|s| match s {
                Stmt::Expr(e) => {
                    if let ExprKind::Assign(lhs, _) = &e.kind {
                        if let ExprKind::Var(n) = &lhs.kind { Some(n.clone()) }
                        else { None }
                    } else { None }
                }
                _ => None,
            }).collect();

        for stmt in &init.body {
            self.emit_init_stmt(stmt, fields);
        }

        for field in fields {
            if !assigned.contains(&field.name) {
                self.emit_field_default(field);
            }
        }

        self.emit_struct_literal(name, fields);
        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new_default(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        self.line("fn new(__device: Device) -> Result<Self, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.emit_pipeline_init(name);
        for field in fields {
            self.emit_field_default(field);
        }
        self.emit_struct_literal(name, fields);
        self.indent -= 1;
        self.line("}");
    }

    fn emit_pipeline_init(&mut self, kernel_name: &str) {
        self.line("let __queue = __device.new_command_queue();");
        self.line("let __options = CompileOptions::new();");
        self.line("let __library = __device.new_library_with_source(BORING_MSL, &__options)");
        self.indent += 1;
        self.line(".map_err(|e| format!(\"MSL compile error: {}\", e))?;");
        self.indent -= 1;
        self.line(&format!(
            "let __func = __library.get_function(\"{}_kernel\", None)",
            kernel_name
        ));
        self.indent += 1;
        self.line(".map_err(|e| format!(\"kernel function not found: {}\", e))?;");
        self.indent -= 1;
        self.line("let __pipeline = __device.new_compute_pipeline_state_with_function(&__func)?;");
    }

    fn emit_field_default(&mut self, field: &KernelFieldDecl) {
        match field.qual {
            GpuQual::Surface => {
                // Surface pixel buffer defaults to single-pixel placeholder (32-bit)
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        self.line(&format!(
                            "let {}: Buffer = __device.new_buffer(mem::size_of::<u32>() as u64, MTLResourceOptions::StorageModeShared);",
                            field.name
                        ));
                    }
                    _ => {
                        let ty = rust_type(&field.ty);
                        let val = field.default.as_ref()
                            .map(emit_scalar_default)
                            .unwrap_or_else(|| "Default::default()".into());
                        self.line(&format!("let {}: {} = {};", field.name, ty, val));
                    }
                }
            }
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                match &field.ty {
                    Type::Array(inner) | Type::ArrayN(inner, _) => {
                        let elem = rust_type(inner);
                        self.line(&format!(
                            "let {}: Buffer = __device.new_buffer(mem::size_of::<{}>() as u64, MTLResourceOptions::StorageModeShared);",
                            field.name, elem
                        ));
                    }
                    _ => {
                        let ty = rust_type(&field.ty);
                        let val = field.default.as_ref()
                            .map(emit_scalar_default)
                            .unwrap_or_else(|| "Default::default()".into());
                        self.line(&format!("let {}: {} = {};", field.name, ty, val));
                    }
                }
            }
            GpuQual::Sync => {}
            GpuQual::Local => {
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        let ty = rust_type(&field.ty);
                        let val = field.default.as_ref()
                            .map(emit_scalar_default)
                            .unwrap_or_else(|| "Default::default()".into());
                        self.line(&format!("let {}: {} = {};", field.name, ty, val));
                    }
                }
            }
        }
    }

    fn emit_struct_literal(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        self.line(&format!("Ok({} {{", name));
        self.indent += 1;
        self.line("__device,");
        self.line("__queue,");
        self.line("__pipeline,");
        for field in fields {
            match field.qual {
                GpuQual::Sync => {}
                GpuQual::Local => match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => self.line(&format!("{},", field.name)),
                },
                _ => match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => self.line(&format!("{},", field.name)),
                    _ => self.line(&format!("{},", field.name)),
                }
            }
        }
        self.indent -= 1;
        self.line("})");
    }

    fn emit_init_stmt(&mut self, stmt: &Stmt, fields: &[KernelFieldDecl]) {
        match stmt {
            Stmt::Expr(e) => {
                if let ExprKind::Assign(lhs, rhs) = &e.kind {
                    if let ExprKind::Var(fname) = &lhs.kind {
                        if let Some(field) = fields.iter().find(|f| &f.name == fname) {
                            match field.qual {
                                GpuQual::Surface => {
                                    // Surface pixel buffer: always 32-bit (BGRA8Unorm = 4 bytes/pixel)
                                    match &rhs.kind {
                                        ExprKind::ArrayFill { value: _, count } | ExprKind::ArrayAlloc { count } => {
                                            let n = self.expr(count);
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer(({n} as usize * mem::size_of::<u32>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        ExprKind::Array(elems) => {
                                            let lit: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                                            self.line(&format!(
                                                "let __data_{fname}: Vec<u32> = vec![{}];", lit.join(", ")
                                            ));
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer_with_data(__data_{fname}.as_ptr() as *const _, (__data_{fname}.len() * mem::size_of::<u32>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        _ => {
                                            let rhs_s = self.expr(rhs);
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer_with_data({rhs_s}.as_ptr() as *const _, ({rhs_s}.len() * mem::size_of::<u32>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                    }
                                }
                                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                                    match &rhs.kind {
                                        ExprKind::ArrayFill { value: _, count } | ExprKind::ArrayAlloc { count } => {
                                            let n = self.expr(count);
                                            let elem = elem_rust_type(&field.ty);
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer(({n} as usize * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        ExprKind::Array(elems) => {
                                            let elem = elem_rust_type(&field.ty);
                                            let lit: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                                            self.line(&format!(
                                                "let __data_{fname}: Vec<{elem}> = vec![{}];", lit.join(", ")
                                            ));
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer_with_data(__data_{fname}.as_ptr() as *const _, (__data_{fname}.len() * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        _ => {
                                            let rhs_s = self.expr(rhs);
                                            match &field.ty {
                                                Type::Array(_) | Type::ArrayN(_, _) => {
                                                    let elem = elem_rust_type(&field.ty);
                                                    self.line(&format!(
                                                        "let {fname}: Buffer = __device.new_buffer_with_data({rhs_s}.as_ptr() as *const _, ({rhs_s}.len() * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                                    ));
                                                }
                                                _ => {
                                                    // Scalar 'const field: store the value directly.
                                                    let ty = rust_type(&field.ty);
                                                    self.line(&format!("let {fname}: {ty} = {rhs_s};"));
                                                }
                                            }
                                            return;
                                        }
                                    }
                                }
                                GpuQual::Local | GpuQual::Sync => {
                                    // Scalar/struct field — emit as local variable declaration
                                    let rhs_s = self.expr(rhs);
                                    let ty = rust_type(&field.ty);
                                    self.line(&format!("let {fname}: {ty} = {rhs_s};"));
                                    return;
                                }
                            }
                        }
                    }
                }
                let s = self.expr(e);
                self.line(&format!("{};", s));
            }
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{} {} = {};", binding, s.name, rhs));
                }
            }
            _ => self.emit_stmt(stmt),
        }
    }

    fn emit_boring_launch(&mut self, _name: &str, fields: &[KernelFieldDecl]) {
        // Auto-grid when there is at least one device array field.
        let auto_grid_field: Option<String> = fields.iter().find_map(|f| {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => Some(f.name.clone()),
                        _ => None,
                    }
                }
                _ => None,
            }
        });

        if auto_grid_field.is_some() {
            self.line(
                "fn __boring_launch(&mut self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, _after: &[()]) \
                 -> Result<(), Box<dyn std::error::Error>> {"
            );
        } else {
            self.line(
                "fn __boring_launch(&mut self, block_dim: (u32,u32,u32), grid_dim: (u32,u32,u32), _after: &[()]) \
                 -> Result<(), Box<dyn std::error::Error>> {"
            );
        }
        self.indent += 1;

        // Grid sizing.
        if let Some(field) = &auto_grid_field {
            let field_qual = fields.iter().find(|f| &f.name == field).map(|f| &f.qual).cloned();
            let is_surface = matches!(field_qual, Some(GpuQual::Surface));
            let dim_field = if is_surface {
                fields.iter().find(|f| matches!(&f.ty, Type::Named(n) if n == "Dimension"))
                    .map(|f| f.name.clone())
            } else {
                None
            };
            self.line("let grid_dim = grid_dim.unwrap_or_else(|| {");
            self.indent += 1;
            if let Some(df) = dim_field {
                // 2D grid from surface Dimension field
                self.line(&format!("let __w = self.{}.width; let __h = self.{}.height;", df, df));
                self.line("((__w + block_dim.0 - 1) / block_dim.0, (__h + block_dim.1 - 1) / block_dim.1, 1)");
            } else if is_surface {
                // 1D fallback for surface without Dimension — use u32 element size
                self.line(&format!(
                    "let n = (self.{}.length() as usize / mem::size_of::<u32>()) as u32;",
                    field
                ));
                self.line("((n + block_dim.0 - 1) / block_dim.0, 1, 1)");
            } else {
                let elem = elem_rust_type(&fields.iter().find(|f| &f.name == field).unwrap().ty);
                self.line(&format!(
                    "let n = (self.{}.length() as usize / mem::size_of::<{}>()) as u32;",
                    field, elem
                ));
                self.line("((n + block_dim.0 - 1) / block_dim.0, 1, 1)");
            }
            self.indent -= 1;
            self.line("});");
        }

        // Dynamic shared memory size (per-block).
        let _dyn_shared_terms: Vec<String> = fields.iter()
            .filter(|f| matches!(f.qual, GpuQual::Sync))
            .filter_map(|f| {
                if let Type::Array(inner) = &f.ty {
                    let sz = elem_size_bytes(inner);
                    Some(format!("block_dim.0 as usize * {}", sz))
                } else {
                    None
                }
            })
            .collect();

        // Dispatch.
        self.line("let __cmd_buf = self.__queue.new_command_buffer();");
        self.line("let __encoder = __cmd_buf.new_compute_command_encoder();");
        self.line("__encoder.set_compute_pipeline_state(&self.__pipeline);");

        // Set buffers in the same order as MSL parameters.
        let mut buf_idx: u64 = 0;
        let mut tg_idx: u64 = 0;

        for f in fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                    if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        self.line(&format!("__encoder.set_buffer({}, Some(&self.{}), 0);", buf_idx, f.name));
                        buf_idx += 1;
                    }
                }
                _ => {}
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Const) {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                    self.line(&format!("__encoder.set_buffer({}, Some(&self.{}), 0);", buf_idx, f.name));
                } else {
                    let elem = elem_rust_type(&f.ty);
                    self.line(&format!(
                        "__encoder.set_bytes({}, mem::size_of::<{}>() as u64, &self.{} as *const _ as *const _);",
                        buf_idx, elem, f.name
                    ));
                }
                buf_idx += 1;
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Local) && !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                let elem = rust_type(&f.ty);
                self.line(&format!(
                    "__encoder.set_bytes({}, mem::size_of::<{}>() as u64, &self.{} as *const _ as *const _);",
                    buf_idx, elem, f.name
                ));
                buf_idx += 1;
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Sync) && matches!(f.ty, Type::Array(_)) {
                if let Type::Array(inner) = &f.ty {
                    let sz = elem_size_bytes(inner);
                    self.line(&format!(
                        "__encoder.set_threadgroup_memory_length({}, (block_dim.0 as usize * {}) as u64);",
                        tg_idx, sz
                    ));
                    tg_idx += 1;
                }
            }
        }

        // Static shared memory doesn't need set_threadgroup_memory_length — declared in MSL.
        let _ = tg_idx;

        self.line("__encoder.dispatch_thread_groups(");
        self.indent += 1;
        self.line("MTLSize { width: grid_dim.0 as u64, height: grid_dim.1 as u64, depth: grid_dim.2 as u64 },");
        self.line("MTLSize { width: block_dim.0 as u64, height: block_dim.1 as u64, depth: block_dim.2 as u64 },");
        self.indent -= 1;
        self.line(");");
        self.line("__encoder.end_encoding();");
        self.line("__cmd_buf.commit();");
        self.line("__cmd_buf.wait_until_completed();");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
    }

    // ── Regular items ──────────────────────────────────────────────────────────

    fn emit_fn(&mut self, f: &FnDecl, self_ty: Option<&str>) {
        if f.is_native { return; }
        let vis = if f.is_pub { "pub " } else { "" };
        let params: Vec<String> = f.params.iter().map(|p| {
            let name = if p.mutable { format!("mut {}", p.name) } else { p.name.clone() };
            match &p.ty {
                Some(ty) => format!("{}: {}", name, rust_type(ty)),
                None => name,
            }
        }).collect();
        let all_params = match self_ty {
            Some(_) => {
                let s = if f.mutating { "&mut self" } else { "&self" };
                if params.is_empty() { s.to_string() } else { format!("{}, {}", s, params.join(", ")) }
            }
            None => params.join(", "),
        };
        let ret = f.return_ty.as_ref().map(rust_type).unwrap_or_else(|| "()".into());
        let sig = format!("{}fn {}({}) -> {}", vis, f.name, all_params, ret);
        if f.body.is_empty() {
            self.line(&format!("{} {{}}", sig));
            return;
        }
        self.line(&format!("{} {{", sig));
        self.indent += 1;
        let len = f.body.len();
        for (i, stmt) in f.body.iter().enumerate() {
            if i + 1 == len { self.emit_stmt_last(stmt); } else { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_struct(&mut self, s: &StructDecl) {
        if s.is_native { return; }
        let vis = if s.is_pub { "pub " } else { "" };
        self.line(&format!("{}struct {} {{", vis, s.name));
        self.indent += 1;
        for f in &s.fields {
            let fvis = if f.is_pub { "pub " } else { "" };
            self.line(&format!("{}{}: {},", fvis, f.name, rust_type(&f.ty)));
        }
        self.indent -= 1;
        self.line("}");
        if !s.methods.is_empty() {
            self.blank();
            self.line(&format!("impl {} {{", s.name));
            self.indent += 1;
            for m in &s.methods { self.emit_fn(m, Some(&s.name)); self.blank(); }
            self.indent -= 1;
            self.line("}");
        }
    }

    fn emit_enum(&mut self, e: &EnumDecl) {
        if e.is_native { return; }
        let vis = if e.is_pub { "pub " } else { "" };
        self.line(&format!("{}enum {} {{", vis, e.name));
        self.indent += 1;
        for v in &e.variants {
            if v.fields.is_empty() {
                self.line(&format!("{},", v.name));
            } else {
                let fs: Vec<String> = v.fields.iter().map(|f| rust_type(&f.ty)).collect();
                self.line(&format!("{}({}),", v.name, fs.join(", ")));
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ─────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                if let Some(val) = &s.value {
                    self.track_kernel_var(&s.name, val);
                    let rhs = self.expr(val);
                    self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                } else {
                    self.line(&format!("{} {}{};", binding, s.name, ty_ann));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    ExprKind::Assign(lhs, rhs) => {
                        let l = self.expr(lhs);
                        let r = self.expr(rhs);
                        self.line(&format!("{} = {};", l, r));
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if {} {{", c)); }
                    else        { self.line(&format!("}} else if {} {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while {} {{", cond));
                self.indent += 1;
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let is_enumerate = f.vars.len() >= 2;
                let var = if is_enumerate {
                    format!("({}, {})", f.vars[0], f.vars[1])
                } else {
                    f.vars.first().cloned().unwrap_or_else(|| "_i".into())
                };
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let range = if *inclusive { format!("{}..={}", lo, hi) } else { format!("{}..{}", lo, hi) };
                        self.line(&format!("for {} in {} {{", var, range));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        if is_enumerate {
                            self.line(&format!("for {} in {}.iter().enumerate() {{", var, iter));
                        } else {
                            self.line(&format!("for {} in {} {{", var, iter));
                        }
                    }
                }
                self.indent += 1;
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            Stmt::Comment(_)          => {}
            Stmt::KernelBlock(kb) => self.emit_kernel_block(&kb.body),
            _ => { self.line("/* unsupported stmt */"); }
        }
    }

    fn emit_kernel_block(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            match stmt {
                Stmt::Expr(e) => {
                    if let Some(launch) = self.try_emit_kernel_launch_call(e) {
                        self.line(&format!("{launch};"));
                    } else {
                        let s = self.expr(e);
                        self.line(&format!("{s};"));
                    }
                }
                Stmt::Loop(l) => {
                    if self.screen_var.is_some() {
                        let body = l.body.clone();
                        self.emit_render_loop(&body);
                    } else {
                        self.line("loop {");
                        self.indent += 1;
                        for s in &l.body { self.emit_stmt(s); }
                        self.indent -= 1;
                        self.line("}");
                    }
                }
                other => self.emit_stmt(other),
            }
        }
    }

    fn try_emit_kernel_launch_call(&mut self, expr: &Expr) -> Option<String> {
        let ExprKind::Call(callee, args) = &expr.kind else { return None; };
        let ExprKind::Var(var_name) = &callee.kind else { return None; };
        let has_block = args.iter().any(|a| a.label.as_deref() == Some("block"));
        if !has_block { return None; }
        let is_kernel = self.var_kernel_type.contains_key(var_name.as_str())
            || self.kernel_names.contains(var_name.as_str());
        if !is_kernel { return None; }
        let kernel_type = self.var_kernel_type.get(var_name.as_str()).cloned()
            .or_else(|| Some(var_name.clone()));
        let auto_grid = kernel_type
            .as_ref()
            .and_then(|t| self.kernel_decls.get(t))
            .map(|decl| decl.fields.iter().any(|f|
                matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
                && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))))
            .unwrap_or(false);
        let block = args.iter().find(|a| a.label.as_deref() == Some("block"))
            .map(|a| self.dim3_expr(&a.value))
            .unwrap_or_else(|| "(1, 1, 1)".into());
        let grid: String = if let Some(g) = args.iter().find(|a| a.label.as_deref() == Some("grid")) {
            if auto_grid { format!("Some({})", self.dim3_expr(&g.value)) }
            else { self.dim3_expr(&g.value) }
        } else if auto_grid { "None".into() } else { "(1, 1, 1)".into() };
        // Metal is synchronous (&mut self, no move needed — wait_until_completed inside).
        // In render loop closures, ? is unavailable — use expect() instead.
        let launch = if self.in_render_loop {
            format!("{var_name}.__boring_launch({block}, {grid}, &[]).expect(\"kernel launch failed\")")
        } else {
            format!("{var_name}.__boring_launch({block}, {grid}, &[])?")
        };
        Some(launch)
    }

    fn emit_stmt_last(&mut self, stmt: &Stmt) {
        if let Stmt::Expr(e) = stmt {
            let s = self.expr(e);
            self.line(&s);
        } else {
            self.emit_stmt(stmt);
        }
    }

    // ── Expressions ────────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)    => n.to_string(),
            ExprKind::Float(f)  => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)   => if *b { "true".into() } else { "false".into() },
            ExprKind::Str(s)    => format!("\"{}\"", s),
            ExprKind::Nil       => "None".into(),
            ExprKind::Void      => "()".into(),
            ExprKind::Var(name) => {
                // Inline top-level scalars when referenced inside kernel new()
                // where they are not in scope as Rust local variables.
                self.top_level_scalars.get(name).cloned().unwrap_or_else(|| name.clone())
            }

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_rust(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_rust(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                if let ExprKind::Field(obj, field) = &arr.kind {
                    if let ExprKind::Var(obj_name) = &obj.kind {
                        if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                            let i = self.expr(idx);
                            return format!("{}[{} as usize]", read_call, i);
                        }
                    }
                }
                format!("{}[{} as usize]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                if let ExprKind::Var(obj_name) = &obj.kind {
                    // screen.X → boring_screen_* variables
                    if self.screen_var.as_deref() == Some(obj_name.as_str()) {
                        return match field.as_str() {
                            "frame"     => "boring_frame".into(),
                            "time"      => "boring_start.elapsed().as_secs_f64()".into(),
                            "closed"    => "boring_screen_closed".into(),
                            "resized"   => "boring_screen_resized".into(),
                            "width"     => "boring_screen_width".into(),
                            "height"    => "boring_screen_height".into(),
                            "dimension" => "Dimension(boring_screen_width as u32, boring_screen_height as u32)".into(),
                            other       => format!("boring_screen_{}", other),
                        };
                    }
                    if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                        return read_call;
                    }
                }
                let o = self.expr(obj);
                // `.length` as a field (Boring style) → Rust `.len() as i64`
                if field == "length" || field == "count" {
                    return format!("{}.len() as i64", o);
                }
                format!("{}.{}", o, field)
            }
            ExprKind::Call(callee, args) => {
                // `GPU(n)` → `boring_metal_device_n(n)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "GPU" {
                        let idx = args.first().map(|a| self.expr(&a.value)).unwrap_or_else(|| "0".into());
                        return format!("boring_metal_device_n({} as usize)?", idx);
                    }
                }
                // `float(expr)` → `expr as f32` (Metal uses f32, not f64)
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "float" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as f32)", inner);
                        }
                    }
                }
                // `int(expr)` → `expr as i64`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "int" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as i64)", inner);
                        }
                    }
                }
                // `uint(expr)` → `expr as u64`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "uint" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as u64)", inner);
                        }
                    }
                }
                // `ord(c)` — char/string → i64 (Boring built-in)
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "ord" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as i64)", inner);
                        }
                    }
                }
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                // `Scale(data)` → `Scale::new(boring_metal_device(), data)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if self.kernel_names.contains(name.as_str()) {
                        let dev = if self.screen_var.is_some() {
                            "boring_device.clone()".to_string()
                        } else {
                            "boring_metal_device()".to_string()
                        };
                        let all = std::iter::once(dev).chain(args_s).collect::<Vec<_>>();
                        return format!("{}::new({})?", name, all.join(", "));
                    }
                }
                // `print(expr)` → `println!("{}", expr)` or `println!("{}", format!(...))` → `println!(...)`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "print" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            // If the argument is already a format! call, lift it to println!
                            if inner.starts_with("format!(") {
                                let inner_args = &inner["format!(".len()..inner.len()-1];
                                return format!("println!({})", inner_args);
                            }
                            return format!("println!(\"{{}}\", {})", inner);
                        }
                        return "println!()".into();
                    }
                }
                let fn_s = self.expr(callee);
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                // screen.key("q") → boring_keys.contains("q")
                if let ExprKind::Var(name) = &obj.kind {
                    if self.screen_var.as_deref() == Some(name.as_str()) {
                        match method.as_str() {
                            "key" => {
                                let k = args.first().map(|a| self.expr(&a.value)).unwrap_or_else(|| "\"\"".into());
                                return format!("boring_keys.contains({})", k);
                            }
                            "key_pressed" => {
                                let k = args.first().map(|a| self.expr(&a.value)).unwrap_or_else(|| "\"\"".into());
                                return format!("boring_keys.contains({})", k);
                            }
                            _ => {}
                        }
                    }
                }
                // `GPU.all()` → Device::all()
                if let ExprKind::Var(name) = &obj.kind {
                    if name == "GPU" && method == "all" {
                        return "Device::all().into_iter().enumerate().map(|(i, d)| (i, d)).collect::<Vec<_>>()".into();
                    }
                    if self.gpu_vars.contains(name.as_str()) {
                        return self.emit_gpu_property(name, method);
                    }
                    // `fs.writeBytes(path, bytes)` — write Vec<i64> as binary file
                    if name == "fs" && method == "writeBytes" {
                        let path  = args.first().map(|a| self.expr(&a.value)).unwrap_or_default();
                        let bytes = args.get(1).map(|a| self.expr(&a.value)).unwrap_or_default();
                        return format!("std::fs::write({}, {}.iter().map(|&b| b as u8).collect::<Vec<u8>>())?", path, bytes);
                    }
                    // `fs.write(path, text)` — write string as text file
                    if name == "fs" && (method == "write" || method == "writeText") {
                        let path = args.first().map(|a| self.expr(&a.value)).unwrap_or_default();
                        let text = args.get(1).map(|a| self.expr(&a.value)).unwrap_or_default();
                        return format!("std::fs::write({}, {}.as_bytes())?", path, text);
                    }
                }
                let o = self.expr(obj);
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                match method.as_str() {
                    "wait" => format!("{}.wait()", o),
                    "done" => format!("{}.done()", o),
                    // `.chars()` — collect to Vec<char> so indexing and .len() work
                    "chars" if args.is_empty() => format!("{}.chars().collect::<Vec<char>>()", o),
                    // `.length` / `.count` — map to .len() as i64
                    "length" | "count" if args.is_empty() => format!("{}.len() as i64", o),
                    // `.add(x)` / `.insert(x)` — Vec push
                    "add" | "insert" if args.len() == 1 => format!("{}.push({})", o, args_s[0]),
                    _ => format!("{}.{}({})", o, method, args_s.join(", ")),
                }
            }
            ExprKind::Pipe(lhs, method, _args) => {
                let l = self.expr(lhs);
                match method.as_str() {
                    // Metal __boring_launch now returns Result<(), _> — no .wait() needed
                    "wait" => l,
                    "done" => "true".into(),
                    _ => format!("{}.{}()", l, method),
                }
            }
            ExprKind::KernelLaunch { config, kernel } => {
                let auto_grid = self.resolve_kernel_type(kernel)
                    .and_then(|t| self.kernel_decls.get(&t))
                    .map(|decl| decl.fields.iter().any(|f|
                        matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
                        && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))))
                    .unwrap_or(false);
                let k = self.expr(kernel);
                let block = config.block.as_ref()
                    .map(|e| self.dim3_expr(e))
                    .unwrap_or_else(|| "(1, 1, 1)".into());
                let grid = if auto_grid {
                    match &config.grid {
                        None => "None".into(),
                        Some(e) => format!("Some({})", self.dim3_expr(e)),
                    }
                } else {
                    config.grid.as_ref()
                        .map(|e| self.dim3_expr(e))
                        .unwrap_or_else(|| "(1, 1, 1)".into())
                };
                // `after =` — Metal is synchronous (&mut self, wait_until_completed inside).
                if self.in_render_loop {
                    format!("{k}.__boring_launch({block}, {grid}, &[]).expect(\"kernel launch failed\")")
                } else {
                    format!("{k}.__boring_launch({block}, {grid}, &[])?")
                }
            }
            ExprKind::New { arena, ctor } => {
                if let ExprKind::Call(callee, args) = &ctor.kind {
                    if let ExprKind::Var(name) = &callee.kind {
                        if self.kernel_names.contains(name.as_str()) {
                            let default_dev = if self.screen_var.is_some() {
                                "boring_device.clone()".to_string()
                            } else {
                                "boring_metal_device()".to_string()
                            };
                            let dev = arena.as_ref()
                                .map(|a| self.expr(a))
                                .unwrap_or(default_dev);
                            let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                            let all = std::iter::once(dev).chain(args_s).collect::<Vec<_>>();
                            return format!("{}::new({})?", name, all.join(", "));
                        }
                    }
                }
                self.expr(ctor)
            }
            ExprKind::Array(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("vec![{}]", s.join(", "))
            }
            ExprKind::ArrayFill { value, count } => {
                let v = self.expr(value);
                let n = self.expr(count);
                format!("vec![{}; {} as usize]", v, n)
            }
            ExprKind::ArrayAlloc { count } => {
                let n = self.expr(count);
                format!("vec![Default::default(); {} as usize]", n)
            }
            ExprKind::Tuple(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("({})", s.join(", "))
            }
            ExprKind::Range { start, end, inclusive } => {
                let lo = self.expr(start);
                let hi = self.expr(end);
                if *inclusive { format!("({}..={})", lo, hi) } else { format!("({}..{})", lo, hi) }
            }
            ExprKind::Cast(inner, ty) => {
                format!("({} as {})", self.expr(inner), rust_type(ty))
            }
            ExprKind::Else(val, default) => {
                format!("{}.unwrap_or({})", self.expr(val), self.expr(default))
            }
            ExprKind::If(i) => {
                let mut out = String::new();
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    let t = body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    if idx == 0 { out.push_str(&format!("if {} {{ {} }}", c, t)); }
                    else        { out.push_str(&format!(" else if {} {{ {} }}", c, t)); }
                }
                if let Some(else_body) = &i.else_body {
                    let e = else_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    out.push_str(&format!(" else {{ {} }}", e));
                }
                out
            }
            ExprKind::StringInterp(segs) => {
                let mut parts = Vec::new();
                let mut fmt_str = String::from("\"");
                let mut fargs = Vec::new();
                for seg in segs {
                    match seg {
                        StringSegment::Lit(s) => fmt_str.push_str(s),
                        StringSegment::Expr(e) => {
                            fmt_str.push_str("{}");
                            fargs.push(self.expr(e));
                        }
                        StringSegment::FormattedExpr(e, fmt) => {
                            let rust_fmt = fmt.trim_end_matches(['f', 'd', 's', 'g', 'G']);
                            fmt_str.push_str(&format!("{{:{}}}", rust_fmt));
                            fargs.push(self.expr(e));
                        }
                    }
                }
                fmt_str.push('"');
                parts.push(fmt_str);
                parts.extend(fargs);
                format!("format!({})", parts.join(", "))
            }
            ExprKind::ArrayComp { expr, var, count } => {
                let n = self.expr(count);
                let body = self.expr(expr);
                format!(
                    "(0..({} as usize)).map(|__boring_i| {{ let {} = __boring_i as i64; {} }}).collect::<Vec<_>>()",
                    n, var, body
                )
            }
            ExprKind::ArrayCompIter { expr, var, iter } => {
                let it = self.expr(iter);
                let body = self.expr(expr);
                format!("{}.iter().map(|{}| {{ {} }}).collect::<Vec<_>>()", it, var, body)
            }
            _ => "/* expr */".into(),
        }
    }

    fn dim3_expr(&mut self, e: &Expr) -> String {
        if let ExprKind::Tuple(elems) = &e.kind {
            let x = elems.first().map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let y = elems.get(1).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let z = elems.get(2).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            format!("({x}, {y}, {z})")
        } else {
            let v = self.expr(e);
            format!("({v} as u32, 1, 1)")
        }
    }

    fn track_kernel_var(&mut self, name: &str, val: &Expr) {
        if let Some(t) = self.resolve_kernel_type(val) {
            self.var_kernel_type.insert(name.to_string(), t);
        }
        if self.is_gpu_expr(val) {
            self.gpu_vars.insert(name.to_string());
        }
    }

    fn is_gpu_expr(&self, expr: &Expr) -> bool {
        match &expr.kind {
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind { n == "GPU" } else { false }
            }
            ExprKind::Var(n) => self.gpu_vars.contains(n.as_str()),
            _ => false,
        }
    }

    /// Map a GPU variable method call to Metal API.
    fn emit_gpu_property(&self, var: &str, method: &str) -> String {
        match method {
            "name"              => format!("{var}.name().to_string()"),
            "totalMem"          => format!("{var}.recommended_max_working_set_size() as i64"),
            "freeMem"           => format!("({var}.recommended_max_working_set_size().saturating_sub({var}.current_allocated_size())) as i64"),
            "computeCapability" => format!("boring_gpu_family(&{var})"),
            "warpSize"          => "32i64".into(),
            "maxThreads"        => "1024i64".into(),
            "maxSharedMem"      => format!("{var}.max_threadgroup_memory_length() as i64"),
            "index"             => format!("Device::all().iter().position(|d| d.name() == {var}.name()).unwrap_or(0) as i64"),
            other               => format!("{var}.{other}()"),
        }
    }

    fn resolve_kernel_type(&self, expr: &Expr) -> Option<String> {
        match &expr.kind {
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind {
                    if self.kernel_names.contains(n.as_str()) { return Some(n.clone()); }
                }
                None
            }
            ExprKind::KernelLaunch { kernel, .. } => self.resolve_kernel_type(kernel),
            ExprKind::New { ctor, .. }             => self.resolve_kernel_type(ctor),
            ExprKind::Pipe(lhs, method, _) if method == "wait" => self.resolve_kernel_type(lhs),
            ExprKind::Var(n) => self.var_kernel_type.get(n.as_str()).cloned(),
            _ => None,
        }
    }

    fn try_gpu_field_read(&self, obj: &str, field: &str) -> Option<String> {
        let kernel_type = self.var_kernel_type.get(obj)?;
        let decl = self.kernel_decls.get(kernel_type)?;
        let kf = decl.fields.iter().find(|f| f.name == field)?;
        match kf.qual {
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                match &kf.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        Some(format!("{}.read_{}()", obj, field))
                    }
                    _ => None,
                }
            }
            _ => None,
        }
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn host_param_type(ty: &Type) -> String {
    match ty {
        Type::Qualified(inner, OwnerQual::GpuUnified)
        | Type::Qualified(inner, OwnerQual::GpuGlobal) => {
            format!("Vec<{}>", elem_rust_type(inner))
        }
        Type::Array(inner) => format!("Vec<{}>", rust_type(inner)),
        _ => rust_type(ty),
    }
}

fn elem_rust_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)        => rust_type(inner),
        Type::ArrayN(inner, _)    => rust_type(inner),
        Type::Qualified(inner, _) => elem_rust_type(inner),
        _                         => rust_type(ty),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int            => "i64".into(),
        Type::Uint           => "u64".into(),
        Type::Uint8          => "u8".into(),
        Type::Int8            => "i8".into(),
        Type::Int16           => "i16".into(),
        Type::Int32           => "i32".into(),
        Type::Int64           => "i64".into(),
        Type::Int128          => "i128".into(),
        Type::Uint16          => "u16".into(),
        Type::Uint32          => "u32".into(),
        Type::Uint64          => "u64".into(),
        Type::Uint128         => "u128".into(),
        Type::Float          => "f32".into(),
        Type::Bool           => "bool".into(),
        Type::Str            => "String".into(),
        Type::Nil            => "()".into(),
        Type::Void           => "()".into(),
        Type::Never          => "!".into(),
        Type::Array(inner)   => format!("Vec<{}>", rust_type(inner)),
        Type::ArrayN(inner, n) => format!("[{}; {}]", rust_type(inner), n),
        Type::Optional(inner)  => format!("Option<{}>", rust_type(inner)),
        Type::Named(n) => match n.as_str() {
            "float" | "f64" => "f32",
            "f32"           => "f32",
            "int"   | "i64" => "i64",
            "uint"  | "u64" => "u64",
            "uint8"         => "u8",
            "int8"          => "i8",
            "int16"         => "i16",
            "int32"         => "i32",
            "int64"         => "i64",
            "int128"        => "i128",
            "uint16"        => "u16",
            "uint32"        => "u32",
            "uint64"        => "u64",
            "uint128"       => "u128",
            "bool"          => "bool",
            "string"        => "String",
            other           => return other.to_string(),
        }.into(),
        Type::TypeParam(p)     => p.clone(),
        Type::Qualified(inner, _) => rust_type(inner),
        Type::Generic(n, args) => {
            let s: Vec<String> = args.iter().map(rust_type).collect();
            format!("{}<{}>", n, s.join(", "))
        }
        _ => "()".into(),
    }
}

fn elem_size_bytes(ty: &Type) -> usize {
    match ty {
        Type::Float                               => 4,
        Type::Int | Type::Uint                    => 8,
        Type::Uint8 | Type::Int8                   => 1,
        Type::Int16 | Type::Uint16                 => 2,
        Type::Int32 | Type::Uint32                 => 4,
        Type::Int64 | Type::Uint64                 => 8,
        Type::Int128 | Type::Uint128               => 16,
        Type::Bool                                => 1,
        Type::Named(n) => match n.as_str() {
            "float" | "f64" => 4,
            "f32"           => 4,
            "int"   | "i64" => 8,
            "uint"  | "u64" => 8,
            "uint8" | "int8" => 1,
            "int16" | "uint16" => 2,
            "int32" | "uint32" => 4,
            "int64" | "uint64" => 8,
            "int128" | "uint128" => 16,
            "i32"           => 4,
            "u32"           => 4,
            _               => 8,
        },
        Type::Qualified(inner, _)                 => elem_size_bytes(inner),
        Type::Array(inner) | Type::ArrayN(inner, _) => elem_size_bytes(inner),
        _                                         => 8,
    }
}

fn emit_scalar_default(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Int(n)   => n.to_string(),
        ExprKind::Float(f) => {
            let s = format!("{}", f);
            if s.contains('.') { s } else { format!("{}.0", s) }
        }
        ExprKind::Bool(b)  => b.to_string(),
        ExprKind::UnaryOp(UnaryOp::Neg, inner) => match &inner.kind {
            ExprKind::Int(n)   => format!("-{}", n),
            ExprKind::Float(f) => format!("-{}", f),
            _ => "Default::default()".into(),
        },
        _ => "Default::default()".into(),
    }
}

fn binop_rust(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",   BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",   BinOp::Rem => "%",
        BinOp::Eq  => "==",  BinOp::NotEq => "!=",  BinOp::RefEq => "==",
        BinOp::Lt  => "<",   BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&",  BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<",  BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_rust(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "!",
    }
}
