// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Rust host-side code emitter for the Metal backend.
// Uses the `metal` crate (objc2-metal migration planned).

use crate::ast::*;

pub(super) fn emit_host_rs(program: &Program, kernel_names: &[String]) -> String {
    let mut e = HostEmitter::new(kernel_names);
    e.emit_program(program, kernel_names);
    e.out
}

struct HostEmitter {
    out: String,
    indent: usize,
    kernel_names: std::collections::HashSet<String>,
    kernel_decls: std::collections::HashMap<String, KernelDecl>,
    var_kernel_type: std::collections::HashMap<String, String>,
    gpu_vars: std::collections::HashSet<String>,
}

impl HostEmitter {
    fn new(kernel_names: &[String]) -> Self {
        Self {
            out: String::new(),
            indent: 0,
            kernel_names: kernel_names.iter().cloned().collect(),
            kernel_decls: std::collections::HashMap::new(),
            var_kernel_type: std::collections::HashMap::new(),
            gpu_vars: std::collections::HashSet::new(),
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program, kernel_names: &[String]) {
        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.kernel_decls.insert(decl.name.clone(), decl.clone());
            }
        }

        self.line("// Generated by boring build --target metal.");
        self.blank();
        self.emit_prelude();

        for item in &program.items {
            match item {
                Item::Kernel(decl) => {
                    self.blank();
                    self.emit_kernel_struct(decl);
                }
                Item::Fn(f) => {
                    self.blank();
                    self.emit_fn(f, None);
                }
                Item::Struct(s) => {
                    self.blank();
                    self.emit_struct(s);
                }
                Item::Enum(e) => {
                    self.blank();
                    self.emit_enum(e);
                }
                Item::Stmt(_) | Item::Let(_) => {}
                _ => {}
            }
        }

        let has_stmts = program.items.iter().any(|i| matches!(i, Item::Stmt(_) | Item::Let(_)));
        if has_stmts || !kernel_names.is_empty() {
            self.blank();
            self.line("fn main() -> Result<(), Box<dyn std::error::Error>> {");
            self.indent += 1;
            for item in &program.items {
                match item {
                    Item::Let(s) => {
                        let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                        let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                        if let Some(val) = &s.value {
                            self.track_kernel_var(&s.name, val);
                            let rhs = self.expr(val);
                            self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                        }
                    }
                    Item::Stmt(stmt) => self.emit_stmt(stmt),
                    _ => {}
                }
            }
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }
    }

    // ── Metal prelude ──────────────────────────────────────────────────────────

    fn emit_prelude(&mut self) {
        self.line("use metal::*;");
        self.line("use std::mem;");
        self.blank();
        self.line("const BORING_MSL: &str = include_str!(\"../kernels/main.metal\");");
        self.blank();
        // Default device helper.
        self.line("fn boring_metal_device() -> Device {");
        self.indent += 1;
        self.line("Device::system_default().expect(\"no Metal device found — macOS 10.14+ required\")");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // GPU(n) → indexed device.
        self.line("fn boring_metal_device_n(idx: usize) -> Result<Device, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("let devices = Device::all();");
        self.line("devices.into_iter().nth(idx)");
        self.indent += 1;
        self.line(".ok_or_else(|| format!(\"GPU index {} out of range\", idx).into())");
        self.indent -= 1;
        self.indent -= 1;
        self.line("}");
        self.blank();
        // GPU family tier helper (computeCapability equivalent).
        self.line("fn boring_gpu_family(device: &Device) -> Vec<i64> {");
        self.indent += 1;
        self.line("let families: &[(MTLGPUFamily, [i64; 2])] = &[");
        self.indent += 1;
        self.line("(MTLGPUFamily::Apple9, [9, 0]),");
        self.line("(MTLGPUFamily::Apple8, [8, 0]),");
        self.line("(MTLGPUFamily::Apple7, [7, 0]),");
        self.line("(MTLGPUFamily::Apple6, [6, 0]),");
        self.line("(MTLGPUFamily::Apple5, [5, 0]),");
        self.line("(MTLGPUFamily::Apple4, [4, 0]),");
        self.line("(MTLGPUFamily::Apple3, [3, 0]),");
        self.line("(MTLGPUFamily::Apple2, [2, 0]),");
        self.line("(MTLGPUFamily::Apple1, [1, 0]),");
        self.indent -= 1;
        self.line("];");
        self.line("for (family, ver) in families {");
        self.indent += 1;
        self.line("if device.supports_family(*family) { return ver.to_vec(); }");
        self.indent -= 1;
        self.line("}");
        self.line("vec![0, 0]");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // KernelHandle — Metal is synchronous (wait_until_completed in __boring_launch).
        self.line("struct KernelHandle<T> { inner: T }");
        self.line("impl<T> KernelHandle<T> {");
        self.indent += 1;
        self.line("fn wait(self) -> T { self.inner }");
        self.line("fn done(&self) -> bool { true }");
        self.indent -= 1;
        self.line("}");
    }

    // ── Kernel struct → Rust host wrapper ─────────────────────────────────────

    fn emit_kernel_struct(&mut self, decl: &KernelDecl) {
        let name = &decl.name;

        self.line(&format!("struct {} {{", name));
        self.indent += 1;
        self.line("__device: Device,");
        self.line("__queue: CommandQueue,");
        self.line("__pipeline: ComputePipelineState,");
        for field in &decl.fields {
            match field.qual {
                GpuQual::Shared | GpuQual::Local => {}
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                    match &field.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => {
                            self.line(&format!("{}: Buffer,", field.name));
                        }
                        _ => {
                            let ty = rust_type(&field.ty);
                            self.line(&format!("{}: {},", field.name, ty));
                        }
                    }
                }
            }
        }
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Local) {
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        let ty = rust_type(&field.ty);
                        self.line(&format!("{}: {},", field.name, ty));
                    }
                }
            }
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line(&format!("impl {} {{", name));
        self.indent += 1;

        for init in &decl.inits {
            self.emit_kernel_new(name, &decl.fields, init);
            self.blank();
        }
        if decl.inits.is_empty() {
            self.emit_kernel_new_default(name, &decl.fields);
            self.blank();
        }

        // Read accessors for 'unified/'global array fields (D2H).
        for field in &decl.fields {
            match field.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                    if matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        let elem = elem_rust_type(&field.ty);
                        self.line(&format!(
                            "fn read_{}(&self) -> Vec<{}> {{",
                            field.name, elem
                        ));
                        self.indent += 1;
                        self.line(&format!(
                            "let n = self.{}.length() as usize / mem::size_of::<{}>();",
                            field.name, elem
                        ));
                        self.line(&format!(
                            "let ptr = self.{}.contents() as *const {};",
                            field.name, elem
                        ));
                        self.line("unsafe { std::slice::from_raw_parts(ptr, n).to_vec() }");
                        self.indent -= 1;
                        self.line("}");
                        self.blank();
                    }
                }
                _ => {}
            }
        }

        self.emit_boring_launch(name, &decl.fields);

        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new(&mut self, name: &str, fields: &[KernelFieldDecl], init: &InitDecl) {
        let params: Vec<String> = init.params.iter().map(|p| {
            let ty = p.ty.as_ref()
                .map(|t| host_param_type(t))
                .unwrap_or_else(|| "()".into());
            format!("{}: {}", p.name, ty)
        }).collect();

        let all_params = if params.is_empty() {
            "__device: Device".into()
        } else {
            format!("__device: Device, {}", params.join(", "))
        };

        self.line(&format!(
            "fn new({}) -> Result<Self, Box<dyn std::error::Error>> {{",
            all_params
        ));
        self.indent += 1;

        self.emit_pipeline_init(name);

        let assigned: std::collections::HashSet<String> = init.body.iter()
            .filter_map(|s| match s {
                Stmt::Expr(e) => {
                    if let ExprKind::Assign(lhs, _) = &e.kind {
                        if let ExprKind::Var(n) = &lhs.kind { Some(n.clone()) }
                        else { None }
                    } else { None }
                }
                _ => None,
            }).collect();

        for stmt in &init.body {
            self.emit_init_stmt(stmt, fields);
        }

        for field in fields {
            if !assigned.contains(&field.name) {
                self.emit_field_default(field);
            }
        }

        self.emit_struct_literal(name, fields);
        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new_default(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        self.line("fn new(__device: Device) -> Result<Self, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.emit_pipeline_init(name);
        for field in fields {
            self.emit_field_default(field);
        }
        self.emit_struct_literal(name, fields);
        self.indent -= 1;
        self.line("}");
    }

    fn emit_pipeline_init(&mut self, kernel_name: &str) {
        self.line("let __queue = __device.new_command_queue();");
        self.line("let __options = CompileOptions::new();");
        self.line("let __library = __device.new_library_with_source(BORING_MSL, &__options)");
        self.indent += 1;
        self.line(".map_err(|e| format!(\"MSL compile error: {}\", e))?;");
        self.indent -= 1;
        self.line(&format!(
            "let __func = __library.get_function(\"{}_kernel\", None)",
            kernel_name
        ));
        self.indent += 1;
        self.line(".map_err(|e| format!(\"kernel function not found: {}\", e))?;");
        self.indent -= 1;
        self.line("let __pipeline = __device.new_compute_pipeline_state_with_function(&__func)?;");
    }

    fn emit_field_default(&mut self, field: &KernelFieldDecl) {
        match field.qual {
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                match &field.ty {
                    Type::Array(inner) | Type::ArrayN(inner, _) => {
                        let elem = rust_type(inner);
                        self.line(&format!(
                            "let {}: Buffer = __device.new_buffer(mem::size_of::<{}>() as u64, MTLResourceOptions::StorageModeShared);",
                            field.name, elem
                        ));
                    }
                    _ => {
                        let ty = rust_type(&field.ty);
                        self.line(&format!("let {}: {} = Default::default();", field.name, ty));
                    }
                }
            }
            GpuQual::Shared => {}
            GpuQual::Local => {
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        let ty = rust_type(&field.ty);
                        self.line(&format!("let {}: {} = Default::default();", field.name, ty));
                    }
                }
            }
        }
    }

    fn emit_struct_literal(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        self.line(&format!("Ok({} {{", name));
        self.indent += 1;
        self.line("__device,");
        self.line("__queue,");
        self.line("__pipeline,");
        for field in fields {
            match field.qual {
                GpuQual::Shared => {}
                GpuQual::Local => match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => self.line(&format!("{},", field.name)),
                },
                _ => match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => self.line(&format!("{},", field.name)),
                    _ => self.line(&format!("{},", field.name)),
                }
            }
        }
        self.indent -= 1;
        self.line("})");
    }

    fn emit_init_stmt(&mut self, stmt: &Stmt, fields: &[KernelFieldDecl]) {
        match stmt {
            Stmt::Expr(e) => {
                if let ExprKind::Assign(lhs, rhs) = &e.kind {
                    if let ExprKind::Var(fname) = &lhs.kind {
                        if let Some(field) = fields.iter().find(|f| &f.name == fname) {
                            match field.qual {
                                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const => {
                                    match &rhs.kind {
                                        ExprKind::ArrayFill { value: _, count } => {
                                            let n = self.expr(count);
                                            let elem = elem_rust_type(&field.ty);
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer(({n} * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        ExprKind::Array(elems) => {
                                            let elem = elem_rust_type(&field.ty);
                                            let lit: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                                            self.line(&format!(
                                                "let __data_{fname}: Vec<{elem}> = vec![{}];", lit.join(", ")
                                            ));
                                            self.line(&format!(
                                                "let {fname}: Buffer = __device.new_buffer_with_data(__data_{fname}.as_ptr() as *const _, (__data_{fname}.len() * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                            ));
                                            return;
                                        }
                                        _ => {
                                            let rhs_s = self.expr(rhs);
                                            match &field.ty {
                                                Type::Array(_) | Type::ArrayN(_, _) => {
                                                    let elem = elem_rust_type(&field.ty);
                                                    self.line(&format!(
                                                        "let {fname}: Buffer = __device.new_buffer_with_data({rhs_s}.as_ptr() as *const _, ({rhs_s}.len() * mem::size_of::<{elem}>()) as u64, MTLResourceOptions::StorageModeShared);"
                                                    ));
                                                }
                                                _ => {
                                                    // Scalar 'const field: store the value directly.
                                                    let ty = rust_type(&field.ty);
                                                    self.line(&format!("let {fname}: {ty} = {rhs_s};"));
                                                }
                                            }
                                            return;
                                        }
                                    }
                                }
                                _ => {}
                            }
                        }
                    }
                }
                let s = self.expr(e);
                self.line(&format!("{};", s));
            }
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{} {} = {};", binding, s.name, rhs));
                }
            }
            _ => self.emit_stmt(stmt),
        }
    }

    fn emit_boring_launch(&mut self, _name: &str, fields: &[KernelFieldDecl]) {
        // Auto-grid when there is at least one device array field.
        let auto_grid_field: Option<String> = fields.iter().find_map(|f| {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => Some(f.name.clone()),
                        _ => None,
                    }
                }
                _ => None,
            }
        });

        if auto_grid_field.is_some() {
            self.line(
                "fn __boring_launch(self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, _after: &[()]) \
                 -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {"
            );
        } else {
            self.line(
                "fn __boring_launch(self, block_dim: (u32,u32,u32), grid_dim: (u32,u32,u32), _after: &[()]) \
                 -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {"
            );
        }
        self.indent += 1;

        // Grid sizing.
        if let Some(field) = &auto_grid_field {
            self.line("let grid_dim = grid_dim.unwrap_or_else(|| {");
            self.indent += 1;
            let elem = elem_rust_type(&fields.iter().find(|f| &f.name == field).unwrap().ty);
            self.line(&format!(
                "let n = (self.{}.length() as usize / mem::size_of::<{}>()) as u32;",
                field, elem
            ));
            self.line("((n + block_dim.0 - 1) / block_dim.0, 1, 1)");
            self.indent -= 1;
            self.line("});");
        }

        // Dynamic shared memory size (per-block).
        let dyn_shared_terms: Vec<String> = fields.iter()
            .filter(|f| matches!(f.qual, GpuQual::Shared))
            .filter_map(|f| {
                if let Type::Array(inner) = &f.ty {
                    let sz = elem_size_bytes(inner);
                    Some(format!("block_dim.0 as usize * {}", sz))
                } else {
                    None
                }
            })
            .collect();

        // Dispatch.
        self.line("let __cmd_buf = self.__queue.new_command_buffer();");
        self.line("let __encoder = __cmd_buf.new_compute_command_encoder();");
        self.line("__encoder.set_compute_pipeline_state(&self.__pipeline);");

        // Set buffers in the same order as MSL parameters.
        let mut buf_idx: u64 = 0;
        let mut tg_idx: u64 = 0;

        for f in fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                    if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        self.line(&format!("__encoder.set_buffer({}, Some(&self.{}), 0);", buf_idx, f.name));
                        buf_idx += 1;
                    }
                }
                _ => {}
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Const) {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                    self.line(&format!("__encoder.set_buffer({}, Some(&self.{}), 0);", buf_idx, f.name));
                } else {
                    let elem = elem_rust_type(&f.ty);
                    self.line(&format!(
                        "__encoder.set_bytes({}, mem::size_of::<{}>() as u64, &self.{} as *const _ as *const _);",
                        buf_idx, elem, f.name
                    ));
                }
                buf_idx += 1;
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Local) && !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                let elem = rust_type(&f.ty);
                self.line(&format!(
                    "__encoder.set_bytes({}, mem::size_of::<{}>() as u64, &self.{} as *const _ as *const _);",
                    buf_idx, elem, f.name
                ));
                buf_idx += 1;
            }
        }
        for f in fields {
            if matches!(f.qual, GpuQual::Shared) && matches!(f.ty, Type::Array(_)) {
                if let Type::Array(inner) = &f.ty {
                    let sz = elem_size_bytes(inner);
                    self.line(&format!(
                        "__encoder.set_threadgroup_memory_length({}, (block_dim.0 as usize * {}) as u64);",
                        tg_idx, sz
                    ));
                    tg_idx += 1;
                }
            }
        }

        // Static shared memory doesn't need set_threadgroup_memory_length — declared in MSL.
        let _ = tg_idx;

        // Additional dynamic shared memory from smem_bytes.
        if !dyn_shared_terms.is_empty() {
            let expr = dyn_shared_terms.join(" + ");
            self.line(&format!("let __smem: usize = {};", expr));
            let _ = __smem_placeholder();  // suppress unused warning in generated code
        }

        self.line("__encoder.dispatch_thread_groups(");
        self.indent += 1;
        self.line("MTLSize { width: grid_dim.0 as u64, height: grid_dim.1 as u64, depth: grid_dim.2 as u64 },");
        self.line("MTLSize { width: block_dim.0 as u64, height: block_dim.1 as u64, depth: block_dim.2 as u64 },");
        self.indent -= 1;
        self.line(");");
        self.line("__encoder.end_encoding();");
        self.line("__cmd_buf.commit();");
        self.line("__cmd_buf.wait_until_completed();");
        self.line("Ok(KernelHandle { inner: self })");
        self.indent -= 1;
        self.line("}");
    }

    // ── Regular items ──────────────────────────────────────────────────────────

    fn emit_fn(&mut self, f: &FnDecl, self_ty: Option<&str>) {
        if f.is_native { return; }
        let vis = if f.is_pub { "pub " } else { "" };
        let params: Vec<String> = f.params.iter().map(|p| {
            let name = if p.mutable { format!("mut {}", p.name) } else { p.name.clone() };
            match &p.ty {
                Some(ty) => format!("{}: {}", name, rust_type(ty)),
                None => name,
            }
        }).collect();
        let all_params = match self_ty {
            Some(_) => {
                let s = if f.mutating { "&mut self" } else { "&self" };
                if params.is_empty() { s.to_string() } else { format!("{}, {}", s, params.join(", ")) }
            }
            None => params.join(", "),
        };
        let ret = f.return_ty.as_ref().map(|t| rust_type(t)).unwrap_or_else(|| "()".into());
        let sig = format!("{}fn {}({}) -> {}", vis, f.name, all_params, ret);
        if f.body.is_empty() {
            self.line(&format!("{} {{}}", sig));
            return;
        }
        self.line(&format!("{} {{", sig));
        self.indent += 1;
        let len = f.body.len();
        for (i, stmt) in f.body.iter().enumerate() {
            if i + 1 == len { self.emit_stmt_last(stmt); } else { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_struct(&mut self, s: &StructDecl) {
        if s.is_native { return; }
        let vis = if s.is_pub { "pub " } else { "" };
        self.line(&format!("{}struct {} {{", vis, s.name));
        self.indent += 1;
        for f in &s.fields {
            let fvis = if f.is_pub { "pub " } else { "" };
            self.line(&format!("{}{}: {},", fvis, f.name, rust_type(&f.ty)));
        }
        self.indent -= 1;
        self.line("}");
        if !s.methods.is_empty() {
            self.blank();
            self.line(&format!("impl {} {{", s.name));
            self.indent += 1;
            for m in &s.methods { self.emit_fn(m, Some(&s.name)); self.blank(); }
            self.indent -= 1;
            self.line("}");
        }
    }

    fn emit_enum(&mut self, e: &EnumDecl) {
        if e.is_native { return; }
        let vis = if e.is_pub { "pub " } else { "" };
        self.line(&format!("{}enum {} {{", vis, e.name));
        self.indent += 1;
        for v in &e.variants {
            if v.fields.is_empty() {
                self.line(&format!("{},", v.name));
            } else {
                let fs: Vec<String> = v.fields.iter().map(|f| rust_type(&f.ty)).collect();
                self.line(&format!("{}({}),", v.name, fs.join(", ")));
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ─────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                if let Some(val) = &s.value {
                    self.track_kernel_var(&s.name, val);
                    let rhs = self.expr(val);
                    self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                } else {
                    self.line(&format!("{} {}{};", binding, s.name, ty_ann));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    ExprKind::Assign(lhs, rhs) => {
                        let l = self.expr(lhs);
                        let r = self.expr(rhs);
                        self.line(&format!("{} = {};", l, r));
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if {} {{", c)); }
                    else        { self.line(&format!("}} else if {} {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while {} {{", cond));
                self.indent += 1;
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let is_enumerate = f.vars.len() >= 2;
                let var = if is_enumerate {
                    format!("({}, {})", f.vars[0], f.vars[1])
                } else {
                    f.vars.first().cloned().unwrap_or_else(|| "_i".into())
                };
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let range = if *inclusive { format!("{}..={}", lo, hi) } else { format!("{}..{}", lo, hi) };
                        self.line(&format!("for {} in {} {{", var, range));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        if is_enumerate {
                            self.line(&format!("for {} in {}.iter().enumerate() {{", var, iter));
                        } else {
                            self.line(&format!("for {} in {} {{", var, iter));
                        }
                    }
                }
                self.indent += 1;
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            Stmt::Comment(_)          => {}
            _ => { self.line("/* unsupported stmt */"); }
        }
    }

    fn emit_stmt_last(&mut self, stmt: &Stmt) {
        if let Stmt::Expr(e) = stmt {
            let s = self.expr(e);
            self.line(&s);
        } else {
            self.emit_stmt(stmt);
        }
    }

    // ── Expressions ────────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)    => n.to_string(),
            ExprKind::Float(f)  => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)   => if *b { "true".into() } else { "false".into() },
            ExprKind::Str(s)    => format!("\"{}\"", s),
            ExprKind::Nil       => "None".into(),
            ExprKind::Void      => "()".into(),
            ExprKind::Var(name) => name.clone(),

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_rust(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_rust(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                if let ExprKind::Field(obj, field) = &arr.kind {
                    if let ExprKind::Var(obj_name) = &obj.kind {
                        if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                            let i = self.expr(idx);
                            return format!("{}[{} as usize]", read_call, i);
                        }
                    }
                }
                format!("{}[{} as usize]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                if let ExprKind::Var(obj_name) = &obj.kind {
                    if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                        return read_call;
                    }
                }
                let o = self.expr(obj);
                format!("{}.{}", o, field)
            }
            ExprKind::Call(callee, args) => {
                // `GPU(n)` → `boring_metal_device_n(n)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "GPU" {
                        let idx = args.first().map(|a| self.expr(&a.value)).unwrap_or_else(|| "0".into());
                        return format!("boring_metal_device_n({} as usize)?", idx);
                    }
                }
                // `float(expr)` → `expr as f32` (Metal uses f32, not f64)
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "float" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as f32)", inner);
                        }
                    }
                }
                // `int(expr)` → `expr as i64`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "int" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as i64)", inner);
                        }
                    }
                }
                // `uint(expr)` → `expr as u64`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "uint" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as u64)", inner);
                        }
                    }
                }
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                // `Scale(data)` → `Scale::new(boring_metal_device(), data)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if self.kernel_names.contains(name.as_str()) {
                        let all = std::iter::once("boring_metal_device()".to_string())
                            .chain(args_s)
                            .collect::<Vec<_>>();
                        return format!("{}::new({})?", name, all.join(", "));
                    }
                }
                // `print(expr)` → `println!("{}", expr)` or `println!("{}", format!(...))` → `println!(...)`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "print" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            // If the argument is already a format! call, lift it to println!
                            if inner.starts_with("format!(") {
                                let inner_args = &inner["format!(".len()..inner.len()-1];
                                return format!("println!({})", inner_args);
                            }
                            return format!("println!(\"{{}}\", {})", inner);
                        }
                        return "println!()".into();
                    }
                }
                let fn_s = self.expr(callee);
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                // `GPU.all()` → Device::all()
                if let ExprKind::Var(name) = &obj.kind {
                    if name == "GPU" && method == "all" {
                        return "Device::all().into_iter().enumerate().map(|(i, d)| (i, d)).collect::<Vec<_>>()".into();
                    }
                    if self.gpu_vars.contains(name.as_str()) {
                        return self.emit_gpu_property(name, method);
                    }
                }
                let o = self.expr(obj);
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                match method.as_str() {
                    "wait" => format!("{}.wait()", o),
                    "done" => format!("{}.done()", o),
                    _ => format!("{}.{}({})", o, method, args_s.join(", ")),
                }
            }
            ExprKind::Pipe(lhs, method, _args) => {
                let l = self.expr(lhs);
                match method.as_str() {
                    "wait" => format!("{}.wait()", l),
                    "done" => format!("{}.done()", l),
                    _ => format!("{}.{}()", l, method),
                }
            }
            ExprKind::KernelLaunch { config, kernel } => {
                let auto_grid = self.resolve_kernel_type(kernel)
                    .and_then(|t| self.kernel_decls.get(&t))
                    .map(|decl| decl.fields.iter().any(|f|
                        matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal)
                        && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))))
                    .unwrap_or(false);
                let k = self.expr(kernel);
                let block = config.block.as_ref()
                    .map(|e| self.dim3_expr(e))
                    .unwrap_or_else(|| "(1, 1, 1)".into());
                let grid = if auto_grid {
                    match &config.grid {
                        None => "None".into(),
                        Some(e) => format!("Some({})", self.dim3_expr(e)),
                    }
                } else {
                    config.grid.as_ref()
                        .map(|e| self.dim3_expr(e))
                        .unwrap_or_else(|| "(1, 1, 1)".into())
                };
                // `after =` — Metal implementation is synchronous, after is a no-op.
                format!("{k}.__boring_launch({block}, {grid}, &[])?")
            }
            ExprKind::New { arena, ctor } => {
                if let ExprKind::Call(callee, args) = &ctor.kind {
                    if let ExprKind::Var(name) = &callee.kind {
                        if self.kernel_names.contains(name.as_str()) {
                            let dev = arena.as_ref()
                                .map(|a| self.expr(a))
                                .unwrap_or_else(|| "boring_metal_device()".into());
                            let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                            let all = std::iter::once(dev).chain(args_s).collect::<Vec<_>>();
                            return format!("{}::new({})?", name, all.join(", "));
                        }
                    }
                }
                self.expr(ctor)
            }
            ExprKind::Array(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("vec![{}]", s.join(", "))
            }
            ExprKind::ArrayFill { value, count } => {
                let v = self.expr(value);
                let n = self.expr(count);
                format!("vec![{}; {} as usize]", v, n)
            }
            ExprKind::Tuple(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("({})", s.join(", "))
            }
            ExprKind::Range { start, end, inclusive } => {
                let lo = self.expr(start);
                let hi = self.expr(end);
                if *inclusive { format!("({}..={})", lo, hi) } else { format!("({}..{})", lo, hi) }
            }
            ExprKind::Cast(inner, ty) => {
                format!("({} as {})", self.expr(inner), rust_type(ty))
            }
            ExprKind::Else(val, default) => {
                format!("{}.unwrap_or({})", self.expr(val), self.expr(default))
            }
            ExprKind::If(i) => {
                let mut out = String::new();
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    let t = body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    if idx == 0 { out.push_str(&format!("if {} {{ {} }}", c, t)); }
                    else        { out.push_str(&format!(" else if {} {{ {} }}", c, t)); }
                }
                if let Some(else_body) = &i.else_body {
                    let e = else_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    out.push_str(&format!(" else {{ {} }}", e));
                }
                out
            }
            ExprKind::StringInterp(segs) => {
                let mut parts = Vec::new();
                let mut fmt_str = String::from("\"");
                let mut fargs = Vec::new();
                for seg in segs {
                    match seg {
                        StringSegment::Lit(s) => fmt_str.push_str(s),
                        StringSegment::Expr(e) => {
                            fmt_str.push_str("{}");
                            fargs.push(self.expr(e));
                        }
                        StringSegment::FormattedExpr(e, fmt) => {
                            fmt_str.push_str(&format!("{{:{}}}", fmt));
                            fargs.push(self.expr(e));
                        }
                    }
                }
                fmt_str.push('"');
                parts.push(fmt_str);
                parts.extend(fargs);
                format!("format!({})", parts.join(", "))
            }
            _ => "/* expr */".into(),
        }
    }

    fn dim3_expr(&mut self, e: &Expr) -> String {
        if let ExprKind::Tuple(elems) = &e.kind {
            let x = elems.first().map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let y = elems.get(1).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let z = elems.get(2).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            format!("({x}, {y}, {z})")
        } else {
            let v = self.expr(e);
            format!("({v} as u32, 1, 1)")
        }
    }

    fn track_kernel_var(&mut self, name: &str, val: &Expr) {
        if let Some(t) = self.resolve_kernel_type(val) {
            self.var_kernel_type.insert(name.to_string(), t);
        }
        if self.is_gpu_expr(val) {
            self.gpu_vars.insert(name.to_string());
        }
    }

    fn is_gpu_expr(&self, expr: &Expr) -> bool {
        match &expr.kind {
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind { n == "GPU" } else { false }
            }
            ExprKind::Var(n) => self.gpu_vars.contains(n.as_str()),
            _ => false,
        }
    }

    /// Map a GPU variable method call to Metal API.
    fn emit_gpu_property(&self, var: &str, method: &str) -> String {
        match method {
            "name"              => format!("{var}.name().to_string()"),
            "totalMem"          => format!("{var}.recommended_max_working_set_size() as i64"),
            "freeMem"           => format!("({var}.recommended_max_working_set_size().saturating_sub({var}.current_allocated_size())) as i64"),
            "computeCapability" => format!("boring_gpu_family(&{var})"),
            "warpSize"          => "32i64".into(),
            "maxThreads"        => "1024i64".into(),
            "maxSharedMem"      => format!("{var}.max_threadgroup_memory_length() as i64"),
            "index"             => format!("Device::all().iter().position(|d| d.name() == {var}.name()).unwrap_or(0) as i64"),
            other               => format!("{var}.{other}()"),
        }
    }

    fn resolve_kernel_type(&self, expr: &Expr) -> Option<String> {
        match &expr.kind {
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind {
                    if self.kernel_names.contains(n.as_str()) { return Some(n.clone()); }
                }
                None
            }
            ExprKind::KernelLaunch { kernel, .. } => self.resolve_kernel_type(kernel),
            ExprKind::New { ctor, .. }             => self.resolve_kernel_type(ctor),
            ExprKind::Pipe(lhs, method, _) if method == "wait" => self.resolve_kernel_type(lhs),
            ExprKind::Var(n) => self.var_kernel_type.get(n.as_str()).cloned(),
            _ => None,
        }
    }

    fn try_gpu_field_read(&self, obj: &str, field: &str) -> Option<String> {
        let kernel_type = self.var_kernel_type.get(obj)?;
        let decl = self.kernel_decls.get(kernel_type)?;
        let kf = decl.fields.iter().find(|f| f.name == field)?;
        match kf.qual {
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                match &kf.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        Some(format!("{}.read_{}()", obj, field))
                    }
                    _ => None,
                }
            }
            _ => None,
        }
    }
}

// Suppress unused variable warning for smem in generated code output string.
fn __smem_placeholder() {}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn host_param_type(ty: &Type) -> String {
    match ty {
        Type::Qualified(inner, OwnerQual::GpuUnified)
        | Type::Qualified(inner, OwnerQual::GpuGlobal) => {
            format!("Vec<{}>", elem_rust_type(inner))
        }
        Type::Array(inner) => format!("Vec<{}>", rust_type(inner)),
        _ => rust_type(ty),
    }
}

fn elem_rust_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)        => rust_type(inner),
        Type::ArrayN(inner, _)    => rust_type(inner),
        Type::Qualified(inner, _) => elem_rust_type(inner),
        _                         => rust_type(ty),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int            => "i64".into(),
        Type::Uint           => "u64".into(),
        Type::Float          => "f32".into(),
        Type::Bool           => "bool".into(),
        Type::Str            => "String".into(),
        Type::Nil            => "()".into(),
        Type::Void           => "()".into(),
        Type::Never          => "!".into(),
        Type::Array(inner)   => format!("Vec<{}>", rust_type(inner)),
        Type::ArrayN(inner, n) => format!("[{}; {}]", rust_type(inner), n),
        Type::Optional(inner)  => format!("Option<{}>", rust_type(inner)),
        Type::Named(n) => match n.as_str() {
            "float" | "f64" => "f32",
            "f32"           => "f32",
            "int"   | "i64" => "i64",
            "uint"  | "u64" => "u64",
            "bool"          => "bool",
            "string"        => "String",
            other           => return other.to_string(),
        }.into(),
        Type::TypeParam(p)     => p.clone(),
        Type::Qualified(inner, _) => rust_type(inner),
        Type::Generic(n, args) => {
            let s: Vec<String> = args.iter().map(|a| rust_type(a)).collect();
            format!("{}<{}>", n, s.join(", "))
        }
        _ => "()".into(),
    }
}

fn elem_size_bytes(ty: &Type) -> usize {
    match ty {
        Type::Float                               => 4,
        Type::Int | Type::Uint                    => 8,
        Type::Bool                                => 1,
        Type::Named(n) => match n.as_str() {
            "float" | "f64" => 4,
            "f32"           => 4,
            "int"   | "i64" => 8,
            "uint"  | "u64" => 8,
            "i32"           => 4,
            "u32"           => 4,
            _               => 8,
        },
        Type::Qualified(inner, _)                 => elem_size_bytes(inner),
        Type::Array(inner) | Type::ArrayN(inner, _) => elem_size_bytes(inner),
        _                                         => 8,
    }
}

fn binop_rust(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",   BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",   BinOp::Rem => "%",
        BinOp::Eq  => "==",  BinOp::NotEq => "!=",  BinOp::RefEq => "==",
        BinOp::Lt  => "<",   BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&",  BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<",  BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_rust(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "!",
    }
}
