// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// CUDA C device code emitter.

use crate::ast::*;

pub(super) fn emit_device_cu(program: &Program) -> String {
    let mut e = DeviceEmitter::new();
    e.emit_program(program);
    e.out
}

struct DeviceEmitter {
    out: String,
    indent: usize,
    current_fields: Vec<KernelFieldDecl>,
    current_kernel: String,
    /// Auto-barrier mode: true when the kernel `def` has no explicit `sync` statements.
    auto_sync: bool,
}

impl DeviceEmitter {
    fn new() -> Self {
        Self { out: String::new(), indent: 0, current_fields: vec![], current_kernel: String::new(), auto_sync: false }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program) {
        self.line("// Generated by boring build --target cuda.");
        self.line("// Compile to PTX with: nvcc --ptx kernels/main.cu -o $OUT_DIR/main.ptx");
        self.blank();
        self.line("#include <cuda_runtime.h>");
        self.line("#include <stdint.h>");
        self.blank();
        self.line("extern \"C\" {");
        self.blank();

        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.emit_kernel_decl(decl);
            }
        }

        self.line("}  // extern \"C\"");
    }

    fn emit_kernel_decl(&mut self, decl: &KernelDecl) {
        self.current_fields = decl.fields.clone();
        self.current_kernel = decl.name.clone();
        self.line(&format!("// ─── kernel {} ───", decl.name));
        self.blank();

        // Emit __constant__ declarations for fixed-size 'const array fields.
        // These are file-scope globals in CUDA, not kernel parameters.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Const) {
                if let Type::ArrayN(inner, n) = &field.ty {
                    let elem = elem_c_type(inner);
                    self.line(&format!("__constant__ {} {}[{}];", elem, field.name, n));
                }
            }
        }

        // Device helper methods (non-entry-point defs).
        for method in &decl.methods {
            if !method.name.is_empty() {
                self.emit_device_fn(&decl.name, method, &decl.fields);
                self.blank();
            }
        }

        // Entry point: `def ()`.
        if let Some(entry) = decl.methods.iter().find(|m| m.name.is_empty()) {
            self.emit_entry_point(decl, entry);
            self.blank();
        }
    }

    fn emit_device_fn(&mut self, kernel: &str, method: &FnDecl, fields: &[KernelFieldDecl]) {
        let ret = method.return_ty.as_ref().map(|t| c_type(t)).unwrap_or_else(|| "void".into());
        let fn_name = format!("{}_{}", kernel, method.name);
        let mut params = field_params(fields);
        for p in &method.params {
            let ty = p.ty.as_ref().map(|t| c_type(t)).unwrap_or_else(|| "int64_t".into());
            params.push(format!("{} {}", ty, p.name));
        }
        self.line(&format!("__device__ {} {}({}) {{", ret, fn_name, params.join(", ")));
        self.indent += 1;
        for stmt in &method.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_entry_point(&mut self, decl: &KernelDecl, entry: &FnDecl) {
        let fn_name = format!("{}_kernel", decl.name);
        let params = field_params(&decl.fields);
        self.line(&format!("__global__ void {}({}) {{", fn_name, params.join(", ")));
        self.indent += 1;
        // Declare shared-memory fields.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Sync) {
                match &field.ty {
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("__shared__ {} {}[{}];", c_type(inner), field.name, n));
                    }
                    _ => {
                        let elem = elem_c_type(&field.ty);
                        self.line(&format!("extern __shared__ {} {}[];", elem, field.name));
                    }
                }
            }
        }
        // Declare per-thread 'local fields inside the kernel body.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Local) {
                match &field.ty {
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("{} {}[{}];", c_type(inner), field.name, n));
                    }
                    Type::Array(_) => {
                        // Unsized local array — not representable; skip.
                    }
                    _ => {
                        // Scalar 'local — declare a zero-initialised register.
                        self.line(&format!("{} {} = 0;", c_type(&field.ty), field.name));
                    }
                }
            }
        }
        let has_sync_fields = self.current_fields.iter().any(|f| matches!(f.qual, GpuQual::Sync));
        self.auto_sync = has_sync_fields && !body_has_explicit_sync(&entry.body);
        if self.auto_sync {
            let split = first_loop_index(&entry.body);
            for stmt in &entry.body[..split] { self.emit_stmt(stmt); }
            if split < entry.body.len() {
                self.line("__syncthreads();");
            }
            for stmt in &entry.body[split..] { self.emit_stmt(stmt); }
        } else {
            for stmt in &entry.body { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let mutable = matches!(s.binding, BindingKind::Mut | BindingKind::Var | BindingKind::Lazy);
                let ty = s.ty.as_ref().map(|t| c_type(t)).unwrap_or_else(|| "auto".into());
                let kw = if mutable { "" } else { "const " };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{}{} {} = {};", kw, ty, s.name, rhs));
                } else {
                    self.line(&format!("{}{} {};", kw, ty, s.name));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    // `print "..."` → printf(...) in device code.
                    ExprKind::Call(callee, args)
                        if matches!(&callee.kind, ExprKind::Var(n) if n == "print") =>
                    {
                        self.emit_printf(args);
                    }
                    ExprKind::Assign(lhs, rhs) => {
                        // Atomic compound assign on an 'actor'global field.
                        if let Some(line) = self.try_atomic_assign(lhs, rhs) {
                            self.line(&line);
                        } else {
                            let l = self.expr(lhs);
                            let r = self.expr(rhs);
                            self.line(&format!("{} = {};", l, r));
                        }
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let cond_s = self.expr(cond);
                    if idx == 0 {
                        self.line(&format!("if ({}) {{", cond_s));
                    } else {
                        self.line(&format!("}} else if ({}) {{", cond_s));
                    }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while ({}) {{", cond));
                self.indent += 1;
                if self.auto_sync && body_accesses_sync_field(&w.body, &self.current_fields) {
                    self.line("__syncthreads();");
                }
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                // `for i in ..n` — range iteration only in kernel context.
                let var = f.vars.first().cloned().unwrap_or_else(|| "_i".into());
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let op = if *inclusive { "<=" } else { "<" };
                        self.line(&format!("for (int64_t {var} = {lo}; {var} {op} {hi}; {var}++) {{"));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        self.line(&format!("/* for {var} in {iter} -- unsupported */"));
                        self.line("{");
                    }
                }
                self.indent += 1;
                if self.auto_sync && body_accesses_sync_field(&f.body, &self.current_fields) {
                    self.line("__syncthreads();");
                }
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            Stmt::Comment(c) if c == "sync" => self.line("__syncthreads();"),
            Stmt::Comment(_) => {}
            _ => { self.line("/* unsupported stmt in kernel */"); }
        }
    }

    /// True if `name` is a field with the `'actor'global` qualifier.
    fn is_actor_global_field(&self, name: &str) -> bool {
        self.current_fields.iter().any(|f|
            f.name == name && matches!(f.qual, GpuQual::ActorGlobal))
    }

    /// Detect `arr[i] OP= v` where `arr` is an `'actor'global` field and emit the
    /// corresponding atomic intrinsic.  Returns `Some(line)` if handled.
    fn try_atomic_assign(&mut self, lhs: &Expr, rhs: &Expr) -> Option<String> {
        // LHS must index an 'actor'global array field.
        let ExprKind::Index(arr, _idx) = &lhs.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !self.is_actor_global_field(&arr_name) { return None; }
        // RHS must be the desugared compound assign: BinOp(op, lhs, value).
        let ExprKind::BinOp(op, _lhs_copy, value) = &rhs.kind else { return None; };
        let intrinsic = match op {
            BinOp::Add    => "atomicAdd",
            BinOp::Sub    => "atomicSub",
            BinOp::BitOr  => "atomicOr",
            BinOp::BitAnd => "atomicAnd",
            BinOp::BitXor => "atomicXor",
            _ => return None,
        };
        let target = self.expr(lhs);
        let v = self.expr(value);
        Some(format!("{}(&{}, {});", intrinsic, target, v))
    }

    /// Emit a `print "..."` statement as a CUDA `printf(...)` call.
    fn emit_printf(&mut self, args: &[Arg]) {
        let Some(first) = args.first() else {
            self.line("printf(\"\\n\");");
            return;
        };
        match &first.value.kind {
            ExprKind::StringInterp(segs) => {
                let mut fmt = String::new();
                let mut call_args: Vec<String> = Vec::new();
                for seg in segs {
                    match seg {
                        StringSegment::Lit(s) => fmt.push_str(s),
                        StringSegment::Expr(e) | StringSegment::FormattedExpr(e, _) => {
                            fmt.push_str(self.printf_spec(e));
                            call_args.push(self.expr(e));
                        }
                    }
                }
                fmt.push_str("\\n");
                if call_args.is_empty() {
                    self.line(&format!("printf(\"{}\");", fmt));
                } else {
                    self.line(&format!("printf(\"{}\", {});", fmt, call_args.join(", ")));
                }
            }
            ExprKind::Str(s) => {
                self.line(&format!("printf(\"{}\\n\");", s));
            }
            other => {
                let _ = other;
                let spec = self.printf_spec(&first.value);
                let v = self.expr(&first.value);
                self.line(&format!("printf(\"{}\\n\", {});", spec, v));
            }
        }
    }

    /// Choose a printf format specifier for an interpolated expression.
    /// float → %f, string → %s, everything else → %lld (int default).
    fn printf_spec(&self, e: &Expr) -> &'static str {
        match &e.kind {
            ExprKind::Float(_) => "%f",
            ExprKind::Str(_) | ExprKind::StringInterp(_) => "%s",
            ExprKind::Var(name) => {
                // Inspect declared field types when available.
                if let Some(f) = self.current_fields.iter().find(|f| &f.name == name) {
                    if matches!(elem_c_type(&f.ty).as_str(), "double") { return "%f"; }
                    if matches!(c_type(&f.ty).as_str(), "const char*") { return "%s"; }
                }
                "%lld"
            }
            _ => "%lld",
        }
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)   => n.to_string(),
            ExprKind::Float(f) => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)  => if *b { "1".into() } else { "0".into() },
            ExprKind::Str(s)   => format!("\"{}\"", s),
            ExprKind::Nil      => "0".into(),
            ExprKind::Void     => "".into(),

            ExprKind::Var(name) => name.clone(),

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_c(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_c(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                format!("{}[{}]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                let obj_s = self.expr(obj);
                map_gpu_field(&obj_s, field)
            }
            ExprKind::Call(callee, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                let fn_s = match &callee.kind {
                    ExprKind::Var(n) => map_builtin_fn(n),
                    ExprKind::Field(obj, method) => {
                        let o = self.expr(obj);
                        format!("{}_{}", o, method)
                    }
                    _ => self.expr(callee),
                };
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                if matches!(&obj.kind, ExprKind::Var(n) if n == "self") {
                    // `self.method(args)` → the sibling device function this method was
                    // emitted as (see `emit_device_fn`): `KernelName_method(fields..., args)`.
                    let mut all_args = field_arg_names(&self.current_fields);
                    all_args.extend(args_s);
                    format!("{}_{}({})", self.current_kernel, method, all_args.join(", "))
                } else {
                    // Method calls on a receiver other than `self` have no C equivalent
                    // in this minimal device emitter — leave a visible marker rather than
                    // silently discarding the call.
                    let obj_s = self.expr(obj);
                    format!("/* unsupported: {}.{}({}) */", obj_s, method, args_s.join(", "))
                }
            }
            ExprKind::Cast(inner, ty) => {
                format!("(({})({})) ", c_type(ty), self.expr(inner))
            }
            ExprKind::If(i) => {
                // Ternary: only first branch used.
                if let Some((cond, then_body)) = i.branches.first() {
                    let c = self.expr(cond);
                    let t = then_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    let e = i.else_body.as_ref().and_then(|b| b.last()).and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    format!("({} ? {} : {})", c, t, e)
                } else {
                    "0".into()
                }
            }
            ExprKind::Range { start, end, inclusive: _ } => {
                format!("/* range {}..{} */", self.expr(start), self.expr(end))
            }
            _ => "/* expr */".into(),
        }
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn field_params(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Sync | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                let base = elem_c_type(&f.ty);
                let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                Some(format!("{}{}* {}", constness, base, f.name))
            }
            GpuQual::Const => {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                    None  // __constant__ arrays are file-scope globals, not parameters
                } else {
                    let base = elem_c_type(&f.ty);
                    Some(format!("const {} {}", base, f.name))
                }
            }
        }
    }).chain(
        // Scalar (non-array) 'local fields: passed by value.
        // `'const` fields are already fully emitted (with the `const` qualifier) by the
        // first iterator above — including them here too would duplicate the parameter
        // and shift every later parameter out of sync with the host launcher's `.arg()` order.
        fields.iter().filter_map(|f| {
            match f.qual {
                GpuQual::Local => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => None,
                        _ => Some(format!("{} {}", c_type(&f.ty), f.name)),
                    }
                }
                _ => None,
            }
        })
    ).collect()
}

/// Argument names to pass at a call site for `field_params(fields)` — same filtering
/// and ordering, but just the bare field names instead of full C parameter declarations.
fn field_arg_names(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Sync | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal => {
                Some(f.name.clone())
            }
            GpuQual::Const => {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                    None  // __constant__ arrays accessed via file-scope global, not as args
                } else {
                    Some(f.name.clone())
                }
            }
        }
    }).chain(
        fields.iter().filter_map(|f| {
            match f.qual {
                GpuQual::Local => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => None,
                        _ => Some(f.name.clone()),
                    }
                }
                _ => None,
            }
        })
    ).collect()
}

fn c_type(ty: &Type) -> String {
    match ty {
        Type::Int              => "int64_t".into(),
        Type::Uint             => "uint64_t".into(),
        Type::Float            => "double".into(),
        Type::Bool             => "int".into(),
        Type::Str              => "const char*".into(),
        Type::Nil | Type::Void => "void".into(),
        Type::Array(inner)     => format!("{}*", c_type(inner)),
        Type::ArrayN(inner, n) => format!("{}[{}]", c_type(inner), n),
        // Named primitives — the kernel field parser may store raw keyword strings.
        Type::Named(n) => match n.as_str() {
            "float" | "f64" | "f32" => "double",
            "int"   | "i64"         => "int64_t",
            "uint"  | "u64"         => "uint64_t",
            "bool"                  => "int",
            other                   => return other.to_string(),
        }.into(),
        Type::Qualified(inner, _) => c_type(inner),
        Type::Optional(inner)  => c_type(inner),
        Type::TypeParam(p)     => p.clone(),
        _                      => "void*".into(),
    }
}

fn elem_c_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)     => c_type(inner),
        Type::ArrayN(inner, _) => c_type(inner),
        Type::Qualified(inner, _) => elem_c_type(inner),
        _                      => c_type(ty),
    }
}

fn binop_c(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",  BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",  BinOp::Rem => "%",
        BinOp::Eq  => "==", BinOp::NotEq => "!=",
        BinOp::Lt  => "<",  BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&", BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<", BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_c(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "~",
    }
}

fn map_gpu_field(obj: &str, field: &str) -> String {
    match (obj, field) {
        ("gpu", "thread")    => "threadIdx".into(),
        ("gpu", "block")     => "blockIdx".into(),
        ("gpu", "block_dim") => "blockDim".into(),
        ("gpu", "grid_dim")  => "gridDim".into(),
        ("threadIdx", "x")   => "threadIdx.x".into(),
        ("threadIdx", "y")   => "threadIdx.y".into(),
        ("threadIdx", "z")   => "threadIdx.z".into(),
        ("blockIdx",  "x")   => "blockIdx.x".into(),
        ("blockIdx",  "y")   => "blockIdx.y".into(),
        ("blockIdx",  "z")   => "blockIdx.z".into(),
        ("blockDim",  "x")   => "blockDim.x".into(),
        ("blockDim",  "y")   => "blockDim.y".into(),
        ("blockDim",  "z")   => "blockDim.z".into(),
        ("gridDim",   "x")   => "gridDim.x".into(),
        ("gridDim",   "y")   => "gridDim.y".into(),
        ("gridDim",   "z")   => "gridDim.z".into(),
        _                    => format!("{}.{}", obj, field),
    }
}

fn map_builtin_fn(name: &str) -> String {
    match name {
        "int"   => "(int64_t)".into(),
        "float" => "(double)".into(),
        "abs"   => "fabs".into(),
        "min"   => "min".into(),
        "max"   => "max".into(),
        "sqrt"  => "sqrt".into(),
        other   => other.into(),
    }
}

// ── Auto-sync helpers ─────────────────────────────────────────────────────────

fn body_has_explicit_sync(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Comment(c) if c == "sync" => true,
        Stmt::While(w)   => body_has_explicit_sync(&w.body),
        Stmt::For(f)     => body_has_explicit_sync(&f.body),
        Stmt::If(i)      => i.branches.iter().any(|(_, b)| body_has_explicit_sync(b))
                         || i.else_body.as_ref().map_or(false, |b| body_has_explicit_sync(b)),
        _ => false,
    })
}

fn body_accesses_sync_field(stmts: &[Stmt], fields: &[KernelFieldDecl]) -> bool {
    let sync_names: Vec<&str> = fields.iter()
        .filter(|f| matches!(f.qual, GpuQual::Sync))
        .map(|f| f.name.as_str())
        .collect();
    if sync_names.is_empty() { return false; }
    stmts_reference_any(stmts, &sync_names)
}

fn stmts_reference_any(stmts: &[Stmt], names: &[&str]) -> bool {
    stmts.iter().any(|s| stmt_references_any(s, names))
}

fn stmt_references_any(stmt: &Stmt, names: &[&str]) -> bool {
    match stmt {
        Stmt::Expr(e) => expr_references_any(e, names),
        Stmt::Return(r) => r.value.as_ref().map_or(false, |v| expr_references_any(v, names)),
        Stmt::Let(s) => s.value.as_ref().map_or(false, |v| expr_references_any(v, names)),
        Stmt::While(w) => stmts_reference_any(&w.body, names),
        Stmt::For(f)   => stmts_reference_any(&f.body, names),
        Stmt::If(i)    => i.branches.iter().any(|(_, b)| stmts_reference_any(b, names))
                       || i.else_body.as_ref().map_or(false, |b| stmts_reference_any(b, names)),
        _ => false,
    }
}

fn expr_references_any(expr: &Expr, names: &[&str]) -> bool {
    match &expr.kind {
        ExprKind::Var(n)           => names.contains(&n.as_str()),
        ExprKind::Index(a, i)      => expr_references_any(a, names) || expr_references_any(i, names),
        ExprKind::Field(e, _)      => expr_references_any(e, names),
        ExprKind::BinOp(_, l, r)   => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::UnaryOp(_, e)    => expr_references_any(e, names),
        ExprKind::Assign(l, r)     => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::Call(f, args)    => expr_references_any(f, names) || args.iter().any(|a| expr_references_any(&a.value, names)),
        _ => false,
    }
}

fn first_loop_index(stmts: &[Stmt]) -> usize {
    stmts.iter().position(|s| matches!(s, Stmt::While(_) | Stmt::For(_)))
        .unwrap_or(stmts.len())
}
