// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// CUDA C device code emitter.

use crate::ast::*;
use crate::transpiler::helpers::{
    reachable_free_fns, float_unary_method_c,
    labeled_array_at_index, labeled_array_dim_literal,
    first_loop_index,
};

pub(super) fn emit_device_cu(program: &Program) -> String {
    let mut e = DeviceEmitter::new();
    e.emit_program(program);
    e.out
}

struct DeviceEmitter {
    out: String,
    indent: usize,
    current_fields: Vec<KernelFieldDecl>,
    current_kernel: String,
    /// Auto-barrier mode: true when the kernel `def` has no explicit `sync` statements.
    auto_sync: bool,
    // Top-level scalar lets inlined into CUDA C (not in scope in device code —
    // see `metal::device`'s identical fix).
    top_level_scalars: std::collections::HashMap<String, String>,
}

impl DeviceEmitter {
    fn new() -> Self {
        Self {
            out: String::new(), indent: 0, current_fields: vec![], current_kernel: String::new(),
            auto_sync: false, top_level_scalars: std::collections::HashMap::new(),
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program) {
        // Pre-pass: collect top-level scalar lets for inlining in device code —
        // a bare top-level `let n = ...` never becomes an actual variable in the
        // generated .cu file, so any kernel body referencing it needs the literal
        // value substituted in directly (mirrors `metal::device`'s identical fix).
        for item in &program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    let is_scalar = crate::transpiler::helpers::is_scalar_let_value(val, s.ty.as_ref());
                    if is_scalar {
                        let rhs = self.expr(val);
                        self.top_level_scalars.insert(s.name.clone(), rhs);
                    }
                }
            }
        }

        self.line("// Generated by boring build --target cuda.");
        self.line("// Compile to PTX with: nvcc --ptx kernels/main.cu -o $OUT_DIR/main.ptx");
        self.blank();
        self.line("#include <cuda_runtime.h>");
        self.line("#include <stdint.h>");
        self.blank();
        // Boring built-in Dimension type (mirrors host-side struct, see
        // helpers::DIMENSION_STRUCT_RUST — width/height are `u32`, so this must
        // stay `uint32_t`/`uint32_t`, not go through `c_type()`'s uint->uint64_t map).
        self.line("struct Dimension { uint32_t width; uint32_t height; };");
        self.blank();

        // Emit free functions as __device__ helpers, but only those actually
        // reachable from kernel code -- free functions are ordinary Boring
        // functions shared with the host (CPU) build, and routinely use
        // dynamic-array / heap constructs (`[float]` growable arrays, `.push`,
        // string formatting, etc.) that have no CUDA C equivalent. Emitting
        // every free function unconditionally makes kernels/main.cu fail to
        // compile as soon as the program has ANY host-only helper with this
        // shape -- even a program with zero kernels at all (see `metal::device`'s
        // identical fix and doc comment).
        let reachable = reachable_free_fns(program);
        for item in &program.items {
            if let Item::Fn(decl) = item {
                if decl.qualifier.is_none() && !decl.task && reachable.contains(&decl.name) {
                    self.emit_free_device_fn(decl);
                    self.blank();
                }
            }
        }

        self.line("extern \"C\" {");
        self.blank();

        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.emit_kernel_decl(decl);
            }
        }

        self.line("}  // extern \"C\"");
    }

    fn emit_free_device_fn(&mut self, decl: &crate::ast::FnDecl) {
        let ret = decl.return_ty.as_ref().map(c_type).unwrap_or_else(|| "void".into());
        let params: Vec<String> = decl.params.iter().map(|p| {
            let ty = p.ty.as_ref().map(c_type).unwrap_or_else(|| "int64_t".into());
            format!("{} {}", ty, p.name)
        }).collect();
        self.line(&format!("__device__ {} {}({}) {{", ret, decl.name, params.join(", ")));
        self.indent += 1;
        for stmt in &decl.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_decl(&mut self, decl: &KernelDecl) {
        self.current_fields = decl.fields.clone();
        self.current_kernel = decl.name.clone();
        self.line(&format!("// ─── kernel {} ───", decl.name));
        self.blank();

        // Emit __constant__ declarations for fixed-size 'const array fields.
        // These are file-scope globals in CUDA, not kernel parameters.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Const) {
                if let Type::ArrayN(inner, n) = &field.ty {
                    let elem = elem_c_type(inner);
                    self.line(&format!("__constant__ {} {}[{}];", elem, field.name, n));
                } else if let Some((elem, _)) = field.ty.as_labeled_array() {
                    // `labeled_array_len()` is `None` when an axis size
                    // references a kernel const-generic param rather than a
                    // literal int — not yet handled here (no real .br file
                    // needs it today; see docs/array-multidim-types.md).
                    if let Some(len) = field.ty.labeled_array_len() {
                        self.line(&format!("__constant__ {} {}[{}];", c_type(elem), field.name, len));
                    }
                }
            }
        }

        // Device helper methods (non-entry-point defs).
        for method in &decl.methods {
            if !method.name.is_empty() {
                self.emit_device_fn(&decl.name, method, &decl.fields);
                self.blank();
            }
        }

        // Entry point: `def ()`.
        if let Some(entry) = decl.methods.iter().find(|m| m.name.is_empty()) {
            self.emit_entry_point(decl, entry);
            self.blank();
        }
    }

    fn emit_device_fn(&mut self, kernel: &str, method: &FnDecl, fields: &[KernelFieldDecl]) {
        let ret = method.return_ty.as_ref().map(c_type).unwrap_or_else(|| "void".into());
        let fn_name = format!("{}_{}", kernel, method.name);
        let mut params = field_params(fields);
        for p in &method.params {
            let ty = p.ty.as_ref().map(c_type).unwrap_or_else(|| "int64_t".into());
            params.push(format!("{} {}", ty, p.name));
        }
        self.line(&format!("__device__ {} {}({}) {{", ret, fn_name, params.join(", ")));
        self.indent += 1;
        for stmt in &method.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_entry_point(&mut self, decl: &KernelDecl, entry: &FnDecl) {
        let fn_name = format!("{}_kernel", decl.name);
        let params = field_params(&decl.fields);
        self.line(&format!("__global__ void {}({}) {{", fn_name, params.join(", ")));
        self.indent += 1;
        // Declare shared-memory fields.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Actor) {
                match &field.ty {
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("__shared__ {} {}[{}];", c_type(inner), field.name, n));
                    }
                    ty if ty.as_labeled_array().is_some() && ty.labeled_array_len().is_some() => {
                        let (elem, _) = ty.as_labeled_array().unwrap();
                        let len = ty.labeled_array_len().unwrap();
                        self.line(&format!("__shared__ {} {}[{}];", c_type(elem), field.name, len));
                    }
                    _ => {
                        let elem = elem_c_type(&field.ty);
                        self.line(&format!("extern __shared__ {} {}[];", elem, field.name));
                    }
                }
            }
        }
        // Declare per-thread 'local fields inside the kernel body.
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Local) {
                match &field.ty {
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("{} {}[{}];", c_type(inner), field.name, n));
                    }
                    Type::Array(_) => {
                        // Unsized local array — not representable; skip.
                    }
                    ty if ty.as_labeled_array().is_some() && ty.labeled_array_len().is_some() => {
                        let (elem, _) = ty.as_labeled_array().unwrap();
                        let len = ty.labeled_array_len().unwrap();
                        self.line(&format!("{} {}[{}];", c_type(elem), field.name, len));
                    }
                    // Scalar 'local: already a by-value kernel parameter (see
                    // `field_params`), seeded from the host's current field value each
                    // launch (`launcher.arg(&self.{field})` in cuda/host.rs) -- redeclaring
                    // it here would both collide with that parameter name (a real "already
                    // declared in this scope" nvcc error, confirmed via
                    // examples/plasma_metal.br's `var float t`) and discard the seeded
                    // value by resetting it to 0. Nothing to do: the parameter already
                    // provides a thread-local mutable register under this exact name.
                    _ => {}
                }
            }
        }
        let has_sync_fields = self.current_fields.iter().any(|f| matches!(f.qual, GpuQual::Actor));
        self.auto_sync = has_sync_fields && !body_has_explicit_sync(&entry.body);
        if self.auto_sync {
            let split = first_loop_index(&entry.body);
            for stmt in &entry.body[..split] { self.emit_stmt(stmt); }
            if split < entry.body.len() {
                self.line("__syncthreads();");
            }
            for stmt in &entry.body[split..] { self.emit_stmt(stmt); }
        } else {
            for stmt in &entry.body { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let mutable = matches!(s.binding, BindingKind::Mut | BindingKind::Var | BindingKind::Lazy);
                let ty = s.ty.as_ref().map(c_type).unwrap_or_else(|| "auto".into());
                let kw = if mutable { "" } else { "const " };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{}{} {} = {};", kw, ty, s.name, rhs));
                } else {
                    self.line(&format!("{}{} {};", kw, ty, s.name));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    // `print "..."` → printf(...) in device code.
                    ExprKind::Call(callee, args)
                        if matches!(&callee.kind, ExprKind::Var(n) if n == "print") =>
                    {
                        self.emit_printf(args);
                    }
                    ExprKind::Assign(lhs, rhs) => {
                        // Atomic compound assign on an 'actor'global field.
                        if let Some(line) = self.try_atomic_assign(lhs, rhs) {
                            self.line(&line);
                        } else {
                            let l = self.expr(lhs);
                            let r = self.expr(rhs);
                            self.line(&format!("{} = {};", l, r));
                        }
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let cond_s = self.expr(cond);
                    if idx == 0 {
                        self.line(&format!("if ({}) {{", cond_s));
                    } else {
                        self.line(&format!("}} else if ({}) {{", cond_s));
                    }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("while ({}) {{", cond));
                self.indent += 1;
                if self.auto_sync && body_accesses_sync_field(&w.body, &self.current_fields) {
                    self.line("__syncthreads();");
                }
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                // `for i in ..n` — range iteration only in kernel context.
                let var = f.vars.first().cloned().unwrap_or_else(|| "_i".into());
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let op = if *inclusive { "<=" } else { "<" };
                        self.line(&format!("for (int64_t {var} = {lo}; {var} {op} {hi}; {var}++) {{"));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        self.line(&format!("/* for {var} in {iter} -- unsupported */"));
                        self.line("{");
                    }
                }
                self.indent += 1;
                if self.auto_sync && body_accesses_sync_field(&f.body, &self.current_fields) {
                    self.line("__syncthreads();");
                }
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            Stmt::Comment(c) if c == "sync" => self.line("__syncthreads();"),
            Stmt::Comment(_) => {}
            _ => { self.line("/* unsupported stmt in kernel */"); }
        }
    }

    /// True if `name` is a field with the `'actor'global` or `'actor'unified` qualifier —
    /// atomicAdd/Sub/Or/And/Xor take a plain pointer of the base type in CUDA C, so the
    /// same intrinsics apply unconditionally regardless of which allocator backs it.
    fn is_atomic_field(&self, name: &str) -> bool {
        self.current_fields.iter().any(|f|
            f.name == name && matches!(f.qual, GpuQual::ActorGlobal | GpuQual::ActorUnified))
    }

    /// Detect `arr[i] OP= v` where `arr` is an `'actor'global`/`'actor'unified` field and
    /// emit the corresponding atomic intrinsic.  Returns `Some(line)` if handled.
    fn try_atomic_assign(&mut self, lhs: &Expr, rhs: &Expr) -> Option<String> {
        // LHS must index an atomic array field.
        let ExprKind::Index(arr, _idx) = &lhs.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !self.is_atomic_field(&arr_name) { return None; }
        // RHS must be the desugared compound assign: BinOp(op, lhs, value).
        let ExprKind::BinOp(op, _lhs_copy, value) = &rhs.kind else { return None; };
        let intrinsic = match op {
            BinOp::Add    => "atomicAdd",
            BinOp::Sub    => "atomicSub",
            BinOp::BitOr  => "atomicOr",
            BinOp::BitAnd => "atomicAnd",
            BinOp::BitXor => "atomicXor",
            _ => return None,
        };
        let target = self.expr(lhs);
        let v = self.expr(value);
        Some(format!("{}(&{}, {});", intrinsic, target, v))
    }

    /// Detect `arr[i].min/max/swap/cas(...)`. Unlike `try_atomic_assign` (a
    /// statement-only compound-assign desugar with no return value), these
    /// return the previous value — `atomicMin`/`atomicMax`/`atomicExch`/
    /// `atomicCAS` all do the same in real CUDA C — so this is handled in
    /// expression position (`let old = counts[i].cas(0, 1)` binds `old` to
    /// the intrinsic's own return value), not as a statement special case.
    ///
    /// `arr` doesn't have to be an `'actor'global`/`'actor'unified` field —
    /// these methods work on *any* indexed element, atomic or not (matching
    /// `+=`/`-=`/etc., which already degrade to plain, non-atomic arithmetic
    /// off an actor-qualified field rather than erroring). When `arr` isn't
    /// atomic, there's no intrinsic to lean on for the "return the previous
    /// value" contract, so it's bridged the same way Metal's `.cas` already
    /// is: a GNU/Clang statement-expression (`({ ... })` — nvcc's device-code
    /// compiler accepts this GNU C extension) that reads the old value,
    /// performs the plain update, and yields the old value.
    fn try_atomic_method_call(&mut self, obj: &Expr, method: &str, args_s: &[String]) -> Option<String> {
        let ExprKind::Index(arr, _idx) = &obj.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !matches!(method, "min" | "max" | "swap" | "cas") { return None; }
        let target = self.expr(obj);
        if self.is_atomic_field(&arr_name) {
            match (method, args_s) {
                ("min", [v]) => Some(format!("atomicMin(&{}, {})", target, v)),
                ("max", [v]) => Some(format!("atomicMax(&{}, {})", target, v)),
                ("swap", [v]) => Some(format!("atomicExch(&{}, {})", target, v)),
                ("cas", [expected, new]) => Some(format!("atomicCAS(&{}, {}, {})", target, expected, new)),
                _ => None,
            }
        } else {
            match (method, args_s) {
                ("min", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = min({t}, ({v})); __old; }})", t = target, v = v)),
                ("max", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = max({t}, ({v})); __old; }})", t = target, v = v)),
                ("swap", [v]) => Some(format!(
                    "({{ auto __old = {t}; {t} = ({v}); __old; }})", t = target, v = v)),
                ("cas", [expected, new]) => Some(format!(
                    "({{ auto __old = {t}; if (__old == ({e})) {t} = ({n}); __old; }})",
                    t = target, e = expected, n = new)),
                _ => None,
            }
        }
    }

    /// `a.axis` — read-only shape-query property on a fixed-shape
    /// `LabeledArray` field (dynamic-shape ones are already desugared to a
    /// shadow field before codegen — see `desugar_labeled_array`). `a[width =
    /// w, height = h]`-style indexing is a distinct `ExprKind::LabeledIndex`
    /// node, handled directly in `expr()`'s main match instead of here.
    fn try_labeled_array_field_access(&mut self, obj: &Expr, field_name: &str) -> Option<String> {
        let ExprKind::Var(name) = &obj.kind else { return None; };
        let field = self.current_fields.iter().find(|f| &f.name == name)?;
        let (_, axes) = field.ty.as_labeled_array()?;
        labeled_array_dim_literal(axes, field_name)
    }

    /// Emit a `print "..."` statement as a CUDA `printf(...)` call.
    fn emit_printf(&mut self, args: &[Arg]) {
        let Some(first) = args.first() else {
            self.line("printf(\"\\n\");");
            return;
        };
        match &first.value.kind {
            ExprKind::StringInterp(segs) => {
                let mut fmt = String::new();
                let mut call_args: Vec<String> = Vec::new();
                for seg in segs {
                    match seg {
                        StringSegment::Lit(s) => fmt.push_str(s),
                        StringSegment::Expr(e) | StringSegment::FormattedExpr(e, _) => {
                            fmt.push_str(self.printf_spec(e));
                            call_args.push(self.expr(e));
                        }
                    }
                }
                fmt.push_str("\\n");
                if call_args.is_empty() {
                    self.line(&format!("printf(\"{}\");", fmt));
                } else {
                    self.line(&format!("printf(\"{}\", {});", fmt, call_args.join(", ")));
                }
            }
            ExprKind::Str(s) => {
                self.line(&format!("printf(\"{}\\n\");", s));
            }
            other => {
                let _ = other;
                let spec = self.printf_spec(&first.value);
                let v = self.expr(&first.value);
                self.line(&format!("printf(\"{}\\n\", {});", spec, v));
            }
        }
    }

    /// Choose a printf format specifier for an interpolated expression.
    /// float → %f, string → %s, everything else → %lld (int default).
    fn printf_spec(&self, e: &Expr) -> &'static str {
        match &e.kind {
            ExprKind::Float(_) => "%f",
            ExprKind::Str(_) | ExprKind::StringInterp(_) => "%s",
            ExprKind::Var(name) => {
                // Inspect declared field types when available.
                if let Some(f) = self.current_fields.iter().find(|f| &f.name == name) {
                    if matches!(elem_c_type(&f.ty).as_str(), "double") { return "%f"; }
                    if matches!(c_type(&f.ty).as_str(), "const char*") { return "%s"; }
                }
                "%lld"
            }
            _ => "%lld",
        }
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)   => n.to_string(),
            ExprKind::Float(f) => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)  => if *b { "1".into() } else { "0".into() },
            ExprKind::Str(s)   => format!("\"{}\"", s),
            ExprKind::Nil      => "0".into(),
            ExprKind::Void     => "".into(),

            ExprKind::Var(name) => {
                // A kernel field of the same name shadows the top-level scalar
                // (e.g. `kernel Saxpy: let float alpha` vs. top-level `let alpha = 2.0`
                // in examples/saxpy.br) -- the field is a real local/parameter in the
                // generated device function, so it must win, not the outer literal.
                if self.current_fields.iter().any(|f| f.name == *name) {
                    name.clone()
                } else {
                    self.top_level_scalars.get(name).cloned().unwrap_or_else(|| name.clone())
                }
            }

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_c(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_c(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                format!("{}[{}]", self.expr(arr), self.expr(idx))
            }
            ExprKind::LabeledIndex(obj, args) => {
                // Stringify every arg's value first (needs `&mut self`) —
                // only then borrow `self.current_fields` immutably, so the
                // two borrows never overlap.
                let pairs: Vec<(String, String)> = args.iter()
                    .filter_map(|a| a.label.clone().map(|l| (l, self.expr(&a.value))))
                    .collect();
                let resolved = if let ExprKind::Var(name) = &obj.kind {
                    self.current_fields.iter().find(|f| &f.name == name)
                        .and_then(|field| field.ty.as_labeled_array())
                        .and_then(|(_, axes)| labeled_array_at_index(axes, &pairs))
                        .map(|offset| format!("{}[{}]", name, offset))
                } else {
                    None
                };
                resolved.unwrap_or_else(|| "/* unsupported labeled index */".to_string())
            }
            ExprKind::Field(obj, field) => {
                if let Some(s) = self.try_labeled_array_field_access(obj, field) {
                    s
                } else {
                    let obj_s = self.expr(obj);
                    map_gpu_field(&obj_s, field)
                }
            }
            ExprKind::Call(callee, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                let fn_s = match &callee.kind {
                    ExprKind::Var(n) => map_builtin_fn(n),
                    ExprKind::Field(obj, method) => {
                        let o = self.expr(obj);
                        format!("{}_{}", o, method)
                    }
                    _ => self.expr(callee),
                };
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                if is_gpu_warp_receiver(obj) {
                    if let Some(call) = gpu_warp_method_call(method, &args_s) {
                        return call;
                    }
                }
                if let Some(call) = self.try_atomic_method_call(obj, method, &args_s) {
                    return call;
                }
                if matches!(&obj.kind, ExprKind::Var(n) if n == "self") {
                    // `self.method(args)` → the sibling device function this method was
                    // emitted as (see `emit_device_fn`): `KernelName_method(fields..., args)`.
                    let mut all_args = field_arg_names(&self.current_fields);
                    all_args.extend(args_s);
                    format!("{}_{}({})", self.current_kernel, method, all_args.join(", "))
                } else if let Some(call) = float_unary_method_c(method, &self.expr(obj), &args_s) {
                    // Boring's built-in numeric methods (`x.exp()`, `x.sqrt()`, ...) map
                    // directly onto CUDA C's device math functions of the same shape.
                    call
                } else {
                    // Method calls on a receiver other than `self` have no C equivalent
                    // in this minimal device emitter — leave a visible marker rather than
                    // silently discarding the call.
                    let obj_s = self.expr(obj);
                    format!("/* unsupported: {}.{}({}) */", obj_s, method, args_s.join(", "))
                }
            }
            ExprKind::Cast(inner, ty) => {
                format!("(({})({})) ", c_type(ty), self.expr(inner))
            }
            ExprKind::If(i) => {
                // Ternary: only first branch used.
                if let Some((cond, then_body)) = i.branches.first() {
                    let c = self.expr(cond);
                    let t = then_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    let e = i.else_body.as_ref().and_then(|b| b.last()).and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    format!("({} ? {} : {})", c, t, e)
                } else {
                    "0".into()
                }
            }
            ExprKind::Range { start, end, inclusive: _ } => {
                format!("/* range {}..{} */", self.expr(start), self.expr(end))
            }
            _ => "/* expr */".into(),
        }
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn field_params(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Actor | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::ActorUnified | GpuQual::Surface => {
                let base = elem_c_type(&f.ty);
                let constness = if matches!(f.binding, FieldBinding::Let) { "const " } else { "" };
                Some(format!("{}{}* {}", constness, base, f.name))
            }
            GpuQual::Const => {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) || f.ty.as_labeled_array().is_some() {
                    None  // __constant__ arrays are file-scope globals, not parameters
                } else {
                    let base = elem_c_type(&f.ty);
                    Some(format!("const {} {}", base, f.name))
                }
            }
        }
    }).chain(
        // Scalar (non-array) 'local fields: passed by value.
        // `'const` fields are already fully emitted (with the `const` qualifier) by the
        // first iterator above — including them here too would duplicate the parameter
        // and shift every later parameter out of sync with the host launcher's `.arg()` order.
        fields.iter().filter_map(|f| {
            match f.qual {
                GpuQual::Local => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => None,
                        ty if ty.as_labeled_array().is_some() => None,
                        _ => Some(format!("{} {}", c_type(&f.ty), f.name)),
                    }
                }
                _ => None,
            }
        })
    ).collect()
}

/// Argument names to pass at a call site for `field_params(fields)` — same filtering
/// and ordering, but just the bare field names instead of full C parameter declarations.
fn field_arg_names(fields: &[KernelFieldDecl]) -> Vec<String> {
    fields.iter().filter_map(|f| {
        match f.qual {
            GpuQual::Actor | GpuQual::Local => None,
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::ActorUnified | GpuQual::Surface => {
                Some(f.name.clone())
            }
            GpuQual::Const => {
                if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) || f.ty.as_labeled_array().is_some() {
                    None  // __constant__ arrays accessed via file-scope global, not as args
                } else {
                    Some(f.name.clone())
                }
            }
        }
    }).chain(
        fields.iter().filter_map(|f| {
            match f.qual {
                GpuQual::Local => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => None,
                        ty if ty.as_labeled_array().is_some() => None,
                        _ => Some(f.name.clone()),
                    }
                }
                _ => None,
            }
        })
    ).collect()
}

fn c_type(ty: &Type) -> String {
    match ty {
        Type::Int              => "int64_t".into(),
        Type::Uint             => "uint64_t".into(),
        // Fixed-width kinds map onto <cstdint> exactly. `__int128`/`unsigned __int128`
        // are a GCC/Clang (and NVCC-supported) extension, not standard C/C++ — flagged
        // in a comment since portability to other compilers isn't guaranteed.
        Type::Uint8             => "uint8_t".into(),
        Type::Int8               => "int8_t".into(),
        Type::Int16              => "int16_t".into(),
        Type::Int32              => "int32_t".into(),
        Type::Int64              => "int64_t".into(),
        Type::Int128              => "__int128 /* GCC/NVCC extension */".into(),
        Type::Uint16             => "uint16_t".into(),
        Type::Uint32             => "uint32_t".into(),
        Type::Uint64             => "uint64_t".into(),
        Type::Uint128             => "unsigned __int128 /* GCC/NVCC extension */".into(),
        Type::Float32            => "float".into(),
        Type::Float64            => "double".into(),
        Type::Bool             => "int".into(),
        Type::Str              => "const char*".into(),
        Type::Nil | Type::Void => "void".into(),
        Type::Array(inner)     => format!("{}*", c_type(inner)),
        Type::ArrayN(inner, n) => format!("{}[{}]", c_type(inner), n),
        Type::LabeledArray(inner, _) => format!("{}*", c_type(inner)),
        // Named primitives — the kernel field parser may store raw keyword strings.
        Type::Named(n) => match n.as_str() {
            "float32" | "f32" => "float".to_string(),
            "float" | "float64" | "f64" => "double".to_string(),
            "int"   | "i64"         => "int64_t".to_string(),
            "uint"  | "u64"         => "uint64_t".to_string(),
            "uint8"                  => "uint8_t".to_string(),
            "int8"                   => "int8_t".to_string(),
            "int16"                  => "int16_t".to_string(),
            "int32"                  => "int32_t".to_string(),
            "int64"                  => "int64_t".to_string(),
            "int128"                 => "__int128 /* GCC/NVCC extension */".to_string(),
            "uint16"                 => "uint16_t".to_string(),
            "uint32"                 => "uint32_t".to_string(),
            "uint64"                 => "uint64_t".to_string(),
            "uint128"                => "unsigned __int128 /* GCC/NVCC extension */".to_string(),
            "bool"                  => "int".to_string(),
            other                   => other.to_string(),
        },
        Type::Qualified(inner, _) => c_type(inner),
        Type::Optional(inner)  => c_type(inner),
        Type::TypeParam(p)     => p.clone(),
        _                      => "void*".into(),
    }
}

fn elem_c_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)     => c_type(inner),
        Type::ArrayN(inner, _) => c_type(inner),
        Type::Qualified(inner, _) => elem_c_type(inner),
        Type::LabeledArray(inner, _) => c_type(inner),
        _                      => c_type(ty),
    }
}

fn binop_c(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",  BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",  BinOp::Rem => "%",
        BinOp::Eq  => "==", BinOp::NotEq => "!=",
        BinOp::Lt  => "<",  BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&", BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<", BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_c(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "~",
    }
}

fn map_gpu_field(obj: &str, field: &str) -> String {
    match (obj, field) {
        ("gpu", "thread")    => "threadIdx".into(),
        ("gpu", "block")     => "blockIdx".into(),
        ("gpu", "block_dim") => "blockDim".into(),
        ("gpu", "grid_dim")  => "gridDim".into(),
        ("threadIdx", "x")   => "threadIdx.x".into(),
        ("threadIdx", "y")   => "threadIdx.y".into(),
        ("threadIdx", "z")   => "threadIdx.z".into(),
        ("blockIdx",  "x")   => "blockIdx.x".into(),
        ("blockIdx",  "y")   => "blockIdx.y".into(),
        ("blockIdx",  "z")   => "blockIdx.z".into(),
        ("blockDim",  "x")   => "blockDim.x".into(),
        ("blockDim",  "y")   => "blockDim.y".into(),
        ("blockDim",  "z")   => "blockDim.z".into(),
        ("gridDim",   "x")   => "gridDim.x".into(),
        ("gridDim",   "y")   => "gridDim.y".into(),
        ("gridDim",   "z")   => "gridDim.z".into(),
        ("gpu", "warp")      => "__warp".into(),
        ("__warp", "size")   => "warpSize".into(),
        ("__warp", "lane")   =>
            "((threadIdx.x + threadIdx.y * blockDim.x + threadIdx.z * blockDim.x * blockDim.y) % warpSize)".into(),
        _                    => format!("{}.{}", obj, field),
    }
}

/// `gpu.warp.sync()` / `gpu.warp.shuffle_down/up/xor/shuffle(...)` — CUDA's
/// `_sync` intrinsics (post-Volta) require an explicit active-lane mask;
/// Boring always passes the full mask (`0xffffffff`) rather than exposing one
/// in source, so these are only as safe as that mask is under thread
/// divergence (see docs/warp-level-primitives.md's divergent-branch caveat).
fn gpu_warp_method_call(method: &str, args: &[String]) -> Option<String> {
    match method {
        "sync"         => Some("__syncwarp(0xffffffff)".into()),
        "shuffle_down" => Some(format!("__shfl_down_sync(0xffffffff, {}, {})", args[0], args[1])),
        "shuffle_up"   => Some(format!("__shfl_up_sync(0xffffffff, {}, {})", args[0], args[1])),
        "shuffle_xor"  => Some(format!("__shfl_xor_sync(0xffffffff, {}, {})", args[0], args[1])),
        "shuffle"      => Some(format!("__shfl_sync(0xffffffff, {}, {})", args[0], args[1])),
        _ => None,
    }
}

fn is_gpu_warp_receiver(obj: &Expr) -> bool {
    matches!(&obj.kind, ExprKind::Field(inner, name) if name == "warp"
        && matches!(&inner.kind, ExprKind::Var(v) if v == "gpu"))
}

fn map_builtin_fn(name: &str) -> String {
    match name {
        "int"   | "i64"    => "(int64_t)".into(),
        "float" | "float64" | "f64" => "(double)".into(),
        // `float32(x)`/`f32(x)` — was missing entirely and fell through to the
        // `other => other.into()` passthrough below, emitting an invalid,
        // undeclared `float32(x)` function call in the generated CUDA C
        // (confirmed via the identical bug on the ROCm backend, this device
        // emitter's near-verbatim clone — see rocm::device's `map_builtin_fn`
        // for the real-hardware repro via `examples/mandelbrot_gpu.br`).
        // Metal's own `map_builtin_fn` already carries the equivalent fix.
        // The rest of this arm set mirrors `c_type`'s `Type::Named` cast-name
        // table just above, for the same call-style casts (`uint8(x)`,
        // `bool(x)`, ...) that table already resolves for `x as T`-style casts.
        "float32" | "f32"  => "(float)".into(),
        "uint"    | "u64"  => "(uint64_t)".into(),
        "uint8"             => "(uint8_t)".into(),
        "int8"              => "(int8_t)".into(),
        "int16"             => "(int16_t)".into(),
        "int32"             => "(int32_t)".into(),
        "int64"             => "(int64_t)".into(),
        "uint16"            => "(uint16_t)".into(),
        "uint32"            => "(uint32_t)".into(),
        "uint64"            => "(uint64_t)".into(),
        "bool"              => "(int)".into(),
        "abs"   => "fabs".into(),
        "min"   => "min".into(),
        "max"   => "max".into(),
        "sqrt"  => "sqrt".into(),
        "exp"   => "exp".into(),
        "log"   => "log".into(),
        "log2"  => "log2".into(),
        "log10" => "log10".into(),
        "sin"   => "sin".into(),
        "cos"   => "cos".into(),
        "tan"   => "tan".into(),
        "tanh"  => "tanh".into(),
        "pow"   => "pow".into(),
        "floor" => "floor".into(),
        "ceil"  => "ceil".into(),
        "round" => "round".into(),
        other   => other.into(),
    }
}

// ── Auto-sync helpers ─────────────────────────────────────────────────────────

fn body_has_explicit_sync(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Comment(c) if c == "sync" => true,
        Stmt::While(w)   => body_has_explicit_sync(&w.body),
        Stmt::For(f)     => body_has_explicit_sync(&f.body),
        Stmt::If(i)      => i.branches.iter().any(|(_, b)| body_has_explicit_sync(b))
                         || i.else_body.as_ref().is_some_and(|b| body_has_explicit_sync(b)),
        _ => false,
    })
}

fn body_accesses_sync_field(stmts: &[Stmt], fields: &[KernelFieldDecl]) -> bool {
    let sync_names: Vec<&str> = fields.iter()
        .filter(|f| matches!(f.qual, GpuQual::Actor))
        .map(|f| f.name.as_str())
        .collect();
    if sync_names.is_empty() { return false; }
    stmts_reference_any(stmts, &sync_names)
}

fn stmts_reference_any(stmts: &[Stmt], names: &[&str]) -> bool {
    stmts.iter().any(|s| stmt_references_any(s, names))
}

fn stmt_references_any(stmt: &Stmt, names: &[&str]) -> bool {
    match stmt {
        Stmt::Expr(e) => expr_references_any(e, names),
        Stmt::Return(r) => r.value.as_ref().is_some_and(|v| expr_references_any(v, names)),
        Stmt::Let(s) => s.value.as_ref().is_some_and(|v| expr_references_any(v, names)),
        Stmt::While(w) => stmts_reference_any(&w.body, names),
        Stmt::For(f)   => stmts_reference_any(&f.body, names),
        Stmt::If(i)    => i.branches.iter().any(|(_, b)| stmts_reference_any(b, names))
                       || i.else_body.as_ref().is_some_and(|b| stmts_reference_any(b, names)),
        _ => false,
    }
}

fn expr_references_any(expr: &Expr, names: &[&str]) -> bool {
    match &expr.kind {
        ExprKind::Var(n)           => names.contains(&n.as_str()),
        ExprKind::Index(a, i)      => expr_references_any(a, names) || expr_references_any(i, names),
        ExprKind::Field(e, _)      => expr_references_any(e, names),
        ExprKind::BinOp(_, l, r)   => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::UnaryOp(_, e)    => expr_references_any(e, names),
        ExprKind::Assign(l, r)     => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::Call(f, args)    => expr_references_any(f, names) || args.iter().any(|a| expr_references_any(&a.value, names)),
        _ => false,
    }
}

