// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Rust host-side code emitter for the CUDA backend.

use crate::ast::*;

pub(super) fn emit_host_rs(program: &Program, kernel_names: &[String]) -> String {
    let mut e = HostEmitter::new(kernel_names);
    e.emit_program(program, kernel_names);
    e.out
}

struct HostEmitter {
    out: String,
    indent: usize,
    /// Names of all `kernel` structs — used to translate `Scale(args)` → `Scale::new(...)`.
    kernel_names: std::collections::HashSet<String>,
    /// Kernel struct declarations indexed by name — for field type lookup at readback sites.
    kernel_decls: std::collections::HashMap<String, KernelDecl>,
    /// Tracks which local variables hold a kernel struct instance and which type.
    /// Used to emit `k.read_buf()?` instead of `k.buf` for device-side fields.
    var_kernel_type: std::collections::HashMap<String, String>,
    /// Variables that hold an `Arc<CudaContext>` (from `GPU(n)` or `new(g) ...`).
    /// Used to map `.name()`, `.total_mem()` etc. to cudarc 0.19 methods.
    gpu_vars: std::collections::HashSet<String>,
}

impl HostEmitter {
    fn new(kernel_names: &[String]) -> Self {
        Self {
            out: String::new(),
            indent: 0,
            kernel_names: kernel_names.iter().cloned().collect(),
            kernel_decls: std::collections::HashMap::new(),
            var_kernel_type: std::collections::HashMap::new(),
            gpu_vars: std::collections::HashSet::new(),
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program, kernel_names: &[String]) {
        for item in &program.items {
            if let Item::Kernel(decl) = item {
                self.kernel_decls.insert(decl.name.clone(), decl.clone());
            }
        }
        self.line("// Generated by boring build --target cuda.");
        self.blank();
        self.emit_prelude(kernel_names);

        // Non-kernel, non-stmt items.
        for item in &program.items {
            match item {
                Item::Kernel(decl) => {
                    self.blank();
                    self.emit_kernel_struct(decl);
                }
                Item::Fn(f) => {
                    self.blank();
                    self.emit_fn(f, None);
                }
                Item::Struct(s) => {
                    self.blank();
                    self.emit_struct(s);
                }
                Item::Enum(e) => {
                    self.blank();
                    self.emit_enum(e);
                }
                Item::Stmt(_) | Item::Let(_) => {}  // handled in main()
                _ => {}
            }
        }

        // Collect top-level stmts and lets.
        let has_stmts = program.items.iter().any(|i| matches!(i, Item::Stmt(_) | Item::Let(_)));
        if has_stmts || !kernel_names.is_empty() {
            self.blank();
            self.line("fn main() -> Result<(), Box<dyn std::error::Error>> {");
            self.indent += 1;
            if !kernel_names.is_empty() {
                self.line("boring_gpu_init()?;");
            }
            for item in &program.items {
                match item {
                    Item::Let(s) => {
                        let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                        let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                        if let Some(val) = &s.value {
                            self.track_kernel_var(&s.name, val);
                            let rhs = self.expr(val);
                            self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                        }
                    }
                    Item::Stmt(stmt) => self.emit_stmt(stmt),
                    _ => {}
                }
            }
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }
    }

    // ── GPU prelude ────────────────────────────────────────────────────────────

    fn emit_prelude(&mut self, kernel_names: &[String]) {
        self.line("use cudarc::driver::{CudaContext, CudaModule, CudaFunction, CudaSlice, CudaStream, LaunchConfig};");
        self.line("use cudarc::nvrtc::Ptx;");
        self.line("use std::sync::{Arc, OnceLock};");
        self.blank();
        self.line("static BORING_PTX: &str = include_str!(env!(\"BORING_PTX_PATH\"));");
        self.blank();
        self.line("static BORING_CTX: OnceLock<Arc<CudaContext>> = OnceLock::new();");
        self.line("static BORING_MODULE: OnceLock<Arc<CudaModule>> = OnceLock::new();");
        self.blank();
        self.line("fn boring_gpu_ctx() -> Arc<CudaContext> {");
        self.indent += 1;
        self.line("Arc::clone(BORING_CTX.get().expect(\"boring_gpu_init() not called\"))");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("fn boring_gpu_init() -> Result<(), Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("let ctx = Arc::new(CudaContext::new(0)?);");
        self.line("let ptx = Ptx::from_src(BORING_PTX);");
        self.line("let module = Arc::new(ctx.load_module(ptx)?);");
        self.line("let _ = BORING_CTX.set(ctx);");
        self.line("let _ = BORING_MODULE.set(module);");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // Multi-GPU context accessor: `GPU(n)` → `boring_gpu_ctx_n(n)?`.
        self.line("fn boring_gpu_ctx_n(idx: usize) -> Result<Arc<CudaContext>, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("Ok(Arc::new(CudaContext::new(idx)?))");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // Each handle owns the CUDA stream its kernel was launched on, so `.wait`
        // synchronizes only that stream (not the whole device).  `after = [..]`
        // dependencies are wired GPU-side via stream ordering, no CPU sync.
        self.line("struct KernelHandle<T> { inner: T, stream: Arc<CudaStream> }");
        self.line("impl<T> KernelHandle<T> {");
        self.indent += 1;
        self.line("fn wait(self) -> Result<T, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("self.stream.synchronize()?;");
        self.line("Ok(self.inner)");
        self.indent -= 1;
        self.line("}");
        self.line("fn done(&self) -> bool { true }");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // Boring built-in Dimension type used by 2-D kernels.
        self.line("#[repr(C)]");
        self.line("#[derive(Copy, Clone, Debug)]");
        self.line("struct Dimension { width: u32, height: u32 }");
        self.line("#[allow(non_snake_case)]");
        self.line("fn Dimension(width: u32, height: u32) -> Dimension { Dimension { width, height } }");
        self.blank();
        // Stream priority helper: wraps cuStreamCreateWithPriority.
        // priority 0 = normal, -1 = high, 1 = low (CUDA convention: lower int = higher priority).
        self.line("fn boring_new_stream_with_priority(ctx: &Arc<CudaContext>, priority: i32) -> Result<Arc<CudaStream>, Box<dyn std::error::Error>> {");
        self.indent += 1;
        self.line("if priority == 0 { return Ok(ctx.new_stream()?); }");
        self.line("use cudarc::driver::sys::*;");
        self.line("let mut raw: CUstream = std::ptr::null_mut();");
        self.line("unsafe { cuStreamCreateWithPriority(&mut raw, CU_STREAM_NON_BLOCKING, priority).result()?; }");
        self.line("Ok(unsafe { Arc::new(CudaStream::from_raw(ctx, raw)) })");
        self.indent -= 1;
        self.line("}");
        let _ = kernel_names; // used by caller for PTX loading
    }

    // ── Kernel struct → Rust host wrapper ─────────────────────────────────────

    fn emit_kernel_struct(&mut self, decl: &KernelDecl) {
        let name = &decl.name;

        // Struct fields.
        self.line(&format!("struct {} {{", name));
        self.indent += 1;
        self.line("__ctx: Arc<CudaContext>,");
        self.line("__stream: Arc<CudaStream>,");
        for field in &decl.fields {
            match field.qual {
                GpuQual::Sync | GpuQual::Local => {
                    // Block SRAM / registers — no host-side storage.
                }
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const | GpuQual::Surface => {
                    let ty = self.host_field_type(field);
                    self.line(&format!("{}: {},", field.name, ty));
                }
            }
        }
        // Scalar non-GPU fields (Local without array, Const scalars).
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Local) {
                match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        let ty = rust_type(&field.ty);
                        self.line(&format!("{}: {},", field.name, ty));
                    }
                }
            }
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        // impl block.
        self.line(&format!("impl {} {{", name));
        self.indent += 1;

        // Constructor(s).
        for init in &decl.inits {
            self.emit_kernel_new(name, &decl.fields, init);
            self.blank();
        }
        if decl.inits.is_empty() {
            self.emit_kernel_new_default(name, &decl.fields);
            self.blank();
        }

        // Accessors for 'unified fields (D2H).
        for field in &decl.fields {
            if matches!(field.qual, GpuQual::Unified) {
                let elem = elem_rust_type(&field.ty);
                self.line(&format!(
                    "fn read_{}(&self) -> Result<Vec<{}>, Box<dyn std::error::Error>> {{",
                    field.name, elem
                ));
                self.indent += 1;
                self.line(&format!("Ok(self.__stream.clone_dtoh(&self.{})?)", field.name));
                self.indent -= 1;
                self.line("}");
                self.blank();
            }
        }

        // __boring_launch.
        self.emit_boring_launch(name, &decl.fields);

        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new(&mut self, name: &str, fields: &[KernelFieldDecl], init: &InitDecl) {
        let params: Vec<String> = init.params.iter().map(|p| {
            let ty = p.ty.as_ref()
                .map(|t| host_param_type(t, fields))
                .unwrap_or_else(|| "()".into());
            format!("{}: {}", p.name, ty)
        }).collect();
        let all_params = if params.is_empty() {
            "__ctx: Arc<CudaContext>".into()
        } else {
            format!("__ctx: Arc<CudaContext>, {}", params.join(", "))
        };

        self.line(&format!(
            "fn new({}) -> Result<Self, Box<dyn std::error::Error>> {{",
            all_params
        ));
        self.indent += 1;

        // Emit init body statements, translating field assignments into device allocations.
        for stmt in &init.body {
            self.emit_init_stmt(stmt, fields);
        }

        // Fall back: fields not set in the body get defaults.
        // We track which fields were assigned in the init body (simple heuristic: name match).
        let assigned: std::collections::HashSet<String> = init.body.iter()
            .filter_map(|s| match s {
                Stmt::Expr(e) => {
                    if let ExprKind::Assign(lhs, _) = &e.kind {
                        if let ExprKind::Var(name) = &lhs.kind { Some(name.clone()) }
                        else { None }
                    } else { None }
                }
                _ => None,
            }).collect();

        for field in fields {
            if !assigned.contains(&field.name) {
                match field.qual {
                    GpuQual::Const if matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) => {
                        let elem = elem_rust_type(&field.ty);
                        self.line(&format!("let {}: Vec<{}> = Vec::new();", field.name, elem));
                    }
                    GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const | GpuQual::Surface => {
                        let elem = elem_rust_type(&field.ty);
                        self.line(&format!(
                            "let {} = __ctx.default_stream().alloc_zeros::<{}>(1)?;",
                            field.name, elem
                        ));
                    }
                    GpuQual::Sync | GpuQual::Local => {
                        match &field.ty {
                            Type::Array(_) | Type::ArrayN(_, _) => {}
                            _ => {
                                let ty = rust_type(&field.ty);
                                self.line(&format!("let {}: {} = Default::default();", field.name, ty));
                            }
                        }
                    }
                }
            }
        }

        self.line(&format!("Ok({} {{", name));
        self.indent += 1;
        self.line("__ctx,");
        self.line("__stream: __ctx.default_stream(),");
        for field in fields {
            match field.qual {
                GpuQual::Sync => {} // no host field
                GpuQual::Local => {
                    match &field.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => {}
                        _ => self.line(&format!("{},", field.name)),
                    }
                }
                _ => self.line(&format!("{},", field.name)),
            }
        }
        self.indent -= 1;
        self.line("})");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_kernel_new_default(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        self.line("fn new(__ctx: Arc<CudaContext>) -> Result<Self, Box<dyn std::error::Error>> {");
        self.indent += 1;
        for field in fields {
            match field.qual {
                GpuQual::Const if matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) => {
                    let elem = elem_rust_type(&field.ty);
                    self.line(&format!("let {}: Vec<{}> = Vec::new();", field.name, elem));
                }
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const | GpuQual::Surface => {
                    let elem = elem_rust_type(&field.ty);
                    self.line(&format!(
                        "let {} = __ctx.default_stream().alloc_zeros::<{}>(1)?;",
                        field.name, elem
                    ));
                }
                GpuQual::Sync => {}
                GpuQual::Local => {
                    match &field.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => {}
                        _ => {
                            let ty = rust_type(&field.ty);
                            self.line(&format!("let {}: {} = Default::default();", field.name, ty));
                        }
                    }
                }
            }
        }
        self.line(&format!("Ok({} {{", name));
        self.indent += 1;
        self.line("__ctx,");
        self.line("__stream: __ctx.default_stream(),");
        for field in fields {
            match field.qual {
                GpuQual::Sync => {}
                GpuQual::Local => match &field.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => self.line(&format!("{},", field.name)),
                },
                _ => self.line(&format!("{},", field.name)),
            }
        }
        self.indent -= 1;
        self.line("})");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_init_stmt(&mut self, stmt: &Stmt, fields: &[KernelFieldDecl]) {
        match stmt {
            Stmt::Expr(e) => {
                if let ExprKind::Assign(lhs, rhs) = &e.kind {
                    if let ExprKind::Var(fname) = &lhs.kind {
                        // Is this a GPU-memory field?
                        if let Some(field) = fields.iter().find(|f| &f.name == fname) {
                            match field.qual {
                                GpuQual::Const if matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) => {
                                    // 'const array field: store as Vec<T> on host.
                                    // The data is uploaded to __constant__ memory in __boring_launch.
                                    let elem = elem_rust_type(&field.ty);
                                    match &rhs.kind {
                                        ExprKind::Array(elems) => {
                                            let lit: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                                            self.line(&format!(
                                                "let {}: Vec<{}> = vec![{}];",
                                                fname, elem, lit.join(", ")
                                            ));
                                        }
                                        _ => {
                                            let rhs_s = self.expr(rhs);
                                            self.line(&format!(
                                                "let {}: Vec<{}> = {}.to_vec();",
                                                fname, elem, rhs_s
                                            ));
                                        }
                                    }
                                    return;
                                }
                                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Const | GpuQual::Surface => {
                                    // Check if RHS is an `ArrayFill` / `[..n]` pattern.
                                    match &rhs.kind {
                                        ExprKind::ArrayFill { value: _, count } | ExprKind::ArrayAlloc { count } => {
                                            let n = self.expr(count);
                                            let elem = elem_rust_type(&field.ty);
                                            self.line(&format!(
                                                "let {} = __ctx.default_stream().alloc_zeros::<{}>({} as usize)?;",
                                                fname, elem, n
                                            ));
                                            return;
                                        }
                                        ExprKind::Array(elems) => {
                                            let elem = elem_rust_type(&field.ty);
                                            let lit: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                                            self.line(&format!(
                                                "let {} = __ctx.default_stream().clone_htod::<{}>(&vec![{}])?;",
                                                fname, elem, lit.join(", ")
                                            ));
                                            return;
                                        }
                                        _ => {
                                            // Assume RHS is a Vec<T> param — upload to device.
                                            let rhs_s = self.expr(rhs);
                                            let elem = elem_rust_type(&field.ty);
                                            self.line(&format!(
                                                "let {} = __ctx.default_stream().clone_htod::<{}>(&{})?;",
                                                fname, elem, rhs_s
                                            ));
                                            return;
                                        }
                                    }
                                }
                                _ => {}
                            }
                        }
                    }
                }
                // Generic stmt.
                let s = self.expr(e);
                self.line(&format!("{};", s));
            }
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    self.line(&format!("{} {} = {};", binding, s.name, rhs));
                }
            }
            _ => self.emit_stmt(stmt),
        }
    }

    fn emit_boring_launch(&mut self, name: &str, fields: &[KernelFieldDecl]) {
        // Auto grid sizing: when the first field is a device array ('unified/'global/
        // 'actor'global), `grid_dim` becomes optional and is derived from its length.
        let auto_grid_field: Option<String> = fields.iter().find_map(|f| {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                    match &f.ty {
                        Type::Array(_) | Type::ArrayN(_, _) => Some(f.name.clone()),
                        _ => None,
                    }
                }
                _ => None,
            }
        });

        if let Some(field) = &auto_grid_field {
            self.line(
                "fn __boring_launch(mut self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, after: &[&Arc<CudaStream>], priority: i32) \
                 -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {"
            );
            self.indent += 1;
            self.line("let grid_dim = grid_dim.unwrap_or_else(|| {");
            self.indent += 1;
            self.line(&format!("let n = self.{}.len() as u32;", field));
            self.line("((n + block_dim.0 - 1) / block_dim.0, 1, 1)");
            self.indent -= 1;
            self.line("});");
        } else {
            self.line(
                "fn __boring_launch(mut self, block_dim: (u32,u32,u32), grid_dim: (u32,u32,u32), after: &[&Arc<CudaStream>], priority: i32) \
                 -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {"
            );
            self.indent += 1;
        }
        // Compute smem_bytes from dynamic 'shared fields (extern __shared__ T arr[]).
        // Statically-sized 'shared ArrayN fields embed their size in the kernel declaration
        // and do not contribute to smem_bytes.
        let dyn_shared_terms: Vec<String> = fields.iter()
            .filter(|f| matches!(f.qual, GpuQual::Sync))
            .filter_map(|f| {
                if let Type::Array(inner) = &f.ty {
                    let sz = elem_size_bytes(inner);
                    Some(format!("block_dim.0 as usize * {}", sz))
                } else {
                    None
                }
            })
            .collect();
        let smem_expr = if dyn_shared_terms.is_empty() {
            "0u32".into()
        } else {
            format!("({}) as u32", dyn_shared_terms.join(" + "))
        };
        self.line(&format!("let smem_bytes: u32 = {};", smem_expr));
        self.line("let cfg = LaunchConfig {");
        self.indent += 1;
        self.line("block_dim,");
        self.line("grid_dim,");
        self.line("shared_mem_bytes: smem_bytes,");
        self.indent -= 1;
        self.line("};");
        // cudarc 0.19: get function from the global module, fork a fresh stream,
        // order it after dependency streams GPU-side, then launch with builder pattern.
        self.line(&format!(
            "let func = BORING_MODULE.get().unwrap().load_function(\"{}_kernel\")?;",
            name
        ));
        self.line("let stream = boring_new_stream_with_priority(&self.__ctx, priority)?;");
        self.line("for dep in after { dep.synchronize()?; }");

        // Upload 'const fixed-size arrays to __constant__ memory before launch.
        for f in fields {
            if matches!(f.qual, GpuQual::Const) && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                self.line(&format!(
                    "if !self.{name}.is_empty() {{",
                    name = f.name
                ));
                self.indent += 1;
                let elem = elem_rust_type(&f.ty);
                self.line(&format!(
                    "let mut __sym_{name} = BORING_MODULE.get().unwrap().get_global::<{elem}>(\"{name}\")?;",
                    name = f.name, elem = elem
                ));
                self.line(&format!(
                    "stream.memcpy_htod(&mut __sym_{name}, &self.{name})?;",
                    name = f.name
                ));
                self.indent -= 1;
                self.line("}");
            }
        }

        // Build the launcher — one .arg() call per kernel parameter.
        self.line("let mut launcher = stream.launch_builder(&func);");
        for f in fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                    self.line(&format!("launcher.arg(&mut self.{});", f.name));
                }
                GpuQual::Const => {
                    if !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        // Scalar 'const: passed as a kernel parameter.
                        self.line(&format!("launcher.arg(&self.{});", f.name));
                    }
                    // Array 'const: uploaded to __constant__ memory above, not a parameter.
                }
                GpuQual::Local => {
                    if !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        self.line(&format!("launcher.arg(&self.{});", f.name));
                    }
                }
                GpuQual::Sync => {}
            }
        }
        self.line("unsafe { launcher.launch(cfg) }?;");

        self.line("let stream = Arc::new(stream);");
        self.line("Ok(KernelHandle { inner: self, stream })");
        self.indent -= 1;
        self.line("}");
    }

    // ── Regular items ──────────────────────────────────────────────────────────

    fn emit_fn(&mut self, f: &FnDecl, self_ty: Option<&str>) {
        if f.is_native { return; }
        let vis = if f.is_pub { "pub " } else { "" };
        let params: Vec<String> = f.params.iter().map(|p| {
            let name = if p.mutable { format!("mut {}", p.name) } else { p.name.clone() };
            match &p.ty {
                Some(ty) => format!("{}: {}", name, rust_type(ty)),
                None => name,
            }
        }).collect();
        let all_params = match self_ty {
            Some(_) => {
                let s = if f.mutating { "&mut self" } else { "&self" };
                if params.is_empty() { s.to_string() } else { format!("{}, {}", s, params.join(", ")) }
            }
            None => params.join(", "),
        };
        let ret = f.return_ty.as_ref().map(|t| rust_type(t)).unwrap_or_else(|| "()".into());
        let sig = format!("{}fn {}({}) -> {}", vis, f.name, all_params, ret);
        if f.body.is_empty() {
            self.line(&format!("{} {{}}", sig));
            return;
        }
        self.line(&format!("{} {{", sig));
        self.indent += 1;
        let len = f.body.len();
        for (i, stmt) in f.body.iter().enumerate() {
            if i + 1 == len { self.emit_stmt_last(stmt); } else { self.emit_stmt(stmt); }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_struct(&mut self, s: &StructDecl) {
        if s.is_native { return; }
        let vis = if s.is_pub { "pub " } else { "" };
        self.line(&format!("{}struct {} {{", vis, s.name));
        self.indent += 1;
        for f in &s.fields {
            let fvis = if f.is_pub { "pub " } else { "" };
            self.line(&format!("{}{}: {},", fvis, f.name, rust_type(&f.ty)));
        }
        self.indent -= 1;
        self.line("}");
        if !s.methods.is_empty() {
            self.blank();
            self.line(&format!("impl {} {{", s.name));
            self.indent += 1;
            for m in &s.methods { self.emit_fn(m, Some(&s.name)); self.blank(); }
            self.indent -= 1;
            self.line("}");
        }
    }

    fn emit_enum(&mut self, e: &EnumDecl) {
        if e.is_native { return; }
        let vis = if e.is_pub { "pub " } else { "" };
        self.line(&format!("{}enum {} {{", vis, e.name));
        self.indent += 1;
        for v in &e.variants {
            if v.fields.is_empty() {
                self.line(&format!("{},", v.name));
            } else {
                let fs: Vec<String> = v.fields.iter().map(|f| rust_type(&f.ty)).collect();
                self.line(&format!("{}({}),", v.name, fs.join(", ")));
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ─────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let binding = if s.binding.is_mutable() { "let mut" } else { "let" };
                let ty_ann = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                if let Some(val) = &s.value {
                    // Track kernel struct type for this variable so field accesses
                    // on it can be redirected to read_<field>() D2H calls.
                    self.track_kernel_var(&s.name, val);
                    let rhs = self.expr(val);
                    self.line(&format!("{} {}{} = {};", binding, s.name, ty_ann, rhs));
                } else {
                    self.line(&format!("{} {}{};", binding, s.name, ty_ann));
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    ExprKind::Assign(lhs, rhs) => {
                        let l = self.expr(lhs);
                        let r = self.expr(rhs);
                        self.line(&format!("{} = {};", l, r));
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if {} {{", c)); }
                    else        { self.line(&format!("}} else if {} {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let c = self.expr(&w.condition);
                self.line(&format!("while {} {{", c));
                self.indent += 1;
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let is_enumerate = f.vars.len() >= 2;
                let var = if is_enumerate {
                    format!("({}, {})", f.vars[0], f.vars[1])
                } else {
                    f.vars.first().cloned().unwrap_or_else(|| "_i".into())
                };
                match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let range = if *inclusive { format!("{}..={}", lo, hi) }
                                    else          { format!("{}..{}", lo, hi) };
                        self.line(&format!("for {} in {} {{", var, range));
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        if is_enumerate {
                            self.line(&format!("for {} in {}.iter().enumerate() {{", var, iter));
                        } else {
                            self.line(&format!("for {} in {} {{", var, iter));
                        }
                    }
                }
                self.indent += 1;
                for s in &f.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            Stmt::Comment(_)          => {}
            Stmt::KernelBlock(kb) => self.emit_kernel_block(&kb.body),
            _ => { self.line("/* unsupported stmt */"); }
        }
    }

    fn emit_kernel_block(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            match stmt {
                Stmt::Expr(e) => {
                    // `k(block = N)` inside kernel: — desugar to k.__boring_launch(...)
                    if let Some(launch) = self.try_emit_kernel_launch_call(e) {
                        self.line(&format!("{launch};"));
                    } else {
                        let s = self.expr(e);
                        self.line(&format!("{s};"));
                    }
                }
                Stmt::Loop(l) => {
                    self.line("loop {");
                    self.indent += 1;
                    for s in &l.body { self.emit_stmt(s); }
                    self.indent -= 1;
                    self.line("}");
                }
                other => self.emit_stmt(other),
            }
        }
    }

    /// If `expr` is `k(block = N[, after = [...]])` where `k` is a tracked kernel
    /// variable, return the `__boring_launch(...)` call string. Otherwise `None`.
    fn try_emit_kernel_launch_call(&mut self, expr: &Expr) -> Option<String> {
        let ExprKind::Call(callee, args) = &expr.kind else { return None; };
        let ExprKind::Var(var_name) = &callee.kind else { return None; };
        let has_block = args.iter().any(|a| a.label.as_deref() == Some("block"));
        if !has_block { return None; }
        let is_kernel = self.var_kernel_type.contains_key(var_name.as_str())
            || self.kernel_names.contains(var_name.as_str());
        if !is_kernel { return None; }
        let kernel_type = self.var_kernel_type.get(var_name.as_str()).cloned()
            .or_else(|| Some(var_name.clone()));
        let auto_grid = kernel_type
            .as_ref()
            .and_then(|t| self.kernel_decls.get(t))
            .map(|decl| decl.fields.iter().any(|f|
                matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
                && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))))
            .unwrap_or(false);
        let block = args.iter().find(|a| a.label.as_deref() == Some("block"))
            .map(|a| self.dim3_expr(&a.value))
            .unwrap_or_else(|| "(1, 1, 1)".into());
        let after_arg = match args.iter().find(|a| a.label.as_deref() == Some("after")) {
            None => "&[]".into(),
            Some(a) => match &a.value.kind {
                ExprKind::Array(elems) => {
                    let refs: Vec<String> = elems.iter()
                        .map(|e| format!("&{}.stream", self.expr(e)))
                        .collect();
                    format!("&[{}]", refs.join(", "))
                }
                _ => { let s = self.expr(&a.value); format!("&[&{s}.stream]") }
            },
        };
        let grid: String = if auto_grid { "None".into() } else { "(1, 1, 1)".into() };
        let priority_arg: String = match args.iter().find(|a| a.label.as_deref() == Some("priority")) {
            None => "0i32".into(),
            Some(a) => match &a.value.kind {
                ExprKind::Str(s) => match s.as_str() {
                    "high"   => "-1i32".into(),
                    "low"    =>  "1i32".into(),
                    _        =>  "0i32".into(),
                },
                _ => "0i32".into(),
            },
        };
        // Re-assign so the moved-into-launch value is returned to the variable.
        Some(format!("{var_name} = {var_name}.__boring_launch({block}, {grid}, {after_arg}, {priority_arg})?.wait()"))
    }

    fn emit_stmt_last(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Expr(e) => { let s = self.expr(e); self.line(&s); }
            _ => self.emit_stmt(stmt),
        }
    }

    // ── Expressions ────────────────────────────────────────────────────────────

    /// Convert a Boring dim expression (int literal or tuple) to a Rust `(u32,u32,u32)` literal.
    /// Scalar `N` → `(N as u32, 1, 1)`.  Tuple `(X, Y)` → `(X as u32, Y as u32, 1)`.  Etc.
    fn dim3_expr(&mut self, e: &Expr) -> String {
        if let ExprKind::Tuple(elems) = &e.kind {
            let x = elems.get(0).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let y = elems.get(1).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            let z = elems.get(2).map(|e| format!("{} as u32", self.expr(e))).unwrap_or_else(|| "1".into());
            format!("({x}, {y}, {z})")
        } else {
            let v = self.expr(e);
            format!("({v} as u32, 1, 1)")
        }
    }

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)    => n.to_string(),
            ExprKind::Float(f)  => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)   => if *b { "true".into() } else { "false".into() },
            ExprKind::Str(s)    => format!("\"{}\"", s),
            ExprKind::Nil       => "None".into(),
            ExprKind::Void      => "()".into(),

            ExprKind::Var(name) => name.clone(),

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_rust(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_rust(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                // `k.buf[i]` where buf is a GPU array field → `k.read_buf()?[i as usize]`
                if let ExprKind::Field(obj, field) = &arr.kind {
                    if let ExprKind::Var(obj_name) = &obj.kind {
                        if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                            let i = self.expr(idx);
                            return format!("{}[{} as usize]", read_call, i);
                        }
                    }
                }
                format!("{}[{} as usize]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                // `k.buf` where buf is a GPU array field → `k.read_buf()?`
                if let ExprKind::Var(obj_name) = &obj.kind {
                    if let Some(read_call) = self.try_gpu_field_read(obj_name, field) {
                        return read_call;
                    }
                }
                let o = self.expr(obj);
                // `.length` as a field (Boring style) → Rust `.len() as i64`
                if field == "length" || field == "count" {
                    return format!("{}.len() as i64", o);
                }
                format!("{}.{}", o, field)
            }
            ExprKind::Call(callee, args) => {
                // `GPU(n)` → `boring_gpu_ctx_n(n)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "GPU" {
                        let idx = args.first().map(|a| self.expr(&a.value)).unwrap_or_else(|| "0".into());
                        return format!("boring_gpu_ctx_n({} as usize)?", idx);
                    }
                }
                // `ord(c)` — char → i64 (Boring built-in)
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "ord" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as i64)", inner);
                        }
                    }
                }
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                // `Scale(data)` → `Scale::new(boring_gpu_ctx(), data)?`
                if let ExprKind::Var(name) = &callee.kind {
                    if self.kernel_names.contains(name.as_str()) {
                        let all = std::iter::once("boring_gpu_ctx()".to_string())
                            .chain(args_s)
                            .collect::<Vec<_>>();
                        return format!("{}::new({})?", name, all.join(", "));
                    }
                }
                // `print(expr)` → `println!(...)`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "print" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            if inner.starts_with("format!(") {
                                let inner_args = &inner["format!(".len()..inner.len()-1];
                                return format!("println!({})", inner_args);
                            }
                            return format!("println!(\"{{}}\", {})", inner);
                        }
                        return "println!()".into();
                    }
                }
                // `float(expr)` → `expr as f64`
                if let ExprKind::Var(name) = &callee.kind {
                    if name == "float" {
                        if let Some(arg) = args.first() {
                            let inner = self.expr(&arg.value);
                            return format!("({} as f64)", inner);
                        }
                    }
                }
                let fn_s = self.expr(callee);
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                // `GPU.all()` → iterator over all CUDA devices.
                if let ExprKind::Var(name) = &obj.kind {
                    if name == "GPU" && method == "all" {
                        return "(0..CudaContext::device_count()? as usize).map(|i| boring_gpu_ctx_n(i).unwrap())".into();
                    }
                    // GPU property methods on a GPU variable.
                    if self.gpu_vars.contains(name.as_str()) {
                        return self.emit_gpu_property(name, method);
                    }
                    // `fs.writeBytes(path, bytes)` — write Vec<i64> as binary file
                    if name == "fs" && method == "writeBytes" {
                        let path  = args.get(0).map(|a| self.expr(&a.value)).unwrap_or_default();
                        let bytes = args.get(1).map(|a| self.expr(&a.value)).unwrap_or_default();
                        return format!("std::fs::write({}, {}.iter().map(|&b| b as u8).collect::<Vec<u8>>())?", path, bytes);
                    }
                    if name == "fs" && (method == "write" || method == "writeText") {
                        let path = args.get(0).map(|a| self.expr(&a.value)).unwrap_or_default();
                        let text = args.get(1).map(|a| self.expr(&a.value)).unwrap_or_default();
                        return format!("std::fs::write({}, {}.as_bytes())?", path, text);
                    }
                }
                let o = self.expr(obj);
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                match method.as_str() {
                    "wait" => format!("{}.wait()?", o),
                    "done" => format!("{}.done()", o),
                    // `.chars()` — collect to Vec<char> so indexing and .len() work
                    "chars" if args.is_empty() => format!("{}.chars().collect::<Vec<char>>()", o),
                    // `.length` / `.count` — map to .len() as i64
                    "length" | "count" if args.is_empty() => format!("{}.len() as i64", o),
                    // `.add(x)` / `.insert(x)` — Vec push
                    "add" | "insert" if args.len() == 1 => format!("{}.push({})", o, args_s[0]),
                    _ => format!("{}.{}({})", o, method, args_s.join(", ")),
                }
            }
            ExprKind::Pipe(lhs, method, args) => {
                let l = self.expr(lhs);
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                match method.as_str() {
                    "wait" => format!("{}.wait()?", l),
                    "done" => format!("{}.done()", l),
                    _ => format!("{}.{}({})", l, method, args_s.join(", ")),
                }
            }
            ExprKind::KernelLaunch { config, kernel } => {
                // Does the target kernel use automatic grid sizing?
                let auto_grid = self.resolve_kernel_type(kernel)
                    .and_then(|t| self.kernel_decls.get(&t))
                    .map(|decl| decl.fields.iter().any(|f|
                        matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
                        && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))))
                    .unwrap_or(false);
                let k = self.expr(kernel);
                let block = config.block.as_ref()
                    .map(|e| self.dim3_expr(e))
                    .unwrap_or_else(|| "(1, 1, 1)".into());
                let grid = if auto_grid {
                    match &config.grid {
                        None => "None".into(),
                        Some(e) => format!("Some({})", self.dim3_expr(e)),
                    }
                } else {
                    config.grid.as_ref()
                        .map(|e| self.dim3_expr(e))
                        .unwrap_or_else(|| "(1, 1, 1)".into())
                };
                // `after = [h1, h2]` — collect stream references from dependency handles.
                // Each handle's `.stream` field is passed as a dependency to __boring_launch.
                let after_arg = match &config.after {
                    None => "&[]".into(),
                    Some(after_expr) => {
                        // Emit a slice literal of stream references from the dependency handles.
                        match &after_expr.kind {
                            ExprKind::Array(elems) => {
                                let refs: Vec<String> = elems.iter()
                                    .map(|e| format!("&{}.stream", self.expr(e)))
                                    .collect();
                                format!("&[{}]", refs.join(", "))
                            }
                            _ => {
                                let s = self.expr(after_expr);
                                format!("&[&{}.stream]", s)
                            }
                        }
                    }
                };
                format!("{k}.__boring_launch({block}, {grid}, {after_arg})?")
            }
            ExprKind::New { arena, ctor } => {
                // `new(g) Scale(data)` → `Scale::new(<g>, data)?` (explicit device placement).
                if let ExprKind::Call(callee, args) = &ctor.kind {
                    if let ExprKind::Var(name) = &callee.kind {
                        if self.kernel_names.contains(name.as_str()) {
                            let dev = arena.as_ref()
                                .map(|a| self.expr(a))
                                .unwrap_or_else(|| "boring_gpu_ctx()".into());
                            let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                            let all = std::iter::once(dev).chain(args_s).collect::<Vec<_>>();
                            return format!("{}::new({})?", name, all.join(", "));
                        }
                    }
                }
                // Non-kernel new: ignore arena, emit the constructor directly.
                self.expr(ctor)
            }
            ExprKind::Array(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("vec![{}]", s.join(", "))
            }
            ExprKind::ArrayFill { value, count } => {
                let v = self.expr(value);
                let n = self.expr(count);
                format!("vec![{}; {} as usize]", v, n)
            }
            ExprKind::ArrayAlloc { count } => {
                let n = self.expr(count);
                format!("vec![Default::default(); {} as usize]", n)
            }
            ExprKind::ArrayComp { expr, var, count } => {
                let n = self.expr(count);
                let body = self.expr(expr);
                format!(
                    "(0..({} as usize)).map(|__boring_i| {{ let {} = __boring_i as i64; {} }}).collect::<Vec<_>>()",
                    n, var, body
                )
            }
            ExprKind::ArrayCompIter { expr, var, iter } => {
                let it = self.expr(iter);
                let body = self.expr(expr);
                format!("{}.iter().map(|{}| {{ {} }}).collect::<Vec<_>>()", it, var, body)
            }
            ExprKind::Tuple(elems) => {
                let s: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("({})", s.join(", "))
            }
            ExprKind::Dict(pairs) => {
                let s: Vec<String> = pairs.iter().map(|(k, v)| {
                    format!("({}, {})", self.expr(k), self.expr(v))
                }).collect();
                format!("[{}].into_iter().collect::<std::collections::HashMap<_,_>>()", s.join(", "))
            }
            ExprKind::Range { start, end, inclusive } => {
                let lo = self.expr(start);
                let hi = self.expr(end);
                if *inclusive { format!("({}..={})", lo, hi) } else { format!("({}..{})", lo, hi) }
            }
            ExprKind::Cast(inner, ty) => {
                format!("({} as {})", self.expr(inner), rust_type(ty))
            }
            ExprKind::Else(val, default) => {
                format!("{}.unwrap_or({})", self.expr(val), self.expr(default))
            }
            ExprKind::If(i) => {
                let mut out = String::new();
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    let t = body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    if idx == 0 { out.push_str(&format!("if {} {{ {} }}", c, t)); }
                    else        { out.push_str(&format!(" else if {} {{ {} }}", c, t)); }
                }
                if let Some(else_body) = &i.else_body {
                    let e = else_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "()".into());
                    out.push_str(&format!(" else {{ {} }}", e));
                }
                out
            }
            ExprKind::StringInterp(segs) => {
                let mut parts = Vec::new();
                let mut fmt_str = String::from("\"");
                let mut args = Vec::new();
                for seg in segs {
                    match seg {
                        StringSegment::Lit(s) => fmt_str.push_str(s),
                        StringSegment::Expr(e) => {
                            fmt_str.push_str("{}");
                            args.push(self.expr(e));
                        }
                        StringSegment::FormattedExpr(e, fmt) => {
                            let rust_fmt = fmt.trim_end_matches(|c| matches!(c, 'f' | 'd' | 's' | 'g' | 'G'));
                            fmt_str.push_str(&format!("{{:{}}}", rust_fmt));
                            args.push(self.expr(e));
                        }
                    }
                }
                fmt_str.push('"');
                parts.push(fmt_str);
                parts.extend(args);
                format!("format!({})", parts.join(", "))
            }
            _ => "/* expr */".into(),
        }
    }

    /// Record that variable `name` holds a kernel struct instance.
    ///
    /// Handles three patterns:
    /// - `Scale(args)` call  → var is type `Scale`
    /// - `kernel(...) k`     → var has same type as `k`
    /// - `... |> .wait`      → var has same type as the kernel being waited on
    fn track_kernel_var(&mut self, name: &str, val: &Expr) {
        let ty = self.resolve_kernel_type(val);
        if let Some(t) = ty {
            self.var_kernel_type.insert(name.to_string(), t);
        }
        // Track GPU device variables: `GPU(n)` or `boring_gpu_ctx_n(...)`.
        if self.is_gpu_expr(val) {
            self.gpu_vars.insert(name.to_string());
        }
    }

    fn is_gpu_expr(&self, expr: &Expr) -> bool {
        match &expr.kind {
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind { n == "GPU" }
                else { false }
            }
            ExprKind::Var(n) => self.gpu_vars.contains(n.as_str()),
            _ => false,
        }
    }

    /// Map a GPU variable method call to cudarc 0.19 API.
    fn emit_gpu_property(&self, var: &str, method: &str) -> String {
        match method {
            "name"                => format!("{var}.name()?"),
            "totalMem"            => format!("{var}.total_mem()?"),
            "freeMem"             => format!("{var}.mem_get_info()?.0"),
            "computeCapability"   => format!("{var}.compute_capability()?"),
            "warpSize"            => format!("{var}.attribute(cudarc::driver::sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_WARP_SIZE)?"),
            "maxThreads"          => format!("{var}.attribute(cudarc::driver::sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK)?"),
            "maxSharedMem"        => format!("{var}.attribute(cudarc::driver::sys::CUdevice_attribute::CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK)?"),
            "index"               => format!("{var}.ordinal()"),
            other                 => format!("{var}.{other}()"),
        }
    }

    fn resolve_kernel_type(&self, expr: &Expr) -> Option<String> {
        match &expr.kind {
            // `Scale(args)` — direct constructor
            ExprKind::Call(callee, _) => {
                if let ExprKind::Var(n) = &callee.kind {
                    if self.kernel_names.contains(n.as_str()) { return Some(n.clone()); }
                }
                None
            }
            // `kernel(...) k` — launch; same type as the kernel variable
            ExprKind::KernelLaunch { kernel, .. } => self.resolve_kernel_type(kernel),
            // `new(g) Scale(args)` — placement; same type as the constructor
            ExprKind::New { ctor, .. } => self.resolve_kernel_type(ctor),
            // `expr |> .wait` — unwrap handle; same type as the launch
            ExprKind::Pipe(lhs, method, _) if method == "wait" => self.resolve_kernel_type(lhs),
            // bare variable — look up in tracked map
            ExprKind::Var(n) => self.var_kernel_type.get(n.as_str()).cloned(),
            _ => None,
        }
    }

    /// Check whether `obj.field` should be rewritten to a D2H read call.
    ///
    /// Returns `Some("obj.read_field()?")` when `obj` is a tracked kernel
    /// variable and `field` is a `'unified` or `'global` array field.
    /// Returns `None` for scalars or non-GPU fields (direct field access is fine).
    fn try_gpu_field_read(&self, obj: &str, field: &str) -> Option<String> {
        let kernel_type = self.var_kernel_type.get(obj)?;
        let decl = self.kernel_decls.get(kernel_type)?;
        let kf = decl.fields.iter().find(|f| f.name == field)?;
        match kf.qual {
            GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
                match &kf.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {
                        Some(format!("{}.read_{}()?", obj, field))
                    }
                    _ => None, // scalar — direct access
                }
            }
            _ => None,
        }
    }

    fn host_field_type(&self, field: &KernelFieldDecl) -> String {
        let elem = elem_rust_type(&field.ty);
        // 'const fixed-size arrays are stored as Vec<T> on the host — they are
        // uploaded to __constant__ memory via memcpy_htod, not as CudaSlice args.
        if matches!(field.qual, GpuQual::Const) && matches!(field.ty, Type::Array(_) | Type::ArrayN(_, _)) {
            return format!("Vec<{}>", elem);
        }
        format!("CudaSlice<{}>", elem)
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

fn host_param_type(ty: &Type, _fields: &[KernelFieldDecl]) -> String {
    match ty {
        Type::Qualified(inner, OwnerQual::GpuUnified)
        | Type::Qualified(inner, OwnerQual::GpuGlobal) => {
            format!("Vec<{}>", elem_rust_type(inner))
        }
        Type::Array(inner) => format!("Vec<{}>", rust_type(inner)),
        _ => rust_type(ty),
    }
}

fn elem_rust_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)     => rust_type(inner),
        Type::ArrayN(inner, _) => rust_type(inner),
        Type::Qualified(inner, _) => elem_rust_type(inner),
        _                      => rust_type(ty),
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Int            => "i64".into(),
        Type::Uint           => "u64".into(),
        Type::Float          => "f64".into(),
        Type::Bool           => "bool".into(),
        Type::Str            => "String".into(),
        Type::Nil            => "()".into(),
        Type::Void           => "()".into(),
        Type::Never          => "!".into(),
        Type::Array(inner)   => format!("Vec<{}>", rust_type(inner)),
        Type::ArrayN(inner, n) => format!("[{}; {}]", rust_type(inner), n),
        Type::Tuple(ts) => {
            let s: Vec<String> = ts.iter().map(|t| rust_type(t)).collect();
            format!("({})", s.join(", "))
        }
        Type::Dict(k, v) => format!(
            "std::collections::HashMap<{}, {}>", rust_type(k), rust_type(v)
        ),
        Type::Optional(inner)  => format!("Option<{}>", rust_type(inner)),
        // Named primitives — the kernel field parser stores raw keyword strings.
        Type::Named(n) => match n.as_str() {
            "float" | "f64" => "f64",
            "f32"           => "f32",
            "int"   | "i64" => "i64",
            "uint"  | "u64" => "u64",
            "bool"          => "bool",
            "string"        => "String",
            other           => return other.to_string(),
        }.into(),
        Type::TypeParam(p)     => p.clone(),
        Type::Qualified(inner, _) => rust_type(inner),
        Type::Generic(n, args) => {
            let s: Vec<String> = args.iter().map(|a| rust_type(a)).collect();
            format!("{}<{}>", n, s.join(", "))
        }
        _ => "()".into(),
    }
}

/// Returns the size in bytes of a scalar element type for shared-memory calculations.
fn elem_size_bytes(ty: &Type) -> usize {
    match ty {
        Type::Float                          => 8, // f64 / double
        Type::Int | Type::Uint               => 8, // i64 / u64
        Type::Bool                           => 1,
        Type::Named(n) => match n.as_str() {
            "float" | "f64"         => 8,
            "f32"                   => 4,
            "int"   | "i64"         => 8,
            "uint"  | "u64"         => 8,
            "i32"                   => 4,
            "u32"                   => 4,
            _                       => 8, // conservative default
        },
        Type::Qualified(inner, _)            => elem_size_bytes(inner),
        Type::Array(inner) | Type::ArrayN(inner, _) => elem_size_bytes(inner),
        _                                    => 8,
    }
}

fn binop_rust(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",   BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",   BinOp::Rem => "%",
        BinOp::Eq  => "==",  BinOp::NotEq => "!=",  BinOp::RefEq => "==",
        BinOp::Lt  => "<",   BinOp::Gt => ">",
        BinOp::LtEq => "<=", BinOp::GtEq => ">=",
        BinOp::And => "&&",  BinOp::Or => "||",
        BinOp::BitAnd => "&", BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<",  BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_rust(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "!",
    }
}
