// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Boring → CUDA transpiler.
//
// Entry point: `transpile_cuda(program)` returns a `CudaOutput` containing:
//   - `host_rs`   — Rust source for the host binary (uses `cudarc` crate)
//   - `device_cu` — CUDA C source for the device kernels
//   - `kernel_names` — list of kernel struct names (used to populate the Cargo project)
//
// Usage:
//   boring build --target cuda main.br
//   → creates main_cuda/
//         src/main.rs         (host_rs)
//         kernels/main.cu     (device_cu)
//         build.rs
//         Cargo.toml

use crate::ast::{Program, Item};

mod device;
mod host;

// ─── Public output type ───────────────────────────────────────────────────────

pub struct CudaOutput {
    /// Rust host source (src/main.rs).
    pub host_rs: String,
    /// CUDA C device source (kernels/main.cu).
    pub device_cu: String,
    /// Names of all `kernel` struct declarations found in the program.
    pub kernel_names: Vec<String>,
    /// Generated build.rs content.
    pub build_rs: String,
    /// Generated Cargo.toml content.
    pub cargo_toml: String,
}

// ─── Public entry point ───────────────────────────────────────────────────────

pub fn transpile_cuda(program: &Program, stem: &str, version: &str) -> CudaOutput {
    // Collect all kernel names.
    let kernel_names: Vec<String> = program.items.iter().filter_map(|item| {
        if let Item::Kernel(decl) = item { Some(decl.name.clone()) } else { None }
    }).collect();

    let device_cu = device::emit_device_cu(program);
    let host_rs   = host::emit_host_rs(program, &kernel_names);
    let build_rs  = emit_build_rs();
    let cargo_toml = emit_cargo_toml(stem, version);

    CudaOutput { host_rs, device_cu, kernel_names, build_rs, cargo_toml }
}

// ─── build.rs generation ─────────────────────────────────────────────────────

fn emit_build_rs() -> String {
    r#"// Generated by boring build --target cuda.
// Compiles kernels/main.cu to PTX via nvcc, then makes the path available
// to main.rs through the BORING_PTX_PATH env var at compile time.

use std::process::Command;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=kernels/main.cu");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let ptx_path = PathBuf::from(&out_dir).join("main.ptx");

    let status = Command::new("nvcc")
        .args([
            "--ptx",
            "-O2",
            "--output-file", ptx_path.to_str().unwrap(),
            "kernels/main.cu",
        ])
        .status()
        .expect("nvcc not found — install the CUDA toolkit (https://developer.nvidia.com/cuda-downloads)");

    if !status.success() {
        panic!("nvcc failed to compile kernels/main.cu");
    }

    println!("cargo:rustc-env=BORING_PTX_PATH={}", ptx_path.display());
}
"#.into()
}

// ─── Cargo.toml generation ────────────────────────────────────────────────────

fn emit_cargo_toml(stem: &str, version: &str) -> String {
    format!(
        r#"[package]
name = "{stem}"
version = "{version}"
edition = "2024"

[[bin]]
name = "{stem}"
path = "src/main.rs"

[dependencies]
cudarc = {{ version = "0.19", features = ["driver", "nvrtc"] }}
"#,
        stem = stem,
        version = version,
    )
}
