// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// WGSL device code emitter for the wgpu backend.

use crate::ast::*;

pub(super) fn emit_device_wgsl(program: &Program, effective_kernels: &[crate::ast::KernelDecl]) -> String {
    let mut e = DeviceEmitter::new();
    e.emit_program(program, effective_kernels);
    e.out
}

struct DeviceEmitter {
    out: String,
    indent: usize,
    current_fields: Vec<KernelFieldDecl>,
    current_kernel: String,
    auto_sync: bool,
    top_level_scalars: std::collections::HashMap<String, String>,
    /// Block sizes per kernel, extracted from call sites: kernel_name → (bx, by, bz).
    block_sizes: std::collections::HashMap<String, (u32, u32, u32)>,
    /// Errors accumulated during emission (e.g. unsupported qualifiers).
    pub errors: Vec<String>,
}

impl DeviceEmitter {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            current_fields: vec![],
            current_kernel: String::new(),
            auto_sync: false,
            top_level_scalars: std::collections::HashMap::new(),
            block_sizes: std::collections::HashMap::new(),
            errors: vec![],
        }
    }

    fn line(&mut self, s: &str) {
        let ind = "    ".repeat(self.indent);
        self.out.push_str(&ind);
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn blank(&mut self) { self.out.push('\n'); }

    fn emit_program(&mut self, program: &Program, effective_kernels: &[crate::ast::KernelDecl]) {
        // Pre-pass: collect top-level scalar lets for inlining.
        for item in &program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    let is_scalar = matches!(val.kind,
                        ExprKind::Int(_) | ExprKind::Float(_) | ExprKind::Bool(_)
                    ) || s.ty.as_ref().map(|t| matches!(t,
                        Type::Int | Type::Uint | Type::Float | Type::Bool
                    )).unwrap_or(false);
                    if is_scalar {
                        let rhs = self.expr(val);
                        self.top_level_scalars.insert(s.name.clone(), rhs);
                    }
                }
            }
        }

        self.line("// Generated by boring build --target wgpu.");
        self.blank();

        // Emit user-defined structs used in kernel fields.
        self.emit_user_structs(program);

        // Built-in Dimension type (i32 fields for easy arithmetic with thread indices).
        self.line("struct Dimension {");
        self.indent += 1;
        self.line("width: i32,");
        self.line("height: i32,");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Pre-pass: extract block sizes from kernel call sites.
        self.block_sizes = collect_block_sizes(program);

        // Emit free functions as WGSL helpers callable from any kernel.
        for item in &program.items {
            if let Item::Fn(decl) = item {
                if decl.qualifier.is_none() && !decl.task {
                    self.emit_free_device_fn(decl);
                    self.blank();
                }
            }
        }

        for decl in effective_kernels {
            self.emit_kernel_decl(decl);
        }
    }

    fn emit_free_device_fn(&mut self, decl: &crate::ast::FnDecl) {
        let ret = decl.return_ty.as_ref().map(|t| wgsl_type(t)).unwrap_or_else(|| "void".into());
        let params: Vec<String> = decl.params.iter().map(|p| {
            let ty = p.ty.as_ref().map(|t| wgsl_type(t)).unwrap_or_else(|| "i32".into());
            format!("{}: {}", p.name, ty)
        }).collect();
        self.line(&format!("fn {}({}) -> {} {{", decl.name, params.join(", "), ret));
        self.indent += 1;
        for stmt in &decl.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    /// Emit WGSL struct declarations for Boring structs referenced in kernel fields.
    fn emit_user_structs(&mut self, program: &Program) {
        // Collect struct names used in kernel fields.
        let mut used: std::collections::HashSet<String> = std::collections::HashSet::new();
        for item in &program.items {
            if let Item::Kernel(decl) = item {
                for f in &decl.fields {
                    if let Some(n) = inner_named_type(&f.ty) {
                        used.insert(n.to_string());
                    }
                }
            }
        }
        for item in &program.items {
            if let Item::Struct(s) = item {
                if used.contains(&s.name) {
                    self.line(&format!("struct {} {{", s.name));
                    self.indent += 1;
                    for f in &s.fields {
                        self.line(&format!("{}: {},", f.name, wgsl_type(&f.ty)));
                    }
                    self.indent -= 1;
                    self.line("}");
                    self.blank();
                }
            }
        }
    }

    fn emit_kernel_decl(&mut self, decl: &KernelDecl) {
        self.current_fields = decl.fields.clone();
        self.current_kernel = decl.name.clone();

        // Validate: reject dynamic 'sync fields ([T]'sync without size).
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Sync) {
                if matches!(f.ty, Type::Array(_)) {
                    self.errors.push(format!(
                        "kernel {}: dynamic '[T]'sync field '{}' is not supported on --target wgpu — \
                         WGSL requires a compile-time workgroup size; use '[T, N]'sync' instead",
                        decl.name, f.name
                    ));
                }
            }
        }

        self.line(&format!("// ─── kernel {} ───", decl.name));
        self.blank();

        // Collect all fields that need bindings: unified, global, actor, surface, const.
        // Scalar local/const fields go into a params uniform struct.
        let has_params = decl.fields.iter().any(|f| is_params_field(f));
        let mut binding: u32 = 0;

        // 1. Array buffer fields.
        for f in &decl.fields {
            if is_buffer_field(f) {
                let (access, ty) = wgsl_buffer_type(f);
                self.line(&format!("@group(0) @binding({}) var<storage, {}> {}: {};",
                    binding, access, f.name, ty));
                binding += 1;
            }
        }

        // 2. Uniform params struct (scalars + fixed arrays + Dimension fields).
        if has_params {
            self.emit_params_struct(decl, binding);
            binding += 1;
        }
        let _ = binding;

        // 3. Workgroup ('sync fixed arrays) — declared inside fn body.

        self.blank();

        self.blank();

        // Device helper functions (named def methods).
        for method in &decl.methods {
            if !method.name.is_empty() {
                self.emit_device_fn(&decl.name, method);
                self.blank();
            }
        }

        // Entry point: `def ()`.
        if let Some(entry) = decl.methods.iter().find(|m| m.name.is_empty()) {
            self.emit_entry_point(decl, entry);
            self.blank();
        }
    }

    fn emit_params_struct(&mut self, decl: &KernelDecl, binding: u32) {
        let struct_name = format!("{}Params", decl.name);
        self.line(&format!("struct {} {{", struct_name));
        self.indent += 1;
        for f in &decl.fields {
            if is_params_field(f) {
                match &f.ty {
                    Type::Named(n) if n == "Dimension" => {
                        self.line(&format!("{}_w: i32,", f.name));
                        self.line(&format!("{}_h: i32,", f.name));
                    }
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("{}: array<{}, {}>,", f.name, wgsl_scalar(inner), n));
                    }
                    _ => {
                        self.line(&format!("{}: {},", f.name, wgsl_scalar(&f.ty)));
                    }
                }
            }
        }
        self.indent -= 1;
        self.line("}");
        let var_name = format!("{}_params", decl.name.to_lowercase());
        self.line(&format!(
            "@group(0) @binding({}) var<uniform> {}: {};",
            binding, var_name, struct_name
        ));
        self.blank();
    }

    fn emit_device_fn(&mut self, kernel: &str, method: &FnDecl) {
        let ret = method.return_ty.as_ref()
            .map(|t| wgsl_type(t))
            .unwrap_or_else(|| "void".into());
        let fn_name = format!("{}_{}", kernel, method.name);
        let params: Vec<String> = method.params.iter().map(|p| {
            let ty = p.ty.as_ref().map(|t| wgsl_type(t)).unwrap_or_else(|| "i32".into());
            format!("{}: {}", p.name, ty)
        }).collect();
        if ret == "void" {
            self.line(&format!("fn {}({}) {{", fn_name, params.join(", ")));
        } else {
            self.line(&format!("fn {}({}) -> {} {{", fn_name, params.join(", "), ret));
        }
        self.indent += 1;
        for stmt in &method.body { self.emit_stmt(stmt); }
        self.indent -= 1;
        self.line("}");
    }

    fn emit_entry_point(&mut self, decl: &KernelDecl, entry: &FnDecl) {
        let fn_name = format!("{}_main", decl.name);

        let (bx, by, bz) = self.block_sizes.get(&decl.name)
            .or_else(|| self.block_sizes.get(&decl.name.to_lowercase()))
            .copied().unwrap_or((1, 1, 1));
        self.line(&format!("@compute @workgroup_size({bx}, {by}, {bz})"));
        self.line(&format!("fn {}(", fn_name));
        self.indent += 1;
        self.line("@builtin(local_invocation_id) bp_tid:  vec3<u32>,");
        self.line("@builtin(workgroup_id)         bp_bid:  vec3<u32>,");
        self.line("@builtin(num_workgroups)       bp_gdim: vec3<u32>,");
        self.indent -= 1;
        self.line(") {");
        self.indent += 1;
        self.line(&format!("let bp_bdim = vec3<u32>({bx}u, {by}u, {bz}u);"));

        // Declare fixed 'sync arrays as workgroup vars.
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Sync) {
                if let Type::ArrayN(inner, n) = &f.ty {
                    self.line(&format!("var<workgroup> {}: array<{}, {}>;",
                        f.name, wgsl_scalar(inner), n));
                }
            }
        }

        // Unpack 'const scalars and Dimension fields from params struct.
        let has_params = decl.fields.iter().any(|f| is_params_field(f));
        if has_params {
            let pvar = format!("{}_params", decl.name.to_lowercase());
            for f in &decl.fields {
                if is_params_field(f) {
                    match &f.ty {
                        Type::Named(n) if n == "Dimension" => {
                            self.line(&format!("let {}: Dimension = Dimension({pvar}.{}_w, {pvar}.{}_h);",
                                f.name, f.name, f.name));
                        }
                        Type::ArrayN(_, _) => {
                            // Fixed arrays are accessed as {pvar}.field[i] directly.
                        }
                        _ => {
                            self.line(&format!("let {}: {} = {pvar}.{};",
                                f.name, wgsl_scalar(&f.ty), f.name));
                        }
                    }
                }
            }
        }

        // Declare 'local scalar fields as function vars.
        // Skip scalars already unpacked from the params uniform (is_params_field covers those).
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Local) && !is_params_field(f) {
                match &f.ty {
                    Type::Array(_) | Type::ArrayN(_, _) => {}
                    _ => {
                        self.line(&format!("var {}: {} = {};",
                            f.name, wgsl_scalar(&f.ty), wgsl_zero(&f.ty)));
                    }
                }
            }
        }

        let has_sync_fields = decl.fields.iter().any(|f| matches!(f.qual, GpuQual::Sync));
        self.auto_sync = has_sync_fields && !body_has_explicit_sync(&entry.body);

        if self.auto_sync {
            let split = first_loop_index(&entry.body);
            for stmt in &entry.body[..split] { self.emit_stmt(stmt); }
            if split < entry.body.len() {
                self.line("workgroupBarrier();");
            }
            for stmt in &entry.body[split..] { self.emit_stmt(stmt); }
        } else {
            for stmt in &entry.body { self.emit_stmt(stmt); }
        }

        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let(s) => {
                let mutable = matches!(s.binding, BindingKind::Mut | BindingKind::Var | BindingKind::Lazy);
                let kw = if mutable { "var" } else { "let" };
                if let Some(val) = &s.value {
                    let rhs = self.expr(val);
                    if let Some(ty) = &s.ty {
                        self.line(&format!("{} {}: {} = {};", kw, s.name, wgsl_type(ty), rhs));
                    } else {
                        self.line(&format!("{} {} = {};", kw, s.name, rhs));
                    }
                }
            }
            Stmt::Expr(e) => {
                match &e.kind {
                    // `print` → silent no-op (no device-side print in WGSL).
                    ExprKind::Call(callee, _)
                        if matches!(&callee.kind, ExprKind::Var(n) if n == "print") => {}
                    ExprKind::Assign(lhs, rhs) => {
                        if let Some(line) = self.try_atomic_assign(lhs, rhs) {
                            self.line(&line);
                        } else {
                            let l = self.expr(lhs);
                            let r = self.expr(rhs);
                            self.line(&format!("{} = {};", l, r));
                        }
                    }
                    _ => {
                        let s = self.expr(e);
                        self.line(&format!("{};", s));
                    }
                }
            }
            Stmt::Return(r) => {
                if let Some(val) = &r.value {
                    let s = self.expr(val);
                    self.line(&format!("return {};", s));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(i) => {
                for (idx, (cond, body)) in i.branches.iter().enumerate() {
                    let c = self.expr(cond);
                    if idx == 0 { self.line(&format!("if ({}) {{", c)); }
                    else        { self.line(&format!("}} else if ({}) {{", c)); }
                    self.indent += 1;
                    for s in body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                if let Some(else_body) = &i.else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_body { self.emit_stmt(s); }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While(w) => {
                let cond = self.expr(&w.condition);
                self.line(&format!("loop {{"));
                self.indent += 1;
                self.line(&format!("if !({})", cond));
                self.indent += 1;
                self.line("{ break; }");
                self.indent -= 1;
                if self.auto_sync && body_accesses_sync_field(&w.body, &self.current_fields) {
                    self.line("workgroupBarrier();");
                }
                for s in &w.body { self.emit_stmt(s); }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::For(f) => {
                let var = f.vars.first().cloned().unwrap_or_else(|| "_i".into());
                // Check for negated range: UnaryOp(Neg, Range{...}) — e.g. `for dy in -1..2`
                let neg_range = if let ExprKind::UnaryOp(UnaryOp::Neg, ref inner) = f.iterable.kind {
                    if let ExprKind::Range { start, end, inclusive } = &inner.kind {
                        Some((format!("-{}", self.expr(start)), self.expr(end), *inclusive))
                    } else { None }
                } else { None };
                if let Some((lo, hi, inclusive)) = neg_range {
                    let op = if inclusive { "<=" } else { "<" };
                    self.line(&format!("var {var}: i32 = {lo};"));
                    self.line(&format!("loop {{"));
                    self.indent += 1;
                    self.line(&format!("if !({var} {op} {hi}) {{ break; }}"));
                    if self.auto_sync && body_accesses_sync_field(&f.body, &self.current_fields) {
                        self.line("workgroupBarrier();");
                    }
                    for s in &f.body { self.emit_stmt(s); }
                    self.line(&format!("{var} = {var} + 1;"));
                    self.indent -= 1;
                    self.line("}");
                } else { match &f.iterable.kind {
                    ExprKind::Range { start, end, inclusive } => {
                        let lo = self.expr(start);
                        let hi = self.expr(end);
                        let op = if *inclusive { "<=" } else { "<" };
                        self.line(&format!("var {var}: i32 = {lo};"));
                        self.line(&format!("loop {{"));
                        self.indent += 1;
                        self.line(&format!("if !({var} {op} {hi}) {{ break; }}"));
                        if self.auto_sync && body_accesses_sync_field(&f.body, &self.current_fields) {
                            self.line("workgroupBarrier();");
                        }
                        for s in &f.body { self.emit_stmt(s); }
                        self.line(&format!("{var} = {var} + 1;"));
                        self.indent -= 1;
                        self.line("}");
                    }
                    _ => {
                        let iter = self.expr(&f.iterable);
                        self.line(&format!("/* for {var} in {iter} -- unsupported in WGSL */"));
                    }
                } } // end else { match
            }
            Stmt::Break(_label, _val) => self.line("break;"),
            Stmt::Continue(_label)    => self.line("continue;"),
            // `sync` statement → explicit workgroup barrier.
            Stmt::Comment(c) if c == "sync" => {
                self.line("workgroupBarrier();");
            }
            Stmt::Comment(_) => {}
            _ => { self.line("/* unsupported stmt in wgsl kernel */"); }
        }
    }

    fn is_actor_global_field(&self, name: &str) -> bool {
        self.current_fields.iter().any(|f|
            f.name == name && matches!(f.qual, GpuQual::ActorGlobal))
    }

    /// Detect `arr[i] OP= v` on an `'actor'global` field → WGSL atomic intrinsic.
    fn try_atomic_assign(&mut self, lhs: &Expr, rhs: &Expr) -> Option<String> {
        let ExprKind::Index(arr, idx) = &lhs.kind else { return None; };
        let arr_name = match &arr.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        if !self.is_actor_global_field(&arr_name) { return None; }
        let ExprKind::BinOp(op, _lhs_copy, value) = &rhs.kind else { return None; };

        let i = self.expr(idx);
        let v = self.expr(value);
        // WGSL atomics require a pointer to the element.
        let ptr = format!("&{}[{} as u32]", arr_name, i);

        let call = match op {
            BinOp::Add    => format!("atomicAdd({}, {})", ptr, v),
            BinOp::Sub    => format!("atomicSub({}, {})", ptr, v),
            BinOp::BitOr  => format!("atomicOr({}, {})", ptr, v),
            BinOp::BitAnd => format!("atomicAnd({}, {})", ptr, v),
            BinOp::BitXor => format!("atomicXor({}, {})", ptr, v),
            _ => return None,
        };
        Some(format!("{};", call))
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Int(n)   => {
                // Values that fit in i32: plain literal (default concrete type).
                // Values in (i32::MAX, u32::MAX]: suffix 'u' to force u32.
                if *n > i32::MAX as i64 && *n <= u32::MAX as i64 {
                    format!("{}u", n)
                } else if *n < i32::MIN as i64 || *n > u32::MAX as i64 {
                    self.errors.push(format!(
                        "integer literal {} out of u32 range on --target wgpu",
                        n
                    ));
                    n.to_string()
                } else {
                    n.to_string()
                }
            }
            ExprKind::Float(f) => {
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') { s } else { format!("{}.0", s) }
            }
            ExprKind::Bool(b)  => if *b { "true".into() } else { "false".into() },
            ExprKind::Str(s)   => format!("\"{}\"", s),
            ExprKind::Nil      => "0".into(),
            ExprKind::Void     => "".into(),
            ExprKind::Var(name) => {
                self.top_level_scalars.get(name).cloned().unwrap_or_else(|| name.clone())
            }

            ExprKind::BinOp(op, lhs, rhs) => {
                let l = self.expr(lhs);
                let r = self.expr(rhs);
                format!("({} {} {})", l, binop_wgsl(op), r)
            }
            ExprKind::UnaryOp(op, operand) => {
                let v = self.expr(operand);
                format!("({}{})", unaryop_wgsl(op), v)
            }
            ExprKind::Assign(lhs, rhs) => {
                format!("({} = {})", self.expr(lhs), self.expr(rhs))
            }
            ExprKind::Index(arr, idx) => {
                format!("{}[u32({})]", self.expr(arr), self.expr(idx))
            }
            ExprKind::Field(obj, field) => {
                let obj_s = self.expr(obj);
                map_gpu_field(&obj_s, field)
            }
            ExprKind::Call(callee, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                let fn_s = match &callee.kind {
                    ExprKind::Var(n) => map_builtin_fn(n),
                    _ => self.expr(callee),
                };
                format!("{}({})", fn_s, args_s.join(", "))
            }
            ExprKind::MethodCall(obj, method, args) => {
                let args_s: Vec<String> = args.iter().map(|a| self.expr(&a.value)).collect();
                if matches!(&obj.kind, ExprKind::Var(n) if n == "self") {
                    let fn_name = format!("{}_{}", self.current_kernel, method);
                    format!("{}({})", fn_name, args_s.join(", "))
                } else {
                    let obj_s = self.expr(obj);
                    format!("/* unsupported: {}.{}({}) */", obj_s, method, args_s.join(", "))
                }
            }
            ExprKind::Cast(inner, ty) => {
                format!("{}({})", wgsl_type(ty), self.expr(inner))
            }
            ExprKind::If(i) => {
                if let Some((cond, then_body)) = i.branches.first() {
                    let c = self.expr(cond);
                    let t = then_body.last().and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    let e = i.else_body.as_ref().and_then(|b| b.last()).and_then(|s| {
                        if let Stmt::Expr(e) = s { Some(self.expr(e)) } else { None }
                    }).unwrap_or_else(|| "0".into());
                    format!("select({}, {}, {})", e, t, c)
                } else {
                    "0".into()
                }
            }
            _ => "/* expr */".into(),
        }
    }
}

// ── Free helpers ──────────────────────────────────────────────────────────────

/// Returns true if the field goes into a storage buffer binding.
fn is_buffer_field(f: &KernelFieldDecl) -> bool {
    match f.qual {
        GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface => {
            matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _))
        }
        _ => false,
    }
}

/// Returns true if the field goes into the params uniform struct.
fn is_params_field(f: &KernelFieldDecl) -> bool {
    match f.qual {
        GpuQual::Const => true,
        GpuQual::Local => !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)),
        _ => {
            // Named struct types (e.g. Dimension) in non-buffer fields go into params.
            matches!(&f.ty, Type::Named(_))
                && !matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
        }
    }
}

/// Returns the WGSL storage access modifier and array type for a buffer field.
fn wgsl_buffer_type(f: &KernelFieldDecl) -> (&'static str, String) {
    let access = match f.qual {
        GpuQual::ActorGlobal => "read_write", // atomics need read_write
        _ => if matches!(f.binding, FieldBinding::Let) { "read" } else { "read_write" },
    };
    let elem = match &f.ty {
        Type::Array(inner) | Type::ArrayN(inner, _) => {
            if matches!(f.qual, GpuQual::ActorGlobal) {
                // atomic<i32> for int, atomic<u32> for uint
                match inner.as_ref() {
                    Type::Int => "atomic<i32>".into(),
                    Type::Named(n) if matches!(n.as_str(), "int" | "i32" | "i64") => "atomic<i32>".into(),
                    Type::Uint => "atomic<u32>".into(),
                    Type::Named(n) if matches!(n.as_str(), "uint" | "u32" | "u64") => "atomic<u32>".into(),
                    other => wgsl_scalar(other),
                }
            } else {
                wgsl_scalar(inner)
            }
        }
        other => wgsl_scalar(other),
    };
    let ty = format!("array<{}>", elem);
    (access, ty)
}

/// WGSL scalar type for kernel use (i32, u32, f32, bool→u32).
fn wgsl_scalar(ty: &Type) -> String {
    match ty {
        Type::Int              => "i32".into(),
        Type::Uint             => "u32".into(),
        Type::Float            => "f32".into(),
        // bool is not allowed in storage/uniform buffers in WGSL — use u32.
        Type::Bool             => "u32".into(),
        Type::Named(n) => match n.as_str() {
            "int"   | "i32" | "i64" => "i32",
            "uint"  | "u32" | "u64" => "u32",
            "float" | "f32" | "f64" => "f32",
            "bool"                  => "u32",
            other                   => return other.to_string(),
        }.into(),
        Type::Qualified(inner, _) => wgsl_scalar(inner),
        _ => "i32".into(),
    }
}

/// Full WGSL type including arrays and structs.
fn wgsl_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)        => format!("array<{}>", wgsl_scalar(inner)),
        Type::ArrayN(inner, n)    => format!("array<{}, {}>", wgsl_scalar(inner), n),
        Type::Named(n) if n == "Dimension" => "Dimension".into(),
        other                     => wgsl_scalar(other),
    }
}

/// Zero-value literal for a WGSL scalar type.
fn wgsl_zero(ty: &Type) -> &'static str {
    match ty {
        Type::Float | Type::Named(_) => "0.0",
        Type::Bool  => "0u",
        _           => "0",
    }
}

fn binop_wgsl(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",    BinOp::Sub => "-",  BinOp::Mul => "*",
        BinOp::Div => "/",    BinOp::Rem => "%",
        BinOp::Eq  => "==",   BinOp::NotEq => "!=",
        BinOp::Lt  => "<",    BinOp::Gt => ">",
        BinOp::LtEq => "<=",  BinOp::GtEq => ">=",
        BinOp::And => "&&",   BinOp::Or => "||",
        BinOp::BitAnd => "&",  BinOp::BitOr => "|", BinOp::BitXor => "^",
        BinOp::Shl => "<<",   BinOp::Shr => ">>",
        _ => "/*op*/",
    }
}

fn unaryop_wgsl(op: &UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg    => "-",
        UnaryOp::Not    => "!",
        UnaryOp::BitNot => "~",
    }
}

fn map_gpu_field(obj: &str, field: &str) -> String {
    match (obj, field) {
        ("gpu", "thread")    => "bp_tid".into(),
        ("gpu", "block")     => "bp_bid".into(),
        ("gpu", "block_dim") => "bp_bdim".into(),
        ("gpu", "grid_dim")  => "bp_gdim".into(),
        // Dimension accessors — cast to i32 for arithmetic (matches Boring int → i32).
        ("bp_tid",  "x") => "i32(bp_tid.x)".into(),
        ("bp_tid",  "y") => "i32(bp_tid.y)".into(),
        ("bp_tid",  "z") => "i32(bp_tid.z)".into(),
        ("bp_bid",  "x") => "i32(bp_bid.x)".into(),
        ("bp_bid",  "y") => "i32(bp_bid.y)".into(),
        ("bp_bid",  "z") => "i32(bp_bid.z)".into(),
        ("bp_bdim", "x") => "i32(bp_bdim.x)".into(),
        ("bp_bdim", "y") => "i32(bp_bdim.y)".into(),
        ("bp_bdim", "z") => "i32(bp_bdim.z)".into(),
        ("bp_gdim", "x") => "i32(bp_gdim.x)".into(),
        ("bp_gdim", "y") => "i32(bp_gdim.y)".into(),
        ("bp_gdim", "z") => "i32(bp_gdim.z)".into(),
        _ => format!("{}.{}", obj, field),
    }
}

fn map_builtin_fn(name: &str) -> String {
    match name {
        "int"   => "i32".into(),
        "uint"  => "u32".into(),
        "float" => "f32".into(),
        "abs"   => "abs".into(),
        "min"   => "min".into(),
        "max"   => "max".into(),
        "sqrt"  => "sqrt".into(),
        "sin"   => "sin".into(),
        "cos"   => "cos".into(),
        "tan"   => "tan".into(),
        "tanh"  => "tanh".into(),
        "exp"   => "exp".into(),
        "log"   => "log".into(),
        "log2"  => "log2".into(),
        "pow"   => "pow".into(),
        "floor" => "floor".into(),
        "ceil"  => "ceil".into(),
        "round" => "round".into(),
        other   => other.into(),
    }
}

/// Extract the inner Named type from an array/qualified type, if any.
fn inner_named_type(ty: &Type) -> Option<&str> {
    match ty {
        Type::Array(inner) | Type::ArrayN(inner, _) => inner_named_type(inner),
        Type::Qualified(inner, _) => inner_named_type(inner),
        Type::Named(n) => Some(n.as_str()),
        _ => None,
    }
}

// ── Auto-sync helpers (identical logic to Metal backend) ──────────────────────

fn body_has_explicit_sync(stmts: &[Stmt]) -> bool {
    stmts.iter().any(|s| match s {
        Stmt::Comment(c) if c == "sync" => true,
        Stmt::While(w)   => body_has_explicit_sync(&w.body),
        Stmt::For(f)     => body_has_explicit_sync(&f.body),
        Stmt::If(i)      => i.branches.iter().any(|(_, b)| body_has_explicit_sync(b))
                         || i.else_body.as_ref().map_or(false, |b| body_has_explicit_sync(b)),
        _ => false,
    })
}

fn body_accesses_sync_field(stmts: &[Stmt], fields: &[KernelFieldDecl]) -> bool {
    let sync_names: Vec<&str> = fields.iter()
        .filter(|f| matches!(f.qual, GpuQual::Sync))
        .map(|f| f.name.as_str())
        .collect();
    if sync_names.is_empty() { return false; }
    stmts_reference_any(stmts, &sync_names)
}

fn stmts_reference_any(stmts: &[Stmt], names: &[&str]) -> bool {
    stmts.iter().any(|s| stmt_references_any(s, names))
}

fn stmt_references_any(stmt: &Stmt, names: &[&str]) -> bool {
    match stmt {
        Stmt::Expr(e)      => expr_references_any(e, names),
        Stmt::Return(r)    => r.value.as_ref().map_or(false, |v| expr_references_any(v, names)),
        Stmt::Let(s)       => s.value.as_ref().map_or(false, |v| expr_references_any(v, names)),
        Stmt::While(w)     => stmts_reference_any(&w.body, names),
        Stmt::For(f)       => stmts_reference_any(&f.body, names),
        Stmt::If(i)        => i.branches.iter().any(|(_, b)| stmts_reference_any(b, names))
                           || i.else_body.as_ref().map_or(false, |b| stmts_reference_any(b, names)),
        _ => false,
    }
}

fn expr_references_any(expr: &Expr, names: &[&str]) -> bool {
    match &expr.kind {
        ExprKind::Var(n)           => names.contains(&n.as_str()),
        ExprKind::Index(a, i)      => expr_references_any(a, names) || expr_references_any(i, names),
        ExprKind::Field(e, _)      => expr_references_any(e, names),
        ExprKind::BinOp(_, l, r)   => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::UnaryOp(_, e)    => expr_references_any(e, names),
        ExprKind::Assign(l, r)     => expr_references_any(l, names) || expr_references_any(r, names),
        ExprKind::Call(f, args)    => expr_references_any(f, names)
                                   || args.iter().any(|a| expr_references_any(&a.value, names)),
        _ => false,
    }
}

fn first_loop_index(stmts: &[Stmt]) -> usize {
    stmts.iter().position(|s| matches!(s, Stmt::While(_) | Stmt::For(_)))
        .unwrap_or(stmts.len())
}

/// Scan `kernel:` blocks for `kname(block = ...)` calls and return per-kernel block sizes.
fn collect_block_sizes(program: &Program) -> std::collections::HashMap<String, (u32, u32, u32)> {
    // Build var_name → kernel_type_name mapping from top-level let/var declarations.
    let mut var_to_type: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    let resolve_let = |s: &LetStmt, map: &mut std::collections::HashMap<String, String>| {
        if let Some(val) = &s.value {
            if let ExprKind::Call(callee, _) = &val.kind {
                if let ExprKind::Var(type_name) = &callee.kind {
                    map.insert(s.name.clone(), type_name.clone());
                }
            }
        }
    };
    for item in &program.items {
        match item {
            Item::Let(s) => resolve_let(s, &mut var_to_type),
            Item::Stmt(Stmt::Let(s)) => resolve_let(s, &mut var_to_type),
            _ => {}
        }
    }
    let mut map = std::collections::HashMap::new();
    for item in &program.items {
        if let Item::Stmt(Stmt::KernelBlock(block)) = item {
            for s in &block.body {
                scan_call_block_size(s, &mut map, &var_to_type);
            }
        }
    }
    map
}

fn scan_call_block_size(s: &Stmt, map: &mut std::collections::HashMap<String, (u32, u32, u32)>, var_to_type: &std::collections::HashMap<String, String>) {
    match s {
        Stmt::Loop(ls) => { for inner in &ls.body { scan_call_block_size(inner, map, var_to_type); } }
        Stmt::Expr(e) => {
            if let ExprKind::Call(callee, args) = &e.kind {
                if let ExprKind::Var(kname) = &callee.kind {
                    if let Some(ba) = args.iter().find(|a| a.label.as_deref() == Some("block")) {
                        let parse_u32 = |e: &Expr| -> u32 {
                            match &e.kind {
                                ExprKind::Int(n) => *n as u32,
                                ExprKind::Var(_) => 1, // conservative fallback
                                _ => 1,
                            }
                        };
                        let (bx, by, bz) = match &ba.value.kind {
                            ExprKind::Tuple(elems) => {
                                let g = |i: usize| elems.get(i).map(|e| parse_u32(e)).unwrap_or(1);
                                (g(0), g(1), g(2))
                            }
                            _ => (parse_u32(&ba.value), 1, 1),
                        };
                        // Index by kernel type name (resolved from variable name if possible).
                        let key = var_to_type.get(kname).cloned().unwrap_or_else(|| kname.clone());
                        map.insert(key, (bx, by, bz));
                    }
                }
            }
        }
        _ => {}
    }
}
