// Copyright (C) 2026 MickaÃ«l LANOÃ‹
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Rust host code emitter for the wgpu backend.

use crate::ast::*;

pub(super) fn emit_host_rs(program: &Program, kernel_names: &[String], effective_kernels: &[KernelDecl]) -> String {
    let mut e = HostEmitter::new(program, kernel_names, effective_kernels);
    e.emit();
    e.out
}

struct HostEmitter<'a> {
    out: String,
    program: &'a Program,
    kernel_names: &'a [String],
    effective_kernels: &'a [KernelDecl],
    has_screen: bool,
    /// When true, render-stmt helpers emit `self.` prefix and `event_loop` for exit.
    in_method: bool,
}

impl<'a> HostEmitter<'a> {
    fn new(program: &'a Program, kernel_names: &'a [String], effective_kernels: &'a [KernelDecl]) -> Self {
        let has_screen = program.items.iter().any(|item| {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    if let ExprKind::Call(callee, _) = &val.kind {
                        if let ExprKind::Var(n) = &callee.kind {
                            return n == "Screen";
                        }
                    }
                }
            }
            false
        });
        Self { out: String::new(), program, kernel_names, effective_kernels, has_screen, in_method: false }
    }

    fn line(&mut self, s: &str) { self.out.push_str(s); self.out.push('\n'); }
    fn blank(&mut self) { self.out.push('\n'); }

    fn emit(&mut self) {
        self.emit_header();
        self.emit_kernel_structs();
        self.emit_gpu_copy_helpers();
        self.emit_main();
    }

    fn emit_header(&mut self) {
        self.line("// Generated by boring build --target wgpu.");
        self.line("// Do not edit -- re-generate with: boring build --target wgpu");
        self.blank();
        if !self.has_screen {
            self.line("use std::collections::HashMap;");
        }
        self.line("use wgpu::util::DeviceExt;");
        self.line("use bytemuck::{Pod, Zeroable};");
        if self.has_screen {
            self.line("use winit::application::ApplicationHandler;");
            self.line("use winit::event::{WindowEvent, ElementState};");
            self.line("use winit::event_loop::{ActiveEventLoop, EventLoop};");
            self.line("use winit::keyboard::{Key, NamedKey};");
            self.line("use winit::window::{Window, WindowAttributes, WindowId};");
        }
        self.blank();
    }

    // â"€â"€ Kernel structs â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€

    fn emit_kernel_structs(&mut self) {
        // Use effective_kernels (monomorphised) rather than raw program items.
        let decls: Vec<KernelDecl> = self.effective_kernels.to_vec();
        for decl in &decls {
            self.emit_kernel_struct(decl);
        }
    }

    fn emit_kernel_struct(&mut self, decl: &KernelDecl) {
        let name = &decl.name;

        // Params struct (scalars + Dimension fields for uniform buffer).
        let params_fields: Vec<&KernelFieldDecl> = decl.fields.iter()
            .filter(|f| is_params_field(f)).collect();
        if !params_fields.is_empty() {
            self.line("#[repr(C)]");
            self.line("#[derive(Debug, Clone, Copy, Pod, Zeroable)]");
            self.line(&format!("struct {}Params {{", name));
            for f in &params_fields {
                match &f.ty {
                    Type::Named(n) if n == "Dimension" => {
                        self.line(&format!("    {}_w: i32,", f.name));
                        self.line(&format!("    {}_h: i32,", f.name));
                    }
                    Type::ArrayN(inner, n) => {
                        self.line(&format!("    {}: [{}; {}],", f.name, host_scalar_type(inner), n));
                    }
                    ty => {
                        self.line(&format!("    {}: {},", f.name, host_scalar_type(ty)));
                    }
                }
            }
            self.line("}");
            self.blank();
        }

        // Kernel host struct.
        self.line(&format!("struct {} {{", name));
        self.line("    device: std::sync::Arc<wgpu::Device>,");
        self.line("    queue: std::sync::Arc<wgpu::Queue>,");
        self.line("    pipeline: wgpu::ComputePipeline,");
        self.line("    bind_group: wgpu::BindGroup,");
        for f in &decl.fields {
            match f.qual {
                GpuQual::Unified | GpuQual::Global | GpuQual::Surface | GpuQual::ActorGlobal => {
                    if matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        self.line(&format!("    {}_buf: wgpu::Buffer,", f.name));
                        // Keep Vec mirror for 'unified fields accessible from host.
                        if matches!(f.qual, GpuQual::Unified | GpuQual::Surface) {
                            let inner_ty = array_inner(&f.ty);
                            self.line(&format!("    {}: Vec<{}>,", f.name, host_scalar_type(&inner_ty)));
                        }
                    }
                }
                GpuQual::Const => {
                    match &f.ty {
                        Type::Named(n) if n == "Dimension" => {
                            self.line(&format!("    {}: (i32, i32),", f.name));
                        }
                        Type::ArrayN(inner, n) => {
                            self.line(&format!("    {}: [{}; {}],", f.name, host_scalar_type(inner), n));
                        }
                        ty => {
                            self.line(&format!("    {}: {},", f.name, host_scalar_type(ty)));
                        }
                    }
                }
                GpuQual::Local => {
                    // Scalar local fields (e.g. `var float t`) get a host mirror so the
                    // caller can update them between dispatches.
                    if !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        self.line(&format!("    {}: {},", f.name, host_scalar_type(&f.ty)));
                    }
                }
                GpuQual::Sync => {
                    // workgroup memory, no host side.
                }
            }
        }
        if !params_fields.is_empty() {
            self.line(&format!("    params_buf: wgpu::Buffer,"));
        }
        self.line("}");
        self.blank();

        // impl block.
        self.line(&format!("impl {} {{", name));

        // Constructor.
        self.emit_kernel_new(decl);
        self.blank();

        // Launch method.
        self.emit_kernel_launch(decl);
        self.blank();

        // gpu.copy helpers: __copy_to_host / __copy_to_device.
        self.emit_kernel_copy_accessors(decl);

        self.line("}");
        self.blank();
    }

    fn emit_kernel_new(&mut self, decl: &KernelDecl) {
        let name = &decl.name;

        // Build constructor params from init method if present.
        let init_params: Vec<String> = if let Some(init) = decl.methods.iter().find(|m| m.name == "init") {
            init.params.iter().map(|p| {
                let ty = p.ty.as_ref().map(|t| host_type(t)).unwrap_or_else(|| "i64".into());
                format!("{}: {}", p.name, ty)
            }).collect()
        } else {
            vec![]
        };
        let params_sig = if init_params.is_empty() { String::new() }
                         else { format!("{}, ", init_params.join(", ")) };

        // Check whether this kernel has a Dimension const field (grid-sized buffers).
        let has_dim_field = decl.fields.iter().any(|f| matches!(&f.ty, Type::Named(n) if n == "Dimension") && matches!(f.qual, GpuQual::Const));
        let dim_param = if has_dim_field { "width: i32, height: i32, " } else { "" };

        self.line(&format!("    fn new({}{dim_param}device: std::sync::Arc<wgpu::Device>, queue: std::sync::Arc<wgpu::Queue>) -> Self {{", params_sig));

        // Load shader.
        self.line("        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {");
        self.line("            label: None,");
        self.line(&format!("            source: wgpu::ShaderSource::Wgsl(include_str!(\"../shaders/main.wgsl\").into()),"));
        self.line("        });");
        self.blank();

        // Collect buffer fields.
        let buf_fields: Vec<&KernelFieldDecl> = decl.fields.iter()
            .filter(|f| matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::Surface | GpuQual::ActorGlobal)
                     && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)))
            .collect();
        let params_fields: Vec<&KernelFieldDecl> = decl.fields.iter()
            .filter(|f| is_params_field(f)).collect();

        // Create GPU buffers.
        for f in &buf_fields {
            let usages = buffer_usages(f);
            let inner_ty = array_inner(&f.ty);
            let host_ty = host_scalar_type(&inner_ty);
            let (size_expr, init_data) = match &f.ty {
                Type::ArrayN(_, n) => {
                    (format!("({} * std::mem::size_of::<{}>()) as u64", n, host_ty),
                     format!("vec![{}::default(); {}]", host_ty, n))
                }
                _ if has_dim_field => {
                    // Dynamic size derived from Dimension (width * height * sizeof<T>).
                    (format!("((width * height) as usize * std::mem::size_of::<{}>()) as u64", host_ty),
                     format!("vec![{}::default(); (width * height) as usize]", host_ty))
                }
                _ => {
                    ("0u64".into(), format!("Vec::<{}>::new()", host_ty))
                }
            };
            let _ = init_data;
            self.line(&format!("        let {}_buf = device.create_buffer(&wgpu::BufferDescriptor {{", f.name));
            self.line("            label: None,");
            self.line(&format!("            size: {},", size_expr));
            self.line(&format!("            usage: {},", usages));
            self.line("            mapped_at_creation: false,");
            self.line("        });");
        }

        // Params buffer.
        if !params_fields.is_empty() {
            self.line(&format!("        let params_buf = device.create_buffer(&wgpu::BufferDescriptor {{"));
            self.line("            label: None,");
            self.line(&format!("            size: std::mem::size_of::<{}Params>() as u64,", name));
            self.line("            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,");
            self.line("            mapped_at_creation: false,");
            self.line("        });");
        }
        self.blank();

        // Pipeline (workgroup size is hardcoded in WGSL, no override constants needed).
        self.line(&format!("        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{"));
        self.line("            label: None,");
        self.line("            layout: None,");
        self.line("            module: &shader,");
        self.line(&format!("            entry_point: \"{}_main\",", name));
        self.line("            compilation_options: wgpu::PipelineCompilationOptions::default(),");
        self.line("            cache: None,");
        self.line("        });");
        self.blank();

        // Bind group.
        let mut binding_entries: Vec<String> = vec![];
        let mut binding_idx: u32 = 0;
        for f in &buf_fields {
            binding_entries.push(format!(
                "            wgpu::BindGroupEntry {{ binding: {binding_idx}, resource: {}_buf.as_entire_binding() }},",
                f.name, binding_idx = binding_idx
            ));
            binding_idx += 1;
        }
        if !params_fields.is_empty() {
            binding_entries.push(format!(
                "            wgpu::BindGroupEntry {{ binding: {binding_idx}, resource: params_buf.as_entire_binding() }},",
                binding_idx = binding_idx
            ));
        }
        let bg_layout = "pipeline.get_bind_group_layout(0)";
        self.line("        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {");
        self.line("            label: None,");
        self.line(&format!("            layout: &{},", bg_layout));
        self.line("            entries: &[");
        for entry in &binding_entries { self.line(entry); }
        self.line("            ],");
        self.line("        });");
        self.blank();

        // Return struct.
        self.line(&format!("        {} {{", name));
        self.line("            device: std::sync::Arc::clone(&device),");
        self.line("            queue: std::sync::Arc::clone(&queue),");
        self.line("            pipeline,");
        self.line("            bind_group,");
        for f in &buf_fields {
            self.line(&format!("            {}_buf,", f.name));
            if matches!(f.qual, GpuQual::Unified | GpuQual::Surface) {
                let inner_ty = array_inner(&f.ty);
                let n = match &f.ty {
                    Type::ArrayN(_, n) => *n,
                    _ => 0,
                };
                self.line(&format!("            {}: vec![{}::default(); {}],",
                    f.name, host_scalar_type(&inner_ty), n));
            }
        }
        if !params_fields.is_empty() {
            self.line("            params_buf,");
        }
        for f in &decl.fields {
            match f.qual {
                GpuQual::Const => {
                    match &f.ty {
                        Type::Named(n) if n == "Dimension" => {
                            // Use width/height params when available (has_dim_field kernel).
                            self.line(&format!("            {}: (width, height),", f.name));
                        }
                        Type::ArrayN(inner, n) => {
                            self.line(&format!("            {}: [{}::default(); {}],",
                                f.name, host_scalar_type(inner), n));
                        }
                        ty => {
                            let val = f.default.as_ref()
                                .map(emit_scalar_default)
                                .unwrap_or_else(|| format!("{}::default()", host_scalar_type(ty)));
                            self.line(&format!("            {}: {},", f.name, val));
                        }
                    }
                }
                GpuQual::Local => {
                    if !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                        let val = f.default.as_ref()
                            .map(emit_scalar_default)
                            .unwrap_or_else(|| format!("{}::default()", host_scalar_type(&f.ty)));
                        self.line(&format!("            {}: {},", f.name, val));
                    }
                }
                _ => {}
            }
        }
        self.line("        }");
        self.line("    }");
    }

    fn emit_kernel_launch(&mut self, decl: &KernelDecl) {
        let name = &decl.name;
        let params_fields: Vec<&KernelFieldDecl> = decl.fields.iter()
            .filter(|f| is_params_field(f)).collect();

        self.line("    fn dispatch(&self, gx: u32, gy: u32, gz: u32) {");

        // Write params before dispatch.
        if !params_fields.is_empty() {
            self.line(&format!("        let params = {}Params {{", name));
            for f in &params_fields {
                match &f.ty {
                    Type::Named(n) if n == "Dimension" => {
                        self.line(&format!("            {}_w: self.{}.0,", f.name, f.name));
                        self.line(&format!("            {}_h: self.{}.1,", f.name, f.name));
                    }
                    Type::ArrayN(_, _) => {
                        self.line(&format!("            {}: self.{},", f.name, f.name));
                    }
                    _ => {
                        self.line(&format!("            {}: self.{},", f.name, f.name));
                    }
                }
            }
            self.line("        };");
            self.line("        self.queue.write_buffer(&self.params_buf, 0, bytemuck::bytes_of(&params));");
        }
        self.blank();

        self.line("        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });");
        self.line("        {");
        self.line("            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });");
        self.line("            cpass.set_pipeline(&self.pipeline);");
        self.line("            cpass.set_bind_group(0, &self.bind_group, &[]);");
        self.line("            cpass.dispatch_workgroups(gx, gy, gz);");
        self.line("        }");
        self.line("        self.queue.submit(std::iter::once(encoder.finish()));");
        // No poll here — caller (present_buffer or explicit sync) handles synchronization.
        self.line("    }");
    }

    fn emit_kernel_copy_accessors(&mut self, decl: &KernelDecl) {
        for f in &decl.fields {
            if matches!(f.qual, GpuQual::Global) && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)) {
                let inner_ty = array_inner(&f.ty);
                let host_ty = host_scalar_type(&inner_ty);
                // D2H.
                self.line(&format!("    fn copy_{}_to_host(&self) -> Vec<{}> {{", f.name, host_ty));
                self.line(&format!("        __boring_gpu_copy_d2h::<{}>(&self.device, &self.queue, &self.{}_buf)", host_ty, f.name));
                self.line("    }");
                // H2D.
                self.line(&format!("    fn copy_{}_to_device(&self, data: &[{}]) {{", f.name, host_ty));
                self.line(&format!("        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.{}_buf);", f.name));
                self.line("    }");
                self.blank();
            }
        }
    }

    // â"€â"€ Staging buffer helpers â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€

    fn emit_gpu_copy_helpers(&mut self) {
        // D2H helper.
        self.line("fn __boring_gpu_copy_d2h<T: bytemuck::Pod>(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> Vec<T> {");
        self.line("    let size = src.size();");
        self.line("    let staging = device.create_buffer(&wgpu::BufferDescriptor {");
        self.line("        label: None,");
        self.line("        size,");
        self.line("        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,");
        self.line("        mapped_at_creation: false,");
        self.line("    });");
        self.line("    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });");
        self.line("    encoder.copy_buffer_to_buffer(src, 0, &staging, 0, size);");
        self.line("    queue.submit(std::iter::once(encoder.finish()));");
        self.line("    device.poll(wgpu::MaintainBase::Wait);");
        self.line("    let slice = staging.slice(..);");
        self.line("    let (tx, rx) = std::sync::mpsc::channel();");
        self.line("    slice.map_async(wgpu::MapMode::Read, move |r| { tx.send(r).unwrap(); });");
        self.line("    device.poll(wgpu::MaintainBase::Wait);");
        self.line("    rx.recv().unwrap().unwrap();");
        self.line("    let data = bytemuck::cast_slice(&staging.slice(..).get_mapped_range()).to_vec();");
        self.line("    staging.unmap();");
        self.line("    data");
        self.line("}");
        self.blank();

        // H2D helper.
        self.line("fn __boring_gpu_copy_h2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &[u8], dst: &wgpu::Buffer) {");
        self.line("    let size = src.len() as u64;");
        self.line("    let staging = device.create_buffer(&wgpu::BufferDescriptor {");
        self.line("        label: None,");
        self.line("        size,");
        self.line("        usage: wgpu::BufferUsages::MAP_WRITE | wgpu::BufferUsages::COPY_SRC,");
        self.line("        mapped_at_creation: true,");
        self.line("    });");
        self.line("    staging.slice(..).get_mapped_range_mut().copy_from_slice(src);");
        self.line("    staging.unmap();");
        self.line("    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });");
        self.line("    encoder.copy_buffer_to_buffer(&staging, 0, dst, 0, size);");
        self.line("    queue.submit(std::iter::once(encoder.finish()));");
        self.line("}");
        self.blank();

        if self.has_screen {
            self.emit_present_buffer_helper();
        }
    }

    fn emit_present_buffer_helper(&mut self) {
        // GPU-only present: runs a render pipeline that reads the storage buffer in a fragment
        // shader and outputs directly to the surface texture. No CPU readback, no blocking poll.
        // A non-blocking Poll before get_current_texture() flushes completed frames back to the
        // swapchain so get_current_texture() doesn't block the Wayland event loop.
        self.line("fn __boring_present_buffer(device: &wgpu::Device, queue: &wgpu::Queue, surface: &wgpu::Surface, pipeline: &wgpu::RenderPipeline, bind_group: &wgpu::BindGroup) {");
        self.line("    device.poll(wgpu::MaintainBase::Poll);");
        self.line("    let output = match surface.get_current_texture() { Ok(t) => t, Err(_) => return };");
        self.line("    let view = output.texture.create_view(&wgpu::TextureViewDescriptor::default());");
        self.line("    let mut enc = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });");
        self.line("    {");
        self.line("        let mut rpass = enc.begin_render_pass(&wgpu::RenderPassDescriptor {");
        self.line("            label: None,");
        self.line("            color_attachments: &[Some(wgpu::RenderPassColorAttachment {");
        self.line("                view: &view, resolve_target: None,");
        self.line("                ops: wgpu::Operations { load: wgpu::LoadOp::Clear(wgpu::Color::BLACK), store: wgpu::StoreOp::Store },");
        self.line("            })],");
        self.line("            depth_stencil_attachment: None, timestamp_writes: None, occlusion_query_set: None,");
        self.line("        });");
        self.line("        rpass.set_pipeline(pipeline);");
        self.line("        rpass.set_bind_group(0, bind_group, &[]);");
        self.line("        rpass.draw(0..6, 0..1);");
        self.line("    }");
        self.line("    queue.submit(std::iter::once(enc.finish()));");
        self.line("    output.present();");
        self.line("}");
        self.blank();
    }

    // Returns the `kernel.field_buf` reference for the first screen.present() call in the loop.
    fn find_present_buffer(&self) -> String {
        let loop_body = self.find_render_loop_body();
        for stmt in &loop_body {
            if let Stmt::Expr(e) = stmt {
                let args = match &e.kind {
                    ExprKind::MethodCall(obj, method, args) if method == "present" => {
                        if let ExprKind::Var(n) = &obj.kind { if n == "screen" { Some(args) } else { None } } else { None }
                    }
                    ExprKind::Call(callee, args) => {
                        if let ExprKind::Field(obj, method) = &callee.kind {
                            if method == "present" {
                                if let ExprKind::Var(n) = &obj.kind { if n == "screen" { Some(args) } else { None } } else { None }
                            } else { None }
                        } else { None }
                    }
                    _ => None,
                };
                if let Some(args) = args {
                    if let Some(arg) = args.first() {
                        if let ExprKind::Field(kobj, kfield) = &arg.value.kind {
                            if let ExprKind::Var(kname) = &kobj.kind {
                                return format!("{kname}.{kfield}_buf");
                            }
                        }
                    }
                }
            }
        }
        "pixels_buf".into()
    }

    fn emit_main(&mut self) {
        if self.has_screen {
            self.emit_screen_main();
        } else {
            self.line("fn main() {");
            self.line("    pollster::block_on(async_main());");
            self.line("}");
            self.blank();
            self.line("async fn async_main() {");
            self.line("    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());");
            self.line("    let adapter = instance.request_adapter(&wgpu::RequestAdapterOptions::default()).await.expect(\"No GPU adapter found\");");
            self.line("    let (device, queue) = adapter.request_device(&wgpu::DeviceDescriptor::default(), None).await.expect(\"Failed to create device\");");
            self.line("    let device = std::sync::Arc::new(device);");
            self.line("    let queue = std::sync::Arc::new(queue);");
            self.blank();
            self.emit_compute_main();
            self.line("}");
        }
    }

    fn emit_screen_main(&mut self) {
        let (w_expr, h_expr, title, _) = self.extract_screen_info();
        let scalars     = self.extract_top_level_scalars();
        let width       = resolve_scalar_expr(&w_expr, &scalars);
        let height      = resolve_scalar_expr(&h_expr, &scalars);
        let loop_body   = self.find_render_loop_body();
        let pixels_buf  = self.find_present_buffer();

        let items: Vec<Item> = self.program.items.clone();

        // Collect scalar names and kernel instantiations for the app struct.
        let scalar_fields: Vec<(String, String)> = items.iter().filter_map(|item| {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    let is_screen = matches!(&val.kind, ExprKind::Call(c, _) if matches!(&c.kind, ExprKind::Var(n) if n == "Screen"));
                    let is_kernel = matches!(&val.kind, ExprKind::Call(c, _) if matches!(&c.kind, ExprKind::Var(kn) if self.kernel_names.contains(kn)));
                    if !is_screen && !is_kernel && matches!(val.kind, ExprKind::Int(_) | ExprKind::Float(_) | ExprKind::Bool(_)) {
                        return Some((s.name.clone(), host_expr(val)));
                    }
                }
            }
            None
        }).collect();

        let kernel_fields: Vec<(String, String, String)> = items.iter().filter_map(|item| {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    if let ExprKind::Call(callee, args) = &val.kind {
                        if let ExprKind::Var(kname) = &callee.kind {
                            if self.kernel_names.contains(kname) {
                                let dim_args = extract_dimension_args(args.first());
                                let new_args = if let Some((w, h)) = dim_args {
                                    format!("{w}, {h}, ")
                                } else { String::new() };
                                return Some((s.name.clone(), kname.clone(), new_args));
                            }
                        }
                    }
                }
            }
            None
        }).collect();

        // ── __App struct ──────────────────────────────────────────────────────
        self.line("struct __App {");
        self.line("    instance: wgpu::Instance,");
        self.line("    adapter:  wgpu::Adapter,");
        self.line("    device:   std::sync::Arc<wgpu::Device>,");
        self.line("    queue:    std::sync::Arc<wgpu::Queue>,");
        for (name, _val) in &scalar_fields {
            self.line(&format!("    {name}: i64,"));
        }
        for (var, kname, _) in &kernel_fields {
            self.line(&format!("    {var}: {kname},"));
        }
        self.line("    __keys: std::collections::HashSet<String>,");
        self.line("    __start_time: std::time::Instant,");
        self.line("    window: Option<std::sync::Arc<Window>>,");
        self.line("    surface: Option<wgpu::Surface<'static>>,");
        self.line("    __blit_pipeline: Option<wgpu::RenderPipeline>,");
        self.line("    __blit_bg:       Option<wgpu::BindGroup>,");
        self.line("    __blit_dim_buf:  Option<wgpu::Buffer>,");
        self.line("}");
        self.blank();

        // ── ApplicationHandler impl ───────────────────────────────────────────
        self.line("impl ApplicationHandler for __App {");
        // resumed(): create window + surface + blit pipeline
        self.line("    fn resumed(&mut self, event_loop: &ActiveEventLoop) {");
        self.line(&format!(
            "        let window = std::sync::Arc::new(event_loop.create_window(WindowAttributes::default().with_title(\"{title}\").with_inner_size(winit::dpi::PhysicalSize::new({width}u32, {height}u32))).unwrap());"
        ));
        self.line("        let surface: wgpu::Surface<'static> = self.instance.create_surface(window.clone()).unwrap();");
        self.line("        let caps = surface.get_capabilities(&self.adapter);");
        self.line("        let fmt  = caps.formats.iter().find(|f| **f == wgpu::TextureFormat::Bgra8Unorm).copied().unwrap_or(caps.formats[0]);");
        self.line("        surface.configure(&self.device, &wgpu::SurfaceConfiguration {");
        self.line("            usage: wgpu::TextureUsages::RENDER_ATTACHMENT, format: fmt,");
        self.line(&format!("            width: {width}, height: {height},"));
        self.line("            present_mode: wgpu::PresentMode::Fifo,");
        self.line("            desired_maximum_frame_latency: 2,");
        self.line("            alpha_mode: caps.alpha_modes[0], view_formats: vec![],");
        self.line("        });");
        // Blit pipeline (inline shader)
        self.line("        let blit_shader = self.device.create_shader_module(wgpu::ShaderModuleDescriptor {");
        self.line("            label: Some(\"blit\"),");
        self.line("            source: wgpu::ShaderSource::Wgsl(std::borrow::Cow::Borrowed(r#\"");
        self.line("@group(0) @binding(0) var<storage, read> blit_pixels: array<u32>;");
        self.line("struct BlitDim { width: u32, height: u32 }");
        self.line("@group(0) @binding(1) var<uniform> blit_dim: BlitDim;");
        self.line("struct BlitVOut { @builtin(position) pos: vec4<f32> }");
        self.line("@vertex fn blit_vs(@builtin(vertex_index) idx: u32) -> BlitVOut {");
        self.line("    var quad = array<vec2<f32>, 6>(");
        self.line("        vec2<f32>(-1.0, -1.0), vec2<f32>(1.0, -1.0), vec2<f32>(-1.0,  1.0),");
        self.line("        vec2<f32>(-1.0,  1.0), vec2<f32>(1.0, -1.0), vec2<f32>( 1.0,  1.0));");
        self.line("    var out: BlitVOut; out.pos = vec4<f32>(quad[idx], 0.0, 1.0); return out; }");
        self.line("@fragment fn blit_fs(in: BlitVOut) -> @location(0) vec4<f32> {");
        self.line("    let x = u32(in.pos.x); let y = u32(in.pos.y);");
        self.line("    let i = y * blit_dim.width + x;");
        self.line("    if i >= blit_dim.width * blit_dim.height { return vec4<f32>(0.0, 0.0, 0.0, 1.0); }");
        self.line("    let raw = blit_pixels[i];");
        self.line("    let r = f32((raw >>  0u) & 0xFFu) / 255.0;");
        self.line("    let g = f32((raw >>  8u) & 0xFFu) / 255.0;");
        self.line("    let b = f32((raw >> 16u) & 0xFFu) / 255.0;");
        self.line("    let a = f32((raw >> 24u) & 0xFFu) / 255.0;");
        self.line("    return vec4<f32>(r, g, b, a); }");
        self.line("            \"#)),");
        self.line("        });");
        self.line("        let blit_bgl = self.device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {");
        self.line("            label: None, entries: &[");
        self.line("                wgpu::BindGroupLayoutEntry { binding: 0, visibility: wgpu::ShaderStages::FRAGMENT,");
        self.line("                    ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Storage { read_only: true },");
        self.line("                        has_dynamic_offset: false, min_binding_size: None }, count: None },");
        self.line("                wgpu::BindGroupLayoutEntry { binding: 1, visibility: wgpu::ShaderStages::FRAGMENT,");
        self.line("                    ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Uniform,");
        self.line("                        has_dynamic_offset: false, min_binding_size: None }, count: None },");
        self.line("            ],");
        self.line("        });");
        self.line(&format!("        let blit_dim_buf = self.device.create_buffer_init(&wgpu::util::BufferInitDescriptor {{"));
        self.line("            label: Some(\"blit_dim\"),");
        self.line(&format!("            contents: bytemuck::cast_slice(&[{width}u32, {height}u32]),"));
        self.line("            usage: wgpu::BufferUsages::UNIFORM,");
        self.line("        });");
        self.line(&format!("        let blit_bg = self.device.create_bind_group(&wgpu::BindGroupDescriptor {{"));
        self.line("            label: None, layout: &blit_bgl, entries: &[");
        self.line(&format!("                wgpu::BindGroupEntry {{ binding: 0, resource: self.{pixels_buf}.as_entire_binding() }},"));
        self.line("                wgpu::BindGroupEntry { binding: 1, resource: blit_dim_buf.as_entire_binding() },");
        self.line("            ],");
        self.line("        });");
        self.line("        let blit_pl = self.device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {");
        self.line("            label: None, bind_group_layouts: &[&blit_bgl], push_constant_ranges: &[],");
        self.line("        });");
        self.line("        let blit_pipeline = self.device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {");
        self.line("            label: None, layout: Some(&blit_pl),");
        self.line("            vertex: wgpu::VertexState { module: &blit_shader, entry_point: \"blit_vs\", buffers: &[],");
        self.line("                compilation_options: wgpu::PipelineCompilationOptions::default() },");
        self.line("            fragment: Some(wgpu::FragmentState { module: &blit_shader, entry_point: \"blit_fs\",");
        self.line("                targets: &[Some(wgpu::ColorTargetState { format: fmt, blend: None,");
        self.line("                    write_mask: wgpu::ColorWrites::ALL })],");
        self.line("                compilation_options: wgpu::PipelineCompilationOptions::default() }),");
        self.line("            primitive: wgpu::PrimitiveState::default(), depth_stencil: None,");
        self.line("            multisample: wgpu::MultisampleState::default(), multiview: None, cache: None,");
        self.line("        });");
        self.line("        self.window = Some(window.clone());");
        self.line("        self.surface = Some(surface);");
        self.line("        self.__blit_pipeline = Some(blit_pipeline);");
        self.line("        self.__blit_bg = Some(blit_bg);");
        self.line("        self.__blit_dim_buf = Some(blit_dim_buf);");
        self.line("        window.request_redraw();");
        self.line("    }");
        self.blank();
        // window_event(): handle all window events
        self.line("    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {");
        self.line("        match event {");
        self.line("            WindowEvent::CloseRequested => { event_loop.exit(); }");
        self.line("            WindowEvent::KeyboardInput { event: ref key_event, .. } => {");
        self.line("                let key_str = match &key_event.logical_key {");
        self.line("                    Key::Named(NamedKey::Escape) => \"Escape\".to_string(),");
        self.line("                    Key::Named(NamedKey::Enter)  => \"Enter\".to_string(),");
        self.line("                    Key::Named(NamedKey::Space)  => \" \".to_string(),");
        self.line("                    Key::Character(c) => c.to_string(),");
        self.line("                    k => format!(\"{k:?}\"),");
        self.line("                };");
        self.line("                match key_event.state {");
        self.line("                    ElementState::Pressed  => { self.__keys.insert(key_str); }");
        self.line("                    ElementState::Released => { self.__keys.remove(&key_str); }");
        self.line("                    _ => {}");
        self.line("                }");
        self.line("            }");
        self.line("            WindowEvent::RedrawRequested => {");
        // Render loop body with self. prefix
        self.in_method = true;
        let w = width.clone();
        let h = height.clone();
        for stmt in &loop_body {
            self.emit_render_stmt(stmt, &w, &h, "                ");
        }
        self.in_method = false;
        self.line("                if let Some(w) = &self.window { w.request_redraw(); }");
        self.line("            }");
        self.line("            _ => {}");
        self.line("        }");
        self.line("    }");
        self.line("}");
        self.blank();

        // ── fn main() ─────────────────────────────────────────────────────────
        self.line("fn main() {");
        self.line("    let (instance, adapter, device, queue) = pollster::block_on(async {");
        self.line("        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());");
        self.line("        let adapter  = instance.request_adapter(&wgpu::RequestAdapterOptions::default())");
        self.line("            .await.expect(\"No GPU adapter found\");");
        self.line("        let (device, queue) = adapter");
        self.line("            .request_device(&wgpu::DeviceDescriptor::default(), None)");
        self.line("            .await.expect(\"Failed to create device\");");
        self.line("        (instance, adapter, device, queue)");
        self.line("    });");
        self.line("    let device = std::sync::Arc::new(device);");
        self.line("    let queue  = std::sync::Arc::new(queue);");
        for (name, val) in &scalar_fields {
            self.line(&format!("    let {name}: i64 = {val};"));
        }
        // Kernel instantiations in main() (need device/queue before struct init)
        for (var, kname, new_args) in &kernel_fields {
            // new_args may be "width, height, " — cast to i32 for the kernel constructor.
            let new_args_cast = if new_args.is_empty() { String::new() } else {
                new_args.split(", ").filter(|s| !s.is_empty())
                    .map(|a| format!("{a} as i32"))
                    .collect::<Vec<_>>().join(", ") + ", "
            };
            self.line(&format!(
                "    let {var} = {kname}::new({new_args_cast}std::sync::Arc::clone(&device), std::sync::Arc::clone(&queue));"
            ));
        }
        // Bug 3 fix: seed 'surface' array buffers with random initial data.
        for (var, kname, _) in &kernel_fields {
            let surface_fields: Vec<String> = self.program.items.iter().find_map(|item| {
                if let Item::Kernel(decl) = item {
                    if &decl.name == kname {
                        let fields: Vec<String> = decl.fields.iter()
                            .filter(|f| matches!(f.qual, GpuQual::Surface)
                                     && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)))
                            .map(|f| f.name.clone())
                            .collect();
                        return Some(fields);
                    }
                }
                None
            }).unwrap_or_default();
            for field in &surface_fields {
                self.line(&format!("    {{"));
                self.line(&format!("        let mut __rng: u64 = 0x12345678ABCDEF01u64;"));
                self.line(&format!("        let __n = ({width} * {height}) as usize;"));
                self.line(&format!("        let __rand_data: Vec<u32> = (0..__n).map(|_| {{ __rng ^= __rng << 13; __rng ^= __rng >> 7; __rng ^= __rng << 17; if __rng % 10 < 3 {{ 1u32 }} else {{ 0u32 }} }}).collect();"));
                self.line(&format!("        queue.write_buffer(&{var}.{field}_buf, 0, bytemuck::cast_slice(&__rand_data));"));
                self.line(&format!("    }}"));
            }
        }
        self.line("    let mut app = __App {");
        self.line("        instance, adapter, device, queue,");
        for (name, val) in &scalar_fields {
            self.line(&format!("        {name}: {val},"));
        }
        for (var, _, _) in &kernel_fields {
            self.line(&format!("        {var},"));
        }
        self.line("        __keys: Default::default(),");
        self.line("        __start_time: std::time::Instant::now(),");
        self.line("        window: None, surface: None,");
        self.line("        __blit_pipeline: None, __blit_bg: None, __blit_dim_buf: None,");
        self.line("    };");
        self.line("    let event_loop = EventLoop::new().unwrap();");
        self.line("    event_loop.run_app(&mut app).unwrap_or_else(|_| {});");
        self.line("}");
    }

    // -- Screen helpers -------------------------------------------------------

    fn extract_screen_info(&self) -> (String, String, String, String) {
        for item in &self.program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    if let ExprKind::Call(callee, args) = &val.kind {
                        if let ExprKind::Var(n) = &callee.kind {
                            if n == "Screen" {
                                let (w, h) = args.first()
                                    .and_then(|a| {
                                        if let ExprKind::Call(dc, da) = &a.value.kind {
                                            if let ExprKind::Var(dn) = &dc.kind {
                                                if dn == "Dimension" {
                                                    let w = da.get(0).map(|x| host_expr(&x.value)).unwrap_or_else(|| "800".into());
                                                    let h = da.get(1).map(|x| host_expr(&x.value)).unwrap_or_else(|| "600".into());
                                                    return Some((w, h));
                                                }
                                            }
                                        }
                                        None
                                    })
                                    .unwrap_or_else(|| ("800".into(), "600".into()));
                                let title = args.iter()
                                    .find(|a| a.label.as_deref() == Some("title"))
                                    .and_then(|a| if let ExprKind::Str(sv) = &a.value.kind { Some(sv.clone()) } else { None })
                                    .unwrap_or_else(|| "boring".into());
                                return (w, h, title, s.name.clone());
                            }
                        }
                    }
                }
            }
        }
        ("800".into(), "600".into(), "boring".into(), "screen".into())
    }

    fn extract_top_level_scalars(&self) -> std::collections::HashMap<String, i64> {
        let mut map = std::collections::HashMap::new();
        for item in &self.program.items {
            if let Item::Let(s) = item {
                if let Some(val) = &s.value {
                    if let ExprKind::Int(n) = &val.kind { map.insert(s.name.clone(), *n); }
                }
            }
        }
        map
    }

    #[allow(dead_code)]
    fn collect_render_block_sizes(&self) -> std::collections::HashMap<String, (String, String, String)> {
        let mut map = std::collections::HashMap::new();
        for item in &self.program.items {
            if let Item::Stmt(Stmt::KernelBlock(block)) = item {
                for s in &block.body {
                    self.scan_block_size_stmt(s, &mut map);
                }
            }
        }
        map
    }

    fn scan_block_size_stmt(
        &self,
        s: &Stmt,
        map: &mut std::collections::HashMap<String, (String, String, String)>,
    ) {
        match s {
            Stmt::Loop(ls) => {
                for inner in &ls.body { self.scan_block_size_stmt(inner, map); }
            }
            Stmt::Expr(e) => {
                if let ExprKind::Call(callee, args) = &e.kind {
                    if let ExprKind::Var(kname) = &callee.kind {
                        if let Some(ba) = args.iter().find(|a| a.label.as_deref() == Some("block")) {
                            let (bx, by, bz) = match &ba.value.kind {
                                ExprKind::Tuple(elems) => {
                                    let g = |i: usize| elems.get(i).map(|e| host_expr(e)).unwrap_or_else(|| "1".into());
                                    (g(0), g(1), g(2))
                                }
                                _ => (host_expr(&ba.value), "1".into(), "1".into()),
                            };
                            map.insert(kname.clone(), (bx, by, bz));
                        }
                    }
                }
            }
            _ => {}
        }
    }

    fn find_render_loop_body(&self) -> Vec<Stmt> {
        for item in &self.program.items {
            if let Item::Stmt(Stmt::KernelBlock(block)) = item {
                for stmt in &block.body {
                    if let Stmt::Loop(ls) = stmt { return ls.body.clone(); }
                }
            }
        }
        vec![]
    }

    fn emit_render_stmt(&mut self, stmt: &Stmt, width: &str, height: &str, indent: &str) {
        match stmt {
            Stmt::Expr(e) => {
                if let Some(s) = self.try_emit_screen_present(e, width, height) {
                    self.line(&format!("{indent}{s}"));
                } else if let Some(s) = self.try_emit_render_dispatch(e, width, height) {
                    self.line(&format!("{indent}{s};"));
                } else if let Some(s) = self.try_emit_field_swap(e) {
                    self.line(&format!("{indent}{s}"));
                } else if let Some(s) = self.try_emit_field_assign(e) {
                    self.line(&format!("{indent}{s}"));
                }
            }
            Stmt::If(if_stmt) => {
                if let Some(s) = self.try_emit_screen_key_if(if_stmt) {
                    self.line(&format!("{indent}{s}"));
                }
            }
            _ => {}
        }
    }

    fn try_emit_screen_present(&self, e: &Expr, _width: &str, _height: &str) -> Option<String> {
        let (obj_name, args) = match &e.kind {
            ExprKind::MethodCall(obj, method, args) if method == "present" => {
                if let ExprKind::Var(n) = &obj.kind { (n.as_str(), args) } else { return None; }
            }
            ExprKind::Call(callee, args) => {
                if let ExprKind::Field(obj, method) = &callee.kind {
                    if method != "present" { return None; }
                    if let ExprKind::Var(n) = &obj.kind { (n.as_str(), args) } else { return None; }
                } else { return None; }
            }
            _ => return None,
        };
        if obj_name != "screen" { return None; }
        // Verify the argument is a field access (e.g. render.pixels) — if not, bail.
        let arg = args.first()?;
        if !matches!(&arg.value.kind, ExprKind::Field(_, _)) { return None; }
        if self.in_method {
            Some("__boring_present_buffer(&self.device, &self.queue, self.surface.as_ref().unwrap(), self.__blit_pipeline.as_ref().unwrap(), self.__blit_bg.as_ref().unwrap());".into())
        } else {
            Some("__boring_present_buffer(&device, &queue, &surface, &__blit_pipeline, &__blit_bg);".into())
        }
    }

    fn try_emit_render_dispatch(&self, e: &Expr, width: &str, height: &str) -> Option<String> {
        let ExprKind::Call(callee, args) = &e.kind else { return None; };
        if !args.iter().any(|a| a.label.as_deref() == Some("block")) { return None; }
        let var_name = if let ExprKind::Var(n) = &callee.kind { n.clone() } else { return None; };
        let ba = args.iter().find(|a| a.label.as_deref() == Some("block"))?;
        let (bx, by) = match &ba.value.kind {
            ExprKind::Tuple(elems) => {
                let g = |i: usize| elems.get(i).map(|e| host_expr(e)).unwrap_or_else(|| "1".into());
                (g(0), g(1))
            }
            _ => (host_expr(&ba.value), "1".into()),
        };
        let gx = format!("({width} + {bx} - 1) / {bx}");
        let gy = format!("({height} + {by} - 1) / {by}");
        let pfx = if self.in_method { "self." } else { "" };
        Some(format!("{pfx}{var_name}.dispatch({gx}, {gy}, 1)"))
    }

    fn try_emit_screen_key_if(&self, if_stmt: &IfStmt) -> Option<String> {
        if if_stmt.branches.len() != 1 { return None; }
        let (cond, body) = &if_stmt.branches[0];
        let (obj_name, args) = match &cond.kind {
            ExprKind::MethodCall(obj, method, args) if method == "key" => {
                if let ExprKind::Var(n) = &obj.kind { (n.as_str(), args) } else { return None; }
            }
            ExprKind::Call(callee, args) => {
                if let ExprKind::Field(obj, method) = &callee.kind {
                    if method != "key" { return None; }
                    if let ExprKind::Var(n) = &obj.kind { (n.as_str(), args) } else { return None; }
                } else { return None; }
            }
            _ => return None,
        };
        if obj_name != "screen" { return None; }
        let key_arg = args.first()?;
        let key_str = if let ExprKind::Str(s) = &key_arg.value.kind { s.clone() } else { return None; };
        let key_rust = boring_key_to_rust(&key_str);
        let is_break = body.iter().any(|s| matches!(s, Stmt::Break(_, _)));
        if is_break {
            let (keys_var, exit_call) = if self.in_method {
                ("self.__keys", "event_loop.exit()")
            } else {
                ("__keys", "elwt.exit()")
            };
            Some(format!("if {keys_var}.contains({key_rust}) {{ {exit_call}; }}"))
        } else {
            Some(format!("// screen.key({key_rust:?}) -- no action"))
        }
    }

    fn emit_compute_main(&mut self) {
        // Emit kernel struct instantiations and dispatch calls.
        // KernelBlock bodies contain regular Stmt::Expr nodes; kernel calls are
        // detected by the presence of a `block = N` labeled argument.
        for item in self.program.items.iter() {
            match item {
                Item::Let(s) => {
                    if let Some(val) = &s.value {
                        if let ExprKind::Call(callee, args) = &val.kind {
                            if let ExprKind::Var(kname) = &callee.kind {
                                if self.kernel_names.contains(kname) {
                                    let dim_args = extract_dimension_args(args.first());
                                    let new_args = if let Some((w, h)) = dim_args {
                                        format!("{w}, {h}, ")
                                    } else { String::new() };
                                    self.line(&format!("    let mut {} = {}::new({}std::sync::Arc::clone(&device), std::sync::Arc::clone(&queue));",
                                        s.name, kname, new_args));
                                }
                            }
                        }
                    }
                }
                Item::Stmt(Stmt::KernelBlock(block)) => {
                    for stmt in &block.body {
                        if let Stmt::Expr(e) = stmt {
                            if let Some(s) = self.try_emit_dispatch(e) {
                                self.line(&format!("    {};", s));
                            } else if let Some(s) = self.try_emit_field_swap(e) {
                                self.line(&format!("    {}", s));
                            } else if let Some(s) = self.try_emit_field_assign(e) {
                                self.line(&format!("    {};", s));
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }

    /// Detect `k(block = N)` or `k(block = (bx, by))` dispatch calls.
    fn try_emit_dispatch(&self, e: &Expr) -> Option<String> {
        let ExprKind::Call(callee, args) = &e.kind else { return None; };
        let has_block = args.iter().any(|a| a.label.as_deref() == Some("block"));
        if !has_block { return None; }
        let var_name = match &callee.kind {
            ExprKind::Var(n) => n.clone(),
            _ => return None,
        };
        // Extract block = (bx, by, bz) or block = N.
        let block_arg = args.iter().find(|a| a.label.as_deref() == Some("block"))?;
        let (bx, by, bz) = match &block_arg.value.kind {
            ExprKind::Tuple(elems) => {
                let get = |i: usize| elems.get(i)
                    .map(|e| host_expr(e))
                    .unwrap_or_else(|| "1".into());
                (get(0), get(1), get(2))
            }
            other => {
                let n = host_expr(&block_arg.value);
                let _ = other;
                (n, "1".into(), "1".into())
            }
        };
        // Grid: auto-compute as gx = ceil(len / bx) for 1D, or explicit `grid = (gx, gy)`.
        let grid_arg = args.iter().find(|a| a.label.as_deref() == Some("grid"));
        let (gx, gy, gz) = if let Some(g) = grid_arg {
            match &g.value.kind {
                ExprKind::Tuple(elems) => {
                    let get = |i: usize| elems.get(i).map(|e| host_expr(e)).unwrap_or_else(|| "1".into());
                    (get(0), get(1), get(2))
                }
                _ => {
                    let n = host_expr(&g.value);
                    (n, "1".into(), "1".into())
                }
            }
        } else {
            // Default: 1 workgroup per dimension -- caller must set explicit grid= when needed.
            ("1".into(), "1".into(), "1".into())
        };
        let _ = (bx, by, bz); // block size already baked into pipeline at new() time
        Some(format!("{var_name}.dispatch({gx}, {gy}, {gz})"))
    }

    /// Detect simultaneous field swap: `k.a, k.b = k.b, k.a`
    /// Emits `std::mem::swap(&mut k.a_buf, &mut k.b_buf);` for buffer fields.
    fn try_emit_field_swap(&self, e: &Expr) -> Option<String> {
        let ExprKind::Assign(lhs, rhs) = &e.kind else { return None; };
        let ExprKind::Tuple(lhs_list) = &lhs.kind else { return None; };
        let ExprKind::Tuple(rhs_list) = &rhs.kind else { return None; };
        if lhs_list.len() != 2 || rhs_list.len() != 2 { return None; }
        // Check it's a swap: lhs[0]==rhs[1] and lhs[1]==rhs[0] (by expression text)
        let field_name = |e: &Expr| -> Option<(String, String)> {
            if let ExprKind::Field(obj, field) = &e.kind {
                if let ExprKind::Var(obj_name) = &obj.kind {
                    return Some((obj_name.clone(), field.clone()));
                }
            }
            None
        };
        let (obj0, f0) = field_name(&lhs_list[0])?;
        let (obj1, f1) = field_name(&lhs_list[1])?;
        let (robj0, rf0) = field_name(&rhs_list[0])?;
        let (robj1, rf1) = field_name(&rhs_list[1])?;
        if obj0 == robj1 && f0 == rf1 && obj1 == robj0 && f1 == rf0 {
            // It's a swap of two fields on the same object
            if obj0 == obj1 {
                let pfx = if self.in_method { "self." } else { "" };
                return Some(format!(
                    "std::mem::swap(&mut {pfx}{}.{}_buf, &mut {pfx}{}.{}_buf);",
                    obj0, f0, obj1, f1
                ));
            }
        }
        None
    }

    /// Detect field assignment: `k.field = expr`
    fn try_emit_field_assign(&self, e: &Expr) -> Option<String> {
        let ExprKind::Assign(lhs, rhs) = &e.kind else { return None; };
        if let ExprKind::Field(obj, field) = &lhs.kind {
            if let ExprKind::Var(obj_name) = &obj.kind {
                // `step.cells_in = step.cells_out` â†' bind buffer alias
                if let ExprKind::Field(robj, rfield) = &rhs.kind {
                    if let ExprKind::Var(robj_name) = &robj.kind {
                        // Try to find the target kernel decl to rebuild its bind group.
                        if let Some(target_decl) = self.find_kernel_decl_for_var(obj_name) {
                            let pfx = if self.in_method { "self." } else { "" };
                            let buf_fields: Vec<&KernelFieldDecl> = target_decl.fields.iter()
                                .filter(|f| matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::Surface | GpuQual::ActorGlobal)
                                         && matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)))
                                .collect();
                            let params_fields: Vec<&KernelFieldDecl> = target_decl.fields.iter()
                                .filter(|f| is_params_field(f)).collect();
                            let mut entries: Vec<String> = vec![];
                            for (idx, f) in buf_fields.iter().enumerate() {
                                if f.name == field.as_str() {
                                    entries.push(format!(
                                        "                wgpu::BindGroupEntry {{ binding: {idx}, resource: {pfx}{robj_name}.{rfield}_buf.as_entire_binding() }},"));
                                } else {
                                    entries.push(format!(
                                        "                wgpu::BindGroupEntry {{ binding: {idx}, resource: {pfx}{obj_name}.{}_buf.as_entire_binding() }},", f.name));
                                }
                            }
                            if !params_fields.is_empty() {
                                let idx = buf_fields.len();
                                entries.push(format!(
                                    "                wgpu::BindGroupEntry {{ binding: {idx}, resource: {pfx}{obj_name}.params_buf.as_entire_binding() }},"));
                            }
                            let entries_str = entries.join("\n");
                            return Some(format!(
                                "{pfx}{obj_name}.bind_group = {pfx}{obj_name}.device.create_bind_group(&wgpu::BindGroupDescriptor {{\n    label: None,\n    layout: &{pfx}{obj_name}.pipeline.get_bind_group_layout(0),\n    entries: &[\n{entries_str}\n    ],\n}});"
                            ));
                        }
                        return Some(format!(
                            "// {}.{} = {}.{} (field alias not yet supported in wgpu)",
                            obj_name, field, robj_name, rfield
                        ));
                    }
                }
                // Scalar field assignment: `k.t = expr` → update the host-side field.
                let pfx = if self.in_method { "self." } else { "" };
                let rhs_str = self.host_expr(rhs);
                return Some(format!("{pfx}{obj_name}.{field} = {rhs_str};"));
            }
        }
        None
    }

    /// Translate a host-side Boring expression to a Rust string.
    /// Handles the subset of expressions that can appear in the top-level kernel loop
    /// (scalar assignments, screen.time, float() casts, arithmetic).
    fn host_expr(&self, e: &Expr) -> String {
        let pfx = if self.in_method { "self." } else { "" };
        match &e.kind {
            // screen.time → elapsed seconds as f32
            ExprKind::Field(obj, field) if field == "time" => {
                if let ExprKind::Var(n) = &obj.kind {
                    if n == "screen" {
                        return format!("{pfx}__start_time.elapsed().as_secs_f32()");
                    }
                }
                format!("{pfx}{}.{}", self.host_expr(obj), field)
            }
            ExprKind::Field(obj, field) => {
                format!("{}.{}", self.host_expr(obj), field)
            }
            // float(expr) → expr as f32
            ExprKind::Call(callee, args) => {
                if let ExprKind::Var(n) = &callee.kind {
                    if n == "float" && args.len() == 1 {
                        return format!("({} as f32)", self.host_expr(&args[0].value));
                    }
                }
                // Generic call (best effort)
                let args_s: Vec<_> = args.iter().map(|a| self.host_expr(&a.value)).collect();
                format!("{}({})", self.host_expr(callee), args_s.join(", "))
            }
            ExprKind::Var(n) => n.clone(),
            ExprKind::Int(v)   => format!("{v}"),
            ExprKind::Float(v) => format!("{v}f32"),
            ExprKind::BinOp(op, l, r) => {
                let op_s = match op {
                    BinOp::Add => "+", BinOp::Sub => "-",
                    BinOp::Mul => "*", BinOp::Div => "/",
                    _ => "/* op */",
                };
                format!("({} {op_s} {})", self.host_expr(l), self.host_expr(r))
            }
            _ => "/* unsupported expr */".into(),
        }
    }

    /// Find the KernelDecl for a top-level kernel variable (e.g. `var render = Render(...)`).
    /// Returns the monomorphised decl from `effective_kernels`.
    fn find_kernel_decl_for_var(&self, var_name: &str) -> Option<&KernelDecl> {
        let ktype_name = self.program.items.iter().find_map(|item| {
            if let Item::Let(s) = item {
                if s.name == var_name {
                    if let Some(val) = &s.value {
                        match &val.kind {
                            ExprKind::Call(callee, _) => {
                                if let ExprKind::Var(kn) = &callee.kind {
                                    if self.kernel_names.contains(kn) {
                                        return Some(kn.clone());
                                    }
                                }
                            }
                            ExprKind::GenericCall(callee, type_args, _) => {
                                if let ExprKind::Var(kn) = &callee.kind {
                                    if self.kernel_names.contains(kn) {
                                        // Build the monomorphised name from the concrete args.
                                        let args: Vec<i64> = type_args.iter().map(|t| {
                                            if let Type::ConstInt(n) = t { *n } else { 0 }
                                        }).collect();
                                        if args.is_empty() {
                                            return Some(kn.clone());
                                        }
                                        let suffix: Vec<String> = args.iter().map(|n| n.to_string()).collect();
                                        return Some(format!("{}_{}", kn, suffix.join("_")));
                                    }
                                }
                            }
                            _ => {}
                        }
                    }
                }
            }
            None
        })?;
        // Look up in effective_kernels (monomorphised) — the first match for this name.
        self.effective_kernels.iter().find(|decl| decl.name == ktype_name)
    }
}

//â"€â"€ Free helpers â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€

/// Emit a simple scalar expression as a Rust literal for use as a kernel field default.
fn emit_scalar_default(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Int(n)   => n.to_string(),
        ExprKind::Float(f) => {
            let s = format!("{}", f);
            if s.contains('.') { s } else { format!("{}.0", s) }
        }
        ExprKind::Bool(b)  => b.to_string(),
        ExprKind::UnaryOp(UnaryOp::Neg, inner) => match &inner.kind {
            ExprKind::Int(n)   => format!("-{}", n),
            ExprKind::Float(f) => format!("-{}", f),
            _ => "Default::default()".into(),
        },
        _ => "Default::default()".into(),
    }
}

fn is_params_field(f: &KernelFieldDecl) -> bool {
    match f.qual {
        GpuQual::Const => true,
        GpuQual::Local => !matches!(f.ty, Type::Array(_) | Type::ArrayN(_, _)),
        _ => {
            matches!(&f.ty, Type::Named(n) if n != "Dimension" || true)
                && matches!(&f.ty, Type::Named(_))
                && !matches!(f.qual, GpuQual::Unified | GpuQual::Global | GpuQual::ActorGlobal | GpuQual::Surface)
        }
    }
}

fn array_inner(ty: &Type) -> Type {
    match ty {
        Type::Array(inner) | Type::ArrayN(inner, _) => (**inner).clone(),
        other => other.clone(),
    }
}

fn host_scalar_type(ty: &Type) -> &'static str {
    match ty {
        // GPU buffers always use 32-bit elements (WGSL narrows int→i32, uint→u32, float→f32).
        Type::Int   => "i32",
        Type::Uint  => "u32",
        Type::Float => "f32",
        Type::Bool  => "bool",
        Type::Named(n) => match n.as_str() {
            "int" | "i64" | "i32"   => "i32",
            "uint" | "u64" | "u32"  => "u32",
            "float" | "f64" | "f32" => "f32",
            "bool"                  => "bool",
            _                       => "i64",
        },
        Type::Qualified(inner, _) => host_scalar_type(inner),
        _ => "i64",
    }
}

fn host_type(ty: &Type) -> String {
    match ty {
        Type::Array(inner)     => format!("Vec<{}>", host_scalar_type(inner)),
        Type::ArrayN(inner, n) => format!("[{}; {}]", host_scalar_type(inner), n),
        Type::Named(n) if n == "Dimension" => "(i32, i32)".into(),
        other => host_scalar_type(other).into(),
    }
}

fn buffer_usages(f: &KernelFieldDecl) -> String {
    match f.qual {
        GpuQual::Unified => "wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST".into(),
        GpuQual::Surface => "wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST".into(),
        GpuQual::Global  => "wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST".into(),
        GpuQual::ActorGlobal => "wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST".into(),
        _ => "wgpu::BufferUsages::STORAGE".into(),
    }
}

/// Emit a host-side expression (simplified -- for init args and dispatch grid).
fn host_expr(e: &Expr) -> String {
    match &e.kind {
        ExprKind::Int(n)        => n.to_string(),
        ExprKind::Float(f)      => format!("{}", f),
        ExprKind::Bool(b)       => b.to_string(),
        ExprKind::Str(s)        => format!("\"{}\"", s),
        ExprKind::Var(n)        => n.clone(),
        ExprKind::BinOp(op, l, r) => {
            let op_s = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                BinOp::Div => "/", _ => "/*op*/",
            };
            format!("({} {} {})", host_expr(l), op_s, host_expr(r))
        }
        ExprKind::Call(callee, args) => {
            let fn_s = if let ExprKind::Var(n) = &callee.kind { n.clone() } else { host_expr(callee) };
            let args_s: Vec<String> = args.iter().map(|a| host_expr(&a.value)).collect();
            format!("{}({})", fn_s, args_s.join(", "))
        }
        _ => "/* expr */".into(),
    }
}

fn resolve_scalar_expr(expr: &str, scalars: &std::collections::HashMap<String, i64>) -> String {
    if let Some(&n) = scalars.get(expr) { return n.to_string(); }
    expr.to_string()
}

fn boring_key_to_rust(s: &str) -> String {
    match s {
        "\x1B" | "\\x1B" | "Escape" | "escape" => "\"Escape\"".into(),
        " " | "Space" | "space"                 => "\" \"".into(),
        "\n" | "\\n" | "Enter" | "enter"        => "\"Enter\"".into(),
        other => format!("\"{}\"", other),
    }
}

/// Extract `(w_str, h_str)` from a `Dimension(w, h)` call arg if present.
fn extract_dimension_args(arg: Option<&Arg>) -> Option<(String, String)> {
    let arg = arg?;
    if let ExprKind::Call(dc, da) = &arg.value.kind {
        if let ExprKind::Var(n) = &dc.kind {
            if n == "Dimension" {
                let w = da.get(0).map(|x| host_expr(&x.value)).unwrap_or_else(|| "800".into());
                let h = da.get(1).map(|x| host_expr(&x.value)).unwrap_or_else(|| "600".into());
                return Some((w, h));
            }
        }
    }
    None
}
