# NVIDIA GeForce RTX 3090 (24 GB GDDR6X)
name = "NVIDIA GeForce RTX 3090"
totalMem = 25769803776      # 24 GB
warpSize = 32
maxThreads = 1024
maxSharedMem = 49152        # 48 KB
computeCapability = [8, 6]
