// Generated by boring build --target wgpu.
// Do not edit — re-generate with: boring build --target wgpu

use std::collections::HashMap;
use wgpu::util::DeviceExt;
use bytemuck::{Pod, Zeroable};

#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
struct MatrixMulParams {
    dim_w: u32,
    dim_h: u32,
}

struct MatrixMul {
    device: std::sync::Arc<wgpu::Device>,
    queue: std::sync::Arc<wgpu::Queue>,
    pipeline: wgpu::ComputePipeline,
    bind_group: wgpu::BindGroup,
    a_buf: wgpu::Buffer,
    b_buf: wgpu::Buffer,
    c_buf: wgpu::Buffer,
    c: Vec<f64>,
    dim: (u32, u32),
    params_buf: wgpu::Buffer,
}

impl MatrixMul {
    fn new(device: std::sync::Arc<wgpu::Device>, queue: std::sync::Arc<wgpu::Queue>, block_x: u32, block_y: u32, block_z: u32) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: None,
            source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/main.wgsl").into()),
        });

        let a_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 0u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let b_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 0u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let c_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 0u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::MAP_WRITE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let params_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: std::mem::size_of::<MatrixMulParams>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let constants: std::collections::HashMap<String, f64> = [
            ("block_x".to_string(), block_x as f64),
            ("block_y".to_string(), block_y as f64),
            ("block_z".to_string(), block_z as f64),
        ].into_iter().collect();
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: None,
            layout: None,
            module: &shader,
            entry_point: "MatrixMul_main",
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &constants,
                ..Default::default()
            },
            cache: None,
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &pipeline.get_bind_group_layout(0),
            entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: a_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: b_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: c_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 3, resource: params_buf.as_entire_binding() },
            ],
        });

        MatrixMul {
            device: std::sync::Arc::clone(&device),
            queue: std::sync::Arc::clone(&queue),
            pipeline,
            bind_group,
            a_buf,
            b_buf,
            c_buf,
            c: vec![f64::default(); 0],
            params_buf,
            dim: (0, 0),
        }
    }

    fn dispatch(&self, gx: u32, gy: u32, gz: u32) {
        let params = MatrixMulParams {
            dim_w: self.dim.0,
            dim_h: self.dim.1,
        };
        self.queue.write_buffer(&self.params_buf, 0, bytemuck::bytes_of(&params));

        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
        {
            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });
            cpass.set_pipeline(&self.pipeline);
            cpass.set_bind_group(0, &self.bind_group, &[]);
            cpass.dispatch_workgroups(gx, gy, gz);
        }
        self.queue.submit(std::iter::once(encoder.finish()));
        self.device.poll(wgpu::MaintainBase::Wait);
    }

    fn copy_a_to_host(&self) -> Vec<f64> {
        __boring_gpu_copy_d2h::<f64>(&self.device, &self.queue, &self.a_buf)
    }
    fn copy_a_to_device(&self, data: &[f64]) {
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.a_buf);
    }

    fn copy_b_to_host(&self) -> Vec<f64> {
        __boring_gpu_copy_d2h::<f64>(&self.device, &self.queue, &self.b_buf)
    }
    fn copy_b_to_device(&self, data: &[f64]) {
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.b_buf);
    }

}

fn __boring_gpu_copy_d2h<T: bytemuck::Pod>(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> Vec<T> {
    let size = src.size();
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(src, 0, &staging, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
    device.poll(wgpu::MaintainBase::Wait);
    let slice = staging.slice(..);
    let (tx, rx) = std::sync::mpsc::channel();
    slice.map_async(wgpu::MapMode::Read, move |r| { tx.send(r).unwrap(); });
    device.poll(wgpu::MaintainBase::Wait);
    rx.recv().unwrap().unwrap();
    let data = bytemuck::cast_slice(&staging.slice(..).get_mapped_range()).to_vec();
    staging.unmap();
    data
}

fn __boring_gpu_copy_h2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &[u8], dst: &wgpu::Buffer) {
    let size = src.len() as u64;
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::MAP_WRITE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: true,
    });
    staging.slice(..).get_mapped_range_mut().copy_from_slice(src);
    staging.unmap();
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(&staging, 0, dst, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
}

fn main() {
    pollster::block_on(async_main());
}

async fn async_main() {
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());
    let adapter = instance.request_adapter(&wgpu::RequestAdapterOptions::default()).await.expect("No GPU adapter found");
    let (device, queue) = adapter.request_device(&wgpu::DeviceDescriptor::default(), None).await.expect("Failed to create device");
    let device = std::sync::Arc::new(device);
    let queue = std::sync::Arc::new(queue);

    let mut k = MatrixMul::new(std::sync::Arc::clone(&device), std::sync::Arc::clone(&queue), 256, 1, 1);
    k.dispatch(1, 1, 1);
}
