// Generated by boring --emit-rust. Compile with: rustc --edition 2021 <file.rs>
use std::collections::{HashMap, HashSet};
use std::rc::Rc;
use std::sync::Arc;
use std::f64::consts::{PI, E, TAU};

fn add(a: i64, b: i64) -> i64 {
    (a + b)
}

fn greet(who: &str) -> Arc<String> {
    Arc::new(format!("Hello, {}!", who))
}

fn display(name: Option<Arc<String>>) -> Arc<String> {
    let Some(n) = name else {
        return Arc::new("nobody".to_string());
    };
    Arc::new(format!("Hello, {}!", n))
}

fn say(msg: Arc<String>) -> Arc<String> {
    msg
}

fn divide(a: i64, b: i64) -> Result<i64, Box<dyn std::error::Error>> {
    if !((b != 0)) {
        return Err("division by zero".into());
    }
    Ok((a / b))
}

#[derive(Clone)]
enum CalcError {
    DivByZero,
    Overflow,
}


fn checked_divide(a: i64, b: i64) -> Result<i64, CalcError> {
    if !((b != 0)) {
        return Err(CalcError::DivByZero.into());
    }
    if !(((a / b) < 1000000)) {
        return Err(CalcError::Overflow.into());
    }
    Ok((a / b))
}

fn identity<T: Clone>(x: T) -> T {
    x
}

fn first<T: Clone>(items: Vec<T>) -> T {
    items[0].clone()
}

fn join(sep: &str, parts: Vec<Arc<String>>) -> Arc<String> {
    let mut result: Arc<String> = Arc::new("".to_string());
    let mut first = true;
    for p in parts.iter().cloned() {
        if first {
            result = p;
            first = false
        } else {
            result = Arc::new(format!("{}{}{}", result, sep, p))
        }
    }
    result
}

fn sum(values: Vec<i64>) -> i64 {
    let mut total = 0;
    for v in values.iter().cloned() {
        total += v;
    }
    total
}

fn sign(n: i64) -> Arc<String> {
    if (n > 0) {
        Arc::new("+".to_string())
    } else if (n < 0) {
        Arc::new("-".to_string())
    } else {
        Arc::new("0".to_string())
    }
}

fn check(n: i64) -> Arc<String> {
    if !((n >= 0)) {
        return Arc::new("negative".to_string());
    }
    Arc::new(format!("ok ({})", n))
}

fn describe(n: i64) -> Arc<String> {
    match n {
        0 => {
            Arc::new("zero".to_string())
        }
        1 | 2 | 3 => {
            Arc::new("small".to_string())
        }
        x if (x < 0) => {
            Arc::new("negative".to_string())
        }
        _ => {
            Arc::new("large".to_string())
        }
    }
}

struct Vec2 {
    pub x: f64,
    pub y: f64,
}

impl Vec2 {
    fn len(&self) -> f64 {
        (((self.x * self.x) + (self.y * self.y))).sqrt()
    }

    fn add(&self, other: Vec2) -> Vec2 {
        Vec2 { x: (self.x + other.x), y: (self.y + other.y) }
    }

}

impl std::fmt::Display for Vec2 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "({}, {})", self.x, self.y)
    }
}

struct Counter {
    value: /* var */ i64,
}

impl Counter {
    pub fn new() -> Self {
        Counter {
            value: 0,
        }
    }

    fn inc(&mut self) -> () {
        self.value += 1
    }

    fn get(&self) -> i64 {
        self.value.clone()
    }

}

#[derive(Clone)]
enum Expr {
    Num(i64),
    Add(i64, i64),
    Mul(i64, i64),
}


fn eval_expr(e: Expr) -> i64 {
    match e {
        Expr::Num(v) => {
            v
        }
        Expr::Add(l, r) => {
            (l + r)
        }
        Expr::Mul(l, r) => {
            (l * r)
        }
    }
}

fn classify_expr(e: Expr) -> Arc<String> {
    match e {
        Expr::Num(v) if (v == 0) => {
            Arc::new("zero literal".to_string())
        }
        Expr::Num(_) => {
            Arc::new("literal".to_string())
        }
        Expr::Add(_, _) => {
            Arc::new("addition".to_string())
        }
        Expr::Mul(_, _) => {
            Arc::new("multiplication".to_string())
        }
    }
}

pub trait Named {
    fn name(&self) -> Arc<String>;
}

pub trait Describable {
    fn describe(&self) -> Arc<String>;
}

struct Animal {
    pub species: Arc<String>,
    pub sound: Arc<String>,
}

impl Animal {
}

impl Named for Animal {
    fn name(&self) -> Arc<String> {
        self.species.clone()
    }

}

impl Describable for Animal {
    fn describe(&self) -> Arc<String> {
        Arc::new(format!("{} says {}", self.species, self.sound))
    }

}

impl Animal {
    fn louder_than(&self, other: Animal) -> bool {
        (self.sound.len() as i64 > other.sound.len() as i64)
    }

}

pub trait Greetable {
    fn greet(&self) -> Arc<String>;
}

impl Greetable for Animal {
    fn greet(&self) -> Arc<String> {
        Arc::new(format!("Hi, I'm a {}!", self.name()))
    }

}

fn safe_parse(s: &str) -> i64 {
    let v: Option<i64> = s.parse::<i64>().ok();
    v.unwrap_or_else(|| (-1))
}

fn read_file(path: &str) -> Result<Arc<String>, Box<dyn std::error::Error>> {
    if !((path.len() as i64 > 0)) {
        return Err("empty path".into());
    }
    Ok(Arc::new(format!("contents of {}", path)))
}

fn try_catch_demo() -> Result<Arc<String>, Box<dyn std::error::Error>> {
    return Err("something went wrong".into());
}

fn apply(f: impl Fn(i64) -> i64, x: i64) -> i64 {
    f(x)
}

struct Config {
    pub host: Option<Arc<String>>,
    pub port: Option<i64>,
}

impl Config {
    pub fn new() -> Self {
        Config {
            host: None,
            port: None,
        }
    }

}

fn connect(c: Config) -> Arc<String> {
    let Some(host) = c.host else {
        return Arc::new("no host".to_string());
    };
    let Some(port) = c.port else {
        return Arc::new("no port".to_string());
    };
    Arc::new(format!("Connecting to {}:{}", host, port))
}

fn minmax(nums: Vec<i64>) -> (i64, i64) {
    let mut mn = nums[0].clone();
    let mut mx = nums[0].clone();
    for num in nums.iter().cloned() {
        if (num < mn) {
            mn = num
        }
        if (num > mx) {
            mx = num
        }
    }
    (mn, mx)
}

fn quadrant(px: i64, py: i64) -> Arc<String> {
    if (px > 0) {
        if (py > 0) {
            Arc::new("I".to_string())
        } else {
            Arc::new("IV".to_string())
        }
    } else {
        if (py > 0) {
            Arc::new("II".to_string())
        } else {
            Arc::new("III".to_string())
        }
    }
}

fn with_cleanup() -> Arc<String> {
    let mut log: Arc<String> = Arc::new("".to_string());
    log = Arc::new(format!("{}{}" , log, "open+work"));
    let __deferred_ret = log.clone();
    log = Arc::new(format!("{}{}" , log, "+closed"));
    __deferred_ret.clone()
}

fn lifo() -> Arc<String> {
    let mut log: Arc<String> = Arc::new("".to_string());
    let __deferred_ret = log.clone();
    log = Arc::new(format!("{}{}" , log, "C"));
    log = Arc::new(format!("{}{}" , log, "B"));
    log = Arc::new(format!("{}{}" , log, "A"));
    __deferred_ret.clone()
}

#[derive(Debug, Clone, PartialEq)]
struct Color {
    pub r: i64,
    pub g: i64,
    pub b: i64,
}

impl Color {
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "rgb({},{},{})", self.r, self.g, self.b)
    }
}

mod math_utils {
    pub fn hypot(a: f64, b: f64) -> f64 {
        (((a * a) + (b * b))).sqrt()
    }
    pub fn clamp_f(v: f64, lo: f64, hi: f64) -> f64 {
        (lo).max((v).min(hi))
    }
    pub fn circle_area(r: f64) -> f64 {
        ((3.14159 * r) * r)
    }
}

use math_utils::*;

use math_utils::clamp_f;

type Score = i64;

fn greet_full(name: Arc<String>, greeting: Arc<String>) -> Arc<String> {
    Arc::new(format!("{}, {}!", greeting, name))
}

fn countdown(mut n: i64) -> i64 {
    let mut total = 0;
    while (n > 0) {
        total += n;
        n -= 1;
    }
    total
}

struct Point {
    pub x: f64,
    pub y: f64,
}

impl Point {
    pub fn new(x:f64, y:f64) -> Self {
        Point {
            x,
            y,
        }
    }

}

struct Temperature {
    celsius: /* var */ f64,
}

impl Temperature {
    fn fahrenheit(&self) -> f64 {
        (((self.celsius * 9.0) / 5.0) + 32.0)
    }

    fn set_fahrenheit(&mut self, f: f64) {
        self.celsius = (((f - 32.0) * 5.0) / 9.0)
    }

}

struct Counter2 {
    pub value: i64,
}

impl Counter2 {
    pub const MAX: i64 = 100;

    pub fn zero() -> Counter2 {
        Counter2 { value: 0 }
    }

}

struct Profile {
    pub name: Arc<String>,
}

impl Profile {
}

struct User2 {
    pub profile: Option<Profile>,
}

impl User2 {
    pub fn new() -> Self {
        User2 {
            profile: None,
        }
    }

}

struct Pair<T, U> {
    pub first: T,
    pub second: U,
}

impl<T, U> Pair<T, U> {
}

fn describe_val<T: Clone + std::fmt::Display>(x: T) -> Arc<String> {
    Arc::new(format!("value: {}", x))
}

struct TextStats {
    pub text: Arc<String>,
    _length: std::cell::Cell<Option<i64>>,
}

impl TextStats {
    fn length(&self) -> i64 {
        if let Some(cached) = self._length.get() {
            return cached;
        }
        let n = self.text.len() as i64;
        self._length.set(Some(n));
        n
    }

}

async fn compute(n: i64) -> i64 {
    (n * n)
}

async fn log_bg(msg: &str) -> () {
    println!("bg: {}", msg)
}

async fn fetch_add(a: i64, b: i64) -> i64 {
    (a + b)
}

async fn fetch_greet(name: &str) -> Arc<String> {
    Arc::new(format!("hello, {}", name))
}

async fn transform(s: &str) -> Arc<String> {
    Arc::new(format!("done: {}", s))
}

struct Worker {
    pub name: Arc<String>,
    pub jobs: i64,
}

impl Worker {
}

impl Worker {
    async fn run(self: Arc<Self>) -> () {
        println!("worker {} processing {} jobs", self.name, self.jobs)
    }

}


struct SharedCount {
    value: /* var */ i64,
}

impl SharedCount {
    pub fn new() -> Self {
        SharedCount {
            value: 0,
        }
    }

    fn inc(&mut self) -> () {
        self.value += 1
    }

    fn get(&self) -> i64 {
        self.value.clone()
    }

}

async fn run_tasks() -> () {
    let f = tokio::spawn(async move { compute(7).await });
    let result = f.await.unwrap();
    println!("compute(7)={}", result);
    tokio::spawn(async move { log_bg("ping").await });
    let f1 = tokio::spawn(async move { fetch_add(10, 20).await });
    let f2 = tokio::spawn(async move { fetch_greet("world").await });
    println!("fetch_add={}, fetch_greet={}", f1.await.unwrap(), f2.await.unwrap());
    let label: Arc<String> = Arc::new("shared".to_string());
    let ft = tokio::spawn({ let label = Arc::clone(&label); async move { transform(&*label).await } });
    println!("label still: {}", label);
    println!("transform: {}", ft.await.unwrap());
    // let T'shared: read-only Arc<T>, task method receiver is Arc<Self>
    let w: Arc<Worker> = Arc::new(Worker { name: Arc::new("alice".to_string()), jobs: 5 });
    let fw = tokio::spawn({ let w = Arc::clone(&w); async move { w.run().await } });
    println!("w.name={}", w.name);
    fw.await.unwrap();
    // T'actor: Arc<Mutex<T>>, all accesses go through .lock().await
    let mut c: Arc<tokio::sync::Mutex<SharedCount>> = Arc::new(tokio::sync::Mutex::new(SharedCount::new()));
    c.lock().await.inc();
    c.lock().await.inc();
    println!("counter = {}", c.lock().await.value)
}

fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {
    if (x.len() > y.len()) {
        x
    } else {
        y
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // boring language showcase
    // Run with:        boring hello.br
    // Transpile with:  boring --emit-rust hello.br
    // ═══════════════════════════════════════════════════════════════════════════════
    // 1. Bindings
    // ═══════════════════════════════════════════════════════════════════════════════
    let name = "World";
    let x: i64 = 42;
    let mut counter = 0;
    let pi: f64 = 3.14159;
    // Tuple + destructuring
    let pair = (10, 20);
    let (lo, hi) = pair;
    counter += 1;
    println!("name={}, x={}, lo={}, hi={}, counter={}", name, x, lo, hi, counter);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 2. String interpolation & format specifiers
    // ═══════════════════════════════════════════════════════════════════════════════
    let n = 255;
    let ratio = 0.753;
    println!("hex: {:x}, HEX: {:X}, bin: {:b}, oct: {:o}", n, n, n, n);
    println!("float: {:.3}, sci: {:.2e}, sign: {:+.2}", ratio, ratio, ratio);
    println!("padded: '{:8}', zero-pad: '{:08}'", n, n);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 3. Functions
    // ═══════════════════════════════════════════════════════════════════════════════
    // Optional parameter + guard let
    // Default parameter
    // throws — untyped: return type is Result<T, Box<dyn Error>>
    // throws Type — typed error: return type is Result<T, ErrorType>
    let r1 = checked_divide(10, 2).unwrap_or_else(|_| (-1));
    let r2 = checked_divide(10, 0).unwrap_or_else(|_| (-1));
    println!("checked: {}, {}", r1, r2);
    // Generic functions
    // Variadic parameter — last param collects remaining args as an array
    println!("{}, {}, {}, {}", add(3, 4), greet("boring"), display(Some(Arc::new("Alice".to_string()))), display(None));
    println!("say: {}, {}", say(Arc::new("hi".to_string())), say(Arc::new("yo".to_string())));
    println!("identity: {}, {}", identity(42), identity("hi"));
    println!("first: {}", first(vec![10, 20, 30]));
    println!("join: {}", join(", ", vec![Arc::new("a".to_string()), Arc::new("b".to_string()), Arc::new("c".to_string())]));
    println!("sum: {}", sum(vec![1, 2, 3, 4, 5]));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 4. Control flow
    // ═══════════════════════════════════════════════════════════════════════════════
    // if / elif / else as expression — inline and block forms both work
    println!("signs: {}, {}, {}", sign(5), sign((-3)), sign(0));
    // if-let
    let maybe: Option<Arc<String>> = Some(Arc::new("found".to_string()));
    if let Some(v) = maybe {
        println!("if-let: {}", v)
    }
    // guard
    println!("{}, {}", check(5), check((-1)));
    // match — literals, or-patterns, guard, wildcard
    println!("{}, {}, {}, {}", describe(0), describe(2), describe((-5)), describe(99));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 5. Loops
    // ═══════════════════════════════════════════════════════════════════════════════
    // while
    let mut i = 1;
    let mut wsum = 0;
    while (i <= 5) {
        wsum += i;
        i += 1;
    }
    println!("while sum 1..=5 = {}", wsum);
    // for over collection
    for w in vec!["boring", "is", "fun"].iter().cloned() {
        println!("  word: {}", w);
    }
    // for over inclusive range (1..=5 = 1 to 5)
    let mut rsum = 0;
    for k in (1..=5) {
        rsum += k;
    }
    println!("range sum 1..=5 = {}", rsum);
    // for exclusive range — no binding needed, just repeat
    let mut rep = 0;
    for _ in (1..4) {
        rep += 1;
    }
    println!("repeat count = {}", rep);
    // for without variable — omit binding entirely (implicit _)
    let mut ticks = 0;
    for _ in (1..=3) {
        ticks += 1;
    }
    println!("ticks = {}", ticks);
    // loop + break + continue
    let mut acc = 0;
    let mut idx = 0;
    loop {
        idx += 1;
        if ((idx % 2) == 0) {
            continue;
        }
        acc += idx;
        if (idx >= 7) {
            break;
        }
    }
    println!("odd sum 1..7 = {}", acc);
    // do-while
    let mut j = 0;
    loop {
        j += 1;
        if !((j < 3)) { break; }
    }
    println!("do-while j = {}", j);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 6. Collections
    // ═══════════════════════════════════════════════════════════════════════════════
    let numbers = vec![1, 2, 3, 4, 5];
    let doubled = numbers.iter().cloned().map(|n| (n * 2)).collect::<Vec<_>>();
    let evens = numbers.iter().cloned().filter(|n| ((n % 2) == 0)).collect::<Vec<_>>();
    println!("doubled: {:?}", doubled);
    println!("evens: {:?}", evens);
    // Chained transformations
    let big_evens = numbers.iter().cloned().filter(|n| ((n % 2) == 0)).collect::<Vec<_>>().iter().cloned().map(|n| (n * 10)).collect::<Vec<_>>();
    println!("big_evens: {:?}", big_evens);
    // Dict
    let scores: HashMap<Arc<String>, i64> = HashMap::from([(Arc::new("Alice".to_string()), 90), (Arc::new("Bob".to_string()), 85)]);
    println!("Alice: {}, Bob: {}", scores[&Arc::new("Alice".to_string())].clone(), scores[&Arc::new("Bob".to_string())].clone());
    // Set (unordered, deduplicates)
    let unique: HashSet<i64> = HashSet::from([1, 2, 3, 2, 1]);
    println!("set size: {}, contains 2: {}, contains 9: {}", unique.len() as i64, unique.contains(&2), unique.contains(&9));
    // Empty containers
    let empty_arr: Vec<i64> = vec![];
    let empty_map: HashMap<i64, i64> = HashMap::new();
    let empty_set: HashSet<i64> = HashSet::new();
    println!("empty array length: {}", empty_arr.len() as i64);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 7. Structs
    // ═══════════════════════════════════════════════════════════════════════════════
    let v1 = Vec2 { x: 3.0, y: 4.0 };
    let v2 = Vec2 { x: 1.0, y: 0.0 };
    let v3 = v1.add(v2);
    println!("v1={}, len={}", Arc::new(v1.to_string()), v1.len());
    println!("v1+v2={}", Arc::new(v3.to_string()));
    // Mutable field
    let mut ctr = Counter::new();
    ctr.inc();
    ctr.inc();
    ctr.inc();
    println!("counter = {}", ctr.get());
    // ═══════════════════════════════════════════════════════════════════════════════
    // 8. Enums
    // ═══════════════════════════════════════════════════════════════════════════════
    let exprs = vec![Expr::Num(7), Expr::Add(3, 4), Expr::Mul(3, 4)];
    for e in exprs.iter().cloned() {
        println!("eval = {}", eval_expr(e));
    }
    // Enum match with guard
    println!("{}, {}", classify_expr(Expr::Num(0)), classify_expr(Expr::Add(1, 2)));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 9. Traits & conformance
    // ═══════════════════════════════════════════════════════════════════════════════
    let cat = Animal { species: Arc::new("Cat".to_string()), sound: Arc::new("meow".to_string()) };
    let dog = Animal { species: Arc::new("Dog".to_string()), sound: Arc::new("woof".to_string()) };
    println!("{}: {}", cat.name(), cat.describe());
    println!("{}: {}", dog.name(), dog.describe());
    // ext — add methods to an existing type
    println!("cat louder than dog: {}", cat.louder_than(dog));
    // ext with trait conformance
    println!("{}", cat.greet());
    // ═══════════════════════════════════════════════════════════════════════════════
    // 10. Error handling
    // ═══════════════════════════════════════════════════════════════════════════════
    // try-else inline
    let r1 = divide(10, 2).unwrap_or_else(|_| 0);
    let r2 = divide(10, 0).unwrap_or_else(|_| (-1));
    println!("10/2={}, 10/0={}", r1, r2);
    // try-catch block
    println!("parse: {}, {}", safe_parse("42"), safe_parse("bad"));
    // throws + guard
    let content = read_file("data.txt").unwrap_or_else(|_| Arc::new("<missing>".to_string()));
    println!("file: {}", content);
    // try / catch block
    let mut caught: Arc<String> = Arc::new("none".to_string());
    {
        let __try_result: Result<(), Box<dyn std::error::Error>> = (|| -> Result<(), Box<dyn std::error::Error>> {
            try_catch_demo()?;
            Ok(())
        })();
        if let Err(error) = __try_result {
            caught = Arc::new("caught!".to_string())
        }
    }
    println!("try-catch: {}", caught);
    // try / catch with re-use of throwing fn
    let mut result: Arc<String> = Arc::new("ok".to_string());
    {
        let __try_result: Result<(), Box<dyn std::error::Error>> = (|| -> Result<(), Box<dyn std::error::Error>> {
            let _ = divide(5, 0)?;
            Ok(())
        })();
        if let Err(error) = __try_result {
            result = Arc::new("caught divide-by-zero".to_string())
        }
    }
    println!("try-catch divide: {}", result);
    // typed catch — multiple throwing calls, String errors only
    let mut typed_result: Arc<String> = Arc::new("none".to_string());
    {
        let __try_result: Result<(), Box<dyn std::error::Error>> = (|| -> Result<(), Box<dyn std::error::Error>> {
            let q = divide(10, 2)?;
            let content = read_file("notes.txt")?;
            println!("  q={}, content={}", q, content);
            return Err("specific error".into());
            Ok(())
        })();
        if let Err(error) = __try_result {
            /* catch String */
            if true {
                typed_result = Arc::new(format!("string error: {}", error))
            } else {
                typed_result = Arc::new("other error".to_string())
            }
        }
    }
    println!("typed catch: {}", typed_result);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 11. Closures & higher-order
    // ═══════════════════════════════════════════════════════════════════════════════
    // Inline closure — type inferred
    let double = |n| (n * 2);
    let add_one = |n| (n + 1);
    println!("double(7)={}, add_one(7)={}", double(7), add_one(7));
    // Closure with block body
    let classify_n = |n: i64| {     if (n > 0) {
        Arc::new("pos".to_string())
    } else if (n < 0) {
        Arc::new("neg".to_string())
    } else {
        Arc::new("zero".to_string())
    } };
    println!("{}, {}, {}", classify_n(5), classify_n((-1)), classify_n(0));
    // Higher-order function
    println!("apply(double, 21) = {}", apply(double, 21));
    // Pipeline of closures
    let pipeline = vec![double, add_one, double];
    let mut pval = 3;
    for r#fn in pipeline.iter().cloned() {
        pval = r#fn(pval);
    }
    println!("pipeline(3) = {}", pval);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 12. Optionals & nil coalescing
    // ═══════════════════════════════════════════════════════════════════════════════
    let some_val: Option<i64> = Some(42);
    let no_val: Option<i64> = None;
    println!("optional: {}, {}", some_val.unwrap_or_else(|| 0), no_val.unwrap_or_else(|| 0));
    // Struct with optional fields
    let cfg = Config { host: Some(Arc::new("localhost".to_string())), port: Some(8080) };
    let empty_cfg = Config { host: None, port: None };
    // Guard with multiple optional bindings
    println!("{}", connect(cfg));
    println!("{}", connect(empty_cfg));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 13. Tuples
    // ═══════════════════════════════════════════════════════════════════════════════
    let (mn, mx) = minmax(vec![5, 3, 8, 1, 9, 2]);
    println!("min={}, max={}", mn, mx);
    // Nested if as expression — inline else (no colon needed)
    println!("quadrant(1,1)={}, (-1,1)={}", quadrant(1, 1), quadrant((-1), 1));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 14. Type cast
    // ═══════════════════════════════════════════════════════════════════════════════
    let parsed = "42".parse::<i64>().ok().unwrap_or_else(|| (-1));
    let bad = "oops".parse::<i64>().ok().unwrap_or_else(|| (-999));
    let as_flt = (42 as f64);
    let as_str = Arc::new(3.to_string());
    println!("cast: {}, bad={}, float={}, str={}", parsed, bad, as_flt, as_str);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 15. Defer
    // ═══════════════════════════════════════════════════════════════════════════════
    println!("defer: {}", with_cleanup());
    // LIFO — last registered defer runs first
    println!("lifo: {}", lifo());
    // ═══════════════════════════════════════════════════════════════════════════════
    // 16. Macros (Rust interop)
    // ═══════════════════════════════════════════════════════════════════════════════
    println!("macro println: {}", 42);
    assert!(((2 + 2) == 4));
    assert_eq!(add(2, 3), 5);
    let fmsg = format!("{} + {} = {}", 1, 2, add(1, 2));
    println!("format!: {}", fmsg);
    // ═══════════════════════════════════════════════════════════════════════════════
    // 17. Attributes
    // ═══════════════════════════════════════════════════════════════════════════════
    let red = Color { r: 255, g: 0, b: 0 };
    let green = Color { r: 0, g: 255, b: 0 };
    println!("red={}, green={}", Arc::new(red.to_string()), Arc::new(green.to_string()));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 18. Modules & use
    // ═══════════════════════════════════════════════════════════════════════════════
    // Import all public items
    // Import specific items by name
    println!("hypot(3,4) = {}", hypot(3.0, 4.0));
    println!("clamp(12, 0, 10) = {}", clamp_f(12.0, 0.0, 10.0));
    println!("circle area r=5 = {}", circle_area(5.0));
    // Type aliases
    let top: Score = 100;
    let double_it = |x| (x * 2.0);
    println!("score={}, doubled={}", top, double_it(3.5));
    // ═══════════════════════════════════════════════════════════════════════════════
    // 19. Ownership qualifiers (type annotations)
    // ═══════════════════════════════════════════════════════════════════════════════
    // Shorthands (aliases):
    // T        = T'stack      → T            (stack, Rust default)
    // T'       = T'heap       → Box<T>       (exclusive heap ownership)
    // T?       = T'option     → Option<T>    (optional value)
    // str      = String'const → &str         (borrowed string slice)
    // string   = String'shared → Arc<String>  (thread-safe shared)
    // int      = Int'copy     → i64
    // uint     = Uint'copy    → u64
    // float    = Float'copy   → f64
    // bool     = Bool'copy    → bool
    // Other qualifiers:
    // T'auto   = Rc<T>        (single-thread shared reference-count)
    // T'shared = Arc<T>       (multi-thread shared reference-count)
    // T'weak   = Weak<T>      (non-owning smart pointer)
    // T'const  = &'static T   (compile-time constant)
    let owned: Arc<String> = Arc::new("shared".to_string());
    let slice = "constant";
    println!("owned={}, slice={}", owned, slice);
    // ═══════════════════════════════════════════════════════════════════════════════
    // A. Labeled arguments
    // ═══════════════════════════════════════════════════════════════════════════════
    // positional
    let ga1 = greet_full(Arc::new("Alice".to_string()), Arc::new("Hello".to_string()));
    // all labeled, any order
    let ga2 = greet_full(Arc::new("Hi".to_string()), Arc::new("Bob".to_string()));
    // mix: positional then labeled
    let ga3 = greet_full(Arc::new("Carol".to_string()), Arc::new("Hey".to_string()));
    println!("labeled: {}, {}, {}", ga1, ga2, ga3);
    // ═══════════════════════════════════════════════════════════════════════════════
    // B. Mutable parameters
    // ═══════════════════════════════════════════════════════════════════════════════
    println!("countdown(5)={}", countdown(5));
    // ═══════════════════════════════════════════════════════════════════════════════
    // C. do: scoped block
    // ═══════════════════════════════════════════════════════════════════════════════
    let block_result = { let a = 10; let b = (a * 2); (b + 1) };
    println!("do block = {}", block_result);
    // ═══════════════════════════════════════════════════════════════════════════════
    // D. init constructor
    // ═══════════════════════════════════════════════════════════════════════════════
    let p = Point::new(1.0, 2.0);
    println!("point=({}, {})", p.x, p.y);
    // ═══════════════════════════════════════════════════════════════════════════════
    // E. Property getter + setter
    // ═══════════════════════════════════════════════════════════════════════════════
    let mut t = Temperature { celsius: 0.0 };
    println!("0°C = {}°F", t.fahrenheit());
    t.set_fahrenheit(212.0);
    println!("212°F = {}°C", t.celsius);
    // ═══════════════════════════════════════════════════════════════════════════════
    // F. Type-level members
    // ═══════════════════════════════════════════════════════════════════════════════
    let c2 = Counter2::zero();
    println!("Counter2.MAX={}, zero.value={}", Counter2::MAX, c2.value);
    // ═══════════════════════════════════════════════════════════════════════════════
    // G. Optional chaining ?.
    // ═══════════════════════════════════════════════════════════════════════════════
    let alice2 = User2 { profile: Some(Profile { name: Arc::new("Alice".to_string()) }) };
    let ghost = User2 { profile: None };
    println!("alice name: {}", alice2.profile.as_ref().map(|__v| __v.name.clone()).unwrap_or_else(|| Arc::new("none".to_string())));
    println!("ghost name: {}", ghost.profile.as_ref().map(|__v| __v.name.clone()).unwrap_or_else(|| Arc::new("none".to_string())));
    // ═══════════════════════════════════════════════════════════════════════════════
    // H. Generic structs
    // ═══════════════════════════════════════════════════════════════════════════════
    let p2 = Pair { first: 10, second: "hello" };
    println!("{} / {}", p2.first, p2.second);
    // ═══════════════════════════════════════════════════════════════════════════════
    // I. Trait constraints
    // ═══════════════════════════════════════════════════════════════════════════════
    println!("{}", describe_val(3.14));
    println!("{}", describe_val("boring"));
    // ═══════════════════════════════════════════════════════════════════════════════
    // J. Transient fields — lazy / cache pattern
    // ═══════════════════════════════════════════════════════════════════════════════
    // A `transient` field can be written from a `req` (non-mutating) method.
    // This is the Boring way to express lazy initialisation / memoisation.
    // The transpiler maps it to Cell<T> (Copy types) or RefCell<T> (non-Copy types).
    let ts = TextStats { text: Arc::new("hello, world".to_string()), _length: std::cell::Cell::new(None) };
    println!("length = {}", ts.length());
    println!("length = {}", ts.length());
    // ═══════════════════════════════════════════════════════════════════════════════
    // 20. Tasks / async
    // ═══════════════════════════════════════════════════════════════════════════════
    // 20-a: basic async function + spawning + .value
    // 20-b: fire-and-forget detached task helper
    // 20-c: parallel tasks helpers
    // 20-d: data capture helper
    // 20-e: task method on Worker (let T'shared = Arc<T>, read-only shared)
    // 20-f: T'actor = Arc<Mutex<T>> — shared MUTABLE state across tasks
    // All field reads/writes and method calls go through .lock().await automatically.
    // run_tasks is called from the top-level with `task run_tasks()`
    // spawning the task demo from top-level auto-promotes main to async
    let t = tokio::spawn(async move { run_tasks().await });
    t.await.unwrap();
    // ── 21: Explicit lifetimes ──────────────────────────────────────────────────
    // T&a = &'a T  — a borrow with an explicit lifetime.
    // The lifetime 'a appears only in the borrow position: T&a, T'heap&a, etc.
    // It is declared as a type parameter with the <'a> syntax, just like in Rust.
    // 
    // Classic example: both parameters must outlive the returned reference.
    let w1: &str = "long string is long";
    let w2: &str = "short";
    println!("longest: {}", longest(w1, w2));
    println!("\n── all features demonstrated ──");
    Ok(())
}
