// Copyright (C) 2026 Mickaël LANOË
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of Boring.
// Boring is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// See the LICENSE file at the project root for the full text.

// Boring → Linux kernel module transpiler.
//
// Entry point: `transpile_kernel(program)` returns a `KernelTranspileOutput`.
// The generated code targets no_std + the `kernel` crate provided by the
// Linux build system (not tokio).

use crate::ast::{Program, Item, Stmt, ExprKind};

mod helpers;
mod emit_top;
mod emit_stmt;
mod emit_expr;

use helpers::KernelTranspiler;

// ─── Output type ─────────────────────────────────────────────────────────────

pub struct KernelTranspileOutput {
    /// The generated Rust source code.
    pub code: String,
}

// ─── Public entry point ───────────────────────────────────────────────────────

pub fn transpile_kernel(program: &Program) -> KernelTranspileOutput {
    let mut t = KernelTranspiler::new();
    t.emit_kernel_program(program);
    KernelTranspileOutput { code: t.out }
}

// ─── Program emission ─────────────────────────────────────────────────────────

/// Return true if the program contains at least one `task def` function.
fn program_has_task_fns(program: &Program) -> bool {
    program.items.iter().any(|item| match item {
        Item::Fn(f) => f.task,
        Item::Struct(s) => s.methods.iter().any(|m| m.task),
        Item::Enum(e)   => e.methods.iter().any(|m| m.task),
        _ => false,
    })
}

/// Return true if any statement (recursively) contains a `channel<T, N>` call.
fn stmts_have_channel(stmts: &[Stmt]) -> bool {
    stmts.iter().any(stmt_has_channel)
}

fn stmt_has_channel(stmt: &Stmt) -> bool {
    match stmt {
        Stmt::LetDestructure(s) => expr_is_channel(&s.value),
        Stmt::Let(s) => s.value.as_ref().map(|v| expr_is_channel(v)).unwrap_or(false),
        Stmt::Expr(e) => expr_is_channel(e),
        Stmt::If(s) => {
            s.branches.iter().any(|(_, b)| stmts_have_channel(b))
                || s.else_body.as_ref().map(|b| stmts_have_channel(b)).unwrap_or(false)
        }
        Stmt::While(s) => stmts_have_channel(&s.body),
        Stmt::For(s)   => stmts_have_channel(&s.body),
        Stmt::Loop(s)  => stmts_have_channel(&s.body),
        _ => false,
    }
}

fn expr_is_channel(expr: &crate::ast::Expr) -> bool {
    matches!(&expr.kind,
        ExprKind::GenericCall(callee, _, _)
        if matches!(&callee.kind, ExprKind::Var(n) if n == "channel"))
}

/// Return true if the program contains any `channel<T, N>` expression.
fn program_has_channel(program: &Program) -> bool {
    program.items.iter().any(|item| match item {
        Item::Fn(f) => stmts_have_channel(&f.body),
        Item::Struct(s) => s.methods.iter().any(|m| stmts_have_channel(&m.body)),
        Item::Enum(e)   => e.methods.iter().any(|m| stmts_have_channel(&m.body)),
        _ => false,
    })
}

/// Return true if the program contains at least one `stream def` function.
fn program_has_stream(program: &Program) -> bool {
    program.items.iter().any(|item| match item {
        Item::Fn(f) => f.stream,
        Item::Struct(s) => s.methods.iter().any(|m| m.stream),
        Item::Enum(e)   => e.methods.iter().any(|m| m.stream),
        _ => false,
    })
}

impl KernelTranspiler {
    fn emit_kernel_program(&mut self, program: &Program) {
        // Minimal no_std prelude for kernel modules.
        self.line("// Generated by boring --target kernel");
        self.line("#![no_std]");
        self.line("extern crate kernel;");
        self.blank();

        let has_tasks  = program_has_task_fns(program);
        let has_chan   = program_has_channel(program);
        let has_stream = program_has_stream(program);

        // Emit shared `use kernel::prelude::Arc` once if needed by any prelude.
        if has_tasks || has_chan || has_stream {
            self.line("use kernel::prelude::Arc;");
            self.blank();
        }

        // Emit KernelFuture<T> prelude if any task defs are present.
        if has_tasks {
            self.emit_kernel_future_prelude();
        }

        // Emit KernelChan ring-buffer prelude if any channel<T, N> or stream def is used.
        if has_chan || has_stream {
            self.has_channel = true;
            self.has_stream = has_stream;
            self.emit_kernel_chan_prelude();
        }

        for item in &program.items {
            self.emit_item(item);
            self.blank();
        }
    }

    fn emit_kernel_chan_prelude(&mut self) {
        self.line("/// Ring-buffer channel generated by boring channel<T, N>.");
        self.line("pub struct KernelChan<T, const N: usize> {");
        self.indent += 1;
        self.line("buf:       [Option<T>; N],");
        self.line("read_idx:  usize,");
        self.line("write_idx: usize,");
        self.line("count:     usize,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("pub struct KernelSender<T, const N: usize> {");
        self.indent += 1;
        self.line("inner: Arc<kernel::sync::Mutex<KernelChan<T, N>>>,");
        self.line("not_empty: Arc<kernel::sync::CondVar>,");
        self.line("not_full:  Arc<kernel::sync::CondVar>,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("pub struct KernelReceiver<T, const N: usize> {");
        self.indent += 1;
        self.line("inner: Arc<kernel::sync::Mutex<KernelChan<T, N>>>,");
        self.line("not_empty: Arc<kernel::sync::CondVar>,");
        self.line("not_full:  Arc<kernel::sync::CondVar>,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl<T, const N: usize> KernelSender<T, N> {");
        self.indent += 1;
        self.line("pub fn send(&self, value: T) {");
        self.indent += 1;
        self.line("let mut guard = self.inner.lock();");
        self.line("self.not_full.wait_while(&mut guard, |c| c.count == N);");
        self.line("guard.buf[guard.write_idx] = Some(value);");
        self.line("guard.write_idx = (guard.write_idx + 1) % N;");
        self.line("guard.count += 1;");
        self.line("self.not_empty.notify_one();");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl<T, const N: usize> KernelReceiver<T, N> {");
        self.indent += 1;
        self.line("pub fn recv(&self) -> T {");
        self.indent += 1;
        self.line("let mut guard = self.inner.lock();");
        self.line("self.not_empty.wait_while(&mut guard, |c| c.count == 0);");
        self.line("let value = guard.buf[guard.read_idx].take().unwrap();");
        self.line("guard.read_idx = (guard.read_idx + 1) % N;");
        self.line("guard.count -= 1;");
        self.line("self.not_full.notify_one();");
        self.line("value");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("fn kernel_channel<T, const N: usize>() -> (KernelSender<T, N>, KernelReceiver<T, N>) {");
        self.indent += 1;
        self.line("let inner = Arc::new(kernel::sync::Mutex::new(KernelChan {");
        self.indent += 1;
        self.line("buf: [const { None }; N],");
        self.line("read_idx: 0,");
        self.line("write_idx: 0,");
        self.line("count: 0,");
        self.indent -= 1;
        self.line("}));");
        self.line("let not_empty = Arc::new(kernel::sync::CondVar::new());");
        self.line("let not_full  = Arc::new(kernel::sync::CondVar::new());");
        self.line("(");
        self.indent += 1;
        self.line("KernelSender  { inner: Arc::clone(&inner), not_empty: Arc::clone(&not_empty), not_full: Arc::clone(&not_full) },");
        self.line("KernelReceiver { inner, not_empty, not_full },");
        self.indent -= 1;
        self.line(")");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_kernel_future_prelude(&mut self) {
        self.line("/// Blocking handle returned by `task def` functions.");
        self.line("pub struct KernelFuture<T> {");
        self.indent += 1;
        self.line("result: Arc<kernel::sync::Mutex<Option<Result<T, kernel::error::Error>>>>,");
        self.line("done_cond: Arc<kernel::sync::CondVar>,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl<T> KernelFuture<T> {");
        self.indent += 1;
        self.line("pub fn done(&self) -> bool {");
        self.indent += 1;
        self.line("match self.result.try_lock() {");
        self.indent += 1;
        self.line("Ok(guard) => guard.is_some(),");
        self.line("Err(_) => false,");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("pub fn wait(self) -> Result<T, kernel::error::Error> {");
        self.indent += 1;
        self.line("let mut guard = self.result.lock();");
        self.line("self.done_cond.wait_while(&mut guard, |r| r.is_none());");
        self.line("guard.take().unwrap()");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }
}
