// Generated by boring build --target wgpu.
// Do not edit -- re-generate with: boring build --target wgpu

use wgpu::util::DeviceExt;
use bytemuck::{Pod, Zeroable};

static __BORING_SHADER_MODULE: std::sync::OnceLock<wgpu::ShaderModule> = std::sync::OnceLock::new();

static VECTORADD_PIPELINE: std::sync::OnceLock<std::sync::Arc<wgpu::ComputePipeline>> = std::sync::OnceLock::new();

struct VectorAdd {
    device: std::sync::Arc<wgpu::Device>,
    queue: std::sync::Arc<wgpu::Queue>,
    pipeline: std::sync::Arc<wgpu::ComputePipeline>,
    bind_group: wgpu::BindGroup,
    a_buf: std::sync::Arc<wgpu::Buffer>,
    b_buf: std::sync::Arc<wgpu::Buffer>,
    result_buf: std::sync::Arc<wgpu::Buffer>,
    result: Vec<i32>,
}

impl VectorAdd {
    fn new(device: std::sync::Arc<wgpu::Device>, queue: std::sync::Arc<wgpu::Queue>) -> Self {

        let a_buf = std::sync::Arc::new(device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        }));
        let b_buf = std::sync::Arc::new(device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        }));
        let result_buf = std::sync::Arc::new(device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        }));

        let pipeline = VECTORADD_PIPELINE.get_or_init(|| {
            let shader = __BORING_SHADER_MODULE.get_or_init(|| {
                device.create_shader_module(wgpu::ShaderModuleDescriptor {
                    label: None,
                    source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/main.wgsl").into()),
                })
            });
            std::sync::Arc::new(device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: None,
                layout: None,
                module: shader,
                entry_point: "VectorAdd_main",
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                cache: None,
            }))
        }).clone();

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &pipeline.get_bind_group_layout(0),
            entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: a_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: b_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: result_buf.as_entire_binding() },
            ],
        });

        VectorAdd {
            device: std::sync::Arc::clone(&device),
            queue: std::sync::Arc::clone(&queue),
            pipeline,
            bind_group,
            a_buf,
            b_buf,
            result_buf,
            result: vec![i32::default(); 0],
        }
    }

    fn rebuild_bind_group(&mut self) {
        let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();
        entries.push(wgpu::BindGroupEntry { binding: 0, resource: self.a_buf.as_entire_binding() });
        entries.push(wgpu::BindGroupEntry { binding: 1, resource: self.b_buf.as_entire_binding() });
        entries.push(wgpu::BindGroupEntry { binding: 2, resource: self.result_buf.as_entire_binding() });
        self.bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &self.pipeline.get_bind_group_layout(0),
            entries: &entries,
        });
    }

    fn dispatch(&self, gx: u32, gy: u32, gz: u32) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.device.push_error_scope(wgpu::ErrorFilter::OutOfMemory);
        self.device.push_error_scope(wgpu::ErrorFilter::Validation);

        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
        {
            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });
            cpass.set_pipeline(&self.pipeline);
            cpass.set_bind_group(0, &self.bind_group, &[]);
            cpass.dispatch_workgroups(gx, gy, gz);
        }
        self.queue.submit(std::iter::once(encoder.finish()));
        if pollster::block_on(self.device.pop_error_scope()).is_some() {
            let _ = pollster::block_on(self.device.pop_error_scope());
            return Err(Box::new(BoringError::Other(std::any::TypeId::of::<GpuError>(), Box::new(GpuError::LaunchError) as Box<dyn BoringVal + Send + Sync>)));
        }
        if pollster::block_on(self.device.pop_error_scope()).is_some() {
            return Err(Box::new(BoringError::Other(std::any::TypeId::of::<GpuError>(), Box::new(GpuError::OutOfMemory) as Box<dyn BoringVal + Send + Sync>)));
        }
        Ok(())
    }

    fn copy_a_to_host(&self) -> Vec<i32> {
        __boring_gpu_copy_d2h::<i32>(&self.device, &self.queue, &self.a_buf)
    }
    fn copy_a_to_device(&mut self, data: &[i32]) {
        let needed = (data.len() * std::mem::size_of::<i32>()) as u64;
        if self.a_buf.size() != needed {
            self.a_buf = std::sync::Arc::new(self.device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size: needed,
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }));
            self.rebuild_bind_group();
        }
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.a_buf);
    }

    fn copy_b_to_host(&self) -> Vec<i32> {
        __boring_gpu_copy_d2h::<i32>(&self.device, &self.queue, &self.b_buf)
    }
    fn copy_b_to_device(&mut self, data: &[i32]) {
        let needed = (data.len() * std::mem::size_of::<i32>()) as u64;
        if self.b_buf.size() != needed {
            self.b_buf = std::sync::Arc::new(self.device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size: needed,
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }));
            self.rebuild_bind_group();
        }
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.b_buf);
    }

    fn copy_result_to_host(&self) -> Vec<i32> {
        __boring_gpu_copy_d2h::<i32>(&self.device, &self.queue, &self.result_buf)
    }
    fn copy_result_to_device(&mut self, data: &[i32]) {
        let needed = (data.len() * std::mem::size_of::<i32>()) as u64;
        if self.result_buf.size() != needed {
            self.result_buf = std::sync::Arc::new(self.device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size: needed,
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }));
            self.rebuild_bind_group();
        }
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.result_buf);
    }

}

#[allow(dead_code)]
#[derive(Clone)]
enum BoringGpuArg<T> {
    Resident(std::sync::Arc<wgpu::Buffer>, usize),
    Host(Vec<T>),
}

#[allow(dead_code)]
impl<T> BoringGpuArg<T> {
    fn len(&self) -> usize {
        match self {
            BoringGpuArg::Resident(_, len) => *len,
            BoringGpuArg::Host(v) => v.len(),
        }
    }
}

thread_local! {
    static __BORING_STAGING_POOL: std::cell::RefCell<Vec<wgpu::Buffer>> = std::cell::RefCell::new(Vec::new());
}

fn __boring_gpu_copy_d2h<T: bytemuck::Pod>(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> Vec<T> {
    let size = src.size();
    let staging = __BORING_STAGING_POOL.with(|pool| {
        let mut pool = pool.borrow_mut();
        match pool.iter().position(|b| b.size() == size) {
            Some(i) => pool.swap_remove(i),
            None => device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size,
                usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }),
        }
    });
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(src, 0, &staging, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
    device.poll(wgpu::MaintainBase::Wait);
    let slice = staging.slice(..);
    let (tx, rx) = std::sync::mpsc::channel();
    slice.map_async(wgpu::MapMode::Read, move |r| { tx.send(r).unwrap(); });
    device.poll(wgpu::MaintainBase::Wait);
    rx.recv().unwrap().unwrap();
    let data = bytemuck::cast_slice(&staging.slice(..).get_mapped_range()).to_vec();
    staging.unmap();
    __BORING_STAGING_POOL.with(|pool| pool.borrow_mut().push(staging));
    data
}

fn __boring_gpu_copy_h2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &[u8], dst: &wgpu::Buffer) {
    let size = src.len() as u64;
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::MAP_WRITE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: true,
    });
    staging.slice(..).get_mapped_range_mut().copy_from_slice(src);
    staging.unmap();
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(&staging, 0, dst, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
}

fn __boring_gpu_copy_d2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> std::sync::Arc<wgpu::Buffer> {
    let size = src.size();
    let dst = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(src, 0, &dst, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
    std::sync::Arc::new(dst)
}

static __BORING_GPU_DEVICE: std::sync::OnceLock<std::sync::Arc<wgpu::Device>> = std::sync::OnceLock::new();
static __BORING_GPU_QUEUE: std::sync::OnceLock<std::sync::Arc<wgpu::Queue>> = std::sync::OnceLock::new();
fn __boring_gpu_device() -> std::sync::Arc<wgpu::Device> { std::sync::Arc::clone(__BORING_GPU_DEVICE.get().expect("GPU device not initialized")) }
fn __boring_gpu_queue() -> std::sync::Arc<wgpu::Queue> { std::sync::Arc::clone(__BORING_GPU_QUEUE.get().expect("GPU queue not initialized")) }

static __BORING_GPU_ADAPTERS: std::sync::OnceLock<Vec<std::sync::Arc<wgpu::Adapter>>> = std::sync::OnceLock::new();
fn __boring_gpu_adapter(idx: usize) -> std::sync::Arc<wgpu::Adapter> {
    let adapters = __BORING_GPU_ADAPTERS.get().expect("GPU adapters not initialized");
    adapters.get(idx).map(std::sync::Arc::clone)
        .unwrap_or_else(|| panic!("GPU({}) out of range -- {} adapter(s) found", idx, adapters.len()))
}
fn __boring_gpu_all() -> Vec<usize> {
    (0..__BORING_GPU_ADAPTERS.get().map(|a| a.len()).unwrap_or(0)).collect()
}
fn __boring_gpu_name(idx: usize) -> String { __boring_gpu_adapter(idx).get_info().name }
fn __boring_gpu_total_mem(_idx: usize) -> i64 { 0 }
fn __boring_gpu_free_mem(_idx: usize) -> i64 { 0 }
fn __boring_gpu_compute_capability(_idx: usize) -> Vec<i64> { vec![0, 0] }
fn __boring_gpu_warp_size(_idx: usize) -> i64 { 32 }
fn __boring_gpu_max_threads(idx: usize) -> i64 { __boring_gpu_adapter(idx).limits().max_compute_invocations_per_workgroup as i64 }
fn __boring_gpu_max_shared_mem(idx: usize) -> i64 { __boring_gpu_adapter(idx).limits().max_compute_workgroup_storage_size as i64 }

// Generated by boring build
use std::collections::{HashMap, HashSet};
use std::hash::Hash;
use std::rc::{Rc, Weak};
use std::sync::Arc;
use std::sync::{Mutex, RwLock};
use std::f64::consts::{PI, E, TAU};
use std::time::Duration;

trait BoringArrayIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Vec<Self::Item>;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone> BoringArrayIndex for Vec<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Vec<T> {
        let mut v = self.clone();
        if let Some(i) = i { if i < v.len() { v.remove(i); } }
        v
    }
    fn get_at(&self, i: Option<usize>) -> T {
        self[i.expect("get_at called with no index (empty collection or exhausted cursor)")].clone()
    }
}
trait BoringDictIndex<K: Clone + Eq + std::hash::Hash, V: Clone> {
    fn first_index(&self) -> Option<K>;
    fn next_index(&self, k: K) -> Option<K>;
    fn remove_at(&self, k: Option<K>) -> Self where Self: Sized;
}
impl<K: Clone + Eq + std::hash::Hash, V: Clone> BoringDictIndex<K, V> for HashMap<K, V> {
    fn first_index(&self) -> Option<K> { self.keys().next().cloned() }
    fn next_index(&self, k: K) -> Option<K> {
        let keys: Vec<_> = self.keys().collect();
        let pos = keys.iter().position(|kk| *kk == &k);
        pos.and_then(|p| keys.get(p + 1)).map(|kk| (*kk).clone())
    }
    fn remove_at(&self, k: Option<K>) -> Self { let mut m = self.clone(); if let Some(k) = k { m.remove(&k); } m }
}
trait BoringSetIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Self where Self: Sized;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone + Eq + std::hash::Hash> BoringSetIndex for HashSet<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Self {
        let elem = i.and_then(|i| self.iter().nth(i).cloned());
        let mut s = self.clone();
        if let Some(e) = elem { s.remove(&e); }
        s
    }
    fn get_at(&self, i: Option<usize>) -> T {
        let i = i.expect("get_at called with no index (empty collection or exhausted cursor)");
        self.iter().nth(i).cloned().expect("get_at index out of range")
    }
}

// BoringFmt — displays Vec<T: Display> as [a, b, c] (no debug quotes on strings).
struct BoringFmt<'a, T: std::fmt::Display>(pub &'a [T]);
impl<'a, T: std::fmt::Display> std::fmt::Display for BoringFmt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.0.iter().enumerate() {
            if i > 0 { write!(f, ", ")?; }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

// BoringVal — bridge trait that gives BoringError::Other both Display and Any (downcast).
// Every user-defined error enum automatically satisfies the blanket impl below.
trait BoringVal: std::fmt::Display + std::any::Any + Send + Sync {
    fn as_any(&self) -> &dyn std::any::Any;
}
impl<T: std::fmt::Display + std::any::Any + Send + Sync + 'static> BoringVal for T {
    fn as_any(&self) -> &dyn std::any::Any { self }
}
impl std::fmt::Debug for dyn BoringVal + Send + Sync {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "BoringVal({})", self)
    }
}

// BoringError — typed exception wrapper so `catch String:` / `catch Int:` / `catch MyError:` can dispatch.
// `Other(TypeId, error)` identifies the thrown type uniquely across modules via std::any::TypeId::of::<T>(),
// which requires no instance — fully collision-free even when two modules define identically-named types.
//
// `Scalar(ScalarKind, u128)` is the fixed-width numeric family's own path —
// int8..int128, uint8..uint128, and float32 — kept OUT of `Other` on purpose
// (docs/float-width-types.md §7): the compiler already knows, statically,
// that a thrown value here is exactly one of eleven small Copy kinds, so
// paying for a heap allocation + `dyn Any` downcast the way `Other` does for
// arbitrary user enums/structs would be pure overhead. The raw bits are
// reinterpreted per `kind` in `Display` below and at each `catch` arm —
// sign/zero-extended into the shared `u128` slot on the way in, truncated (or
// bit-reinterpreted, for float32) back to the exact original type on the way
// out; this round-trips exactly, it never touches `Other`'s TypeId machinery
// at all. `float`/`float64` deliberately stay on their own pre-existing
// `BoringError::Float(f64)` fast path instead of joining `Scalar` — unlike
// the other eleven kinds, they already had a dedicated, no-allocation
// representation before this family existed, and giving them a second,
// parallel one here would only create two disjoint representations for the
// same type with no single `catch` spelling reliably catching both (a literal
// float throw and a `float64`-typed variable throw would land in different
// variants). `Other` still exists, narrowed to what only it can do: genuine
// user-defined enums/structs the compiler can't enumerate in advance.
#[derive(Debug, Clone, Copy, PartialEq)]
enum ScalarKind { Int8, Int16, Int32, Int64, Int128, Uint8, Uint16, Uint32, Uint64, Uint128, Float32 }
impl BoringError {
    fn scalar_i8(v: i8) -> Self { BoringError::Scalar(ScalarKind::Int8, v as i128 as u128) }
    fn scalar_i16(v: i16) -> Self { BoringError::Scalar(ScalarKind::Int16, v as i128 as u128) }
    fn scalar_i32(v: i32) -> Self { BoringError::Scalar(ScalarKind::Int32, v as i128 as u128) }
    fn scalar_i64(v: i64) -> Self { BoringError::Scalar(ScalarKind::Int64, v as i128 as u128) }
    fn scalar_i128(v: i128) -> Self { BoringError::Scalar(ScalarKind::Int128, v as u128) }
    fn scalar_u8(v: u8) -> Self { BoringError::Scalar(ScalarKind::Uint8, v as u128) }
    fn scalar_u16(v: u16) -> Self { BoringError::Scalar(ScalarKind::Uint16, v as u128) }
    fn scalar_u32(v: u32) -> Self { BoringError::Scalar(ScalarKind::Uint32, v as u128) }
    fn scalar_u64(v: u64) -> Self { BoringError::Scalar(ScalarKind::Uint64, v as u128) }
    fn scalar_u128(v: u128) -> Self { BoringError::Scalar(ScalarKind::Uint128, v) }
    fn scalar_f32(v: f32) -> Self { BoringError::Scalar(ScalarKind::Float32, v.to_bits() as u128) }
}
#[derive(Debug)]
enum BoringError {
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(&'static str),
    String(Arc<str>),
    Scalar(ScalarKind, u128),
    Other(std::any::TypeId, std::boxed::Box<dyn BoringVal + Send + Sync>),
}
impl std::fmt::Display for BoringError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            BoringError::Int(n)         => write!(f, "{}", n),
            BoringError::Float(n)       => write!(f, "{}", n),
            BoringError::Bool(b)        => write!(f, "{}", b),
            BoringError::Str(s)         => write!(f, "{}", s),
            BoringError::String(s)      => write!(f, "{}", s),
            BoringError::Scalar(k, bits) => match k {
                ScalarKind::Int8    => write!(f, "{}", *bits as i128 as i8),
                ScalarKind::Int16   => write!(f, "{}", *bits as i128 as i16),
                ScalarKind::Int32   => write!(f, "{}", *bits as i128 as i32),
                ScalarKind::Int64   => write!(f, "{}", *bits as i128 as i64),
                ScalarKind::Int128  => write!(f, "{}", *bits as i128),
                ScalarKind::Uint8   => write!(f, "{}", *bits as u8),
                ScalarKind::Uint16  => write!(f, "{}", *bits as u16),
                ScalarKind::Uint32  => write!(f, "{}", *bits as u32),
                ScalarKind::Uint64  => write!(f, "{}", *bits as u64),
                ScalarKind::Uint128 => write!(f, "{}", *bits),
                ScalarKind::Float32 => write!(f, "{}", f32::from_bits(*bits as u32)),
            },
            BoringError::Other(_, e)    => write!(f, "{}", e),
        }
    }
}
impl std::error::Error for BoringError {}

// Boring standard error enum — always available without import.
// Use `throw Error.Expired` / `catch Error:` / `match err: Error.Expired: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum Error {
    Expired,
    Cancelled,
    NotFound,
    InvalidInput,
    OutOfBounds,
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::Expired      => write!(f, "timeout expired"),
            Error::Cancelled    => write!(f, "task cancelled"),
            Error::NotFound     => write!(f, "not found"),
            Error::InvalidInput => write!(f, "invalid input"),
            Error::OutOfBounds  => write!(f, "index out of bounds"),
        }
    }
}
impl std::error::Error for Error {}

// Boring GPU error enum — thrown by kernel dispatch on a device-side
// failure. Always available without import. Currently wired up on the
// wgpu target only (its host codegen shares this same general pipeline);
// cuda/rocm/metal report GPU failures as plain string-message errors
// instead of this typed enum -- see `docs/gpu-module.md`'s error-handling
// notes for why (their host transpilers don't share this prelude).
// Use `catch GpuError.OutOfMemory:` / `match err: GpuError.Timeout: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum GpuError {
    LaunchError,
    OutOfMemory,
    IllegalAccess,
    StackOverflow,
    Timeout,
    DeviceLost,
}
impl std::fmt::Display for GpuError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            GpuError::LaunchError   => write!(f, "GPU kernel launch failed"),
            GpuError::OutOfMemory   => write!(f, "GPU out of memory"),
            GpuError::IllegalAccess => write!(f, "GPU illegal memory access"),
            GpuError::StackOverflow => write!(f, "GPU stack overflow"),
            GpuError::Timeout       => write!(f, "GPU operation timed out"),
            GpuError::DeviceLost    => write!(f, "GPU device lost"),
        }
    }
}
impl std::error::Error for GpuError {}

const N: i64 = 1000;


fn boring_main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // GPU vector addition — Boring with CUDA/Metal backend
    let mut host_a: Vec<isize> = (0..(N as usize)).map(|__boring_i| { let i = __boring_i as isize; i }).collect::<Vec<_>>();
    let mut host_b: Vec<isize> = (0..(N as usize)).map(|__boring_i| { let i = __boring_i as isize; (i * 2) }).collect::<Vec<_>>();
    let mut k = VectorAdd::new(__boring_gpu_device(), __boring_gpu_queue());
    k.copy_a_to_device(&host_a.iter().map(|&x| x as i32).collect::<Vec<i32>>());
    k.copy_b_to_device(&host_b.iter().map(|&x| x as i32).collect::<Vec<i32>>());
    k.copy_result_to_device(&vec![(0) as i32; (N) as usize]);
    k.dispatch((1) as u32, (1) as u32, (1) as u32)?;
    // `k.result[i]` alone would read the whole buffer back from the GPU on every
    // iteration of this loop. Binding it through an alias and reading it inside a
    // `with` block materializes it exactly once instead — see
    // docs/scoped-access-blocks.md. The `'gpu'unified` qualifier is inferred here
    // from `k.result` itself being declared `'unified` above; no annotation needed.
    {
        let result = k.copy_result_to_host().iter().map(|&x| x as i64).collect::<Vec<i64>>();
        for i in (0..N) {
            println!("c[{}] = {}", i, result[(i) as usize].clone());
        }
    }
    Ok(())
}

fn main() {
    pollster::block_on(async_main());
}

async fn async_main() {
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());
    let adapter = instance.request_adapter(&wgpu::RequestAdapterOptions::default()).await.expect("No GPU adapter found");
    let (device, queue) = adapter.request_device(&wgpu::DeviceDescriptor::default(), None).await.expect("Failed to create device");
    device.poll(wgpu::MaintainBase::Wait);
    device.on_uncaptured_error(Box::new(|e| eprintln!("boring: uncaptured GPU error: {}", e)));
    let device = std::sync::Arc::new(device);
    let queue = std::sync::Arc::new(queue);
    let _ = __BORING_GPU_DEVICE.set(std::sync::Arc::clone(&device));
    let _ = __BORING_GPU_QUEUE.set(std::sync::Arc::clone(&queue));
    let adapter = std::sync::Arc::new(adapter);
    let __boring_primary_info = adapter.get_info();
    let mut __boring_gpu_adapters: Vec<std::sync::Arc<wgpu::Adapter>> = vec![std::sync::Arc::clone(&adapter)];
    for __boring_other in instance.enumerate_adapters(wgpu::Backends::all()) {
        if __boring_other.get_info() != __boring_primary_info {
            __boring_gpu_adapters.push(std::sync::Arc::new(__boring_other));
        }
    }
    let _ = __BORING_GPU_ADAPTERS.set(__boring_gpu_adapters);

    if let Err(e) = boring_main() {
        eprintln!("error: {}", e);
        std::process::exit(1);
    }
}
