// Generated by boring build --target wgpu.

struct Dimension {
    width: u32,
    height: u32,
}

// ─── kernel MatrixMul ───

@group(0) @binding(0) var<storage, read> a: array<f32>;
@group(0) @binding(1) var<storage, read> b: array<f32>;
@group(0) @binding(2) var<storage, read_write> c: array<f32>;
struct MatrixMulParams {
    dim_w: u32,
    dim_h: u32,
}
@group(0) @binding(3) var<uniform> __params: MatrixMulParams;


override block_x: u32 = 1;
override block_y: u32 = 1;
override block_z: u32 = 1;

@compute @workgroup_size(block_x, block_y, block_z)
fn MatrixMul_main(
    @builtin(local_invocation_id)   __tid:  vec3<u32>,
    @builtin(workgroup_id)           __bid:  vec3<u32>,
    @builtin(local_invocation_size) __bdim: vec3<u32>,
    @builtin(num_workgroups)         __gdim: vec3<u32>,
) {
    let dim: Dimension = Dimension(__params.dim_w, __params.dim_h);
    let row = ((i32(__bid.y) * i32(__bdim.y)) + i32(__tid.y));
    let col = ((i32(__bid.x) * i32(__bdim.x)) + i32(__tid.x));
    if (((row < 32) && (col < 32))) {
        var sum: f32 = 0.0;
        var k: i32 = 0;
        loop {
            if !(k < 32) { break; }
            sum = (sum + (a[u32(((row * 32) + k))] * b[u32(((k * 32) + col))]));
            k = k + 1;
        }
        c[u32(((row * 32) + col))] = sum;
    }
}

