// Generated by boring build --target metal.

use metal::*;
use std::mem;

const BORING_MSL: &str = include_str!("../kernels/main.metal");

fn boring_metal_device() -> Device {
    Device::system_default().expect("no Metal device found — macOS 10.14+ required")
}

fn boring_metal_device_n(idx: usize) -> Result<Device, Box<dyn std::error::Error>> {
    let devices = Device::all();
    devices.into_iter().nth(idx)
        .ok_or_else(|| format!("GPU index {} out of range", idx).into())
}

fn boring_gpu_family(device: &Device) -> Vec<i64> {
    let families: &[(MTLGPUFamily, [i64; 2])] = &[
        (MTLGPUFamily::Apple9, [9, 0]),
        (MTLGPUFamily::Apple8, [8, 0]),
        (MTLGPUFamily::Apple7, [7, 0]),
        (MTLGPUFamily::Apple6, [6, 0]),
        (MTLGPUFamily::Apple5, [5, 0]),
        (MTLGPUFamily::Apple4, [4, 0]),
        (MTLGPUFamily::Apple3, [3, 0]),
        (MTLGPUFamily::Apple2, [2, 0]),
        (MTLGPUFamily::Apple1, [1, 0]),
    ];
    for (family, ver) in families {
        if device.supports_family(*family) { return ver.to_vec(); }
    }
    vec![0, 0]
}

struct KernelHandle<T> { inner: T }
impl<T> KernelHandle<T> {
    fn wait(self) -> T { self.inner }
    fn done(&self) -> bool { true }
}

struct Saxpy {
    __device: Device,
    __queue: CommandQueue,
    __pipeline: ComputePipelineState,
    alpha: f32,
    x: Buffer,
    y: Buffer,
}

impl Saxpy {
    fn new(__device: Device, a: f32, xs: Vec<f32>, ys: Vec<f32>) -> Result<Self, Box<dyn std::error::Error>> {
        let __queue = __device.new_command_queue();
        let __options = CompileOptions::new();
        let __library = __device.new_library_with_source(BORING_MSL, &__options)
            .map_err(|e| format!("MSL compile error: {}", e))?;
        let __func = __library.get_function("Saxpy_kernel", None)
            .map_err(|e| format!("kernel function not found: {}", e))?;
        let __pipeline = __device.new_compute_pipeline_state_with_function(&__func)?;
        let alpha: f32 = a;
        let x: Buffer = __device.new_buffer_with_data(xs.as_ptr() as *const _, (xs.len() * mem::size_of::<f32>()) as u64, MTLResourceOptions::StorageModeShared);
        let y: Buffer = __device.new_buffer_with_data(ys.as_ptr() as *const _, (ys.len() * mem::size_of::<f32>()) as u64, MTLResourceOptions::StorageModeShared);
        Ok(Saxpy {
            __device,
            __queue,
            __pipeline,
            alpha,
            x,
            y,
        })
    }

    fn read_x(&self) -> Vec<f32> {
        let n = self.x.length() as usize / mem::size_of::<f32>();
        let ptr = self.x.contents() as *const f32;
        unsafe { std::slice::from_raw_parts(ptr, n).to_vec() }
    }

    fn read_y(&self) -> Vec<f32> {
        let n = self.y.length() as usize / mem::size_of::<f32>();
        let ptr = self.y.contents() as *const f32;
        unsafe { std::slice::from_raw_parts(ptr, n).to_vec() }
    }

    fn __boring_launch(self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, _after: &[()]) -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {
        let grid_dim = grid_dim.unwrap_or_else(|| {
            let n = (self.x.length() as usize / mem::size_of::<f32>()) as u32;
            ((n + block_dim.0 - 1) / block_dim.0, 1, 1)
        });
        let __cmd_buf = self.__queue.new_command_buffer();
        let __encoder = __cmd_buf.new_compute_command_encoder();
        __encoder.set_compute_pipeline_state(&self.__pipeline);
        __encoder.set_buffer(0, Some(&self.x), 0);
        __encoder.set_buffer(1, Some(&self.y), 0);
        __encoder.set_bytes(2, mem::size_of::<f32>() as u64, &self.alpha as *const _ as *const _);
        __encoder.dispatch_thread_groups(
            MTLSize { width: grid_dim.0 as u64, height: grid_dim.1 as u64, depth: grid_dim.2 as u64 },
            MTLSize { width: block_dim.0 as u64, height: block_dim.1 as u64, depth: block_dim.2 as u64 },
        );
        __encoder.end_encoding();
        __cmd_buf.commit();
        __cmd_buf.wait_until_completed();
        Ok(KernelHandle { inner: self })
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let N = 16;
    let alpha = 2.0;
    let g = boring_metal_device_n(0 as usize)?;
    println!("Device : {}", g.name().to_string());
    println!("Memory : {} GB", (g.recommended_max_working_set_size() as i64 / 1073741824));
    let mut x: Vec<f32> = vec![0.0; N as usize];
    let mut y: Vec<f32> = vec![1.0; N as usize];
    for i in 0..N {
        x[i as usize] = (i as f32);
    }
    let mut k = Saxpy::new(boring_metal_device(), alpha, x, y)?;
    let mut k = k.__boring_launch((N as u32, 1, 1), None, &[])?.wait();
    println!("{}", "Results (expected: y[i] = 2*i + 1):");
    for (i, v) in k.read_y().iter().enumerate() {
        println!("  y[{}] = {}", i, v);
    }
    Ok(())
}
