// Generated by boring build --target cuda.

use cudarc::driver::{CudaContext, CudaModule, CudaFunction, CudaSlice, CudaStream, LaunchConfig};
use cudarc::nvrtc::Ptx;
use std::sync::{Arc, OnceLock};

static BORING_PTX: &str = include_str!(env!("BORING_PTX_PATH"));

static BORING_CTX: OnceLock<Arc<CudaContext>> = OnceLock::new();
static BORING_MODULE: OnceLock<Arc<CudaModule>> = OnceLock::new();

fn boring_gpu_ctx() -> Arc<CudaContext> {
    Arc::clone(BORING_CTX.get().expect("boring_gpu_init() not called"))
}

fn boring_gpu_init() -> Result<(), Box<dyn std::error::Error>> {
    let ctx = Arc::new(CudaContext::new(0)?);
    let ptx = Ptx::from_src(BORING_PTX);
    let module = Arc::new(ctx.load_module(ptx)?);
    let _ = BORING_CTX.set(ctx);
    let _ = BORING_MODULE.set(module);
    Ok(())
}

fn boring_gpu_ctx_n(idx: usize) -> Result<Arc<CudaContext>, Box<dyn std::error::Error>> {
    Ok(Arc::new(CudaContext::new(idx)?))
}

struct KernelHandle<T> { inner: T, stream: Arc<CudaStream> }
impl<T> KernelHandle<T> {
    fn wait(self) -> Result<T, Box<dyn std::error::Error>> {
        self.stream.synchronize()?;
        Ok(self.inner)
    }
    fn done(&self) -> bool { true }
}

struct Saxpy {
    __ctx: Arc<CudaContext>,
    __stream: Arc<CudaStream>,
    alpha: CudaSlice<f64>,
    x: CudaSlice<f64>,
    y: CudaSlice<f64>,
}

impl Saxpy {
    fn new(__ctx: Arc<CudaContext>, a: f64, xs: Vec<f64>, ys: Vec<f64>) -> Result<Self, Box<dyn std::error::Error>> {
        let alpha = __ctx.default_stream().clone_htod::<f64>(&a)?;
        let x = __ctx.default_stream().clone_htod::<f64>(&xs)?;
        let y = __ctx.default_stream().clone_htod::<f64>(&ys)?;
        Ok(Saxpy {
            __ctx,
            __stream: __ctx.default_stream(),
            alpha,
            x,
            y,
        })
    }

    fn read_x(&self) -> Result<Vec<f64>, Box<dyn std::error::Error>> {
        Ok(self.__stream.clone_dtoh(&self.x)?)
    }

    fn read_y(&self) -> Result<Vec<f64>, Box<dyn std::error::Error>> {
        Ok(self.__stream.clone_dtoh(&self.y)?)
    }

    fn __boring_launch(mut self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, after: &[&Arc<CudaStream>]) -> Result<KernelHandle<Self>, Box<dyn std::error::Error>> {
        let grid_dim = grid_dim.unwrap_or_else(|| {
            let n = self.x.len() as u32;
            ((n + block_dim.0 - 1) / block_dim.0, 1, 1)
        });
        let smem_bytes: u32 = 0u32;
        let cfg = LaunchConfig {
            block_dim,
            grid_dim,
            shared_mem_bytes: smem_bytes,
        };
        let func = BORING_MODULE.get().unwrap().load_function("Saxpy_kernel")?;
        let stream = self.__ctx.new_stream()?;
        for dep in after { dep.synchronize()?; }
        let mut launcher = stream.launch_builder(&func);
        launcher.arg(&self.alpha);
        launcher.arg(&mut self.x);
        launcher.arg(&mut self.y);
        unsafe { launcher.launch(cfg) }?;
        let stream = Arc::new(stream);
        Ok(KernelHandle { inner: self, stream })
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    boring_gpu_init()?;
    let N = 16;
    let alpha = 2.0;
    let g = boring_gpu_ctx_n(0 as usize)?;
    println!("Device : {}", g.name()?);
    println!("Memory : {} GB", (g.total_mem()? / 1073741824));
    let mut x: Vec<f64> = vec![0.0; N as usize];
    let mut y: Vec<f64> = vec![1.0; N as usize];
    for i in 0..N {
        x[i as usize] = (i as f64);
    }
    let mut k = Saxpy::new(boring_gpu_ctx(), alpha, x, y)?;
    let mut k = k.__boring_launch((N as u32, 1, 1), None, &[])?.wait()?;
    println!("{}", "Results (expected: y[i] = 2*i + 1):");
    for (i, v) in k.read_y()?.iter().enumerate() {
        println!("  y[{}] = {}", i, v);
    }
    Ok(())
}
