// Generated by boring build --target metal.

use metal::*;
use std::mem;

const BORING_MSL: &str = include_str!("../kernels/main.metal");

fn boring_metal_device() -> Device {
    Device::system_default().expect("no Metal device found — macOS 10.14+ required")
}

fn boring_metal_device_n(idx: usize) -> Result<Device, Box<dyn std::error::Error>> {
    let devices = Device::all();
    devices.into_iter().nth(idx)
        .ok_or_else(|| format!("GPU index {} out of range", idx).into())
}

fn boring_gpu_family(device: &Device) -> Vec<i64> {
    let families: &[(MTLGPUFamily, [i64; 2])] = &[
        (MTLGPUFamily::Apple9, [9, 0]),
        (MTLGPUFamily::Apple8, [8, 0]),
        (MTLGPUFamily::Apple7, [7, 0]),
        (MTLGPUFamily::Apple6, [6, 0]),
        (MTLGPUFamily::Apple5, [5, 0]),
        (MTLGPUFamily::Apple4, [4, 0]),
        (MTLGPUFamily::Apple3, [3, 0]),
        (MTLGPUFamily::Apple2, [2, 0]),
        (MTLGPUFamily::Apple1, [1, 0]),
    ];
    for (family, ver) in families {
        if device.supports_family(*family) { return ver.to_vec(); }
    }
    vec![0, 0]
}

struct KernelHandle<T> { inner: T }
impl<T> KernelHandle<T> {
    fn wait(self) -> T { self.inner }
    fn done(&self) -> bool { true }
}

#[repr(C)]
#[derive(Copy, Clone, Debug)]
struct Dimension { width: u32, height: u32 }
#[allow(non_snake_case)]
fn Dimension(width: u32, height: u32) -> Dimension { Dimension { width, height } }

#[macro_use] extern crate objc;

fn boring_screen_present(
    layer: &metal::MetalLayer,
    queue: &metal::CommandQueue,
    src: &metal::Buffer,
    width: u64,
    height: u64,
) {
    let drawable = match layer.next_drawable() { Some(d) => d, None => return };
    let cmd_buf = queue.new_command_buffer();
    let blit = cmd_buf.new_blit_command_encoder();
    blit.copy_from_buffer_to_texture(
        src, 0, width * 4, width * height * 4,
        metal::MTLSize { width, height, depth: 1 },
        drawable.texture(), 0, 0,
        metal::MTLOrigin { x: 0, y: 0, z: 0 },
        metal::MTLBlitOption::empty(),
    );
    blit.end_encoding();
    cmd_buf.present_drawable(&drawable);
    cmd_buf.commit();
    cmd_buf.wait_until_completed();
}

fn boring_key_str(key: winit::event::VirtualKeyCode) -> String {
    use winit::event::VirtualKeyCode::*;
    match key {
        Escape => "\x1B".into(),
        Space => " ".into(),
        Return => "\r".into(),
        Up => "\x1B[A".into(),
        Down => "\x1B[B".into(),
        Left => "\x1B[D".into(),
        Right => "\x1B[C".into(),
        A => "a".into(), B => "b".into(), C => "c".into(),
        D => "d".into(), E => "e".into(), F => "f".into(),
        G => "g".into(), H => "h".into(), I => "i".into(),
        J => "j".into(), K => "k".into(), L => "l".into(),
        M => "m".into(), N => "n".into(), O => "o".into(),
        P => "p".into(), Q => "q".into(), R => "r".into(),
        S => "s".into(), T => "t".into(), U => "u".into(),
        V => "v".into(), W => "w".into(), X => "x".into(),
        Y => "y".into(), Z => "z".into(),
        Key1 => "1".into(), Key2 => "2".into(), Key3 => "3".into(),
        Key4 => "4".into(), Key5 => "5".into(), Key6 => "6".into(),
        Key7 => "7".into(), Key8 => "8".into(), Key9 => "9".into(),
        Key0 => "0".into(),
        _ => format!("{:?}", key).to_lowercase(),
    }
}

struct Plasma {
    __device: Device,
    __queue: CommandQueue,
    __pipeline: ComputePipelineState,
    pixels: Buffer,
    dim: Dimension,
    t: f32,
}

impl Plasma {
    fn new(__device: Device, d: Dimension) -> Result<Self, Box<dyn std::error::Error>> {
        let __queue = __device.new_command_queue();
        let __options = CompileOptions::new();
        let __library = __device.new_library_with_source(BORING_MSL, &__options)
            .map_err(|e| format!("MSL compile error: {}", e))?;
        let __func = __library.get_function("Plasma_kernel", None)
            .map_err(|e| format!("kernel function not found: {}", e))?;
        let __pipeline = __device.new_compute_pipeline_state_with_function(&__func)?;
        let pixels: Buffer = __device.new_buffer(((d.width * d.height) as usize * mem::size_of::<u32>()) as u64, MTLResourceOptions::StorageModeShared);
        let dim: Dimension = d;
        let t: f32 = 0.0;
        Ok(Plasma {
            __device,
            __queue,
            __pipeline,
            pixels,
            dim,
            t,
        })
    }

    fn read_pixels(&self) -> Vec<u64> {
        let n = self.pixels.length() as usize / mem::size_of::<u64>();
        let ptr = self.pixels.contents() as *const u64;
        unsafe { std::slice::from_raw_parts(ptr, n).to_vec() }
    }

    fn __boring_launch(&mut self, block_dim: (u32,u32,u32), grid_dim: Option<(u32,u32,u32)>, _after: &[()]) -> Result<(), Box<dyn std::error::Error>> {
        let grid_dim = grid_dim.unwrap_or_else(|| {
            let __w = self.dim.width; let __h = self.dim.height;
            ((__w + block_dim.0 - 1) / block_dim.0, (__h + block_dim.1 - 1) / block_dim.1, 1)
        });
        let __cmd_buf = self.__queue.new_command_buffer();
        let __encoder = __cmd_buf.new_compute_command_encoder();
        __encoder.set_compute_pipeline_state(&self.__pipeline);
        __encoder.set_buffer(0, Some(&self.pixels), 0);
        __encoder.set_bytes(1, mem::size_of::<Dimension>() as u64, &self.dim as *const _ as *const _);
        __encoder.set_bytes(2, mem::size_of::<f32>() as u64, &self.t as *const _ as *const _);
        __encoder.dispatch_thread_groups(
            MTLSize { width: grid_dim.0 as u64, height: grid_dim.1 as u64, depth: grid_dim.2 as u64 },
            MTLSize { width: block_dim.0 as u64, height: block_dim.1 as u64, depth: block_dim.2 as u64 },
        );
        __encoder.end_encoding();
        __cmd_buf.commit();
        __cmd_buf.wait_until_completed();
        Ok(())
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let width = 800;
    let height = 600;
    use winit::platform::run_return::EventLoopExtRunReturn;
    let mut boring_event_loop = winit::event_loop::EventLoop::new();
    let boring_window = winit::window::WindowBuilder::new()
        .with_title("Plasma — boring")
        .with_inner_size(winit::dpi::LogicalSize::new(800 as u32, 600 as u32))
        .build(&boring_event_loop)?;
    let boring_device = boring_metal_device();
    let boring_layer = metal::MetalLayer::new();
    boring_layer.set_device(&boring_device);
    boring_layer.set_pixel_format(metal::MTLPixelFormat::BGRA8Unorm);
    boring_layer.set_framebuffer_only(false);
    boring_layer.set_drawable_size(core_graphics::geometry::CGSize::new(800 as f64, 600 as f64));
    unsafe {
        use winit::platform::macos::WindowExtMacOS;
        use objc::runtime::*;
        let ns_view = boring_window.ns_view() as *mut Object;
        let () = objc::msg_send![ns_view, setLayer: boring_layer.as_ref()];
        let () = objc::msg_send![ns_view, setWantsLayer: YES];
    }
    let boring_queue = boring_device.new_command_queue();
    let mut boring_frame: i64 = 0;
    let boring_start = std::time::Instant::now();
    let mut boring_keys: std::collections::HashSet<String> = Default::default();
    let mut boring_screen_width: i64 = 800;
    let mut boring_screen_height: i64 = 600;
    let mut boring_screen_resized = false;
    let mut boring_screen_closed = false;
    let mut k = Plasma::new(boring_device.clone(), Dimension(800, 600))?;
    boring_event_loop.run_return(|__boring_event, _, __boring_cf| {
        *__boring_cf = winit::event_loop::ControlFlow::Poll;
        boring_screen_resized = false;
        match __boring_event {
            winit::event::Event::WindowEvent { event: winit::event::WindowEvent::CloseRequested, .. } => {
                boring_screen_closed = true;
                *__boring_cf = winit::event_loop::ControlFlow::Exit;
            }
            winit::event::Event::WindowEvent { event: winit::event::WindowEvent::Resized(__boring_size), .. } => {
                boring_screen_width = __boring_size.width as i64;
                boring_screen_height = __boring_size.height as i64;
                boring_screen_resized = true;
            }
            winit::event::Event::WindowEvent { event: winit::event::WindowEvent::KeyboardInput { input: __boring_ki, .. }, .. } => {
                if let Some(__boring_key) = __boring_ki.virtual_keycode {
                    let __boring_ks = boring_key_str(__boring_key);
                    match __boring_ki.state {
                        winit::event::ElementState::Pressed  => { boring_keys.insert(__boring_ks); }
                        winit::event::ElementState::Released => { boring_keys.remove(&__boring_ks); }
                    }
                }
            }
            winit::event::Event::MainEventsCleared => {
                k.t = (boring_start.elapsed().as_secs_f64() as f32);
                k.__boring_launch((16 as u32, 16 as u32, 1), None, &[]).expect("kernel launch failed");
                boring_screen_present(&boring_layer, &boring_queue, &k.pixels, k.dim.width as u64, k.dim.height as u64);
                if boring_keys.contains("\x1B") {
                    *__boring_cf = winit::event_loop::ControlFlow::Exit;
                    return;
                }
                boring_frame += 1;
            }
            _ => {}
        }
    });
    Ok(())
}
