// Generated by boring build --target wgpu.
// Do not edit -- re-generate with: boring build --target wgpu

use wgpu::util::DeviceExt;
use bytemuck::{Pod, Zeroable};

static __BORING_SHADER_MODULE: std::sync::OnceLock<wgpu::ShaderModule> = std::sync::OnceLock::new();

static SAXPY_PIPELINE: std::sync::OnceLock<std::sync::Arc<wgpu::ComputePipeline>> = std::sync::OnceLock::new();

#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
struct SaxpyParams {
    alpha: f32,
}

struct Saxpy {
    device: std::sync::Arc<wgpu::Device>,
    queue: std::sync::Arc<wgpu::Queue>,
    pipeline: std::sync::Arc<wgpu::ComputePipeline>,
    bind_group: wgpu::BindGroup,
    alpha: f32,
    x_buf: std::sync::Arc<wgpu::Buffer>,
    x: Vec<f32>,
    y_buf: std::sync::Arc<wgpu::Buffer>,
    y: Vec<f32>,
    params_buf: wgpu::Buffer,
}

impl Saxpy {
    fn new(device: std::sync::Arc<wgpu::Device>, queue: std::sync::Arc<wgpu::Queue>) -> Self {

        let x_buf = std::sync::Arc::new(device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        }));
        let y_buf = std::sync::Arc::new(device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4u64,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        }));
        let params_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: std::mem::size_of::<SaxpyParams>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let pipeline = SAXPY_PIPELINE.get_or_init(|| {
            let shader = __BORING_SHADER_MODULE.get_or_init(|| {
                device.create_shader_module(wgpu::ShaderModuleDescriptor {
                    label: None,
                    source: wgpu::ShaderSource::Wgsl(include_str!("../shaders/main.wgsl").into()),
                })
            });
            std::sync::Arc::new(device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: None,
                layout: None,
                module: shader,
                entry_point: "Saxpy_main",
                compilation_options: wgpu::PipelineCompilationOptions::default(),
                cache: None,
            }))
        }).clone();

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &pipeline.get_bind_group_layout(0),
            entries: &[
            wgpu::BindGroupEntry { binding: 0, resource: x_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 1, resource: y_buf.as_entire_binding() },
            wgpu::BindGroupEntry { binding: 2, resource: params_buf.as_entire_binding() },
            ],
        });

        Saxpy {
            device: std::sync::Arc::clone(&device),
            queue: std::sync::Arc::clone(&queue),
            pipeline,
            bind_group,
            x_buf,
            x: vec![f32::default(); 0],
            y_buf,
            y: vec![f32::default(); 0],
            params_buf,
            alpha: f32::default(),
        }
    }

    fn rebuild_bind_group(&mut self) {
        let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();
        entries.push(wgpu::BindGroupEntry { binding: 0, resource: self.x_buf.as_entire_binding() });
        entries.push(wgpu::BindGroupEntry { binding: 1, resource: self.y_buf.as_entire_binding() });
        entries.push(wgpu::BindGroupEntry { binding: 2, resource: self.params_buf.as_entire_binding() });
        self.bind_group = self.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: None,
            layout: &self.pipeline.get_bind_group_layout(0),
            entries: &entries,
        });
    }

    fn dispatch(&self, gx: u32, gy: u32, gz: u32) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.device.push_error_scope(wgpu::ErrorFilter::OutOfMemory);
        self.device.push_error_scope(wgpu::ErrorFilter::Validation);
        let params = SaxpyParams {
            alpha: self.alpha,
        };
        self.queue.write_buffer(&self.params_buf, 0, bytemuck::bytes_of(&params));

        let mut encoder = self.device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
        {
            let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None, timestamp_writes: None });
            cpass.set_pipeline(&self.pipeline);
            cpass.set_bind_group(0, &self.bind_group, &[]);
            cpass.dispatch_workgroups(gx, gy, gz);
        }
        self.queue.submit(std::iter::once(encoder.finish()));
        if pollster::block_on(self.device.pop_error_scope()).is_some() {
            let _ = pollster::block_on(self.device.pop_error_scope());
            return Err(Box::new(BoringError::Other(std::any::TypeId::of::<GpuError>(), Box::new(GpuError::LaunchError) as Box<dyn BoringVal + Send + Sync>)));
        }
        if pollster::block_on(self.device.pop_error_scope()).is_some() {
            return Err(Box::new(BoringError::Other(std::any::TypeId::of::<GpuError>(), Box::new(GpuError::OutOfMemory) as Box<dyn BoringVal + Send + Sync>)));
        }
        Ok(())
    }

    fn copy_x_to_host(&self) -> Vec<f32> {
        __boring_gpu_copy_d2h::<f32>(&self.device, &self.queue, &self.x_buf)
    }
    fn copy_x_to_device(&mut self, data: &[f32]) {
        let needed = (data.len() * std::mem::size_of::<f32>()) as u64;
        if self.x_buf.size() != needed {
            self.x_buf = std::sync::Arc::new(self.device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size: needed,
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }));
            self.rebuild_bind_group();
        }
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.x_buf);
    }

    fn copy_y_to_host(&self) -> Vec<f32> {
        __boring_gpu_copy_d2h::<f32>(&self.device, &self.queue, &self.y_buf)
    }
    fn copy_y_to_device(&mut self, data: &[f32]) {
        let needed = (data.len() * std::mem::size_of::<f32>()) as u64;
        if self.y_buf.size() != needed {
            self.y_buf = std::sync::Arc::new(self.device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size: needed,
                usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }));
            self.rebuild_bind_group();
        }
        __boring_gpu_copy_h2d(&self.device, &self.queue, bytemuck::cast_slice(data), &self.y_buf);
    }

}

#[allow(dead_code)]
#[derive(Clone)]
enum BoringGpuArg<T> {
    Resident(std::sync::Arc<wgpu::Buffer>, usize),
    Host(Vec<T>),
}

#[allow(dead_code)]
impl<T> BoringGpuArg<T> {
    fn len(&self) -> usize {
        match self {
            BoringGpuArg::Resident(_, len) => *len,
            BoringGpuArg::Host(v) => v.len(),
        }
    }
}

thread_local! {
    static __BORING_STAGING_POOL: std::cell::RefCell<Vec<wgpu::Buffer>> = std::cell::RefCell::new(Vec::new());
}

fn __boring_gpu_copy_d2h<T: bytemuck::Pod>(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> Vec<T> {
    let size = src.size();
    let staging = __BORING_STAGING_POOL.with(|pool| {
        let mut pool = pool.borrow_mut();
        match pool.iter().position(|b| b.size() == size) {
            Some(i) => pool.swap_remove(i),
            None => device.create_buffer(&wgpu::BufferDescriptor {
                label: None,
                size,
                usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
                mapped_at_creation: false,
            }),
        }
    });
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(src, 0, &staging, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
    device.poll(wgpu::MaintainBase::Wait);
    let slice = staging.slice(..);
    let (tx, rx) = std::sync::mpsc::channel();
    slice.map_async(wgpu::MapMode::Read, move |r| { tx.send(r).unwrap(); });
    device.poll(wgpu::MaintainBase::Wait);
    rx.recv().unwrap().unwrap();
    let data = bytemuck::cast_slice(&staging.slice(..).get_mapped_range()).to_vec();
    staging.unmap();
    __BORING_STAGING_POOL.with(|pool| pool.borrow_mut().push(staging));
    data
}

fn __boring_gpu_copy_h2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &[u8], dst: &wgpu::Buffer) {
    let size = src.len() as u64;
    let staging = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::MAP_WRITE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: true,
    });
    staging.slice(..).get_mapped_range_mut().copy_from_slice(src);
    staging.unmap();
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(&staging, 0, dst, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
}

fn __boring_gpu_copy_d2d(device: &wgpu::Device, queue: &wgpu::Queue, src: &wgpu::Buffer) -> std::sync::Arc<wgpu::Buffer> {
    let size = src.size();
    let dst = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    encoder.copy_buffer_to_buffer(src, 0, &dst, 0, size);
    queue.submit(std::iter::once(encoder.finish()));
    std::sync::Arc::new(dst)
}

static __BORING_GPU_DEVICE: std::sync::OnceLock<std::sync::Arc<wgpu::Device>> = std::sync::OnceLock::new();
static __BORING_GPU_QUEUE: std::sync::OnceLock<std::sync::Arc<wgpu::Queue>> = std::sync::OnceLock::new();
fn __boring_gpu_device() -> std::sync::Arc<wgpu::Device> { std::sync::Arc::clone(__BORING_GPU_DEVICE.get().expect("GPU device not initialized")) }
fn __boring_gpu_queue() -> std::sync::Arc<wgpu::Queue> { std::sync::Arc::clone(__BORING_GPU_QUEUE.get().expect("GPU queue not initialized")) }

static __BORING_GPU_ADAPTER: std::sync::OnceLock<std::sync::Arc<wgpu::Adapter>> = std::sync::OnceLock::new();
fn __boring_gpu_adapter() -> std::sync::Arc<wgpu::Adapter> { std::sync::Arc::clone(__BORING_GPU_ADAPTER.get().expect("GPU adapter not initialized")) }
fn __boring_gpu_name() -> String { __boring_gpu_adapter().get_info().name }
fn __boring_gpu_total_mem() -> i64 { 0 }
fn __boring_gpu_free_mem() -> i64 { 0 }
fn __boring_gpu_compute_capability() -> Vec<i64> { vec![0, 0] }
fn __boring_gpu_warp_size() -> i64 { 32 }
fn __boring_gpu_max_threads() -> i64 { __boring_gpu_adapter().limits().max_compute_invocations_per_workgroup as i64 }
fn __boring_gpu_max_shared_mem() -> i64 { __boring_gpu_adapter().limits().max_compute_workgroup_storage_size as i64 }

// Generated by boring build
use std::collections::{HashMap, HashSet};
use std::hash::Hash;
use std::rc::{Rc, Weak};
use std::sync::Arc;
use std::sync::{Mutex, RwLock};
use std::f64::consts::{PI, E, TAU};
use std::time::Duration;

trait BoringArrayIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Vec<Self::Item>;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone> BoringArrayIndex for Vec<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Vec<T> {
        let mut v = self.clone();
        if let Some(i) = i { if i < v.len() { v.remove(i); } }
        v
    }
    fn get_at(&self, i: Option<usize>) -> T {
        self[i.expect("get_at called with no index (empty collection or exhausted cursor)")].clone()
    }
}
trait BoringDictIndex<K: Clone + Eq + std::hash::Hash, V: Clone> {
    fn first_index(&self) -> Option<K>;
    fn next_index(&self, k: K) -> Option<K>;
    fn remove_at(&self, k: Option<K>) -> Self where Self: Sized;
}
impl<K: Clone + Eq + std::hash::Hash, V: Clone> BoringDictIndex<K, V> for HashMap<K, V> {
    fn first_index(&self) -> Option<K> { self.keys().next().cloned() }
    fn next_index(&self, k: K) -> Option<K> {
        let keys: Vec<_> = self.keys().collect();
        let pos = keys.iter().position(|kk| *kk == &k);
        pos.and_then(|p| keys.get(p + 1)).map(|kk| (*kk).clone())
    }
    fn remove_at(&self, k: Option<K>) -> Self { let mut m = self.clone(); if let Some(k) = k { m.remove(&k); } m }
}
trait BoringSetIndex {
    type Item: Clone;
    fn first_index(&self) -> Option<usize>;
    fn next_index(&self, i: Option<usize>) -> Option<usize>;
    fn remove_at(&self, i: Option<usize>) -> Self where Self: Sized;
    fn get_at(&self, i: Option<usize>) -> Self::Item;
}
impl<T: Clone + Eq + std::hash::Hash> BoringSetIndex for HashSet<T> {
    type Item = T;
    fn first_index(&self) -> Option<usize> {
        if self.is_empty() { None } else { Some(0) }
    }
    fn next_index(&self, i: Option<usize>) -> Option<usize> {
        i.and_then(|i| if i + 1 < self.len() { Some(i + 1) } else { None })
    }
    fn remove_at(&self, i: Option<usize>) -> Self {
        let elem = i.and_then(|i| self.iter().nth(i).cloned());
        let mut s = self.clone();
        if let Some(e) = elem { s.remove(&e); }
        s
    }
    fn get_at(&self, i: Option<usize>) -> T {
        let i = i.expect("get_at called with no index (empty collection or exhausted cursor)");
        self.iter().nth(i).cloned().expect("get_at index out of range")
    }
}

// BoringFmt — displays Vec<T: Display> as [a, b, c] (no debug quotes on strings).
struct BoringFmt<'a, T: std::fmt::Display>(pub &'a [T]);
impl<'a, T: std::fmt::Display> std::fmt::Display for BoringFmt<'a, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.0.iter().enumerate() {
            if i > 0 { write!(f, ", ")?; }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

// BoringVal — bridge trait that gives BoringError::Other both Display and Any (downcast).
// Every user-defined error enum automatically satisfies the blanket impl below.
trait BoringVal: std::fmt::Display + std::any::Any + Send + Sync {
    fn as_any(&self) -> &dyn std::any::Any;
}
impl<T: std::fmt::Display + std::any::Any + Send + Sync + 'static> BoringVal for T {
    fn as_any(&self) -> &dyn std::any::Any { self }
}
impl std::fmt::Debug for dyn BoringVal + Send + Sync {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "BoringVal({})", self)
    }
}

// BoringError — typed exception wrapper so `catch String:` / `catch Int:` / `catch MyError:` can dispatch.
// `Other(TypeId, error)` identifies the thrown type uniquely across modules via std::any::TypeId::of::<T>(),
// which requires no instance — fully collision-free even when two modules define identically-named types.
#[derive(Debug)]
enum BoringError {
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(&'static str),
    String(Arc<str>),
    Other(std::any::TypeId, std::boxed::Box<dyn BoringVal + Send + Sync>),
}
impl std::fmt::Display for BoringError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            BoringError::Int(n)         => write!(f, "{}", n),
            BoringError::Float(n)       => write!(f, "{}", n),
            BoringError::Bool(b)        => write!(f, "{}", b),
            BoringError::Str(s)         => write!(f, "{}", s),
            BoringError::String(s)      => write!(f, "{}", s),
            BoringError::Other(_, e)    => write!(f, "{}", e),
        }
    }
}
impl std::error::Error for BoringError {}

// Boring standard error enum — always available without import.
// Use `throw Error.Expired` / `catch Error:` / `match err: Error.Expired: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum Error {
    Expired,
    Cancelled,
    NotFound,
    InvalidInput,
    OutOfBounds,
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::Expired      => write!(f, "timeout expired"),
            Error::Cancelled    => write!(f, "task cancelled"),
            Error::NotFound     => write!(f, "not found"),
            Error::InvalidInput => write!(f, "invalid input"),
            Error::OutOfBounds  => write!(f, "index out of bounds"),
        }
    }
}
impl std::error::Error for Error {}

// Boring GPU error enum — thrown by kernel dispatch on a device-side
// failure. Always available without import. Currently wired up on the
// wgpu target only (its host codegen shares this same general pipeline);
// cuda/rocm/metal report GPU failures as plain string-message errors
// instead of this typed enum -- see `docs/gpu-module.md`'s error-handling
// notes for why (their host transpilers don't share this prelude).
// Use `catch GpuError.OutOfMemory:` / `match err: GpuError.Timeout: ...`
#[derive(Debug, Clone)]
#[allow(dead_code)]
enum GpuError {
    LaunchError,
    OutOfMemory,
    IllegalAccess,
    StackOverflow,
    Timeout,
    DeviceLost,
}
impl std::fmt::Display for GpuError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            GpuError::LaunchError   => write!(f, "GPU kernel launch failed"),
            GpuError::OutOfMemory   => write!(f, "GPU out of memory"),
            GpuError::IllegalAccess => write!(f, "GPU illegal memory access"),
            GpuError::StackOverflow => write!(f, "GPU stack overflow"),
            GpuError::Timeout       => write!(f, "GPU operation timed out"),
            GpuError::DeviceLost    => write!(f, "GPU device lost"),
        }
    }
}
impl std::error::Error for GpuError {}

const N: i64 = 16;

const ALPHA: f64 = 2.0;


fn boring_main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // saxpy.br — SAXPY on GPU: y[i] = alpha * x[i] + y[i]
    // 
    // Classic "Hello World" of GPU computing.
    // The same source runs on all three targets:
    // 
    // boring run saxpy.br                          # interpreted simulation
    // boring build --target cuda saxpy.br          # CUDA (simulation on macOS without nvidia)
    // boring build --target metal saxpy.br         # Metal (macOS native)
    let g = ((0) as usize);
    println!("Device : {}", __boring_gpu_name());
    println!("Memory : {} GB", (__boring_gpu_total_mem() / 1073741824));
    let mut x: Vec<f64> = vec![0.0; N as usize];
    let mut y: Vec<f64> = vec![1.0; N as usize];
    for i in (0..N) {
        x[(i) as usize] = (i as f64);
    }
    let mut k = Saxpy::new(__boring_gpu_device(), __boring_gpu_queue());
    k.alpha = (ALPHA) as f32;
    k.copy_x_to_device(&x.iter().map(|&x| x as f32).collect::<Vec<f32>>());
    k.copy_y_to_device(&y.iter().map(|&x| x as f32).collect::<Vec<f32>>());
    k.dispatch((1) as u32, (1) as u32, (1) as u32)?;
    println!("Results (expected: y[i] = 2*i + 1):");
    for (i, v) in k.copy_y_to_host().iter().map(|&x| x as f64).collect::<Vec<f64>>().into_iter() {
        println!("  y[{}] = {}", i, v);
    }
    Ok(())
}

fn main() {
    pollster::block_on(async_main());
}

async fn async_main() {
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());
    let adapter = instance.request_adapter(&wgpu::RequestAdapterOptions::default()).await.expect("No GPU adapter found");
    let (device, queue) = adapter.request_device(&wgpu::DeviceDescriptor::default(), None).await.expect("Failed to create device");
    device.poll(wgpu::MaintainBase::Wait);
    device.on_uncaptured_error(Box::new(|e| eprintln!("boring: uncaptured GPU error: {}", e)));
    let device = std::sync::Arc::new(device);
    let queue = std::sync::Arc::new(queue);
    let _ = __BORING_GPU_DEVICE.set(std::sync::Arc::clone(&device));
    let _ = __BORING_GPU_QUEUE.set(std::sync::Arc::clone(&queue));
    let _ = __BORING_GPU_ADAPTER.set(std::sync::Arc::new(adapter));

    if let Err(e) = boring_main() {
        eprintln!("error: {}", e);
        std::process::exit(1);
    }
}
