// Generated by boring build --target wgpu.

struct Dimension {
    width: u32,
    height: u32,
}

// ─── kernel Mandelbrot ───

@group(0) @binding(0) var<storage, read_write> image: array<f32>;
struct MandelbrotParams {
    dim_w: u32,
    dim_h: u32,
}
@group(0) @binding(1) var<uniform> __params: MandelbrotParams;


override block_x: u32 = 1;
override block_y: u32 = 1;
override block_z: u32 = 1;

@compute @workgroup_size(block_x, block_y, block_z)
fn Mandelbrot_main(
    @builtin(local_invocation_id)   __tid:  vec3<u32>,
    @builtin(workgroup_id)           __bid:  vec3<u32>,
    @builtin(local_invocation_size) __bdim: vec3<u32>,
    @builtin(num_workgroups)         __gdim: vec3<u32>,
) {
    let dim: Dimension = Dimension(__params.dim_w, __params.dim_h);
    let col = ((i32(__bid.x) * i32(__bdim.x)) + i32(__tid.x));
    let row = ((i32(__bid.y) * i32(__bdim.y)) + i32(__tid.y));
    if (((col < 64) && (row < 48))) {
        let x0 = (x_min + ((f32(col) * (1.0 - x_min)) / f32(64)));
        let y0 = (y_min + ((f32(row) * (1.5 - y_min)) / f32(48)));
        var cx: f32 = 0.0;
        var cy: f32 = 0.0;
        var it: i32 = 0;
        loop {
            if !(((((cx * cx) + (cy * cy)) < 4.0) && (it < 100)))
                { break; }
            let xtemp = (((cx * cx) - (cy * cy)) + x0);
            cy = (((2.0 * cx) * cy) + y0);
            cx = xtemp;
            it = (it + 1);
        }
        let value = select((f32(it) / f32(100)), 1.0, (it == 100));
        image[u32(((row * 64) + col))] = value;
    }
}

